### ISSUE TITLE
Update Zowe VSCode extension

### ISSUE THREAD

**Issue by JTonda** [zowe/vscode-extension-for-zowe#1]
As Michelle, I want the Zowe VSCode Extension to work properly with profiles stored in plain text so that I can continue to make use of it to improve my interaction with z/OS datasets.

Update Zowe VSCode extension to work with profile credentials now stored in plain text under .zowe. Update documentation. No requirement to also work with securely stored profiles (eg 1.x).

~Enhance error message to say that version is incompatible, please upgrade to the latest version.~ See comment below.

Depends on zowe/zowe-cli#7
'Replace Keytar - Store creds in plain text' in Zowe CLI repo

- [x]  Bump versions of zowe and imperative
Status:  Completed
Assigned: @AHumanFromCA 

- [x]  Remove calls to CredentialManager and keytar
Status: Completed
Assigned: @AHumanFromCA 

- [x]  Initialize logger to prevent possible problems
Status: Completed
Assigned: @lyzla01 

- [x]  Modify CliProfileManager calls to account for plaintext credentials
Status: It just worked without any changes :)
Assigned:

- [x]  Run system tests
Status: Completed
Assigned: @AHumanFromCA 

- [ ]  Update documentation
Status:
Assigned: @JamesBauman 

*Accept feature with PM when complete (This & zowe/zowe-cli#16 both in this Sprint)
8 point story

**Comment by AHumanFromCA** [comment]
**Meeting Notes**

- Remove calls to CredentialManager / keytar
- Initialize the logger
- Possible updates to CliProfileManager call to account for no credential manager
- Update documentation
  - Remove doc about keytar
- Publish via pipeline not part of this story
- Bump version of zowe and imperative
- Run existing system tests. They should all pass

**Comment by AHumanFromCA** [comment]
After further discussions this ask might be impossible:

> Enhance error message to say that version is incompatible, please upgrade to the latest version.

**Reasons**

- The meta file for profiles does not contain any versioning information
- The new system can work without zowe-cli being installed as all profiles can be hand created

**Notes:**
- As is currently, if there are missing properties, the CliProfileManager will inform of the missing fields

```
Command Error:
Expect Error: Required parameter 'hostname' must be defined
```

**Comment by AHumanFromCA** [comment]
At this point, the story wasn't to enable plaintext profiles. I think the actual story should be more like, bring VSC Extension quality :/
