### ISSUE TITLE
Refactor Code for Profiles.ts

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1000]
**Is your feature request related to a problem? Please describe.**

I would like to re-factor the overall solution of Profiles.ts Maybe create a folder structure similar to datasets, uss or jobs

**Describe the solution you'd like**

Discuss with the squad on how to do efficiently do this.

**Describe alternatives you've considered**

**Additional context**

**Comment by jellypuno** [comment]
Minor Issues from #979 that we can probably address

**Comment by jellypuno** [comment]
TODO: Move addSession and addSingleSession to abstract/ZoweTreeProvider. Pattern it to editSession

**Comment by zFernand0** [comment]
With the latest improvements to the ZE API NPM package, I believe this issue can be marked as resolved.
