### ISSUE TITLE
Zowe Explorer activation only when extension is accessed

### ISSUE THREAD

**Issue by Alexandru-Dumitru** [zowe/vscode-extension-for-zowe#1001]
**Is your feature request related to a problem? Please describe.**

Currently Zowe Explorer is activated when VS Code starts up. This can potentially slow down startup or present unrelated error messages.
See https://github.com/zowe/vscode-extension-for-zowe/blob/master/package.json#L31-L33

**Describe the solution you'd like**

I suggest:
```
  "activationEvents": [
    "onView:zowe"
  ],
```

**Describe alternatives you've considered**

```
  "activationEvents": [
    "onStartupFinished"
  ],
```
But this only improves startup speed.

**Additional context**

For example, I have some profiles which are miss configured (reason is not important) but I get this error on VS Code startup.

![image (1)](https://user-images.githubusercontent.com/45846673/92122856-4433ac00-edfc-11ea-8285-48d753e151ad.png)

**Comment by zdmullen** [comment]
We should consider the messages that come up on activation. We'll address those elsewhere, such as in #1163.
