### ISSUE TITLE
Favoriting a profile without a search saves an empty space in Favorites (Data Sets and USS)

### ISSUE THREAD

**Issue by lauren-li** [zowe/vscode-extension-for-zowe#1002]
**Describe the bug**

Saving a profile name without a search to go along with it results in an empty space in the favorites.

**To Reproduce**
1. Open VS Code with Zowe Explorer
2. Right-click a profile name in either the Data Sets or USS view, and select "Add to Favorites"
3. Expand the Favorites section, and see that the profile has been added as a favorite with no search label.

**Screenshots**
Screenshot and gif courtesy of @JillieBeanSim. Thanks!
Data Sets:
![favs-emptysearch](https://user-images.githubusercontent.com/49491949/91916612-8c7f8c80-ec8b-11ea-874d-d6bbcb90a10e.gif)

USS:
![image](https://user-images.githubusercontent.com/49491949/91918051-b63ab280-ec8f-11ea-9bb9-b156967fb280.png)

**Expected behavior**
The system should either not allow the user to favorite a profile with no associated search, or the user should be prompted to execute a search with the profile before being able to add it to favorites. 

**Desktop (please complete the following information):**

-   OS: MacOS
-   Zowe Explorer Version: 1.8.0
-   (Optional) Zowe CLI Version:
-   (Optional) Are you using Secure Credential Store?

**Comment by JillieBeanSim** [comment]
related to #1029

**Comment by adam-wolfe** [comment]
Resolved in version 2.6.1.
