### ISSUE TITLE
Compatibility with the use of base profiles

### ISSUE THREAD

**Issue by FALLAI-Denis** [zowe/vscode-extension-for-zowe#1003]
**Describe the bug**

After modifying the z/OSMF profile to use a default base profile (in particular removal of user and password information), the Zowe Explorer extension became unusable.

**To Reproduce**

1. Create a ZOWE CLI base profile with the user, password, host information.
2. Delete and recreate the ZOWE CLI  z/OSMF profile without the user, password, and host information.
3. Try to access the ZOWE Explorer extension.

**Expected behavior**

ZOWE Explorer must support z / OSMF profiles that make use of a base profile.

**Screenshots**

![2020-09-04 ZE using base profile](https://user-images.githubusercontent.com/63861965/92224840-ab0ba080-eea2-11ea-9de8-aa51e7d48565.png)

[2020-09-04 ZE using base profile.log](https://github.com/zowe/vscode-extension-for-zowe/files/5173951/2020-09-04.ZE.using.base.profile.log)

**Desktop (please complete the following information):**

-   OS: Windows 10 64 bits
-   Zowe Explorer Version: 1.8.0
-   Zowe CLI Version: 6.22.0
-   Are you using Secure Credential Store? No (not compatible with IBM Z Open Editor / Broadcom Endevor)

**Additional context**

None

**Comment by zdmullen** [comment]
Hey Denis,
We currently have a PR open to handle base profiles (https://github.com/zowe/vscode-extension-for-zowe/pull/993). It will be merged some time very soon and will be available as part of the 1.9 release (to go out next week).
Thanks,
Zach

**Comment by FALLAI-Denis** [comment]
@zdmullen Good news !
I close this issue.
