### ISSUE TITLE
Recommendations for the use of Zowe-Temp-Folder-Location setting

### ISSUE THREAD

**Issue by FALLAI-Denis** [zowe/vscode-extension-for-zowe#1004]
**Is your feature request related to a problem? Please describe.**

Documentation and recommendations for using the Zowe-Temp-Folder-Location setting

**Describe the solution you'd like**

Zowe Explorer allows you to designate a location for storing temporary files: Zowe-Temp-Folder-Location setting.

It should be specified:
* what are these temporary files
* what does temporary mean: what duration?
* relations with the workspace (VS Code): common space or by workspace?
* is it possible to use environment variables for the path? how to express them?
* give recommendations and the impacts of different choices, depending on the host operating system (Windows, Linux, MacOs) and the host application (VS Code, Theia).

**Comment by anaxceron** [comment]
Closing w/ documentation done w/ [PR 2810](https://github.com/zowe/docs-site/pull/2810)
