### ISSUE TITLE
Profile validation more than doubles the time it takes to view files and does not handle errors sufficiently 

### ISSUE THREAD

**Issue by kristinochka** [zowe/vscode-extension-for-zowe#1011]
**Describe the bug**
Profile validation more than doubles the initial time it takes to view files on USS and MVS. 
- Many users open and close VS Code many times a day therefore, they experience profile validation many times. 
- If I use a firewall, I experience profile validation many times as the connection times out.
- Some systems take a very long time to validate making Zowe explorer hang.
- The profile validation makes the User experience feel very slow. 
Another issue is insufficient error handling of invalid profiles

**To Reproduce**

Click the looking glass button to enter a path for USS or MVS file

**Current behavior:**
Takes 3 to 10 seconds to validate profile and only then I can enter the search path.

**Expected behavior**

After clicking on the looking glass, I should be able to enter the path immediately and get response from my zOS system. 

Error handling:
**Current behavior:**
1)	Create zOSMF profile with any invalid parameter
2)	Click the looking glass button to enter a path for USS or MVS file
3)	Profile validation happens
4)	Get error message that profile is “inactive”
5)	Fix the profile and try again
6)	Get same error message that profile is “inactive”

**Expected behavior:**
1)	Create zOSMF profile with any invalid parameter
2)	Click the looking glass button to enter a path for USS or MVS file
3)	Enter path in the popup box at the top
4)	Get error message that search could not complete due to a specific error
5)	Fix the profile and try again
6)	This time the search should work

Related issues:
 https://github.com/zowe/vscode-extension-for-zowe/issues/977
 https://github.com/zowe/vscode-extension-for-zowe/pull/979
https://github.com/zowe/vscode-extension-for-zowe/issues/918
No validation should be the default behavior.

**Comment by jellypuno** [comment]
Profile Validation can be deactivated in VSCode Settings. Once you disabled it, it will be the default value.

@zdmullen @IgorCATech Is validation added in our docs?

**Comment by jellypuno** [comment]
Closing this issue. Global Validation can be set in VSCode settings and this is also part of our documentation.
