### ISSUE TITLE
Uploading multiple files to PDS fails

### ISSUE THREAD

**Issue by AnthonyGiorgio** [zowe/vscode-extension-for-zowe#1012]
When using the "Upload Member..." menu option on a PDS, uploading multiple files fails.

**Describe the bug**
Error message:
```
z/OSMF REST API Error:
Rest API failure with HTTP(S) status 500
rc:       4
reason:   3
details: 
  -   ISPT036 Table in use            -/-TBOPEN issued for table ISPSPROF that is in use, ENQUEUE failed.                   
  - READY 
category: 2
message:  ServletDispatcher failed - received TSO Prompt when expecting TSO_SERVLET_DISPATCHER_READY
 Error: z/OSMF REST API Error:
Rest API failure with HTTP(S) status 500
rc:       4
reason:   3
details: 
  -   ISPT036 Table in use            -/-TBOPEN issued for table ISPSPROF that is in use, ENQUEUE failed.                   
  - READY 
category: 2
message:  ServletDispatcher failed - received TSO Prompt when expecting TSO_SERVLET_DISPATCHER_READY
```

**To Reproduce**

1. Right-click on a PDS, and choose "Upload Member..."   
2. Use the file picker dialog to select multiple files.
3. Submit the dialog.
4. See the error message.

**Expected behavior**

I wanted multiple files to be uploaded at once.  Instead, I had to upload them individually.

**Screenshots**

**Desktop (please complete the following information):**

-   OS: Fedora Linux 32
-   Zowe Explorer Version: 1.8.0
-   (Optional) Zowe CLI Version: 6.22.0
-   (Optional) Are you using Secure Credential Store? No

**Additional context**

**Comment by JillieBeanSim** [comment]
this is resolved with v2.3.0 multi select work
