### ISSUE TITLE
Zowe Security: Credential Key Restart Required

### ISSUE THREAD

**Issue by dkelosky** [zowe/vscode-extension-for-zowe#1014]
**Is your feature request related to a problem? Please describe.**

After you enter a `Credential Key` in Zowe Explorer - it seems like you need to restart Zowe Explorer for the new value to take effect.  

**Describe the solution you'd like**

Perhaps the settings should mention that restart is required after setting this value or otherwise trigger a restart automatically?  

**Describe alternatives you've considered**

**Additional context**

**Comment by JillieBeanSim** [comment]
is this still an issue @dkelosky with the latest release? fyi @zFernand0

**Comment by JillieBeanSim** [comment]
this should be fixed now for v1 and v2 profile management
