### ISSUE TITLE
Zowe Explorer Fails to Load Old Profiles After Setting Zowe Security: Credential Key 

### ISSUE THREAD

**Issue by dkelosky** [zowe/vscode-extension-for-zowe#1015]
**Describe the bug**

If you create a profile in Zowe Explorer, then set a Zowe Security Credential Key in settings.  After you restart, no profiles are loaded and you cannot create any new profiles in Zowe Explorer.  

**To Reproduce**

1. Clear all old profiles.
2. Set Zowe Security: Credential Key blank.
3. Restart Zowe Explorer.
4. Create a z/OSMF profile in Zowe Explorer. 
5. Set Zowe Security: Credential Key `Zowe-Plugin`
6. Restart Zowe Explorer.
7. Observe that you cannot create profiles. 

**Expected behavior**

Perhaps a migration option should be presented to convert my old profiles created with Zowe Explorer and/or at least permit creating new profiles.  Right now, new profiles cannot be created.

**Screenshots**

**Desktop (please complete the following information):**

-   OS: Windows 10 😎 
-   Zowe Explorer Version: 1.8.0
-   (Optional) Zowe CLI Version:
-   (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by zFernand0** [comment]
For more context, in the CLI and SCS plugin, we recommend that old profiles be recreated after installing the SCS plugin. 
In Zowe Explorer we "install" the security module by adding the Credential Key.
I think it's fair to at least add warning message or something. 😋

**Comment by zFernand0** [comment]
Hey @dkelosky, are you able to reproduce this issue.
Tried it on my personal PC and also on a VM and I can still create profiles even after changing the security key.
