### ISSUE TITLE
Add ability to filter by jobid

### ISSUE THREAD

**Issue by markcocker** [zowe/vscode-extension-for-zowe#102]
When using the JOBS view provided by the Zowe extension for VSC, it would be useful to be able to filter by jobid. For example `zowe zos-jobs list jobs` returns a list of jobids so it would be useful to copy a jobid from that list and find it quickly using the extension.

**Comment by dkelosky** [comment]
Perhaps the default view should show the job id by default in place of the job name.

When you submit a job, you're presented the jobid although you view it by jobname:
![image](https://user-images.githubusercontent.com/14940561/59039296-8f9a8b80-8842-11e9-8bd0-5d3751518194.png)

Maybe the presentation of the jobs could be similar to z/OS explorer jobs view?

**Comment by MikeBauerCA** [comment]
It would be beneficial to be able to see both the job name and the job id, especially in cases where you submit the same job multiple times.

**Comment by crshnburn** [comment]
@MikeBauerCA You can see the Job Id if you hover on a particular job

![JobIdHover](https://user-images.githubusercontent.com/860280/59116512-9e1c9c00-8943-11e9-90c9-bdb7a91210d1.png)

The aim with showing either the RC or the ACTIVE status was that if the same job had been submitted multiple times then the latest one would be easy to find.

**Comment by Colin-Stone** [comment]
work in conjunction with #118

**Comment by Colin-Stone** [comment]
https://github.com/zowe/vscode-extension-for-zowe/pull/247

**Comment by Colin-Stone** [comment]
@markcocker There is now a magnifying glass option to specify a more comprehensive search that includes owner, prefix or jobId. That option also has access to search history. The intention was to get something out there (whilst we are still in development mode) and ask for feedback. VSCode supports the creation of create simple dialogs (an entry field or quick pick) and to get a combination of items the only option is to link them. So it would be good to get your perspective.

**Comment by markcocker** [comment]
@Colin-Stone Thanks - initial feedback from trying it out:
1. For consistency, should label "Search for Jobs using attributes" be "Search Jobs Using Attributes"?
   Compare to casing and style of "Search Data Sets by Entering Patterns".
2. Label "Choose "Create new..." to define a new filter alternatively select a previously defined filter" needs to have a comma, be two sentences or rephrased
   eg. "Choose "Create new..." to define a new filter or select a previously defined filter".
3. When creating a new filter and entering the owner, it allows for multiple words eg. "COCKERM BLA" when only one word is actually used.
4. Its not clear to me how you can remove filter definitions?

**Comment by Colin-Stone** [comment]
Thanks Mark. I created https://github.com/zowe/vscode-extension-for-zowe/issues/263 to cover points to 3.
The answer to 4 is that you can't. I've implemented a set with a capacity of 5 unique items each time you create a new item or select an item from the set it gets pushed to the front. If you add a new item to the set and the set exceeds 5 the last one drops off. So for example if you had a specific jobId filter set up and you have deleted that job, it would remain as an option in the filter list until you added enough additional filters for it to drop off the end of the list from lack of use. 

Hope that makes sense. It seemed a reasonable solution I could apply consistently to filters on all three views
