### ISSUE TITLE
Unable to remove favorite profile from JOBS tree

### ISSUE THREAD

**Issue by deepali-hub** [zowe/vscode-extension-for-zowe#1020]
**Describe the bug**

When you add profile to Favorites under JOBS  in THEIA and refresh the page. You can not find option to remove that profile from favorites(Same in VSCODE)

**To Reproduce**

1. Go to 'Theia page'
2. Create profile in Data Sets
3. Add Same Profile in Jobs
4. Add above added profile to Favorites in Jobs
5. Now expand the favorite tab and expand profile and you can see magnifying glass(See the below  attached Screenshot 1)
6. Now refresh the page and navigate to Jobs->Favorite and click on profile name
7. You can not see magnifying glass and you can not remove profile from favorite(See the below  attached Screenshot 2)

**Expected behavior**

After refreshing the window magnifying glass should be visible inside favorite profile under JOBS tree 

**Screenshots**
Screenshot 1:
![image](https://user-images.githubusercontent.com/63286916/93450587-6fc39580-f8d6-11ea-8332-780cafefc995.png)

Screenshot 2:
![image](https://user-images.githubusercontent.com/63286916/93450845-bd400280-f8d6-11ea-895e-773251e1735d.png)
 

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Zowe Explorer Version: 1.9.0
-   (Optional) Zowe CLI Version: 6.22.0
-   (Optional) Are you using Secure Credential Store?

**Additional context**

If you click on favorite profile name i get error message "Jobs: Cannot read property 'ISession' of null".

**Comment by deepali-hub** [comment]
@lauren-li  This issue resolved. Now i can delete profile from Favorites under Jobs tree.

**Comment by lauren-li** [comment]
Thanks @deepali-hub for the update! Closing issue as resolved.
