### ISSUE TITLE
USS Favorited search creates extra profile node

### ISSUE THREAD

**Issue by lauren-li** [zowe/vscode-extension-for-zowe#1029]
**Describe the bug**
Clicking on a favorited USS search (especially more than once) creates an extra profile node. This bug is present at least as far back as ZE version 1.7.1.

**To Reproduce**
1. Favorite a search in the USS view, noting the profile name.
2. Navigate to the USS Favorites and open the profile folder containing your favorite from Step 1.
3. Click on the favorited search.
4. See that an extra profile node with the same profile name - but no search filter - is created in the USS view (outside of Favorites).

*Note: If you restart VS Code between Steps 2 and 3, you will have to click on the favorited search twice to see the issue. The first click will run the search as expected. The second click will create an extra profile node with no associated search filter - i.e. Step 4. This is what is depicted in the gif below.

**Screenshots**
![ze extra prof node](https://user-images.githubusercontent.com/45975633/94162174-6d23eb80-fe54-11ea-9e2c-ac5407eaeaa3.gif)

**Expected behavior**
Clicking on a favorited search in USS should run the search filter on the existing profile node, or, if the profile has been hidden, it should create a node for that profile with the favorited search filter applied. At most, there should just be one node per profile (not including in the Favorites section), no matter how many times a favorited USS search has been clicked.

**Desktop (please complete the following information):**

-   OS: Mac
-   Zowe Explorer Version: 1.9.0 (Although this bug appears to be present at least as far back as ZE v1.7.1)
-   (Optional) Zowe CLI Version: 6.22.0
-   (Optional) Are you using Secure Credential Store? Yes

**Comment by jellypuno** [comment]
@lauren-li Is this still happening? Can we close this issue?

**Comment by lauren-li** [comment]
@jellypuno I still see this happening:

![ze-favSearch](https://user-images.githubusercontent.com/45975633/108113669-ca1f7880-7065-11eb-9533-a3a02a01480a.gif)

**Comment by JillieBeanSim** [comment]
this is still happening
<img width="345" alt="Screen Shot 2022-09-28 at 7 56 44 AM" src="https://user-images.githubusercontent.com/49491949/192772937-b66793c2-6236-4200-bcd7-fe857f0ee7ef.png">
