### ISSUE TITLE
Request to see binary data sets 

### ISSUE THREAD

**Issue by zdmullen** [zowe/vscode-extension-for-zowe#1034]
**Is your feature request related to a problem? Please describe.**

A user, Ian C, made a request for binary data set support in Zowe Explorer in our Slack channel. He would like to be able to get them and examine them the way he does in ISPF

**Describe the solution you'd like**

Ability to view binary data sets (and not receive the error that is currently there)

**Describe alternatives you've considered**

**Additional context**

There are issues with this, as there are limitations on the zOSMF API. Perhaps too, there is necessary work needed on the CLI side. @dkelosky, is this true?

**Comment by jellypuno** [comment]
Closing in favor of #1135
