### ISSUE TITLE
Ensure docs for Zowe Explorer are up-to-date

### ISSUE THREAD

**Issue by katelynienaber** [zowe/vscode-extension-for-zowe#1041]
We should make sure that the Explorer section of [docs.zowe.org](https://docs.zowe.org/) has up-to-date information about all the new functions we've been adding :)

@IgorCATech and I decided to make a list of all the functions, and then we can check what's up with the docs. So yeah here's the issue for that :)

Feel free to add whatever.

**Comment by IgorCATech** [comment]
Cool beans @katelynienaber Ok, so here's the list so far:

- Allocate Like 
- Base Profiles
- Allocate multiple data sets from JSON file

@zdmullen Surely, you know more ;) Feel free to add them

**Comment by IgorCATech** [comment]
On another but related note, the videos are outdated, so it would be nice to work on them at some point.

**Comment by katelynienaber** [comment]
Maybe also:
- New Favorites view

**Comment by IgorCATech** [comment]
We tend not to document enhancements of UI. Good UI/UX needs no doc :P

**Comment by zdmullen** [comment]
So thanks for creating this. One thing I want to stress however, is that we do not get in the habit of creating these kinds of issues, but instead check up on the development as it's happening and make sure we maintain the doc continuously. This also depends on contributors actively marking their PRs as "Updates to documentation" in the checklist.

**Comment by jellypuno** [comment]
Closing this in favor of the doc epic
