### ISSUE TITLE
After upgrade to 1.9 jobs dropdown to show all jes2 datasets for job isn't working

### ISSUE THREAD

**Issue by fbeyl** [zowe/vscode-extension-for-zowe#1045]
**Describe the bug**

In version 1.4 when click on a jobname in jobs panel the list of all jes2 datasets for the job is opened (dropdown). After upgrade to 1.9 the list is not showing anymore. The map icon changes but nothing below.
After uninstall & reinstall it seems the issue comes with version 1.5. Reinstall 1.4 all is ok.

**Screenshots**
1.9 before click:
![Before click](https://user-images.githubusercontent.com/42418931/96431008-35198980-1203-11eb-97d6-5ce6ab126ad0.JPG)
1.9 after click
![After click](https://user-images.githubusercontent.com/42418931/96430979-2c28b800-1203-11eb-83e9-1b0184ec61f1.JPG)
1.4 after click
![After click 1 4](https://user-images.githubusercontent.com/42418931/96431021-3ba80100-1203-11eb-90cc-9ad76db3e72a.JPG)

**Desktop (please complete the following information):**

-   OS: Windows 10 Enterprise
-   Zowe Explorer Version: 1.9
-   (Optional) Zowe CLI Version: not installed
-   (Optional) Are you using Secure Credential Store? no

**Comment by fbeyl** [comment]
Is there a setting, variable or ... to generate debug info in log? I'm interested to see z/osmf request & respone.

**Comment by jellypuno** [comment]
@fbeyl The vscode logs are in C:\Users\UserName\.vscode\extensions\zowe.vscode-extension-for-zowe-1.11.1\logs. But if you are looking for the specific z/OSMF logs then we are not extracting it.

**Comment by zdmullen** [comment]
Hey @fbeyl, have you tried with the most recent version, 1.11.1? Thanks.

**Comment by fbeyl** [comment]
I tried reinstall and this issue is now gone but the plugin drops favorites and profiles. In the office a lot of changes are ongoing which I don't control. We are shifting from file servers to cloud storage, network management changes, software installation  ... I suspect these activities influence the plugin but I can't spend much time to investigate and on my private laptop I run Linux mint 32bit and can't upgrade to 64bit due to hardware thus I can't upgrade. VSC as the 32bit is no longer supported. 
 Please close this issue as solved as I'm quit sure problem is not with explorer.

**Comment by jellypuno** [comment]
@fbeyl Thank you for the update. I'll close the issue.
