### ISSUE TITLE
Error encountered while activating and initializing logger (solved by removing base profile)

### ISSUE THREAD

**Issue by FALLAI-Denis** [zowe/vscode-extension-for-zowe#1047]
**Describe the bug**

Apparently since the update of Zowe Explorer to version 1.10.0, or since the VS Code version upgrade to 1.50.x, a warning window is displayed when VS Code is launched concerning access to a function.

**To Reproduce**

1. Start VS Code
2. A pop-up window displays an error concerning the management of the Zowe Explorer log

**Screenshots**

![Error encountered while activating and initializing logger](https://user-images.githubusercontent.com/63861965/96618157-de947400-1304-11eb-8f3a-2d5db173a1cd.PNG)

**Desktop (please complete the following information):**

-   OS: Windows 10 x64
-   VS Code Version : 1.50.1
-   Zowe Explorer Version: v1.10.0
-   Zowe CLI Version: 6.22.0
-   Are you using Secure Credential Store? No

**Additional context**

N/A

**Comment by FALLAI-Denis** [comment]
Solved by erasing all preferences about Zowe Explorer in settings.json.....
Having also problems on profiles...

**Comment by jellypuno** [comment]
Adding to #1000 .

**Comment by FALLAI-Denis** [comment]
The error is repeated every time you start VS Code and blocks the use of Zowe Explorer.

Solution:
* open the settings.json file
* remove the profiles referenced in the "sessions" properties
* restart VS Code

Zowe Explorer extension redetects default profiles and declares them automatically in settings.json.
Zowe Explorer works ... until the next restart of VS Code.

**Comment by FALLAI-Denis** [comment]
The problem is caused by the existence of a base profile declared by default.

Removing the default base profile permanently eliminates the problem.

**Comment by mpettis** [comment]
How can I find where this `settings.json` file is?

**Comment by katelynienaber** [comment]
@mpettis You can access `settings.json` here: 
![image](https://user-images.githubusercontent.com/58596139/101499800-f768ef80-396d-11eb-871e-4499b43ed5b2.png)

Or, go to `File >> Preferences >> Settings`, then locate **Zowe Explorer Settings** in the list on the left, and click **Edit in settings.json** under one of the categories on the right:
![image](https://user-images.githubusercontent.com/58596139/101500177-69413900-396e-11eb-8d1e-e2f9d3e4e047.png)

@zdmullen I think this was fixed in PR [#993](https://github.com/zowe/vscode-extension-for-zowe/pull/993), I will look into it...

**Comment by zdmullen** [comment]
@katelynienaber, any update on this?

**Comment by katelynienaber** [comment]
@zdmullen This is resolved. The initialization was hanging during `getCliProfileManager` but we added an `if()` so now if you are missing a certain type of profile you can still start the extension.

I tested if it works when the base folder is completely missing, and when the folder is present but doesn't contain any default.yaml file.

This could also fix issue #1067...but their post is so vague, they could be referring to any kind of error during init.

**Comment by jellypuno** [comment]
Thank you for investigating this @katelynienaber.

@FALLAI-Denis Can we close this issue?

**Comment by crawr** [comment]
Issue seems to be resolved

**Comment by zFernand0** [comment]
Oi @ViAndrade,
Eu acredito que esse erro somente ocorre no Zowe V1. 
Qual é a tua versão?

**Comment by ViAndrade** [comment]
Olá, @zFernand0. É a v2.0.

![image](https://user-images.githubusercontent.com/79453625/166834915-b23c1002-47f3-4058-a9d6-4d5f8b364197.png)

**Comment by zFernand0** [comment]
Olá, @ViAndrade,
Qual é o erro que você esta vendo? Você pode tirar uma captura de tela semelhante a esta?
![image](https://user-images.githubusercontent.com/37381190/166982934-db93c008-158e-40c3-bb2c-d29bc0710a94.png)

FYI, I'm getting help from my wife to translate from Spanish to Portuguese 😋

**Comment by ViAndrade** [comment]
![image](https://user-images.githubusercontent.com/79453625/167029676-9e5a74cf-4719-47fa-9074-11266c3da9d3.png)

**Comment by zFernand0** [comment]
Muito obrigado @ViAndrade 
Parece ser um erro no arquivo
Por favor, você pode mandar seu `zowe.config.json` ?
Arquivo ta em `C:\Users\<ID>\.zowe\`

**Comment by ViAndrade** [comment]
Inside the zip file is the file zowe.config.json. I sent all the files that are related because it might help. I also sent some error prints, which arise when I open the VS.

![image](https://user-images.githubusercontent.com/79453625/167128252-f2792b83-4492-4a68-8bf3-999c84f90980.png)
![image](https://user-images.githubusercontent.com/79453625/167128437-014564a2-2216-4df2-a13b-a5dab00c5505.png)

[.zowe.zip](https://github.com/zowe/vscode-extension-for-zowe/files/8639910/default.zowe.zip)

**Comment by zFernand0** [comment]
Thank you for sharing : )
I see you are also discussing similar topics with Peter H on:
- https://github.com/zowe/vscode-extension-for-zowe/issues/1779

As a quick workaround to the problem, I suggest deleting this file and reloading the VSCode window.
That way Zowe Explorer will refresh and be able to initialize normally.
From there you can follow the [`Create a Team Configuration File`](https://github.com/zowe/vscode-extension-for-zowe/blob/master/docs/Early%20Access%20-%20Using%20Global%20Profile%20Configuration.md#create-a-team-configuration-file) guide 😋 

Espero que ajude! : )

**Comment by ViAndrade** [comment]
@zFernand0 Good! A question, I exclude only the file zowe.config.json? After deleting, do I close vscode and abro again?

**Comment by zFernand0** [comment]
It will probably be safer to delete both `zowe.config.json` and `zowe.schema.json`.
And after deleting, close and reopen vscode.
Then go through the guide: [Create a Team Configuration File](https://github.com/zowe/vscode-extension-for-zowe/blob/master/docs/Early%20Access%20-%20Using%20Global%20Profile%20Configuration.md#create-a-team-configuration-file)

**Comment by ViAndrade** [comment]
Hi, @zFernand0. I was able to solve the problem. Thank you for your help. God bless you!
