### ISSUE TITLE
Relative path for Zowe-Temp-Folder-Location

### ISSUE THREAD

**Issue by FALLAI-Denis** [zowe/vscode-extension-for-zowe#1053]
In our experience, the Zowe-Temp-Folder-Location parameter can only handle absolute paths.

We would like to be able to set a relative path, especially relative to the root folder of a workspace, in order to place temporary items inside the workspace.

Use case:
* use of a Git repository
* VS Code opened on the root folder of the local Git repository
* declaration of an ".imports" folder at the root of the workspace
* declaration of the ".imports" folder in the .gitignore file
* the ".imports" folder is used by the IBM Z Open Editor extension to search for "local" type copybooks / includes
* we would like all items opened by Zowe Explorer to be stored in the ".imports" folder (so that IBM Z Open Editor can find the copybooks / includes imported by Zowe Explorer)

**Comment by zdmullen** [comment]
@zFernand0 to add details about environmental variable reading etc.

**Comment by IgorCATech** [comment]
I'm not sure we are explaining this in our docs. The only doc we mention about this is Zowe Docs https://docs.zowe.org/stable/user-guide/ze-install.html#configuration 
here we only mention that it is possible to change the path but there's no information on absolute vs. relative paths. 

Do you feel this is something that our users need to be aware of?

**Comment by jellypuno** [comment]
Billie and Pete will come up with an approach and discuss it with the team
