### ISSUE TITLE
Extension icons not visible when running under WSL2 (Windows 10)

### ISSUE THREAD

**Issue by jguillaumes** [zowe/vscode-extension-for-zowe#1057]
**Describe the bug**

The extension icons are not visible when running Visual Studio Code in "remote WSL" mode using a WSL instance set up to version 2 (WSL2). If the same WSL instance is converted to WSL1 the icons are shown normally.

**To Reproduce**

1. Be sure you've got a working version of Code in Windows, with a working ZOWE Explorer extension set up.
1. Enable WSL version 2 and configure a linux distribution to run in that mode (Ubuntu works fine)
2. Start a WSL shell and invoke code from within it using ```code .``` to trigger the installation of the Remote WSL extension.
3. Install the ZOWE Explorer plugin into the remote Code instance.
4. The Zowe extension will be available and work, but you'll have to "blind click" the non-visible icon in the task bar.

**Screenshots**

- Code running under WSL2, icons not visible:

<img width="727" alt="Captura de pantalla 2020-11-02 111211" src="https://user-images.githubusercontent.com/1552242/97857901-ad517600-1cfe-11eb-818b-73ac4ea9cf40.png">

- Code running under WSL1, icons visible:

![Captura de pantalla 2020-11-02 112257](https://user-images.githubusercontent.com/1552242/97857917-b3475700-1cfe-11eb-9fd8-0ecdb08845eb.png)

**Desktop (please complete the following information):**

-   OS: WIndows 10 2004 (build 19041.572)
-   Zowe Explorer Version: 1.10.0
-   (Optional) Zowe CLI Version: 6.24.2
-   (Optional) Are you using Secure Credential Store? Yes

**Additional context**

- Linux kernel version: Linux U0180113 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Linux distribution: Ubuntu 20.04.1 LTS

The linux distribution is up to date, with all the packages to the last version. All the Windows updates have been applied.

**Comment by zdmullen** [comment]
We're going to look into this as a squad once we determine what we need to set up on our end. Thanks!

**Comment by crawr** [comment]
Hi, can you please confirm if this is still happening with our latest release? Thanks!
