### ISSUE TITLE
Multiple root nodes off profile

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#106]
## Problem

Users have requested the ability to have multiple "start points" in explorer style views that display host files. For example they want to see the members of dataset "PROD1.CNTL.*" and "MYHLQ.CNTL.*". We can currently do this by specifying a comma separated filter but we don't explicitly indicate this combination criteria in the view or have any logical separation between the results so our output is simply a result set. It would be more understandable if we allowed users to define these as separate filters and not mix the results.

For USS files we could provide comma separation in the filter which would display a combined result set but at least provide an indication of the filter query in the tree. I'm not sue however how obvious that would appear to the user. I suggest going further allowing users to specify multiple filters which showed the results under separate roots.

Jobs are a different case. The query can be a combination of Owner, Prefix and we should also include JobId. Since the parameters are && together it is not currently possible to show jobs owned by two different owners. If we provided the mechanism to define separate filters we would be able to do this  

## Proposed Implementation
To achieve this we need a new category of tree element: USS file root, Dataset root and Job root. Each of these elements would be associated with the filter operation and resulting output that is unique to that element. The major reason for providing this new element is to display the search criteria employed as it's label and provide a hook for other operations such that can be performed at that location. For example if you are in a root node you can create a new folder or file.

The parent of the "Root nodes"  element is a session node and a session node can contain multiple instances of the root node.

The children of the "Root nodes" are Jobs, Datasets or USSFiles which previously were children of the session node. The session node will now have the "+" sign menu item with tooltip dependent upon the type (Job, USS, dataset). For example, Add root filter, Add Search.. (To be decided) The resulting Root nodes would have a - sign to remove it and it's children along with tooltip stating remove.

For the initial release the dialog that pops up when the session node "+" menu is pressed is dependent up the type of object:
- USS File: a simple path name Q. Should we also provide comma separated ?
- Dataset: A highlevel qualifier.. Q. Should we keep this comma separated ?
- Jobs: An && combination of PREFIX= OWNER= JOBID=

Once the dialog is complete the new element is added to the tree without a collapsed/expanded indicator and the API called. Once a response is received an expanded icon is added and the items displayed as before under the session 

in the case of Jobs we should remove the menu items for Owner, Prefix etc and replace with a query magnifier glass as for the USS and datasets. I would recommend the filter dialog initially appears filled in greyed out style as out with  OWNER= PREFIX= JOBID=

**Comment by Colin-Stone** [comment]
Users require flexibility in filtering options for each of the three containers: USS, Datasets and Jobs. Users also require the ability to see multiple combinations of these.

To achieve this we need a new category of tree element: USS file root, Dataset root and Job root. Each of these elements would be associated with a filter operation and resulting output that is unique to that element. 

The parent of the "Root nodes" is element is a session node and a session node can contain multiple instances.

The children of the "Root nodes" are Jobs, Datasets or USSFiles which previously were children of the session node. The session node should now have the following menu item depending upon the type of object. For example, Add root filter, Add Search.. (To be decided) In each case it would be better to have a + sign to indicate adding a new root with the tooltip being descriptive. The Root nodes would have a - sign to remove it and it's children along with tooltip stating remove.

For the initial release the dialog that pops when a root node is added is dependent up the type of object:
- USS File: a simple path name
- Dataset: A highlevel qualifier.. Q. Should we keep comma separated ?
- Jobs: An && combination of PREFIX= OWNER= ID=

**Comment by Colin-Stone** [comment]
@MarkAckert I've updated the proposal to better describe what the intention is. Even if we decided not to have the multiple root nodes for now I think we still require a single root node under the profile that describes the filter criteria being used. This is also something we would need as and when we get to the single tree structure

**Comment by Colin-Stone** [comment]
@MikeBauerCA  I'm starting to have a change of mind regarding this approach to solving flexibility. The problem is the same one as you described in https://github.com/zowe/vscode-extension-for-zowe/issues/118 but I now think Favorites is a better solution than multiple nodes. In Datasets we save a search as a favorite. Then clicking it applies it. 

I have an issue to recreate the same function for uss favorites 
https://github.com/zowe/vscode-extension-for-zowe/issues/162 
and reckon we should implement favorites for Jobs 
https://github.com/zowe/vscode-extension-for-zowe/issues/163
and we are there. What do you think?

It then logically feels a bit like a GA version albeit ambitious for the end of this PI

**Comment by MikeBauerCA** [comment]
I would like my most recently used filters to be set on subsequent starts of VSCode. It would also be desirable to recall saved filters as you mention. Favorites could work, but another option would be to allow users to select from a list of saved filters or enter a new filter after clicking the magnifying glass. I do not see much of an issue with a single result set being returned. Adding nodes takes up more screen space.

**Comment by Colin-Stone** [comment]
> I would like my most recently used filters to be set on subsequent starts of VSCode. It would also be desirable to recall saved filters as you mention. Favorites could work, but another option would be to allow users to select from a list of saved filters or enter a new filter after clicking the magnifying glass. I do not see much of an issue with a single result set being returned when using comma separated patterns. Adding nodes takes up more screen space.

I propose closing/rejecting this issue but completing #118, #162 and #163 as our GA finishing line. I don't think it will be completed by the end of the current PI however

**Comment by MikeBauerCA** [comment]
I would support that proposal
