### ISSUE TITLE
Update ReadMe files after monorepo restructuring

### ISSUE THREAD

**Issue by crawr** [zowe/vscode-extension-for-zowe#1060]
**Is your feature request related to a problem? Please describe.**

After the folder restructuring, the ReadMe files need to be kept up to date as well. At the moment, the top level ReadMe also reflects the developer version instead of the marketplace version.

**Describe the solution you'd like**

Perhaps the new structure should be as follows:

```markdown
.
│-- README.md (Top level ReadMe featured in VScode marketplace)
│
└───docs
│   │-- Developer ReadMe (Install, Build, and Test the Extension)
│   │-- README-Extending.md
│   │-- README-Security.md
│   │-- README-Theia.md
│
└───packages
│   └───eslint-plugin-zowe-explorer
│   │   │-- ZE eslint plugin ReadMe
│   │
│   └───zowe-explorer-api
│   │   │-- ZE API ReadMe
│   │
│   └───zowe-explorer-ftp-extension
│   │   │-- ZE FTP extension ReadMe
│   │
│   └───zowe-explorer
│       │-- ZE Core ReadMe
```

**Additional context**

The references to the old file structure have to be updated, too (e.g. `./resources/testProfileData.example.ts`).

**Comment by IgorCATech** [comment]
+ add doc on such features as  alloc like + assoc prof + base prof to Readme

**Comment by zdmullen** [comment]
We need to expand the Theia readme with new setup details.

After you set up your Theia instance, the information there is sparse.

**Comment by IgorCATech** [comment]
@zdmullen When you talk about the Theia ReadMe, do you mean this one https://github.com/zowe/vscode-extension-for-zowe/blob/ReadMe_UPD/docs/README-Theia.md ?

**Comment by crawr** [comment]
A new Doc Updates Epic was opened to track all the related issues. This issue will focus on the top level readme update

**Comment by IgorCATech** [comment]
@jellypuno @crawr  Let's articulate this issue a bit more. 
Here are the suggested sections for the landing page readme:

- Short Introduction
- Available Documentation
- Directory Structure
- Requirements
- Getting Started (for developers)
     - Running tests {this can be part of the Getting Started section}
- How to Contribute
- License
- {another section}

Are these sections sufficient to cover what we want in the landing ReadMe? Also, do we want to agree on what exactly those sections will reflect?

**Comment by jellypuno** [comment]
Just an idea, do you think its good to add the Zowe Medium Link and some youtube vids from me and Bill?

**Comment by IgorCATech** [comment]
Absolutely, I think these Medium articles can help new users with faster onboarding thus they can contribute to the extension even sooner.

**Comment by jellypuno** [comment]
Notes from our parking lot:

- Let's make is shorter
- Point it towards to developers
- Docs learn about different aspects of Zowe Explorer
- 
- Getting Started -  simple run yarn. Maybe rename it to How to build it locally.
- Directory Structure - Brief intro to our main packages. 
- 
- Available Documentation - Contribute to awesome-zowe for zowe explorer links (youtube vids)
- External Links after license

**Comment by jellypuno** [comment]
I can do the contributions to awesome-zowe

**Comment by jellypuno** [comment]
awesome-zowe PR: https://github.com/tucker01/awesome-zowe/pull/7
