### ISSUE TITLE
Error on logger, prevents usage of plugin

### ISSUE THREAD

**Issue by mpettis** [zowe/vscode-extension-for-zowe#1067]
When starting VSCode, I get error:

```
Error encountered while activating and initializing logger! TypeError: Cannot read property 'debug' of undefined
```

This prevents VSCode from reading my profiles, and I cannot create them.  So I cannot access any mainframe systems.

- OS: Windows 7
- Zowe Explorer Version: 1.10.1

**Comment by mpettis** [comment]
Not sure why, but I got this to work after i removed my `.zowe` directory and created a new one from scratch.  I still contend there is a bug somewhere.

**Comment by jellypuno** [comment]
yes. this a known issue. 

tagging  to issue #1000

**Comment by katelynienaber** [comment]
Related to #1047?

**Comment by katelynienaber** [comment]
@mpettis From the fix you applied, this sounds like the same issue as #1047. So closing this issue in favor of that one.
