### ISSUE TITLE
Zowe Extension Not Working

### ISSUE THREAD

**Issue by aspiringHaasie** [zowe/vscode-extension-for-zowe#1069]
Issue Type: <b>Bug</b>

I am using Zowe in conjuction with the IBM Z Open Editor Extension. When I hit the plus (+) button next to each of the tables, the search bar doesn't show up. This has been a problem for about a week. I have tried uninstalling and reinstalling VS Code, refreshing, uninstalling and reinstalling the extensions, etc. Nothing has worked thus far.

Extension version: 1.10.1
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (3.28GB free)|
|Process Argv|--crash-reporter-id 0791fe06-d114-4b4c-b2f0-6153207aeb16|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jellypuno** [comment]
@aspiringHaasie Is this still an issue for you?

**Comment by aspiringHaasie** [comment]
Yes.

**Comment by jellypuno** [comment]
@aspiringHaasie ok. Additional Information will be helpful in investigating this.

1. Can you try again and then send the logs? It can be found here: C:\Users\YourUserName\.vscode\extensions\zowe.vscode-extension-for-zowe-1.10.1\logs

2. Are you using base profiles? Meaning did you login using `zowe auth login apiml`? If yes, how does your profile looks like?
3. Do you have Secure Credential Store installed?

**Comment by zdmullen** [comment]
@aspiringHaasie, could you provide responses to @jellypuno 's questions above?

**Comment by crawr** [comment]
Closing this issue. No new response received
