### ISSUE TITLE
Investigate performance impact on VS Code startup

### ISSUE THREAD

**Issue by tjohnsonBCM** [zowe/vscode-extension-for-zowe#107]
I have noticed that when the Zowe extension is enabled, other panels in the sidebar (particularly Source Control) take significantly longer to load. To verify this, I launched VS Code several times first with the extension disabled, and then several times with it enabled, and measured the time after clicking on "Source Control" in the sidebar until it loaded (meaning it no longer showed the "No source control providers registered" message). These were the results:
* Without Zowe extension - 3-4 sec
* With Zowe extension - 17-19 sec

While it is understandable for the Zowe extension itself to take a while to load, I would expect it to do so in an asynchronous manner that has minimal performance impact on the loading speed of other VS Code components.

**Comment by Colin-Stone** [comment]
I think we should look at this as things are likely to get worse as more code is added to the extension. I have been considering getting the extension to persist the last opened trees and automatically connect to them when started. But until we get a handle on why initialization is having such an impact we should hold back

**Comment by Colin-Stone** [comment]
@tjohnsonBCM Do you think this is still an issue?. Since I bypassed the syncSpawn operation in https://github.com/zowe/vscode-extension-for-zowe/pull/266 everything appears to be starting really quickly and I don't really know what to look into.

**Comment by tjohnsonBCM** [comment]
@Colin-Stone The situation is greatly improved. It seems there may still be a delay of a few seconds induced by the Zowe extension, but that is likely reasonable to expect. I'm happy with the performance of the extension as it stands currently, so unless others disagree I think this issue can be closed.

**Comment by Colin-Stone** [comment]
Thanks @tjohnsonBCM
