### ISSUE TITLE
Error loading Base Profile Created via Zowe CLI Within Zowe Explorer 

### ISSUE THREAD

**Issue by dkelosky** [zowe/vscode-extension-for-zowe#1073]
I'm using a base profile and am getting the following errors within Zowe Explorer:

`Retrieving response from zowe.GetJobs Error: Expect Error: Required object must be defined`
`Error: Profile Name test is inactive. Please check if your Zowe server is active or if the URL and port in your profile is correct.`

**Describe the bug**

**To Reproduce**

1. Start with no profiles
2. `zowe auth login apiml` and respond to prompts
3. `zowe profiles create zosmf test --host xxx --base-path api/v1 --dd`
4. verify `zowe jobs list jobs` is succesful
5. attempt to browse jobs or data sets in Zowe Explorer

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/14940561/99555988-f3f5d000-298e-11eb-8cd2-0e6a9bb9339d.png)

**Desktop (please complete the following information):**

- OS:  Windows 10
- Zowe Explorer Version: `1.10.1`
- (Optional) Zowe CLI Version: `7.0.0...@next`
- (Optional) Are you using Secure Credential Store? yes

**Additional context**

**Comment by jellypuno** [comment]
Can you try to do 2 things? 
- Click the Refresh Icon then try again. If this doesn't work.
- Try to reload VSC?

**Comment by dkelosky** [comment]
Thanks @jellypuno - I get the same results trying those two things.

**Comment by jellypuno** [comment]
I tried it and it is working for me

**Comment by jellypuno** [comment]
I tried it and it is working for me

**Comment by venkatzhub** [comment]
@jellypuno - you are using the same versions of Zowe Explorer and Zowe CLI as @dkelosky ?

**Comment by jellypuno** [comment]
@venkatzhub I'm using Zowe CLI 6.23.0. I'll try to upgrade to 7.0

**Comment by jellypuno** [comment]
Now, I'm having trouble with zowe auth 😢 

```
C:\Users
λ zowe auth login apiml
Command Error:
Command failed due to improper syntax
Command entered: "zowe auth login apiml"
Unknown group: auth
Did you mean:  plugins list?
Use "zowe --help" to view groups, commands, and options.

C:\Users
λ zowe -V
7.0.0-next.202003271736
```

**Comment by dkelosky** [comment]
I'm also using `7.0.0-next.202003271736` - however, I built from source on https://github.com/zowe/zowe-cli/tree/next

Apparently - this isn't published on npm 😢 .  Hopefully, it will be "soon" along with the daemon work.

**Comment by venkatzhub** [comment]
Here is the requested information to diagnose the issue: 

Zowe Explorer Version => 1.10.1
Zowe CLI Version => 6.23.0

[zowe.log](https://github.com/zowe/vscode-extension-for-zowe/files/5567575/zowe.log)
[imperative.log](https://github.com/zowe/vscode-extension-for-zowe/files/5567576/imperative.log)

**Comment by jellypuno** [comment]
@venkatzhub this is the error:

```
[2020/11/18 15:11:15.047] [DEBUG] [extension.js:73] Validate Error - Invalid Profile: Error: z/OSMF REST API Error:
http(s) request error event called
Error: self signed certificate in certificate chain
```

I want to confirm if you are connecting to apiml? if yes, please make sure that reject unauthorized is set to true and basepath is equal to APIML basepath

**Comment by venkatzhub** [comment]
The customer was indeed connecting using APIML. Here is what I got in an earlier email: 

zowe auth login apiml --host ${zowehost} --port ${zomwemlport} --user ${myuser} --password ${mypassticket}-ru false

zowe profiles create zosmf maint-zosmf --base-path api/v1 --disable-defaults

**Comment by jellypuno** [comment]
@venkatzhub ok. great. reject unauthorized should be set to true if connecting through apiml

**Comment by venkatzhub** [comment]
@jellypuno - based on the tests you did, is it fair to say that ru is not influencing the behavior?

**Comment by dkelosky** [comment]
In this case @jellypuno, would we want `false` for `rejectUnauthorized` since there are self signed certs in play?

**Comment by dkelosky** [comment]
From @zFernand0 :
`zowe profiles update base default --ru false` 

This still doesn't answer how / why `zowe jobs list jobs` runs without also getting a certificate error.

**Comment by dkelosky** [comment]
@venkatzhub - can you request the user test `zowe zos-jobs list jobs --zosmf-p maint-zosmf` (explicitly qualify the newly created profile?  Perhaps the command works picking up another, working default

**Comment by venkatzhub** [comment]
@dkelosky  - done!

**Comment by zdmullen** [comment]
So the customer with this particular issue came back and everything is working now. @dkelosky, shall I keep it open for what you experienced?

**Comment by dkelosky** [comment]
I didn't resolve this on my end yet, but I'll close until I can try to revalidate this again.
