### ISSUE TITLE
Allow refreshing / reloading spool files of jobs 

### ISSUE THREAD

**Issue by ChrisBoehmCA** [zowe/vscode-extension-for-zowe#1074]
**Is your feature request related to a problem? Please describe.**

I want to monitor the spool of a running (`ACTIVE` job status) job on z/OS. As is, the content is frozen at the point of time when you first click the spool file. 

**Describe the solution you'd like**

Having a "pull" button next to the spool file or something similar to the data set interface would be nice. Or simply clicking on the spool file again to update the contents.

**Describe alternatives you've considered**

None that I know of. Maybe if I went in to the temporary directory and manually deleted the backing local file it would trick the extension into downloading the content again. 

**Additional context**

Zowe Explorer v1.10.1

**Comment by lauren-li** [comment]
This sounds quite similar to #988 (Enable update of Job Logs). Perhaps we could combine these two issues/close one as duplicate?

**Comment by ChrisBoehmCA** [comment]
Yup no problem, sorry for the duplicate

**Comment by crawr** [comment]
closing in favor of #988
