### ISSUE TITLE
Sensitive terminology in Zowe Explorer

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#1080]
Identify sensitive terminology in the API ML source code to assess effort to adjust it as per guidelines: https://github.com/zowe/zlc/issues/199

**Comment by MikeBauerCA** [comment]
I noted one sensitive term here: https://github.com/zowe/vscode-extension-for-zowe/blob/ad0c7627931ddf99719652256da113eb5a709ae7/packages/zowe-explorer/theia_tests.Jenkinsfile#L11

**Comment by zFernand0** [comment]
I believe we need help with this one since it's configuration related on Wash.zowe.
@MarkAckert, @jackjia-ibm, @Roavill2, thoughts?

**Comment by jackjia-ibm** [comment]
@zFernand0 these are the replacement for the old build labels:

`ibm-jenkins-slave-dind` => `zowe-jenkins-agent-dind`
`ibm-jenkins-slave-nvm` => `zowe-jenkins-agent`

In the above example, it can be updated to `zowe-jenkins-agent-dind`.
