### ISSUE TITLE
It is strange to specify the full dataset name without splitting into project, group and type like in ISPF

### ISSUE THREAD

**Issue by nickImbirev** [zowe/vscode-extension-for-zowe#1084]
**AS IS:**

When you are trying to create a new dataset - you should specify all by yourself with dots. From my perspective, it is weird, because it is not intuitive and error providing approach.

**TO BE**

When you create dataset, you'll have several prompts: 
**Project, Group, Type**

Alternative and great proposal can be seen below in the comment: https://github.com/zowe/vscode-extension-for-zowe/issues/1084#issuecomment-735024201

**Comment by FALLAI-Denis** [comment]
@nickImbirev 
I think splitting "project" / "group" / "type" come from "SCLM", not "ISPF/PDF".
The use of separate fields to name a dataset is too restrictive because it is limited to 3 levels of dsname.
We never use this possibility.

Zowe Explorer is not ISPF/PDF ...
Zowe Explorer is closer to TSO than ISPF/PDF

What could be useful is that Zowe Explorer displays the list of datasets rather with a hierarchical representation of the levels of dsname, as in USS :
```
v lpar
  v project
    v group1
      > type1
      v type2
          membre1
          membre2
          ...  
    v group2
      > type3
```
A right click on a level of dsname would create a new dataset with the same prefix coming from the higher hierarchy.

**Comment by nickImbirev** [comment]
> @nickImbirev
> I think splitting "project" / "group" / "type" come from "SCLM", not "ISPF/PDF".
> The use of separate fields to name a dataset is too restrictive because it is limited to 3 levels of dsname.
> We never use this possibility.
> 
> Zowe Explorer is not ISPF/PDF ...
> Zowe Explorer is closer to TSO than ISPF/PDF
> 
> What could be useful is that Zowe Explorer displays the list of datasets rather with a hierarchical representation of the levels of dsname, as in USS :
> 
> ```
> v lpar
>   v project
>     v group1
>       > type1
>       v type2
>           membre1
>           membre2
>           ...  
>     v group2
>       > type3
> ```
> 
> A right click on a level of dsname would create a new dataset with the same prefix coming from the higher hierarchy.

Agree with you about the proposal, it would be an awesome enhancement and a great alternative for my initial proposal. I will update the description with mention of this comment. 

Thank you!

**Comment by FALLAI-Denis** [comment]
Perhaps we should leave the choice to the end user to choose his display mode:
- flat list, with full name of the dsnames
- hierarchical, with one level of hierarchy per level of dsname

To be managed either fixedly in the settings of the extension, or dynamically by allowing to switch from one display mode to another via the user interface.

Also add a filter on the local list in "ISPF/PDF 3.4" format, by allowing the wildcard character "*" or "**" on the 1st level of dsname:
- project. **. type: list all the dsnames with a hlq "project" and a "type" suffix
- **. type: all dsnames with a "type" suffix
- **. type (pref *): all members prefixed "pref" in the (pds) dsnames with "type" suffix

![image](https://user-images.githubusercontent.com/63861965/100583868-99903400-32eb-11eb-8ecd-5774e4a7f651.png)
