### ISSUE TITLE
It would be great to have the same as ISPF screen splitting for the tree view for the datasets

### ISSUE THREAD

**Issue by nickImbirev** [zowe/vscode-extension-for-zowe#1086]
**AS IS**
You have only one TreeView in sidebar without any other options.
_The problem is:_ when you are working with several libraries, it is hard to scroll between them.

**TO BE**
There should be ability to work with several TreeView sidebars (like in JetBrains products, for example).

**Alternative approach:**
There should be ability to work with several search filter results at the same time, it would be great feature to speed up the process of coding. (The example, can be seen in IDz Eclipse Extension from the IBM)

**Comment by travatine** [comment]
Hi,

Have you used the "Favourites" node?

![image](https://user-images.githubusercontent.com/17565183/103060929-a18a7d80-45e4-11eb-84b1-29d6c26111ae.png)

You can add a dataset or a query as a favourite and it will appear under the favourites node.

When you select a favourite item, the matching dataset or query is displayed.

**Comment by jellypuno** [comment]
@nickImbirev in Zowe Explorer v1.13.0, we can filter the datasets in this manner `HLQ1.*.COBOL, HLQ1.JCL(*EL*)`. This will display multiple datasets in the tree and at the same time filter `HLQ1.JCL` with members that has `EL` on the name. Additionally, you can use Favorites like @travatine mentioned. And if you need to search for your loaded datasets in the tree, you can also use `Cmd+Alt+P` to search for your datasets and USS files loaded in the tree. Would these features help?

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
