### ISSUE TITLE
When you are close the filter of Datasets (fold it), it starts refreshing

### ISSUE THREAD

**Issue by nickImbirev** [zowe/vscode-extension-for-zowe#1087]
**The flow is simple:**

1. Open VS Code
2. Open Zowe Explorer Extension
3. Establish connection
4. Try to filter for some datasets
5. Fold the filter after the successful search
6. It starts refreshing again.. 

**AS IS:**
During the **6** point, you cannot do anything at all, because the refresh is in process and this can take a while.

**TO BE**
Not refresh the filter results (fetching the datasets) during folding the filter results.

**Environment:**
Zowe Extension version - v1.10.1
VS Code version - 1.51.1
OS - MacOS Catalina

**Comment by zdmullen** [comment]
Hey Nikolay-- Lauren is looking at the refresh behavior throughout the extension in this Issue: #1048 
This should be covered there. Have a look at the list she has compiled though.

**Comment by lauren-li** [comment]
@nickImbirev I believe this issue is a duplicate of #754 (Requests are issued to z/OS when a tree item is being closed). Could you please take a look at it and confirm?

**Comment by nickImbirev** [comment]
> @nickImbirev I believe this issue is a duplicate of #754 (Requests are issued to z/OS when a tree item is being closed), although the specific steps you gave to recreate the issue are very much appreciated. Could you please take a look at #754 and confirm?

Yep, correct, I'll close this one
