### ISSUE TITLE
Retrieving Jobs doesn't work

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1088]
**Describe the bug**

Retrieving the submitted job doesn't work.

**To Reproduce**

1. Login to apiml using `zowe auth login apiml`
2. Add the service profile and submit a job
3. Click on the JobID. Make sure that the service profile is in the Jobs tree
4. Error happens.

**Expected behavior**

Jobs retrieved successfully

**Screenshots**

![image](https://user-images.githubusercontent.com/45042840/99970968-de244880-2d9c-11eb-903d-e2ba3b3f59fc.png)

**Desktop (please complete the following information):**

- OS: Windows
- Zowe Explorer Version: Latest
- (Optional) Zowe CLI Version: Latest
- (Optional) Are you using Secure Credential Store? No

**Additional context**

**Comment by jellypuno** [comment]
Hi @JillieBeanSim and @lauren-li , I have a question. I have the FTP extension installed and during my debugging session, I noticed that allProfiles array is being refreshed to its old state when the FTP extension is initially loaded.

I use the allProfiles array in getCombinedProfile function when I merge the info from base and zosmf profiles. Once the FTP extension is loaded, that combination is removed because the extension is calling the reloadProfiles API. I think we should change the reload part of the FTP extension so it won't affect the zosmf profiles. But what do you think?

**Comment by crawr** [comment]
Is this related to #1039 as well?
