### ISSUE TITLE
Use the --dd Disable defaults parameter when creating a profile

### ISSUE THREAD

**Issue by zdmullen** [zowe/vscode-extension-for-zowe#1090]
**Is your feature request related to a problem? Please describe.**

This a question/request. Should we pass the -dd (disable defaults) parameter from CLI when a user creates a new profile in Zowe Explorer? This would go along with the ability to have all parameters optional and support the use case with base profiles (that I need to create a zosmf or service profile that only has the base-path for the mediation layer. 

**Describe the solution you'd like**

A discussion of whether we want to pass this parameter and then an implementation (or not).

This in part is linked to our issues connected to base profiles (such as #1073 or #1044).

**Comment by jellypuno** [comment]
@katelynienaber Is it okay to close this issue?

**Comment by katelynienaber** [comment]
@jellypuno yes I think so.

I am not sure if #1044 can be closed. I found [this additional issue](https://github.com/zowe/vscode-extension-for-zowe/issues/1203) which is somewhat related...

**Comment by jellypuno** [comment]
Closing this issue. Fix is available in v1.12.1
