### ISSUE TITLE
Spike: Error is encountered when using RU false with base profiles using API ML

### ISSUE THREAD

**Issue by crawr** [zowe/vscode-extension-for-zowe#1094]
**Describe the bug**

An error message `Error: self signed certificate in certificate chain` is encountered when creating a session using `apimlAuthenticationToken` and `rejectUnauthorized = false` in the base and service profile.

The same profile combination is usable in the CLI, but not via ZE.

**To Reproduce**

1. Create a base profile using CLI (`zowe auth login apiml --ru false`)
2. Create a zosmf service profile containing just `rejectUnauthorized: false` and `basePath: api/v1`
3. Load this profile in ZE and filter datasets
4. Processing stops with: `Error: self signed certificate in certificate chain`

**Expected behavior**

The combined session from base and service profile with these contents can be used in ZE without errors

**Desktop (please complete the following information):**

- OS: Windows/Mac
- Zowe Explorer Version: v1.10.1
- (Optional) Zowe CLI Version: 6.21.1
- (Optional) Are you using Secure Credential Store? No

**Additional context**

Issue cannot be replicated using Broadcom API ML instance.

**Comment by dkelosky** [comment]
I'm getting similar results.  I don't have `rejectUnauthorized: false` in my z/OSMF service profile.  My error is:
```
[2020/12/09 09:11:01.025] [DEBUG] [extension.js:73] Validate Error - Invalid Profile: Error: z/OSMF REST API Error:
http(s) request error event called
Error: unable to verify the first certificate
```

`~/.zowe/profiiles/base/default.yaml`:
```
host: xxx
port: 61432
rejectUnauthorized: false
tokenType: apimlAuthenticationToken
tokenValue: 'managed by @zowe/secure-credential-store-for-zowe-cli'
```

`~/.zowe/profiiles/zosmf/default.yaml`
```
basePath: api/v1/ibmzosmf
```
