### ISSUE TITLE
Enhance Optional Profiles

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1095]
Currently, Optional Profiles are creating a profile with User and Pass as spaces. And because of this feature, it creates a lot of inconsistencies and contradictions with the recent Zowe SDK functionalities. I would like to enhance it and keep it consistent with the SDK so we can have a better profile experience.

**Comment by katelynienaber** [comment]
Link to [issue #1000](https://github.com/zowe/vscode-extension-for-zowe/issues/1000)

**Comment by jellypuno** [comment]
Closing issue. Fix is merged in v1.12.x
