### ISSUE TITLE
Profile Inactive Error

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1096]
We need to add more information in the profile inactive error. It is very vague.

**Comment by juler69** [comment]
I second this.  I have had an error for months now which makes Zowe Explorer unusable.  I can use the CLI just fine but the Explorer throws a profile inactive error for any profile I create either zosmf or rse and simply will not work.  I have no idea why because the CLI is using the same profile as explorer.

**Comment by jellypuno** [comment]
Hi @juler69 Thank you for letting us know. To help in the investigation of the error that you are experiencing, can you please answer the following questions:

1. Are you using other VSCode extensions such as FTP, Z Open Editor and RSE extension?
2. Are you logging in through API Mediation Layer? Did you use the command `zowe auth login apiml`?
3. How does your profile look like? What information does it contain?
4. Are you using secure credential store plugin? If you type `zowe plugins list`, Can you see the SCS there?
5. When you encounter the error, are there any information added in the logs? The logs can be found here: `C:\Users\YourUserName\.vscode\extensions\zowe.vscode-extension-for-zowe-1.10.1\logs`
6. Lastly, if you `right click on your profile > Disable validation` and then try to filter the datasets, what happens?

**Comment by juler69** [comment]
1. I have many extensions active but none of those listed or any other Broadcom / Zowe related extensions.
2. No
3. I have tried using zosmf and rse, neither works, both get the same issue:
`host: my.hostname.com
port: 1111
user: 'managed by Zowe Explorer'
password: 'managed by Zowe Explorer'
rejectUnauthorized: false
encoding: 0
responseTimeout: 5`
4. Yes
5. I use a Mac...
`[2020/12/09 09:29:19.807] [ERROR] [extension.js:73] [i [Error]: z/OSMF REST API Error:
http(s) request error event called
Error: write EPROTO 140239298518392:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

	at s.populateError (/Users/p719952/.vscode/extensions/zowe.vscode-extension-for-zowe-1.10.1/out/src/extension.js:69:308126)
	at ClientRequest.<anonymous> (/Users/p719952/.vscode/extensions/zowe.vscode-extension-for-zowe-1.10.1/out/src/extension.js:69:301302)
	at ClientRequest.emit (events.js:223:5)
	at ClientRequest.EventEmitter.emit (domain.js:475:20)
	at onerror (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/https-proxy-agent/node_modules/agent-base/index.js:101:9)
	at callbackError (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/https-proxy-agent/node_modules/agent-base/index.js:123:5)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)] {
  mDetails: {
    msg: 'z/OSMF REST API Error:\n' +
      'http(s) request error event called\n' +
      'Error: write EPROTO 140239298518392:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:\n',
    causeErrors: [Error: write EPROTO 140239298518392:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:
    
    	at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:16)] {
      errno: 'EPROTO',
      code: 'EPROTO',
      syscall: 'write'
    },
    source: 'client',
    errorCode: undefined,
    port: 1111,
    host: 'example.com',
    basePath: '',
    httpStatus: undefined,
    errno: undefined,
    syscall: undefined,
    payload: undefined,
    headers: [ [Object], [Object], [Object] ],
    resource: '/zosmf/restfiles/ds?dslevel=A123456.*',
    request: 'GET',
    additionalDetails: 'HTTP(S) client encountered an error. Request could not be initiated to host.\n' +
      'Review connection details (host, port) and ensure correctness.\n' +
      '\n' +
      'Host:      example.com\n' +
      'Port:      1111\n' +
      'Base Path: \n' +
      'Resource:  /zosmf/restfiles/ds?dslevel=A123456.*\n' +
      'Request:   GET\n' +
      'Headers:   [{"X-IBM-Attributes":"base"},{"X-IBM-Max-Items":"0"},{"X-CSRF-ZOSMF-HEADER":true}]\n' +
      'Payload:   undefined'
  },
  mMessage: 'z/OSMF REST API Error:\n' +
    'http(s) request error event called\n' +
    'Error: write EPROTO 140239298518392:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:\n'
}
`
6. I tried this and still get:
Retrieving response from zowe.List Error: z/OSMF REST API Error: http(s) request error event called Error: write EPROTO 140239298518392:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

**Comment by juler69** [comment]
I fiddled with my comment but simply couldn't get the log to show as code sorry.

**Comment by jellypuno** [comment]
@juler69 are you using a proxy? You have an error in your protocol. Zowe Explorer sets the protocol to  https and it seems like your server is not accepting that.

**Comment by juler69** [comment]
Yes there is a proxy, but the Zowe CLI doesn't have any problem with it, is Explorer different?

**Comment by jellypuno** [comment]
Are you using tokens? I want to re-create this but I need to know what are the fields available in your profile.

Tagging @dkelosky for awareness.

**Comment by juler69** [comment]
When you say profile, is it not the details I added in point 3 in an earlier post? (Repeated here to save you hunting...)
`
host: my.hostname.com 
port: 1111 
user: \'managed by Zowe Explorer\' 
password: \'managed by Zowe Explorer\' 
rejectUnauthorized: false 
encoding: 0 
responseTimeout: 5
`
No I am not using tokens.

**Comment by jellypuno** [comment]
@juler69 you are right. Sorry about that 😊

**Comment by juler69** [comment]
Any update?

**Comment by jellypuno** [comment]
[PR](https://github.com/zowe/vscode-extension-for-zowe/pull/1100) is still open. If you want, you can fetch the branch and test it there. Let me know if you are still experiencing the issues

**Comment by juler69** [comment]
I wouldn't have a clue how to do that sorry...happy to wait for the official drop.  Thanks for the reply.

**Comment by jellypuno** [comment]
@juler69 The fix will be available on v1.12

**Comment by Krishan0031** [comment]
Hi Team,

I am facing same issue, i created new connection of http://ip:port, but it still gives me same error that its an HTTP(S) connection.
Could someone please let me know the solution to fix it ?

Do i need some JAva updates for it, or some CLI ?

I am using VS Code --> Zowe Explorer
:
![image](https://github.com/zowe/vscode-extension-for-zowe/assets/98732548/4fd286dc-7870-42b0-bc35-40eb18dc5d43)


errorDetails: [i [Error]: z/OSMF REST API Error:
  http(s) request error event called
  Error: write EPROTO 12081672:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:..\..\third_party\boringssl\src\ssl\tls_record.cc:231:
  
  	at o.populateError (c:\Users\Krishan.Singh\.vscode\extensions\zowe.vscode-extension-for-zowe-2.9.1\out\src\extension.js:80:20446)
  	at ClientRequest.<anonymous> (c:\Users\Krishan.Singh\.vscode\extensions\zowe.vscode-extension-for-zowe-2.9.1\out\src\extension.js:80:12433)
  	at ClientRequest.emit (node:events:525:35)
  	at TLSSocket.socketErrorListener (node:_http_client:481:9)
  	at TLSSocket.emit (node:events:513:28)
  	at emitErrorNT (node:internal/streams/destroy:157:8)
  	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
  	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)] {
    mDetails: {
      msg: 'z/OSMF REST API Error:\n' +
        'http(s) request error event called\n' +
        'Error: write EPROTO 12081672:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:..\\..\\third_party\\boringssl\\src\\ssl\\tls_record.cc:231:\n',
      causeErrors: [Error: write EPROTO 12081672:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:..\..\third_party\boringssl\src\ssl\tls_record.cc:231:
      
      	at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] {
        errno: -4046,
        code: 'EPROTO',
        syscall: 'write'
      },
      source: 'client',
      errorCode: undefined,
      **protocol: 'https',**
      port: 23,
      host: '999.999.99.99',
      basePath: '',
      httpStatus: undefined,
      errno: undefined,
      syscall: undefined,
