### ISSUE TITLE
Create a better landing Readme for the whole monorepo

### ISSUE THREAD

**Issue by zdmullen** [zowe/vscode-extension-for-zowe#1107]
**Is your feature request related to a problem? Please describe.**

Currently we have the readme for Zowe Explorer duplicated at the top level for the whole repo. We'll need to specify the different components of the monorepo and provide guidance at that top level. 

**Describe the solution you'd like**

A new readme for the whole repo. 

**Additional context**

This follows PR #1068.

**Comment by IgorCATech** [comment]
I've added this 1.12 milestone to this issue. @zdmullen  Should things change, please update accordingly

**Comment by zdmullen** [comment]
Also, please consult @lauren-li and @phaumer about the readme for the FTP extension.

**Comment by crawr** [comment]
closing in favor of #1060
