### ISSUE TITLE
Add an icon for the PDS member search filter

### ISSUE THREAD

**Issue by zdmullen** [zowe/vscode-extension-for-zowe#1112]
**Is your feature request related to a problem? Please describe.**

I'd like to have an icon or marker on the folder where I've done a search filter for particular members. This follows from the functionality implemented by @JillieBeanSim from issue #868 (PR #1072 ). 

**Describe the solution you'd like**

Utilize the icon that @jelaplan is developing now.

**Comment by lauren-li** [comment]
@jelaplan @JillieBeanSim I just realized, VS Code already has a filter icon in its UI. Maybe we can take it and paste a smaller version onto the lower left corner of the (non-profile) folder icons?:

<img width="331" alt="Screen Shot 2020-12-17 at 7 37 21 AM" src="https://user-images.githubusercontent.com/45975633/102495245-dc6c3e80-4043-11eb-8dae-5d12db4b77f5.png">
