### ISSUE TITLE
Copy Paste

### ISSUE THREAD

**Issue by moueza** [zowe/vscode-extension-for-zowe#1115]
**Describe the bug**
Copy paste with error :
`Error running command zowe.pasteDataSet: z/OSMF REST API Error:
Rest API failure with HTTP(S) status 500
category: 4
rc:       20
reason:   0
message:  Copy dataset failed
details: 
  - ISRZ002 Authorization failed - You may not use this protected data set. Open 913 abend.

. This is likely caused by the extension that contributes zowe.pasteDataSet.`

**To Reproduce**
steps from pdf https://mtm.masterthemainframe.com/forum/t/files-for-miles-pds1/30

 
**Desktop (please complete the following information):**

- OS: Linux Ubuntu 20.10
- Zowe Explorer Version: 1.11.1

**Comment by jellypuno** [comment]
@moueza please check the authorization that you have in accessing the protected dataset. This is not a Zowe Explorer issue but a Mainframe Access issue.
