### ISSUE TITLE
file occludes others

### ISSUE THREAD

**Issue by moueza** [zowe/vscode-extension-for-zowe#1117]
Open Mainframe Project : in id.JCJ when I open CBL0001J, then CBL0002J, CBL0001J is closed in the editor, instead of having both files opened.

**Comment by zdmullen** [comment]
Hi! Thanks for opening the issue. This has actually been mentioned before, in issue #509. We'll talk about it in the squad though in future planning sessions. Thanks again!

**Comment by jellypuno** [comment]
closing in favor of #509
