### ISSUE TITLE
Create a new profile text

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/vscode-extension-for-zowe#1123]
After clicking the `+` icon on the DATA SETS tree to create a new profile, I see this:
![image](https://user-images.githubusercontent.com/35504792/104058088-2f5b9080-51c1-11eb-9e0a-d05a01244f1c.png)

`Add` should be lowercase
`USS Explorer` should be `DATA SETS Explorer`
The text box uses the term "profile" and the button uses the term "connection".

OS: Windows 10 & Ubuntu 16.04
Zowe Explorer Version: 1.11.1

**Comment by zdmullen** [comment]
Looking back through issues and I found this #885. Needless to say, we haven't got to it yet. Thanks for pointing it out again, @MikeBauerCA!

**Comment by zdmullen** [comment]
Perhaps this deserves a review of all strings in general with a tech writer. @IgorCATech 

All the strings are externalized and the review can be done easily.

**Comment by jellypuno** [comment]
We could make this string generic because we are sharing this function across all trees

https://github.com/zowe/vscode-extension-for-zowe/blob/master/packages/zowe-explorer/src/Profiles.ts#L311

**Comment by IgorCATech** [comment]
@zdmullen I'd like to help with the doc matters here, but currently am 100% allocated to something that requires immediate attention. I should have more time next week but don't want to promise

**Comment by jellypuno** [comment]
Will assign this issue to [Nikolay](https://github.com/nickImbirev) as soon as he is added to the Zowe Org

**Comment by anokhikastia** [comment]
I would be interested in working on this issue.
