### ISSUE TITLE
Multiple "validating" messages

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/vscode-extension-for-zowe#1126]
When I attempt to perform an initial action, I receive multiple validation messages:
![image](https://user-images.githubusercontent.com/35504792/104060029-4a7bcf80-51c4-11eb-9955-46be95d3eb67.png)

I believe I should only receive one notification.

OS: Windows 10 & Ubuntu 16.04
Zowe Explorer Version: 1.11.1

**Comment by jellypuno** [comment]
@MikeBauerCA This issue is now fixed in v1.12.1
