### ISSUE TITLE
Reject Unauthorized Value defaults back to true when editing profile

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/vscode-extension-for-zowe#1127]
When using ZE, if you just want to update one field, like password, you are presented with all of the prompts. If I had previously selected false for reject unauthorized, I would expect it to be prepopulated with false when editing. But nothing is prepopulated and if I quickly proceed through the remaining prompts, I will accidentally change the value to true.
![image](https://user-images.githubusercontent.com/35504792/104060706-4ef4b800-51c5-11eb-8a2b-44a4a3b0084d.png)

OS: Windows 10 & Ubuntu 16.04
Zowe Explorer Version: 1.11.1

**Comment by zdmullen** [comment]
The question here is whether there is a value associated with this quick-pick item. We'll have to research it.

**Comment by JillieBeanSim** [comment]
@jellypuno after investigating how to pre-select/pre-highlight options in the quick pick I have found that this is only available if the multi select is true which we do not want with a true/false option.  We could add the preselected value in the text box but it would only show as a helpful hint like the description is doing now vs a pre-filled value and still cannot just be entered passed if the false value is what should be chosen

**Comment by katelynienaber** [comment]
@JillieBeanSim could we maybe dynamically add the options in order, based on the info in the profile?

Like if True is in the profile, then we add that first to the quickPick options list? And vice versa if False is in profile.

**Comment by JillieBeanSim** [comment]
@katelynienaber I already have a PR in for this https://github.com/zowe/vscode-extension-for-zowe/pull/1218
