### ISSUE TITLE
Improve profile update integration between Zowe Explorer and Zowe CLI

### ISSUE THREAD

**Issue by lauren-li** [zowe/vscode-extension-for-zowe#1138]
**Is your feature request related to a problem? Please describe.**

When I am using Zowe CLI within VS Code's terminal to create a Zowe profile, and then try to use the profile in Zowe Explorer, the profile does not appear in the list of available profiles to add, until I click the "Refresh" arrow button or restart VS Code.

**Describe the solution you'd like**

I would like profiles I create/update outside of Zowe Explorer to be updated automatically in Zowe Explorer, without additional actions needed, even if they were updated externally (e.g. if password or config was changed in Zowe CLI or otherwise outside of Zowe Explorer).

**Describe alternatives you've considered**

Currently, users can get their latest profile information by clicking the "Refresh" button, or by just restarting VS Code. This extra step is particularly unfriendly to new users who may be trying to use both Zowe CLI and Zowe Explorer together in VS Code.

**Comment by crawr** [comment]
I believe this was requested before as well via issue #752

**Comment by lauren-li** [comment]
> I believe this was requested before as well via issue #752

@crawr Thanks for bringing this to my attention! I remembered the Zowe Explorer squad talked about this before, but was unable to find this existing issue for it so I made one. I'll close mine as a duplicate.
