### ISSUE TITLE
Remove favorite Profile from all the trees in THEIA and VScode not working

### ISSUE THREAD

**Issue by deepali-hub** [zowe/vscode-extension-for-zowe#1144]
**Describe the bug**

**To Reproduce**

1. Go to THEIA or VSCODE
2. Add profile to Favorites (Under any tree Datasets/USS/Jobs)
3. Go to Favorites
4. Right click on favorite profile and select "Remove profile from Favorites" and select "Continue"
5. Now you can see profile is removed from Favorite tab but refresh the page and you can see same profile in Favorites

**Expected behavior**

Profile should remove from favorite

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Zowe Explorer Version: 1.11.1
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by lauren-li** [comment]
Thanks @deepali-hub for catching this. The logic was missing updating the settings file when the user clicked "Continue". Can you please see if this issue is fixed in PR #1151?

**Comment by deepali-hub** [comment]
Thanks @lauren-li I have verified the issue in PR #1151 and now it is fixed and working as expected .

**Comment by crawr** [comment]
Fixed in v1.12.1
