### ISSUE TITLE
Issues found in the current master branch

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1147]
This is a compilation of all the errors that I've seen in the current master branch. These are functionalities that are currently working in v1.11.1

## Searching for Datasets

This is currently addressed by PR #1146 

![SEARCHpdS](https://user-images.githubusercontent.com/45042840/105174958-97946580-5b23-11eb-870e-414f17a5dc49.gif)

## Get List Informational Message appears too much

![GetList](https://user-images.githubusercontent.com/45042840/105175401-25705080-5b24-11eb-9de0-c503f509e484.gif)

## Issue with log-in. 

For some reason, the update of allProfiles variable is not correct. @jellypuno is investigating this.

![LoginErr](https://user-images.githubusercontent.com/45042840/105175532-59e40c80-5b24-11eb-8aaf-5d9d71fb0a6e.gif)

## Validation Error

When trying to use the Disable Validation, the context menu does not change to enable and the dataset tree doesn't disable the validation

![VAlidationIssue](https://user-images.githubusercontent.com/45042840/105175636-8566f700-5b24-11eb-8b93-df7b8174c5d7.gif)

## Prompt Error

When I cancel the prompting of my profile, the prompt appears again. If I try to use my other profile, the prompt will appear again.

@katelynienaber says: I'm fixing this issue in PR #1150.

![PromptErr](https://user-images.githubusercontent.com/45042840/105175740-a16a9880-5b24-11eb-9048-ca980e1bfbdc.gif)

**Comment by ChrisBoehmCA** [comment]
I can confirm I am seeing many duplicate messages whenever I download USS files in addition to data sets. For USS It seems like I sometimes get 5-6 duplicates when opening a file

![image](https://user-images.githubusercontent.com/42545737/106766047-79d8fd00-6607-11eb-8dd0-2ababfc41c8c.png)

**Comment by crawr** [comment]
Fixed in v1.12.1
