### ISSUE TITLE
Spike: Investigate the use of color and graphics in the explorer views

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#115]
As more element types are being added to the tree structure we need to consider the best UX experience enabling users to easily distinguish between them.

Potentially work with themes.

**Comment by jelaplan** [comment]
@Colin-Stone Could you share  your ideas with me and @jayenzi . I'm wary of some rainbow look. Tools like Windows explorer and Mac Finder generally don't use color to distinguish file types. They often rely on file type icons and file extensions to distinguish file types. It is common to support sorting on file type as well.

**Comment by Colin-Stone** [comment]
Hi John. I know exactly what you mean hence why I created this spike. Part of the motivation is that I would like to set the direction for use of color and graphics rather than "leave it open to interpretation". All input welcome. Here are some of the most current scenarios.

1. I have a long term goal of merging all three of the current views into one with nodes instead representing USS, Datasets and Jobs.  Additionally these nodes could have multiple roots so not restricted to the one as we have currently. so.. It would benefit usability if the use of color or graphics to the left of the node or multiple root made them stand out and indicate a division. 
2. There is a menu function that downloads file as binary and we should have a facility to add a decorators to indicate this (for example)
3. I would like small graphics that can indicate datasets with members and potentially other decorators that would indicate say Enhanced datasets
4. We store file locally with a suffix so that syntax coloring can be applied. From the explorer views it would be good if these items were shown using the same theme as in the standard VSCode file view

**Comment by Colin-Stone** [comment]
I would like to use the VSCode minimal graphics on the extension. I have mocked (aka virtually implemented) this up for the Dataset view. The first image shows the use of the "root folder" images on the session and on Favorites 
![image](https://user-images.githubusercontent.com/30794003/61865498-37d7e280-aecb-11e9-94be-8aa82f2b949b.png)
The next image shows them expanded. Dataset libraries have a plain folder and all folders are expandable. Files are simple document images however at a later stage I would like specific documents that images indicate the file type (e.g. assembler)
![image](https://user-images.githubusercontent.com/30794003/61865528-48885880-aecb-11e9-950e-3d07c98565c4.png)
The Favorites have an additional icon the magnifying glass indicating a search.
![image](https://user-images.githubusercontent.com/30794003/61865551-5211c080-aecb-11e9-9c48-5c15cb5531ad.png)
I would like to apply these styles to the USS and Jobs views for consistency across the views

**Comment by Colin-Stone** [comment]
Conclusion is to proceed with these images for all three views. Future evolutions will include explicit file/document icons for files recognized as a certain type such as assembler, cobol etc. I'm still considering use of color when we look at reducing the three sections into one.
