### ISSUE TITLE
Improvements to Regression Testing

### ISSUE THREAD

**Issue by zdmullen** [zowe/vscode-extension-for-zowe#1154]
**Is your feature request related to a problem? Please describe.**

This is a follow-up to the PR that Deepali introduced recently (#1005). Two requests were made for continued improvement:

- Include a better way to figure out what fields are prompted for the profile creation
- Introduce a cleanup routine before or after the tests. The behavior between running the tests from the pipeline and running locally can differ. See the notes for details.

**Describe the solution you'd like**

Improve the tests based on these two points. 

**Describe alternatives you've considered**

**Additional context**

Reviewer (Richelle) comments: 
Initially, I had a problem running the test locally since my CLI version is not the same as the one in the repo. As I mentioned in my other comment, there could be a better way to figure out what fields are prompted for the profile creation. But I think that could be handled in a separate PR.
Another point of improvement that I saw was that perhaps there should be a cleanup routine before or after the tests. Running the tests as-is in the pipeline is fine since a new docker image is created per build. But locally, I ran the tests without the headless option and I saw that the creation of new profiles failed because the profile name is existing; but the tests passed because it was able to find the profile name in the tree. This could be an issue if the profile creation really failed.
I am fine with going with this PR for 1.12 and we can handle the improvements in a later version, especially since this is internal and transparent to the end user.

Just to document how I was able to run the tests locally:

Make sure my geckodriver and chromedriver is updated and compatible with my browser versions
Update my zowe-cli version to 6.24.4 same as in the yarn.lock file
Delete the zosmf_meta.yaml and allow the new version of the cli to create a new one
Compile the project
Start a local Theia instance
Run the Theia tests

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
