### ISSUE TITLE
Support for configuration file that Zowe CLI @next provides

### ISSUE THREAD

**Issue by zdmullen** [zowe/vscode-extension-for-zowe#1160]
**Is your feature request related to a problem? Please describe.**
I would like to take advantage of the configuration file that Zowe CLI @next provides. I see the use case as the following:

I'm Michelle and I receive a config.json file from one of my colleagues. I upload this file to my project (or globally). I go to Zowe Explorer and want to get to work. Because I have the config file, Zowe Explorer will display the profiles* that I could utilize for my work. When I click on the profile in the tree that I want to use to look at datasets, I am prompted for my credentials with two dialog boxes*. Then I can view the datasets and get started.

Notes: 

- *1: Zowe Explorer will need to get the appropriate profile objects from the Zowe SDK, i.e. service profile, or base + service URL, etc. 

- *2: There could be more dialog boxes if information is missing. Of course, in the typical, or ideal, situation, Michelle only needs to provide credentials
- These dialogs correspond to the zowe config secure command from the CLI. Alternatively, if the profile information comes from a base profile associated with the API ML, the prompts will correspond to the zowe auth login apiml commands
Zowe Explorer prompts --> user enters info --> this is sent to SDK, which deals with it and stores into the config
- UX: For this initial iteration, we will only have the above dialogs. We will not have any UI for initializing the config file, nor will we have a web view for management. 

Technical issues:
- Loading the profiles into the tree on opening Zowe Explorer may affect refresh/favorites that were part of a previous project you had open (see next)
- Figuring out the context (project, switched folder etc. in VS Code) is not yet something which Zowe Explorer can do. This will require some effort  
- Zowe Explorer will need to have the information of the profiles nicely rounded/put together by the SDK (noted in the SDK issue already)
- 
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jellypuno** [comment]
Closing in favor #1181
