### ISSUE TITLE
Zowe Explorer does not activate when there are issues with profiles or settings

### ISSUE THREAD

**Issue by phaumer** [zowe/vscode-extension-for-zowe#1163]
**Describe the bug**

There are various use cases in which user reported problems in Slack or here where Zowe Explorer does not activate. Users who do not know about VS Code behavior just report that Zowe Explorer stopped responding. The problem is that activation performs too many long running operations such as reading profiles that can fail and are not handled correctly. 

**To Reproduce**

1. Edit your profiles to make them invalid
2. Start VS Code 
3. Tree browsers appear empty

**Expected behavior**

Activation of an extension, especially one that starts up when VS Code starts, should be minimal and should never fail.  Problems with profiles and settings need to be reported, but the extension needs to not fail starting based on the issues and needs to be able to recover. 

**Desktop (please complete the following information):**

- OS: any
- Zowe Explorer Version: any
- (Optional) Zowe CLI Version: any
- (Optional) Are you using Secure Credential Store? both

**Additional context**

**Comment by zdmullen** [comment]
Following this effort, #1015 Zowe Explorer Fails to Load Old Profiles After Setting Zowe Security: Credential Key can be examined, since it also relates to activation.
