### ISSUE TITLE
Research: Configuration file in @next of Imperative

### ISSUE THREAD

**Issue by zdmullen** [zowe/vscode-extension-for-zowe#1165]
**Is your feature request related to a problem? Please describe.**

As a developer, I want to better understand what the @next version of Imperative and the SDK provide in terms of the configuration json file experience. This research will better help the Explorers squad understand what they need to do to support the configuration file for users of Zowe Explorer. 

This is part of the effort of issue #1181.

**Describe the solution you'd like**

Experiment with @next and take notes about the configuration file as well as how the SDK handles profile information. 

**Describe alternatives you've considered**

**Additional context**

**Comment by VitGottwald** [comment]
The first two resources to get familiar with the config file in @next version of CLI I would suggest are

- [Zowe CLI — Getting Started, Made Easy!](https://medium.com/zowe/zowe-cli-getting-started-made-easy-f53d769c678e)
- [Using global profile configuration with Zowe CLI](https://github.com/zowe/zowe-cli/blob/next/docs/Early%20Access%20-%20Using%20Global%20Profile%20Configuration.md)

When I was following the instructions I ran into a small issue and documented it here https://github.com/zowe/zowe-cli/issues/949.

**Comment by VitGottwald** [comment]
The way the config file is implemented today, it has a concept of nesting profiles to inherit properties and a concept of user overrides (in the form of `zowe.config.user.json`. It is briefly described in the medium article (first link above). But I have not seen a deeper discussion about the intended benefits vs costs of this approach.
