### ISSUE TITLE
Issuing Commands

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1168]
**Describe the bug**

I have a profile that doesn't have a Username and Password field in my yaml file. When I try to right-click > Issue Command, this prompt appeared:

![image](https://user-images.githubusercontent.com/45042840/106150231-69460400-617b-11eb-9d31-6ae6cc90ba48.png)

**To Reproduce**

1. Create a profile that doesn't have a username and password
2. Right Click > Issue Command
3. The prompt to select a profile  appears

**Expected behavior**

I expect that it will prompt me for my credentials rather than select a profile

**Screenshots**

![image](https://user-images.githubusercontent.com/45042840/106150375-9397c180-617b-11eb-8306-f306b3392990.png)

**Desktop (please complete the following information):**

- OS:
- Zowe Explorer Version:
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by JillieBeanSim** [comment]
Addressed with PR #1231
