### ISSUE TITLE
Favorites not updated when password is changed

### ISSUE THREAD

**Issue by gorelikg** [zowe/vscode-extension-for-zowe#1170]
**Describe the bug**

Recently I updated my MVS password. Once i had the new password, I edit my existing data set, uss, and jobs profiles with the new password. Although the primary 'profile' is now working properly (i'm able to search, view, etc), it appears my 'favorites' are still using the old password. A restart of Visual Studio Code appears to correct the issue. (After i received the error last night, i shut down vsc and my laptop, i started it up and tried to reproduce it, and i'm no longer receiving the error.) 

**To Reproduce**
1. create favorite data sets
2. change the Data Set profile password
3. attempt to access the favorite data sets content
4. zowe encountered login error accessing the favorite entity

**Expected behavior**
I would have expected the 'favorite' entities to work once i updated the 'profile' password with no addition steps

**Desktop (please complete the following information):**

- OS: macOs BitSur (11.1)
- Zowe Explorer Version: 1.11.1 in VSC
- (Optional) Zowe CLI Version: n/a
- (Optional) Are you using Secure Credential Store? no

**Additional context**

**Comment by lauren-li** [comment]
Thank you @gorelikg for notifying us of this issue! I'm glad you are no longer experiencing it. We'll leave this issue open a while in case anyone else may have encountered it. Please don't hesitate to update us here if you start to see it happening again or otherwise want to share additional information about it. Thanks again!

**Comment by crawr** [comment]
Closing this issue, no new feedback received.
