### ISSUE TITLE
correct encoding of national characters (1141) only by explicit "pull from mainframe"

### ISSUE THREAD

**Issue by jHeidenberger** [zowe/vscode-extension-for-zowe#1171]
Hello, 

I work with two encoding profiles: IBM 1047 and IBM 1141. When opening files with encoding 1141, the national characters are displayed in encoding 1047. I have to explicitly click on button "Pull from Mainframe" to get the characters in the editor in encoding 1141. The error occurs only since some time, possibly with an update of the extension. If I don't use "pull from mainframe" I get the following error message when I try to  save the file:
“Failed to save …: The content of the file is newer”. 
The national characters are then displayed to me as changes.
Thanks in ad advance! 

Best regards, Jörg 

**To Reproduce**

**Screenshots**
before "Pull from Mainframe"
![image](https://user-images.githubusercontent.com/57558300/106266174-681ee080-6228-11eb-86ed-b263cdc23dca.png)

after "Pull from Mainframe"
![image](https://user-images.githubusercontent.com/57558300/106267440-ec259800-6229-11eb-9a47-ab4f2dfc0b9b.png)

**Desktop:**

- OS: Windows_NT x64 10.0.18363
- VSC: 1.51.0 
- Zowe Explorer Version: 1.11.1
- (Optional) Zowe CLI Version: 1.17.0
- (Optional) Are you using Secure Credential Store? no

**Comment by jellypuno** [comment]
@dkelosky

**Comment by jellypuno** [comment]
@jJeidenberger Do you think this related to #923 or #260

**Comment by jJeidenberger** [comment]
> @jJeidenberger Do you think this related to #923 or #260

@jellypuno Thanks for the fast reply. No, I don't think so. National char profiles are a new function and it worked fine in the past months but suddenly the profiles are not automatically considered anymore.

**Comment by fbeyl** [comment]
@jJeieidenberger What encoding did you specify in the profile?

**Comment by jHeidenberger** [comment]
@fbeyl  Hello, 
thank you very much for your help and you are right. I want to work with two profiles (1047, 1141). However, even under the 1141 encoding profile, I first get encoding 1047. An explicit pull then shows me the files in encoding 1141. I have now deleted the profile with encoding 1047, restarted VSC, but still have the same problem. 
Best regards

**Comment by jHeidenberger** [comment]
@fbeyl maybe there is a problem with my filetag? Files tagged with ISO-8859-1 are opened with the correct enconding 1141. Files tagged with IBM-1141 are opend with 1047 (I guess) and after pull the encoding is changed to 1141.

**Comment by fbeyl** [comment]
Now I'm puzzled ... ISO-8859-1 is an ascii superset where IBM-1141 is an ebcdic superset ? Can you share screenshot with output from ls -alT command?

**Comment by fbeyl** [comment]
@jHeidenberger I think file tags are not yet used by explorer, see https://github.com/zowe/vscode-extension-for-zowe/issues/887 
I still have similar issue but can't reproduce, I have the impression something goes wrong when using two connections simultaneous.

**Comment by jHeidenberger** [comment]
Hello,
I think it is not a problem of parallel profiles. I have uninstalled all my extension and cleaned the directory. Then installed the latest versions of cli and the zowe extension and created only one profile with encoding IBM-1141.  But the effect is the same. Files (tagged with IBM-1141) are opened in encoding 1047 and only a "pull from mainframe" changes the encoding to 1141. I tried it on the client of a colleague and also here vsc behaves identically - i.e. "pull from mainframe" is necessary. We work with rocket git on uss and various encodings. IBM-1047, ISO-8859-1, IBM-1141 in one repository.  Your extension processes everything correctly only the problem with "pull from mainframe" occurs since some time.

**Comment by jHeidenberger** [comment]
example with ISO-8859-1 tagged file - loaded from uss. Encoding is correct (Jörg Heidenberger)
![image](https://user-images.githubusercontent.com/57558300/108062067-90e10b80-7059-11eb-80ec-4ea1be89a149.png)
example with IBM-1141 tagged file - before "pull from mainframe"
![image](https://user-images.githubusercontent.com/57558300/108062359-fcc37400-7059-11eb-97e4-03e5f0b0fd7f.png)
previous example after "pull from mainframe" 
![image](https://user-images.githubusercontent.com/57558300/108062514-2f6d6c80-705a-11eb-8cd6-344c12b30be2.png)

**Comment by jHeidenberger** [comment]
@fbeyl Thank you very much! I have provided screenshots.

**Comment by fbeyl** [comment]
I see there were quit some changes in the profile handling in latest version 1.12.1 . Did you try to go back to 1.12.0 and see if the issue goes away?

**Comment by jHeidenberger** [comment]
@fbeyl I know that version 1.11 shows the same error with a colleague. I therefore have reset to version 1.8 and the error no longer occurs.

**Comment by fbeyl** [comment]
@jHeidenberger You might check the contents of entry _"Zowe-Temp-Folder-Location":_ in vsc preferences/settings for zowe explorer extension .
Since I upgraded to 1.9 I had a json error in it about wrong escape character and as long as that error existed the settings were no more updated causing me lot of trouble. I don't know if it will solve this issue but since I corrected the error I didn't have it anymore ... worth a try ...

**Comment by jHeidenberger** [comment]
@fbeyl I'm sorry, but it was not the temp folder. Have the icons for "pull from mainframe" been removed on purpose in version 12? I now always have to go through the context menu.

**Comment by fbeyl** [comment]
@jHeidenberger I don't know if the icons were intentionally removed, perhaps a new issue? Do you connect to z/OSMF rest on host or to ftp server or Rse?

**Comment by jHeidenberger** [comment]
@fbeyl I'm sorry, please excuse the late reply. 
I connect through z/OSMF and have since tested the latest versions. Unfortunately the behavior has not changed even with v1.16.0. The file is opened with the default encoding and I have to select "pull from mainframe" to get the encoding stored in the profile. My colleagues have the same problem and we would like to change from v.1.8 to the current version.

**Comment by fbeyl** [comment]
@jHeidenberger I see you don't use the secure credential store.
The default in zowe explorer changed to use the scs. If you don't have it installed you should change the vsc zowe explorer plugin settings and stop saving credentials afterwards of course.
I can't use scs and when I accidently click save credentials the profile gets corrupted with all kind of issues afterwards. Since I changed settings, recreated my profiles and don't click save the issue doesn't appear anymore. 
If you can best is to install and use the secure credential store plugin ( but as I 'm not allowed I'm kind of blocked and have to enter my credentials all the time ...).
