### ISSUE TITLE
Add a tip/procedure for the member filter search

### ISSUE THREAD

**Issue by zdmullen** [zowe/vscode-extension-for-zowe#1174]
**Is your feature request related to a problem? Please describe.**

Document the member filter search in more detail, so that it has a procedure etc. 

**Describe the solution you'd like**

Procedure/tip for how best to take advantage of the functionality. 

**Describe alternatives you've considered**

**Additional context**

**Comment by IgorCATech** [comment]
This has been addressed as part of [PR-1198](https://github.com/zowe/vscode-extension-for-zowe/pull/1198). Feel free to close the issue
