### ISSUE TITLE
Re-visit our documentation

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1182]
Let's re-visit our documentation and check if our current gifs are still up to date and if we have functionalities that are missing.

**Comment by IgorCATech** [comment]
The issue has been addressed as part of PR-1198. Please close the issues unless there are still some sections of the doc that require changes.

**Comment by IgorCATech** [comment]
@jellypuno @crawr 

Please review and verify the functionalities listed below. If there are any functionalities that I've missed, please add them, using the following format:

- Functionality 1 [your name]
- Functionality 2 [your name]
- etc...

This is for my reference. I'll add those asap.

PS: USS, jobs, and MVS/TSO functionalities were intentionally excluded not to overload the readme with too much information. To get information about the abovementioned functionalities, customers are directed to Zowe Docs from Marketplace. 

---- 
Here's the list of the Data Set functionalities with updated gifs in the Zowe Explorer repo core ReadMe:

1. Allocate Like
2. Set Parameters for a New Data Set
3. Copy a Data Set Member
4. Delete a Data Set (and Data Set Member)
5. Edit and Upload a Member

List of all functionalities covered in the Zowe Explorer repo core ReadMe:

- Add to Favorites
- Create a profile
- View multiple profiles simultaneously
- Delete a profile
- Hide a profile
- Associate a profile
- Use base profiles 
- Log in to the Authentication Service
- Enable Secure Credential Store
- View data sets and use filters
- View data sets with member filters
- Refresh the data set list
- Rename the data set
- Edit and upload a data set
- Prevent merge conflicts (while uploading a data set)
- Create a data set (+specify its parameters)
- Create a data set member
- Delete a data set and data set member


Notes (for the tech.writer): 
 - The Zowe Docs ZE docset has not been updated with the new gifs yet (as of 17.02.2021). This is yet to be done.
 - Ensure that there is a link to the USS, jobs, and MVS/TSO page on the Marketplace page.

**Comment by IgorCATech** [comment]
PR opened in the Docs-site repo https://github.com/zowe/docs-site/pull/1581

**Comment by crawr** [comment]
- For Profile Validation, an explanation of the different profile icons might be useful? And an explanation how to turn validation on/off could be documented too
- I see `Log in to the Authentication Service` but I do not see the log out counterpart. Is this covered under the same section?

**Comment by IgorCATech** [comment]
@crawr Good call wrt Profile Validation, I've added the section to the core ReadMe in this PR https://github.com/zowe/vscode-extension-for-zowe/pull/1199 
As for the Log out counterpart, see Lines 115-123 in the core ReadMe.

**Comment by lauren-li** [comment]
@IgorCATech In addition to the existing text about adding favorites, can we also please add a short snippet about removing favorites?
