### ISSUE TITLE
Zowe Explorer Vs Code Extension was not Found... TypeError: Cannot Read property 'loadALL' of undefined.

### ISSUE THREAD

**Issue by hhlp** [zowe/vscode-extension-for-zowe#1185]
**Describe the bug**

You might have disabled or you're running a version that is too old. You will not able to use Zowe Explorer with the IBM Remote System Explorer API (RSE API), the following Error was found: 

TypeError: Cannot Read property 'loadALL' of undefined.

**To Reproduce** Always

1. Install zowe VSCode
2. close VSCode
3. Start VSCode
4. error

**Expected behavior**

Don't see this Error on every Start of VSCode.

**Screenshots**

![Captura de pantalla de 2021-02-05 17-44-10](https://user-images.githubusercontent.com/2659606/107063965-48188f80-67db-11eb-80f2-33c8e3ed2c29.png)

**Desktop (please complete the following information):**

- OS: Fedora 33 x86_64
- Zowe Explorer Version: 1.12.0 and Enabled
- (Optional) Zowe CLI Version: N/A
- (Optional) Are you using Secure Credential Store? N/A

**Comment by jellypuno** [comment]
Hi @lauren-li @JillieBeanSim , Do you think this issue is related to RSE?

**Comment by JillieBeanSim** [comment]
I am wondering with the `loadAll` error if it's related to @zFernand0 's issue he ran into with a profile that had errors in the yaml.  Also if the profile doesn't include user/pass fields with values it may be a good idea to update the Zowe Explorer to 1.12.1

**Comment by zFernand0** [comment]
> I am wondering with the `loadAll` error if it's related to @zFernand0 's issue he ran into with a profile that had errors in the yaml. Also if the profile doesn't include user/pass fields with values it may be a good idea to update the Zowe Explorer to 1.12.1

Yeah, if there are any errors not properly handled by the SDK, then the CLIProfileManager just returns `undefined`.
Similar issue https://github.com/zowe/zowe-cli/issues/960. In this case it's an error in the meta.yaml file validation, but any other unhandled errors will result in the same `undefined` behavior.

**Comment by hhlp** [comment]
Solved in License V1.14.0
