### ISSUE TITLE
Deployment pipeline not posting release on GitHub

### ISSUE THREAD

**Issue by zdmullen** [zowe/vscode-extension-for-zowe#1186]
**Describe the bug**

We are out of sync with what we make available in the VS Code Marketplace and what is under our releases in GitHub. This is due to an issue in the deployment pipeline. 

**Expected behavior**

Consistency between the release version and what is in GitHub release

**Comment by jellypuno** [comment]
Problem: 
it is not working probabaly because of the node or git version. 
The pipeline is not able to detect the changes (Git diff) so it is not publishing anything

Solution: 
1. Remove the check and ensure that the release is tagged. Possibly a new release tag specific for release

**Comment by crawr** [comment]
@katelynienaber Can this issue be closed now?

**Comment by katelynienaber** [comment]
Yep! Closing. Sorry for delay :)
