### ISSUE TITLE
Credentials are not prompted and login is not supported for some profiles

### ISSUE THREAD

**Issue by crawr** [zowe/vscode-extension-for-zowe#1190]
**Describe the bug**

I have a z/OSMF service profile with the same host but different port from my base profile. I expected that this would be treated as a profile having optional credentials and I will be prompted for my username and password. Instead, I get an error message that my connection is no longer active and I need to login. When I use the login action, I get an error message that the profile does not support login.

My service profile:
```json
host: host.com
port: 1234
```
My base profile:
```json
host: host.com
port: 5678
tokenType: apimlAuthenticationToken
tokenValue: <token value>
```

**To Reproduce**

1. Setup the z/OSMF service profile and base profile as above
2. Use the service profile to search for datasets
3. See error

**Expected behavior**

I will be prompted to enter my username and password.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Zowe Explorer Version: v1.12.1
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by jellypuno** [comment]
As per our discussion, this is an edge case. I will add 21PI1 label but, so far,  this is a low priority issue.
