### ISSUE TITLE
UX: How to handle protocol when creating a new profile?

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#1192]
**Is your feature request related to a problem? Please describe.**

With the introduction of the `protocol` field in the CLI (see https://github.com/zowe/zowe-cli/pull/909), we may want to rethink how we are handling URLs when users create a new profile through the extension. 

**Describe the solution you'd like**

Ideally we don't ask people twice for information they have already provided.
Consider: `<protocol>://<user>:<password/token>@<host>:<port>`

**Additional context**

Similar issue #1124 
See https://github.com/zowe/vscode-extension-for-zowe/discussions/1189 for more details

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
