### ISSUE TITLE
Provide an API for appending local file extensions for data set members

### ISSUE THREAD

**Issue by phaumer** [zowe/vscode-extension-for-zowe#1193]
**Is your feature request related to a problem? Please describe.**

Currently there is a hard-coded `appendSuffix()` method in `packages/zowe-explorer/src/shared/utils.ts` that append a file extension to a data set member when it gets downloaded and opened for editing. This method makes a lot of assumptions about languages and how the members will be used, which is fine for default behavior, but extenders might want to change these mappings. 

**Describe the solution you'd like**

I propose that extenders can inject their own mapping functions that should be used for their profile types. For that we should provide an interface in our Zowe Explorer API.

**Describe alternatives you've considered**

I considered access the tree view directly to override this, but that does not seem a good idea and the appendSuffix is called by getDocumentFilePath() which is used in many, many places. So replacing the file extensions would have side effects.

**Additional context**

**Comment by zFernand0** [comment]
we believe that the `appendSuffix` method is being called with the `label` provided when calling `getDocumentFilePath`
