### ISSUE TITLE
Re-visit our testing guidelines

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1204]
Check if the testing guidelines are still applicable and up to date

**Comment by zFernand0** [comment]
With some of the latest updates to out Wiki (thanks to @JillieBeanSim), I believe we can consider this as completed.
- https://github.com/zowe/vscode-extension-for-zowe/wiki/Unit-Tests
We can always revisit out testing guidelines in the future, if/when new contributors find things to improve upon 😋 

Closing.
