### ISSUE TITLE
DATA SETS error opening PDS member containing a '#' character in the name, when connected via the APIML

### ISSUE THREAD

**Issue by chidcp1** [zowe/vscode-extension-for-zowe#1215]
**Describe the bug**

When connected to zOSMF via the APIML, using the DATA SETS option in Explorer and trying to open a member of a PDS, where the member name contains a '#' character, throws an error:

z/OSMF REST API Error: Rest API failure with HTTP(S) status 400 <!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title> 

This only affects members with a **_'#' character anywhere in the member name_** and **_only when access to zOSMF is via the APIML_**. If the connection is direct to zOSMF, then the members open OK.

**To Reproduce**

Setup a zosmf profile that connects to zosmf using the APIML. 
Connect the DATA SETS explorer using the zosmf profile via the APIML
List member of a PDS where a member uses a '#' character in any position
Click on member to open
Throws error

**Expected behavior**

Should open the member containing a '#' character in the member name, regardless of whether zosmf access is direct or via the APIML.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Zowe Explorer Version: v1.12.1
- (Optional) Zowe CLI Version: 6.25.2
- (Optional) Are you using Secure Credential Store? Yes

**Additional context**

**Comment by adam-wolfe** [comment]
This issue is resolved in Zowe Explorer v2.8.0.
