### ISSUE TITLE
Cannot read property 'getSessionNode' of null.

### ISSUE THREAD

**Issue by EmlynWill** [zowe/vscode-extension-for-zowe#1221]
**Describe the bug**

**To Reproduce**
In the USS section, click on the magnifying glass

**Expected behavior**

Error running command zowe.uss.fullPath: Cannot read property 'getSessionNode' of null. This is likely caused by the extension that contributes zowe.uss.fullPath.

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Zowe Explorer Version: v1.12.1
- (Optional) Zowe CLI Version: n/a
- (Optional) Are you using Secure Credential Store? No

**Additional context**

**Comment by jellypuno** [comment]
@EmlynWill What type of profile are you using? Are you connecting via FTP, zosmf or APIML? Are you using tokens?

If you refresh your VSCode (View > Command Palette > Developer: Reload Window) does the error persists? Did you receive more error messages?

**Comment by EmlynWill** [comment]
z/OSMF
No tokens
Developer: Reload Window didn't fix it, same error message
BTW - The Datasets and Jobs sections both work

**Comment by jellypuno** [comment]
Are you using Windows?

**Comment by EmlynWill** [comment]
Yes

**Comment by jellypuno** [comment]
Hmmm.... This is not happening for me. Are you using/creating a different extension that runs on top of Zowe Explorer?  

If possible, a gif would be super helpful

**Comment by EmlynWill** [comment]
No, it's a fresh install of Zowe explorer, I had my machine rebuilt to see if I could resolve the problem. I did have it working on another machine.

**Comment by jellypuno** [comment]
>  I had my machine rebuilt to see if I could resolve the problem

Just for clarification, does this mean you are running on a VM? Are you also using theia?

**Comment by EmlynWill** [comment]
Yes to VM, no to theia

**Comment by EmlynWill** [comment]
This issue has been resolved. Our support desk uninstalled VSCode, removed all folders, gpupdate, reinstalled manually (instead of our automated process). Then restarted VSCode and everything is working. Thank you for looking into this.

**Comment by jellypuno** [comment]
Good to hear. Thank you for the update @EmlynWill . Closing this issue...
