### ISSUE TITLE
Document how to use context menus

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1222]
Extenders are able to extend ZE's context menus. We need to document more information about it

```
		"menus": {
			"view/item/context": [
				{
                                    "when": "view == zowe.uss.explorer && viewItem =~ /^binaryFile.*/",
                                    "command": "zowe.uss.text",
                                    "group": "2_systemSpecific@2"
                                },
            ],
        ..
        ..
   }
```

**Comment by JillieBeanSim** [comment]
@jellypuno @lauren-li wasn't this item already addressed https://github.com/zowe/vscode-extension-for-zowe/blob/master/docs/README-Extending.md#creating-an-extension-that-adds-menu-commands

**Comment by lauren-li** [comment]
@JillieBeanSim I believe you are correct. I think this item might have just slipped through when we were collecting issues for the larger Extenders epic, and was addressed via a separate issue. I'll go ahead and close it now. Thanks for pointing this out!
