### ISSUE TITLE
SCS plugin required for credentials to be stored securely

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#1223]
**Describe the bug**

We may need to revisit the Settings implementation as we still depend on the SCS plugin to be installed and configured in the CLI for the Security Key to take effect.

**To Reproduce**

0. [recommended before doing next step]: `zowe scs revert -f` (revert profiles to plain text)
1. `zowe config reset CredentialManager`
2. Verify you have the Security Key set to something other than blank `""` (recommend: `Zowe-Plugin`)
3.  Reload VSCode (or open the command palette [`Ctrl+Shift+p`] and type `Reload Window`)
4. Create a new profile (and specify username and password)
5. Notice your profile is in plain text

To go back to secure profiles
1. `zowe config set CredentialManager @zowe/secure-credential-store-for-zowe-cli`
2. `zowe scs u`
3. Reload VSCode

**Expected behavior**

The ZE Security Key should take effect even when the SCS plugin is not configured in the CLI

**Comment by crawr** [comment]
Hi @zFernand0 we discussed this today in the SU meeting and we were wondering if (a) you think the dependency with SCS plugin should be solved, or (b) if we just need better documentation for the SCS integration between CLI and ZE. Please let us know. Thanks!

**Comment by crawr** [comment]
Linked to #722

**Comment by zFernand0** [comment]
Hey @crawr,
I believe we could do something about this.
For instance, we could look at the imperative overrides (in `~/.zowe/settings/impertive.json`) and check if `overrides.CredentialManager !== false` before trying to create profiles or load credentials.

Using the latest versions (ZE v1.17.0, CLI v6.32.2, SCS v4.1.5, node v14.17.3, npm v6.14.13), 
The ZE creates and loads plain text profiles when the imperative setting is not set (regardless of the ZE Credential Key setting).

Solution:
Setup the imperative override setting instead of telling users to verify (and fix) their credential manager configuration via the CLI.
