### ISSUE TITLE
Support multi-root vscode workspace

### ISSUE THREAD

**Issue by VitGottwald** [zowe/vscode-extension-for-zowe#1226]
VSCode allows the creation of a workspace that groups together several user specified folders (referred to as a _root_). Such a workspace is called a [multi-root workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces).

ZE has a dedicated [Activity Bar](https://code.visualstudio.com/docs/getstarted/userinterface) icon and its own tree views. Is there anything specific that we would need to do to support multi-root workspaces?

For example:
1. Is there any functionality that relies on the currently opened “folder”?
1. Currently all configuration and profiles are global. How does a change to a project level scope map to this?

**Comment by venkatzhub** [comment]
For me, more than ZE, it is about how the Project/Global config(s) - and how would they behave in the multi-root workspace. In #1166, you described a scenario to illustrate the Global vs Local issue - and I think one variation of that use case is, a user can "add" (folder) Project B to the existing workspace - so what happens to the profiles? Do I see profiles from Project A and B? What would be the default profile? what if there is a common profile in Project A and B?

**Comment by VitGottwald** [comment]
The way VSCode File Explorer handles multi-root workspaces is by having a root node in its tree view for each of the root folders. We could do the same thing in our views (datasets, uss, jobs) and prefix the current tree with a top level nodes that would represent the individual workspace roots.

I see several potential issues with this approach

1. Will it be clear to the user that the top level  in the dataset, uss, and jobs trees now represent workspace roots?
2. I expect that implementing this will be a significant effort because we would be going from code that handles only one thing to code that needs to handle many things and I do not think we have the right abstractions in place

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
