### ISSUE TITLE
Expose API for extenders to log in when credentials are missing/expired

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/vscode-extension-for-zowe#1228]
**Is your feature request related to a problem? Please describe.**

When using an extension like [JCL Language Support](https://marketplace.visualstudio.com/items?itemName=broadcomMFD.jcl-language-support), I can only manage my connection info for profiles of type X (e.g., "jclcheck") thru Zowe CLI.

To get started, I have to run a CLI command to create a profile with host, user, and password. When my password or MFA token expires, I have to run a CLI command again to update my credentials.

Having to learn and remember CLI commands to use a graphical VSCE is inconvenient.

**Describe the solution you'd like**

I'd like an easy-to-use API in Zowe Explorer that can be called by another VSCE, and could:
1. Prompt for host, user, and password to create a new profile of type X if none exists yet.
1. Prompt for user and password to update an existing profile of type X if the credentials have expired.

**Describe alternatives you've considered**

Using Zowe CLI to manage profiles is a workaround, but it's not ideal for VSCE users to have to install Zowe CLI only for that purpose.

**Additional context**

Zowe Explorer provides a great experience for managing z/OSMF profiles, in the way it prompts users for connection info. Making this experience available for any type of profile would be awesome for extenders 🙂

**Comment by crawr** [comment]
Is this related to #1255?

**Comment by t1m0thyj** [comment]
It does seem related 🙂 A few questions about #1258 
* Is support for basic auth with user/password planned, or just tokens?
* How will expired credentials be handled? Are extenders expected to detect the error returned by their API when credentials are expired, and handle it accordingly to call the `login` method?

**Comment by crawr** [comment]
Task list:
1. Expose prompts API in the vscode package for items in the secure array
2. Dealing with expired credentials (user/password) - will be handled in a different issue
