### ISSUE TITLE
Do not ask for port if already supplied in URL

### ISSUE THREAD

**Issue by VitGottwald** [zowe/vscode-extension-for-zowe#1234]
**Is your feature request related to a problem? Please describe.**

In the add profile wizard, I fill in the requested URL, including PORT. In the next step I am prompted to provide/confirm the PORT. This is a redundant and confusing question.

**Describe the solution you'd like**

Do not prompt for PORT if provided in the URL.

**Comment by crawr** [comment]
closing in favor of #1124
