### ISSUE TITLE
Use Welcome Content Button if no profile defined

### ISSUE THREAD

**Issue by VitGottwald** [zowe/vscode-extension-for-zowe#1236]
**Is your feature request related to a problem? Please describe.**

After I installed ZOWE Explorer, I see three views (Datasets/USS/JOBS), but do not know how to start

**Describe the solution you'd like**

Could we display a [Welcome Content](https://code.visualstudio.com/api/extension-guides/tree-view#welcome-content) with a button to add a profile instead of the tree views if no profile is defined yet?

**Comment by zFernand0** [comment]
Maybe related to #839

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
