### ISSUE TITLE
Right-Click Action on Data Sets to filter Members Within Treeview

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#1241]
**Is your feature request related to a problem? Please describe.**

This is an extension of the issue https://github.com/zowe/vscode-extension-for-zowe/issues/868 to add the right-click action on a PDS to add a member filter search to be displayed in the treeview

**Describe the solution you'd like**

1. Have a list of Data Sets
2. Right-click on a PDS and have an option for `Filter Members`
3. Once selected a pop-up text box will appear to enter the member filter string
4. The icon on the data set will change to the filter folder icon and a list of members matching that filter will appear within the opened PDS

**Describe alternatives you've considered**

We already have an alternative method in place with the member filter search by clicking the magnifying glass icon on a session.

**Discussion**
To undo the filter in place, should we also include a right-click action for `Remove Filter` if one is found to be in place?

**Comment by JillieBeanSim** [comment]
@jelaplan @jellypuno @crawr I have closed the larger story that this branched from and set a scope around this story for the right-click member filter in the treeview.

I did leave a discussion question in the description that can be discussed here in the issue before we begin work bringing this into a release.

**Comment by azarrafa** [comment]
Hello , 
I wonder if you can add a button or filter to sort members of a PDS by last change, like in ISPF ;)

Regards,
