### ISSUE TITLE
Can't use Del key when renaming file in VS Code

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/vscode-extension-for-zowe#1260]
**Describe the bug**

When renaming a file in the VS Code file explorer, pressing the Delete key doesn't work as expected, because Zowe Explorer intercepts the keypress and tries to delete jobs.

**To Reproduce**

1. Go to the VS Code file explorer pane (not the Zowe Explorer data sets pane)
2. Right-click on a file and select "Rename"
3. Press the Delete key while in edit mode
4. See that the filename doesn't change, and occasionally an error message is shown

**Expected behavior**

Outside of the Zowe Explorer pane, Zowe Explorer should not affect the behavior of the Delete key in VS Code.

**Screenshots**

Attempting to rename a file:
![image](https://user-images.githubusercontent.com/22344007/113768888-59541e80-96ee-11eb-99eb-2cd18985dfdf.png)

Sometimes this error appears:
![image](https://user-images.githubusercontent.com/22344007/113768419-d5019b80-96ed-11eb-8f42-c94d3eff66ea.png)

**Desktop (please complete the following information):**

- OS: Windows 10 build 19042
- Zowe Explorer Version: 1.13.1

**Additional context**

I believe the cause is this keybinding defined in package.json:

https://github.com/zowe/vscode-extension-for-zowe/blob/e721225315862326db53d8e7b270f2c38cb3b7dc/packages/zowe-explorer/package.json#L72-L76

The event filter "listSupportsMultiselect" seems to include the VS Code file explorer tree.

**Comment by lauren-li** [comment]
@crawr Could this be resolved by just using the following `when` statement?:
`"when": "view == zowe.jobs && listSupportsMultiselect"`

**Comment by crawr** [comment]
@lauren-li I tried this one, but it didn't work for me. I also tried restricting it to just the context value but that didn't work either. :thinking:

**Comment by t1m0thyj** [comment]
@crawr I tried this one and it seems to work for me locally:
`"when": "focusedView == zowe.jobs && listSupportsMultiselect"`
