### ISSUE TITLE
Handle protocol validation

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1264]
https://github.com/zowe/vscode-extension-for-zowe/pull/1262#issuecomment-814929041

**Comment by deepali-hub** [comment]
Zowe-Cli 6.30.0 has added one new field:  `The maximum amount of time in seconds the z/OSMF Files TSO servlet should run before returning a response. Any request exceeding this amount of time will be terminated and return an error. Allowed values: 5 - 600 (Press 'Enter' to confirm your input or 'Escape' to cancel)` and this new field/input box is not locatable through selenium in Zowe Explorer while creating a profile(in Firefox and in Chrome as well). It always shows error message as element is not interactable or not reachable.

**Comment by jellypuno** [comment]
This is already added in v1.18.0
