### ISSUE TITLE
Error when adding job spool to favorites after submitting job

### ISSUE THREAD

**Issue by lauren-li** [zowe/vscode-extension-for-zowe#1265]
**Describe the bug**

The first time during a session that I use a profile to submit a job, click on the job ID from the "Job submitted" message, and try to favorite the resulting job, I get a command error. (See below for screenshot.)

**To Reproduce**

1. Submit a job
1. Click the Job ID from the message
1. Click the Star Icon
 1. Error Message appears:
        ![image](https://user-images.githubusercontent.com/45042840/113863892-81a15300-97aa-11eb-9caf-0647d5f0a76e.png)

**Expected behavior**

The job should be favorited without any error.

**Desktop (please complete the following information):**

- OS: Reproduced on Mac and Windows
- Zowe Explorer Version: 1.13.1

**Additional context**

This issue only appears to happen the first time I do this for a given profile during a VS Code session. In the Jobs tree's `addFavorite` function, when the issue occurs, the argument passed into the function is `undefined`, where it should be the job node. Thank you @tiantn and @jellypuno for these findings!

**Comment by tiantn** [comment]
Hi @lauren-li, Qi helped to debug this problem today and we have a workaround method to avoid the problem. We copied the code of refreshElement to setItem part in packages/zowe-explorer/src/abstract/ZoweTreeProvider.ts. It  works well.
`    public setItem(treeView: vscode.TreeView<IZoweTreeNode>, item: IZoweTreeNode) {
        treeView.reveal(item, { select: true, focus: true });
        this.mOnDidChangeTreeData.fire(item);
    }`
But we can't confirm if it is a formal way. Thank you!

**Comment by crawr** [comment]
@jellypuno will test for zosmf, @lauren-li will test for zftp

**Comment by jellypuno** [comment]
This is not happening in z/OSMF with ZE v1.17.0

**Comment by lauren-li** [comment]
@crawr @jellypuno I do not see this issue happening with zftp in ZE 1.17.0 + ZE for FTP 1.17.0. I think this issue can be closed. Thank you for helping me follow up on it!
