### ISSUE TITLE
Too many info messages appear for some commands

### ISSUE THREAD

**Issue by katelynienaber** [zowe/vscode-extension-for-zowe#1272]
**Describe the bug**

`xyz command submitted` info messages are appearing repeatedly for a single call to some commands.

**To Reproduce**

Try ex. renaming a USS directory/file, as demonstrated here (2 calls to rename, one after the other):
![renameDoesntCollapse](https://user-images.githubusercontent.com/58596139/115422487-3bfa7680-a1fd-11eb-997c-9d2039d4148b.gif)

Also maybe check the logic for opening a USS file, it happens a lot when you do this.

But we should probably check on `getChildren` as well.

**Expected behavior**

This dialog should only appear once for each call to any command `in the context menu`. ie. if a command calls getChildren ten times, we should only see one info message for the original command, not ten for all the getChildren calls.

**Comment by adam-wolfe** [comment]
Number of displayed pop-ups has been significantly reduced, particularly for USS actions.
