### ISSUE TITLE
ESLINT Errors 

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1274]
There are Eslint errors when I executed npm run package. We should add a fix for those on the next release.

**Comment by jellypuno** [comment]
![image](https://user-images.githubusercontent.com/45042840/116571267-37277800-a90b-11eb-8a61-9c02d83613ac.png)

**Comment by jellypuno** [comment]
![image](https://user-images.githubusercontent.com/45042840/116571417-5920fa80-a90b-11eb-8943-04b460081530.png)

**Comment by zFernand0** [comment]
In addition, we should enable eslint in the ZE codebase too 😋
