### ISSUE TITLE
Zowe Explorer unit test suite to review extenders' API methods

### ISSUE THREAD

**Issue by lauren-li** [zowe/vscode-extension-for-zowe#1278]
To facilitate testing Zowe Explorer extenders for conformance, develop a unit test suite that calls each of the implemented API methods for review.

- Enables reviewers of extender conformance to verify that all methods for the extender's selected ZoweExplorerAPI data provider interface(s) are either implemented or throw exceptions that provide meaningful user messages.
- This helps support the following proposed conformance criteria item: 
  - If the extension contributes a new data provider to one of the Zowe Explorer tree browsers, it fully implements one of the Zowe Explorer API interfaces (MVS, JES, and USS), or:
  - If the extension has unimplemented methods, it throws exceptions and provides meaningful user messages

**Comment by zFernand0** [comment]
Unit tests have been written for the Zowe Explorer APIs.
As far as the second portion of this issue...
We will consider providing some Conformance Validation automation once the Zowe Org requires each squad to provide such scripts to the OMP.
Closing!
