### ISSUE TITLE
Standardize Zowe Explorer context menus and document for extenders

### ISSUE THREAD

**Issue by lauren-li** [zowe/vscode-extension-for-zowe#1279]
Documentation: Provide either a wiki or docs page for Zowe Explorer extenders to reference when adding new commands that build off of Zowe Explorer.

Development: Refactor Zowe Explorer menu items to follow the standards defined in the above documentation. (This will mostly involve updating group numberings in `package.json` to ensure a 1:1 pairing between context menu category and category order number.)

**Comment by jellypuno** [comment]
- V2 API to access context menu
  - V2 Adding items into dropdown 
  - V1 Document this in extending docs. Add rules for groupings and categories. Start with the Wiki. - Lauren

**Comment by lauren-li** [comment]
Listing of current commands and their groupings:
- [ZE command org.docx](https://github.com/zowe/vscode-extension-for-zowe/files/6423486/ZE.command.org.docx)

I will use this as the basis for creating a proposal for consistent context menu groupings.

Some questions to consider:
-  Do we only want to allow extenders to contribute to context menus? (As opposed also contributing to the DS/USS/Jobs view headers, etc.?)
- Do we want to allow extenders to contribute to Zowe Explorer's existing menu groupings, or require them to create their own extender-specific groupings?
-  Do we want to allow extenders to contribute to the inline menus? I.e. These are the little icons that appear when you hover over a header bar or tree item. There's also the potential for extenders to do something ugly like this:
    <img width="319" alt="Screen Shot 2021-05-04 at 3 25 23 PM" src="https://user-images.githubusercontent.com/45975633/117060969-9c0a1600-acef-11eb-9032-cdcbe80f4754.png">

**Note:** When we consider how restrictive we want to be in our conformance criteria, we should also consider how much extra work would be required from conformance reviewers to verify it. We may also want to consider just making some of our decisions for the above questions "best practices" rather than "requirements" if there is too much added overhead to verify conformance.

**Comment by lauren-li** [comment]
Additional considerations:
- Implement keybindings for commands. (Handle in issue https://github.com/zowe/vscode-extension-for-zowe/issues/313)
- Add "Zowe Explorer" prefix to commands (e.g. so users know which commands do and don't belong to Zowe Explorer in the command palette).
- Consider adding conformance criteria requiring extenders to add prefixes for their commands.

**Comment by lauren-li** [comment]
I put together a list of proposed command groupings, aiming to minimize impacts to the UI while also grouping commands consistently and in ways that would make sense to developers and users. I have attached the full list of proposed command groupings at the end of this comment. At a high level, the proposed changes can be summarized as follows. (FYI @katelynienaber)

Code changes in `package.json` (non-UI; developer-facing):
- Prefix all command groups with `##_zowe_mvs`, `##_zowe_uss`, or `##_zowe_jobs` depending on which view the command group applies to. (This is to align with the proposed conformance criteria in PR #1290.)
  - **Note 1:** The proposed conformance criteria only specifies that Zowe Explorer is using the `##_zowe_` prefix. However, because our commands currently all apply to one of the 3 views (Data Sets, USS, or Jobs), I think it will be helpful for Zowe Explorer developers to also include the view in the prefix.
  - **Note 2:** Modification commands (e.g. update/rename/hide/delete) and Profile authentication commands are prefixed with high numbers (e.g. 99, 98) to keep them consistently at the bottom of the Zowe Explorer context menus. I also propose that we use high numbers after the `@` (e.g. `...modification@99`) for these core commands so developers don't have to keep remembering to modify the ordering whenever a new context menu option is added into these categories.
- Rename some command groups for consistency between Data Sets, USS, and Jobs.

UI changes (common between views):
@jelaplan, @tomofbroadcom, @IlyaKreynin you may be interested in these.
- Move "Search", "Refresh"/"Pull from mainframe", and "Issue command" commands into their own group (separate from the Create commands). This separate group would encompass general mainframe interactions.
- Move "Copy", "Copy path", and "Paste" commands into their own group (separate from the Create commands). This organization will be more consistent with [how VS Code groups their explorer context menu commands](https://code.visualstudio.com/api/references/contribution-points#Sorting-of-groups), as they have a command group dedicated to cut/copy/paste. 
- Remove "Enable/Disable validation" command from favorited searches (Jobs view) to be consistent with MVS and USS views. (I think the command appearing here was originally a mistake since no other views have it in this context.)
- TBD: For profiles in the Jobs view, consider removing “Set Job Prefix” and “Set Owner”, as their functionality is covered by "Search Jobs using Attributes". Also, consider the following command renames for consistency and clarity:
  - "Search Jobs using Attributes" --> "Search Jobs" (consistent with our "Search Data Sets" and "Search USS" command labels)
  - "Set Job Prefix" --> "Search Jobs by Job Prefix" (If we keep this command.)
  - "Set Owner" --> "Search Jobs by Owner" (If we keep this command.)

Full list of proposed command groupings:
[proposed ZE command org.docx](https://github.com/zowe/vscode-extension-for-zowe/files/6515386/proposed.ZE.command.org.docx)

**Comment by lauren-li** [comment]
Proposed Zowe Explorer developer guidance for context menu commands:

**Contributing context menu items**
If adding a command, make sure you assign it to a group. For details on how to do this, see the following VS Code documentation:
- [Sorting context menu groups](https://code.visualstudio.com/api/references/contribution-points#Sorting-of-groups)
- [Sorting inside groups](https://code.visualstudio.com/api/references/contribution-points#Sorting-inside-groups)

**Context menu groups**
Group names for Zowe Explorer are formatted as follows: `##_zowe_<view><groupSpecifier>`
Per the proposed conformance criteria (PR #1290), we have `##_zowe_` reserved for use with core Zowe Explorer command groups.
- `##` represents a number from 00 - 99. Command groups are organized alphabetically in VS Code, and this numbering helps Zowe Explorer's context menu groups stay in a predefined order that makes sense in the UI.
- `<view>` represents which of Zowe Explorer's views the command group applies to.
  - `mvs`: Use this to specify a command group for the Data Sets view.
  - `uss`: Use this to specify a command group for the USS view.
  - `jobs`: Use this to specify a command group for the Jobs view.
- `<groupSpecifier>` is a short name describing of what types functional commands the group contains. See below for the current group specifiers used by Zowe Explorer, as well as some examples for each:
  - `Workspace`: Commands related to workspace manipulation.
    - Examples: Add/Remove favorites
  - `MainframeInteraction`: Commands related to interacting with the mainframe in general
    - Examples: Search, Issue command, Download from mainframe, Download spool
  - `Create`: Commands related to creation of files or folders
    - Examples: Create data set, Upload data set member; Create/Upload file or director
  - `MvsHsmCommands`: Commands for HSM commands for data sets
    - Migrate/Recall data sets
  - `CutCopyPaste`: Commands related to cutting, copying, and pasting of files or paths.
    - Examples: Copy member/data set, Copy path, Paste (data set/member)
  - `*Modification`: Commands related to modification of files. (Not for profiles.)
    - Examples: Rename, delete data set or file
  - `SystemSpecific`: Commands specific to the Data Sets, USS, or Jobs view.
    - Examples: Toggle binary (USS), Issue stop command (Jobs)
  - `profileAuthentication`: Commands related to authentication of profiles.
    - Examples: Login, Logout, Enable/Disable validation
  - `ProfileModification`: Commands related to modification of profiles.
    - Examples: Update profile, Hide profile, Delete profile
