### ISSUE TITLE
Make the profilesCache available to extenders

### ISSUE THREAD

**Issue by lauren-li** [zowe/vscode-extension-for-zowe#1281]
**Is your feature request related to a problem? Please describe.**

Extenders currently cannot access their list of loaded profiles from Zowe Explorer's API.

**Describe the solution you'd like**

Provide a common Profiles Cache to extenders via API. 
(Note: This may be dependent on developments with team config file.)

**Comment by jellypuno** [comment]
@lauren-li Is it okay to close this issue?
