### ISSUE TITLE
Add profile functionalities for Zowe Explorer FTP extension

### ISSUE THREAD

**Issue by lauren-li** [zowe/vscode-extension-for-zowe#1284]
Implement the following with zftp profile:

1. **Profile validation:**
    This enhancement would allow users to easily see at a glance whether the zftp profile they are using is successfully connected to z/OS or not, similar to what is shown with z/OSMF profiles in the gif below. (Active profiles get a green status circle, while inactive profiles get a red one.)
        ![ze-validation](https://user-images.githubusercontent.com/45975633/127265449-dbbee273-7e93-475b-a859-c9a5558925c5.gif)

    The work for this would involve implementing the getStatus() function from the Zowe Explorer API. As an example, here is what the code looks like for z/OSMF: https://github.com/zowe/vscode-extension-for-zowe/blob/master/packages/zowe-explorer-api/src/profiles/ZoweExplorerZosmfApi.ts#L63

2. **Check credentials:**
    This enhancement would enable a prompt for the user to check and correct their credentials for a zftp profile that has invalid credentials. It would look like the implementation for z/OSMF in the gif below, but work for zftp profiles:
        ![ze-checkCredsUss](https://user-images.githubusercontent.com/45975633/127267363-8b794427-9c10-4837-8c5b-87bd838589bb.gif)

**Comment by jellypuno** [comment]
FTP has a logon operation to test the validation.

**Comment by jellypuno** [comment]
Connected to #1305

**Comment by crawr** [comment]
Can we close this issue since #1443 has been merged?
