### ISSUE TITLE
Support multiple VS Code windows for files opened via Zowe Explorer

### ISSUE THREAD

**Issue by phaumer** [zowe/vscode-extension-for-zowe#1291]
**Is your feature request related to a problem? Please describe.**

How to reproduce:

- Open a file such as a data set member in VS Code using Zowe Explorer
- In VS Code select File > New Window
- Observe that the open editor in the old window shows now `(Deleted)`

This is because opening a new Window in VS Code is like starting a new instance of Zowe Explorer that goes through an activation lifecycle. In activation Zowe Explorer cleans up all left-behind temp file such as downloaded mvs files and therefore the files that are opened by other windows are deleted and users might lose their work if they made changes.

**Describe the solution you'd like**

There could be different ways of solving this:

- A setting that disables temp file cleanup in general
- Rewrite the cleanup code that searches for all open editors in all open workspaces for files that match the files in the temp folders and do not delete them. Only delete files that are not opened in any other workspace.

**Comment by jellypuno** [comment]
Similar to #509
