### ISSUE TITLE
Issue TSO & MVS Commands Polish Work

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#1297]
Polish item for issuing TSO and MVS commands, some may require a discussion.

What I would like to see:
1.  Separate console window for each instead of same title for both `Zowe Command`
2. Revisit where the option is presented.  I believe we should only present the option within the Data Sets view and not within all tree views.  This may allow the validation of profiles icon to be present upon validation and remove some duplicate code I put in when first implemented this.
3.  Possibly separate the saved commands in the settings.  At this time TSO & MVS commands are saved together under one section.
```
"Zowe Commands: History": {
    "persistence": true,
    "history": [],
    "fileHistory": [],
    "sessions": [],
    "searchHistory": [
      "PROFILE",
      "D T"
    ]
  },
```
4. Investigate creation of TSO profiles or caching the account number while the VS Code session is in place as to not be prompted with every command issued if TSO profile isn't found.
5. [FIXED] If escape when prompted for account number `operation cancelled` info message pops up but command text box also appears and needs to be escaped again. (bug)
6. If escape when prompted for a command `operation cancelled` info message doesn't pop up...[possible solution here](https://github.com/zowe/vscode-extension-for-zowe/pull/1479#issuecomment-919110641)

**Comment by zFernand0** [comment]
A way we could polish a bit more the command handlers is to provide a common "handler" for any terminal-like functionality we have in ZE. (MVS, TSO, and possibly SSH). This command handler will keep an open connection and hook into the VSCode terminal. It could be influenced by extension settings (and should make it easier to save history)

**Comment by JillieBeanSim** [comment]
that sounds awesome @zFernand0, and with removal of v1 profiles in v3 we will already have ssh & tso profiles easily accessible out the box upon config creation.
