### ISSUE TITLE
Need the ability to execute JCL from a local Git repo in Wazi Code Ready Workspaces

### ISSUE THREAD

**Issue by jt-atkins** [zowe/vscode-extension-for-zowe#1299]
Just like eclipse (IDz), we need the ability to execute JCL from a Git repo on a chosen target z/OS environment. It could just execute on the default z/OS Connection for now. Ideally, you would want to right click > Submit > Choose your environment to execute the JCL on.

**Comment by jt-atkins** [comment]
This was suppose to be a feature request

**Comment by jellypuno** [comment]
This needs more information. What do you mean by local Git repo? Also, what do you mean environment? Is the info for the environment not included in the profile? A screenshot would also be helpful

**Comment by jellypuno** [comment]
no need to close it, I can change the tag to feature

**Comment by jt-atkins** [comment]
Hi, 

Please see the images attached.

I have raise a enhancement request here: 
https://github.com/zowe/vscode-extension-for-zowe/issues/1300 


Joseph Taffe-Atkins
Mainframe Specialist | z Systems 
Phone: +44776 848 6765
E-mail: ***@***.***
IBM Southbank
London, SE1 9PZ
United Kingdom



From:   Jessielaine Punongbayan ***@***.***>
To:     zowe/vscode-extension-for-zowe 
***@***.***>
Cc:     Jt-atkins ***@***.***>, State change 
***@***.***>
Date:   04/05/2021 11:37
Subject:        [EXTERNAL] Re: [zowe/vscode-extension-for-zowe] Need the 
ability to execute JCL from a local Git repo in Wazi Code Ready Workspaces 
(#1299)



This needs more information. What do you mean by local Git repo? Also, 
what do you mean environment? Is the info for the environment not included 
in the profile? A screenshot would also be helpful — You are receiving 
this because you ZjQcmQRYFpfptBannerStart 
This Message Is From an External Sender 
This message came from outside your organization. 
ZjQcmQRYFpfptBannerEnd
This needs more information. What do you mean by local Git repo? Also, 
what do you mean environment? Is the info for the environment not included 
in the profile? A screenshot would also be helpful
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.


Unless stated otherwise above:
IBM United Kingdom Limited - Registered in England and Wales with number 
741598. 
Registered office: PO Box 41, North Harbour, Portsmouth, Hampshire PO6 3AU
