### ISSUE TITLE
Need CI/CD

### ISSUE THREAD

**Issue by AHumanFromCA** [zowe/vscode-extension-for-zowe#13]
If this is to be a production app, there should be a CI/CD pipeline associated with it.

Perhaps @zFernand0 we can just build a from scratch ci/cd pipeline and use all of the knowledge we have gained in the course of the Zowe project to do it proper from the start. I don't want to keep hacking and slashing the same base CI/CD that we've been using due to flaws in the design.

**Comment by Colin-Stone** [comment]
Include requirements from https://github.com/zowe/vscode-extension-for-zowe/issues/34

**Comment by Colin-Stone** [comment]
@zFernand0 I reckon this is done unless you had any other enhancements

**Comment by zFernand0** [comment]
Hey @Colin-Stone,
There is something I'd like to add/modify.
I was trying an email approach for the purpose of versioning and changelog entries, however @tjohnsonBCM mentioned that you had a better suggestion for the master pipeline. 
`To leave the versioning and changelog to the user, and only publish after merging a PR into master that has a new version number which matches the latest changelog entry`

**Comment by Colin-Stone** [comment]
Okay that's much simpler and we can control when we release. Personally I get annoyed when you install an upgrade and it has no real benefits e.g. a typo fix. I would prefer to send it out when we have more to shout about.
