### ISSUE TITLE
Need the ability to execute JCL from a local Git repo in Wazi Code Ready Workspaces

### ISSUE THREAD

**Issue by jt-atkins** [zowe/vscode-extension-for-zowe#1300]
**Is your feature request related to a problem? Please describe.**
Yes, when I clone a repo with JCL in it, there is no way to right click and execute that JCL (locally) without having to go through the RSE API guide to figure out the command to upload the JCL. Which should not be the practise.

**Describe the solution you'd like**
Just like eclipse (IDz), we need the ability to execute JCL from a Git repo on a chosen target z/OS environment. It could just execute on the default z/OS Connection for now. Ideally, you would want to right click > Submit > Choose your environment to execute the JCL on.

**Describe alternatives you've considered**
Create a member on z/OS via Z Open Editor
Then copy the JCL (highlight and copy)
Paste into the new JCL member on host

**Additional context**
A suggestion, we need to use IDz eclipse member menus as a guide to what we should add into Wazi Code Ready Workspaces

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
