### ISSUE TITLE
Improve the Changelog structure

### ISSUE THREAD

**Issue by IgorCATech** [zowe/vscode-extension-for-zowe#1302]
**Is your feature request related to a problem? Please describe.**

As a user, I'd like a more informative/structured changelog.

**Describe the solution you'd like**

I was inspired by Nikolay's suggestion to follow the conventions for changelogs formalized in https://keepachangelog.com/en/0.3.0/. We implemented these standards in one of our changelogs.

Let's rework our current changelog to match the standards outlined in the above-mentioned doc (website). Let me know what you think.

**Describe alternatives you've considered**

Leave everything as is if there's no concenus.

**Additional context**

**Comment by lauren-li** [comment]
@IgorCATech The article linked in the description seems like a good read! I'm having some trouble finding a list of standards in it, though. Is it just [the changelog](https://github.com/olivierlacan/keep-a-changelog/blob/main/CHANGELOG.md) that they link to? If not, could you provide (or link to) some more specifications on exactly what you're hoping our changelog will end up looking like? Thanks!

**Comment by IgorCATech** [comment]
@lauren-li Thanks for checking out the information from the linked web page. 
To answer your last question, yes that's how (https://github.com/olivierlacan/keep-a-changelog/blob/main/CHANGELOG.md) the changelog will end up looking like. We might change the short description under the title a bit, but structure-wise, that's how we will break down the sections of notes - using `added`, `changed`, and so on sub-headings. 
I hope it makes sense, and this is just a suggestion.
