### ISSUE TITLE
Update Profile should not try to validate

### ISSUE THREAD

**Issue by phaumer** [zowe/vscode-extension-for-zowe#1305]
**Describe the bug**

A main reason to update a profile is that it does not work and something needs to change such as the password expired and the user needs to update it. Hence, running a validation of the profile when the command is started does not add value as it is likely to fail. It even prevents users from actually making changes as the validation hangs or fails. 

**To Reproduce**

1. Create a profile with an invalid password
2. Right-click Update Profile
3. The validation is performed

**Expected behavior**

No validation before Update only after.

**Screenshots**

**Desktop (please complete the following information):**

- OS: all
- Zowe Explorer Version: 1.13
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by jellypuno** [comment]
This will be fixed in the Core ZE

**Comment by jellypuno** [comment]
- Research if the update is calling the validation or is it the checkCurrentProfile. Come up with a way why checkCurrentProfile is called.
- Come up with an approach 
- Update Known Issues document about this problem

Workaround: Just switch off the validation via context menu or settings.

Default behaviour is to validate after the profile update

**Comment by JillieBeanSim** [comment]
I have the fix for this, will put in a PR today
