### ISSUE TITLE
Allocate Like not working

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1321]
Steps to reproduce:
1. Search for a dataset
2. Right-click on a dataset then click allocate like
3. Enter the name of the new dataset
4. Hit Enter.
5. Error will appear

![image](https://user-images.githubusercontent.com/45042840/118690030-efa85380-b807-11eb-88ac-9a44f8c55237.png)

I am actually confused why it is a dynamic allocation error. 😞

**Comment by jellypuno** [comment]
Fix in Zowe CLI: https://github.com/zowe/zowe-cli/pull/1017
Integration Test added in ZE: https://github.com/zowe/vscode-extension-for-zowe/pull/1322

The possible change that we are going to do is to update the Zowe CLI version and add that to our 1.16 release

**Comment by bknaysi** [comment]
Additionally, the error message shows the "Not implemented..." string twice.

### Evidence
<img width="458" alt="Allocate Like Error Message" src="https://user-images.githubusercontent.com/78445752/119551896-203c4000-bd68-11eb-88e6-ecc035312413.png">

**Comment by crawr** [comment]
Fix applied via #1322 and will be released with v1.16.0
