### ISSUE TITLE
Issue UNIX Command Capability

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#1326]
**Describe the solution you'd like**

Would like to see a right click action for `Issue UNIX Command` and have it available via the Zowe Explorer API like we have `Issue TSO Command` and `Issue MVS Command`.

For zOSMF profile users we could have a check for an SSH profile.  Some extenders may have their own APIs to issue UNIX Commands so we would need to consider that as well.

**Comment by Joe-Winchester** [comment]
This would be great !  Very often I find myself using Zowe Explorer to edit .sh files and then wanting to run them, and if I could right mouse and "Run as shell script" this would be great.  It might want to add parms like "myscript.sh -o options" so maybe there is a general "Issue UNIX command" that can be run against a file that opens a general prompt (and runs the script with cwd inside that directory) and against a file if it detects it's .sh pre-fills the prompt with the file name to allow args to be added

**Comment by Joe-Winchester** [comment]
Awesome to see this in PI2.    

Q.   To do this from the USS tree it'd be great to have a way to associate a z/OSMF profile with an SSH one, and also likewise to this for TSO,  and allow it to be extended to other types.     Maybe have an association `sshProfile` and `tsoProfile` to be added to a zosmf (or ftp or otherwise base profile type),  so that the `Issue TSO command` in the Data Sets view or `Issue SSH command` in the USS view can link to the associated profile.  If an associated profile is not present the user with a drop down list of TSO or USS profiles to run the command, but then persist that back in the configuration file so next time they aren't prompted.  

```
 "zosmf_3b": {
            "type": "zosmf",
            "properties": {
                "host": "a.b.c.d",
                "port": 443,
                "rejectUnauthorized": false,
                "protocol": "https",
                "sshProfile": "ssh_3b",
                "tsoProfile": "tso_3b"
            }
        },
 ...
       "tso_3b": {
            "type": "tso",
            "properties": {
                "account": "",
                "codePage": "1047",
                "logonProcedure": "IZUFPROC"
            },
            "secure": []
        },
        "ssh_3b": {
            "host": "a.b.c.d",
            "type": "ssh",
            "properties": {
                "port": 22
            },
            "secure": []
        },
        
```

**Comment by JillieBeanSim** [comment]
moving to High Priority due to upvotes

**Comment by Joe-Winchester** [comment]
This issue could be a pre-req for issue https://github.com/zowe/vscode-extension-for-zowe/issues/2113, which is a request to be able to issue a `chtag` command from the USS tree to be able to change file tagging, which can be done by issuing a targeted shell command.

**Comment by JillieBeanSim** [comment]
I believe this would be implemented easily into v3 when only v2 profiles are supported and in most cases the ssh profile is added upon config creation.

**Comment by fbeyl** [comment]
> Issue https://github.com/zowe/vscode-extension-for-zowe/issues/2113 can be delivered thru z/OSMF api. This comes in handy for those who have only z/OSMF and not SSH.

**Comment by JillieBeanSim** [comment]
@likhithanimma1 wants to work on this issue
