### ISSUE TITLE
Support UNNUMBER in MVS explorer

### ISSUE THREAD

**Issue by pdbossman** [zowe/vscode-extension-for-zowe#1336]
Working with datasets in VSCode via the dataset explorer, it can be unnatural to have numbers.  This is particularly troublesome working with SQL, as the line numbers can be interpreted as SQL text.

Currently, the solution is to use UNNUMBER edit macro.

This has to be done on the host.  In my case, I also needed to completely close and restart VSCode, otherwise VSCode still had line numbers and would save them back.  Basically it was incredibly confusing.

1. Add unnumber option to zowe dataset explorer
2. Allow setting a property to default to unnumber datasets on open in vscode.

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
