### ISSUE TITLE
Multiple deletion of USS folders/files

### ISSUE THREAD

**Issue by katelynienaber** [zowe/vscode-extension-for-zowe#1339]
We should allow users to select multiple USS files & folders in the tree view, and delete them.

Acceptance criteria:
- Multiple USS files and/or folders can be selected in the tree for deletion (but not profiles, for consistency with DS tree)
- Selected items can be deleted by pressing the "delete" key (be careful, this hotkey is already associated with deletion of DS/members!! So that needs to be dealt with)
- Selected items can be deleted via the context menu
- A progress bar is shown during deletion (for consistency with DS & Jobs tree)

This issue is related to the following other multi-delete issues:
- [Add progress bar for multi-delete in Jobs tree](https://github.com/zowe/vscode-extension-for-zowe/issues/1338)
- [Multi-select actions for DS tree](https://github.com/zowe/vscode-extension-for-zowe/issues/1286)

**Comment by JillieBeanSim** [comment]
this has been completed
