### ISSUE TITLE
Add normal Job context menu commands for favorited jobs

### ISSUE THREAD

**Issue by lauren-li** [zowe/vscode-extension-for-zowe#1341]
**Is your feature request related to a problem? Please describe.**

Currently, the only thing you can do with a job in Favorites is remove it. If you want to do any action with the job (other than viewing its status/spool files), you have to search for the job outside of Favorites, which is an additional inconvenient step.

**Describe the solution you'd like**

Add normal Job context menu commands for favorited jobs.

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
