### ISSUE TITLE
Dev task - Clean up Zowe Explorer command localization keys

### ISSUE THREAD

**Issue by lauren-li** [zowe/vscode-extension-for-zowe#1345]
Task: Clean up command localization keys in `package.nls.json`, particularly for view-specific strings. For example, the large majority of strings for Zowe Explorer's Data Sets view have no prefix on them, making it hard for developers to be certain what view they apply to, especially since they are mixed with commands from other views. This task would mainly involve reviewing the key names and ensuring they follow the guidance outlined in `docs/developer/Menu-Commands.md`.

Completing this task should improve code maintainability, and should not have any UI impact. However, when renaming localization keys, care needs to be taken to search for and update any source code that references the updated keys.

Screenshot of current `package.nls.json`:
<img width="576" alt="Screen Shot 2021-06-04 at 8 46 38 AM" src="https://user-images.githubusercontent.com/45975633/120803560-acd9c180-c511-11eb-8fc8-8eaa74518fff.png">

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
