### ISSUE TITLE
Make sure that multi-select is handled in all tree functions

### ISSUE THREAD

**Issue by katelynienaber** [zowe/vscode-extension-for-zowe#1350]
We now have 2 functions which work for multi-select (deletion of jobs & datasets). This means 2 of our 3 trees have multi-selection enabled.

Users might think they can use multi-select everywhere in those trees, but they would be wrong!

We should check all of our DS/Jobs tree functions, to make sure they don't cause bugs on multi-select. And maybe we should show an error message if the user tries to do a multi-select action when it's not supported, even if the function "technically works" (ie. no bug happens, but just the first selected item is handled by the function, not all of them, as the user might expect)

**Comment by JillieBeanSim** [comment]
the multi select epic has been completed
