### ISSUE TITLE
Fix integration tests for "Enter Pattern"

### ISSUE THREAD

**Issue by katelynienaber** [zowe/vscode-extension-for-zowe#1354]
There is an issue with the following integration tests:
![image](https://user-images.githubusercontent.com/58596139/121489069-ffb0ee80-c9d3-11eb-9a00-6a9bf1dc448a.png)

For some reason the multi-delete PR changed these tests, and now they don't pass. Something to do with the node that happens to be at the top of the list when getChildren is called...

**Comment by JillieBeanSim** [comment]
![image](https://user-images.githubusercontent.com/49491949/126642923-661651fd-d6c5-4f62-84ad-08f7ad4ce817.png)
