### ISSUE TITLE
Refresh Jobs contents in Zowe Explorer

### ISSUE THREAD

**Issue by rudyflores** [zowe/vscode-extension-for-zowe#1357]
Currently, once the user expands a folder in the Jobs view, there is no intuitive way for them to get the latest list of Jobs for that folder. Consequently, they might guess to click the "Refresh Jobs View" icon, which collapses the entire tree and can frustrate the user, as they have to re-expand everything to get to where they were before.

This feature request proposes a Jobs-specific "Refresh" command in the context menu that pulls the latest list of Jobs. 

Workarounds: Users can currently close and re-expand a folder in the Jobs view to get the latest list of Jobs, but this is not necessarily an intuitive action.

**Comment by rudyflores** [comment]
Hi @nickImbirev I was wondering if you are currently working on this issue since I plan on working on this soon?

**Comment by lauren-li** [comment]
@rudyflores Was this issue resolved by PR #1363 (update job logs ability)?

**Comment by rudyflores** [comment]
Yes, we should be able to close this issue now @lauren-li
