### ISSUE TITLE
Refactor redundant/outdated favoriting commands

### ISSUE THREAD

**Issue by lauren-li** [zowe/vscode-extension-for-zowe#1364]
Zowe Explorer contains favoriting-related code that appears redundant/outdated. Although there seems to be no adverse UI/UX impact from this, it makes the code more confusing for developers to maintain. The following commands should be compared and reviewed for the 3 trees (Data Sets, USS, and Jobs) to ensure that redundant/outdated commands are either removed or updated, and that the relevant tests are also updated.

**Adding favorites:**

- `addFavorite`
- `saveSearch`

**Removing favorites:**

- `removeFavorite`
- `removeSavedSearch`

After this issue is addressed, UI/UX behavior should remain the same, but the code should be easier for developers to read.

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
