### ISSUE TITLE
'zowe.createDataset' failed - Rest API failure with HTTP(S) status 500 category: 8 rc: 22292 reason: 0 message: Dynamic allocation Error

### ISSUE THREAD

**Issue by jercab** [zowe/vscode-extension-for-zowe#1368]
Hello,

Any idea on these errors? Kindly help. Thank you in advance.

**Issue:**

When searching dataset ,  it is ok.
When creating dataset (Dat Set Classic), I am getting this error rc: 22292. 
I tried to create again (Z87217.TEST) to simplify with options Data Set Partitioned and Data Set Sequential, unfortunately, I got the same errors though.

**Installation steps:**
1. Install node.js
2. Install vscode (1.57.1)
3. Install zowe cli (1.16.0)

**Profile is created based on below parameters:**
- username and password from zskilss@us.ibm.com and Zih
- url: https://192.86.32.250:10443
- profile type: zosmf
- False - Accept connections with self-signed certificates

Please refer to **screenshots** when creating datasets and resulting errors.

Error encountered when creating data set! z/OSMF REST API Error: Rest API failure with HTTP(S) status 500 category: 8 rc: 22292 reason: 0 message: Dynamic allocation Error Error: z/OSMF REST API Error: Rest API failure with HTTP(S) status 500 category: 8 rc: 22292 reason: 0 message: Dynamic allocation Error

Error running command zowe.createDataset: Running the contributed command: 'zowe.createDataset' failed.. This is likely caused by the extension that contributes zowe.createDataset.

- OS: Windows 10 x64
- Zowe Explorer Version: 1.16.0 (VS code extension)

<img width="639" alt="000-zowe_searchdataset_ok" src="https://user-images.githubusercontent.com/83829417/122643991-58efef00-d145-11eb-91a6-1e06e764f11d.png">

<img width="484" alt="001-zowe_createdataset_01" src="https://user-images.githubusercontent.com/83829417/122643712-fa764100-d143-11eb-9b13-4930816be169.png">
<img width="464" alt="002-zowe_createdataset_02_select Classic" src="https://user-images.githubusercontent.com/83829417/122643719-fea25e80-d143-11eb-9b56-910820e1df4a.png">
<img width="465" alt="003-zowe_createdataset_03_select AllocateDataSet" src="https://user-images.githubusercontent.com/83829417/122643723-05c96c80-d144-11eb-8b83-0725a1518e8c.png">
<img width="344" alt="004-zowe_createdataset_04_errors" src="https://user-images.githubusercontent.com/83829417/122643726-09f58a00-d144-11eb-9bab-496971a76c0c.png">

**Comment by crawr** [comment]
Hi @jercab, is this issue still happening for you with our latest version?
