### ISSUE TITLE
Enforce read only on the member downloaded for specific PDS

### ISSUE THREAD

**Issue by jkothurigithub** [zowe/vscode-extension-for-zowe#1374]
Not sure if such feature exists in extension
the feature expected is to enforce read only mode for all the member downloaded from a specific PDS's.
on opening the members from the exception PDS they must be opened in read only mode in vscode editor to avoid unexpected change during analysis, like production/special user exit libraries.

Solution
Option to mention PDS's to be downloaded in read only mode in extension settings like "HLQ.PROD.COBOL", "HLQ.PROD.COPY", or "HLQ.PROD.*"
on opening the member, should open in read only mode irrespective of access right on mainframe

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
