### ISSUE TITLE
Save VSAM datasets into favorities

### ISSUE THREAD

**Issue by zimlu02** [zowe/vscode-extension-for-zowe#1376]
**Is your feature request related to a problem? Please describe.**

VSAM files cannot be added into Favorities. 

**Describe the solution you'd like**

I would like to add my VSAM files into the Favorities folder.

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
