### ISSUE TITLE
Install semantic PR bot

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1385]
I saw this repo and I thought it would be great to have this in our PR checks: https://github.com/zeke/semantic-pull-requests

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
