### ISSUE TITLE
Extend ProfilesCache to deal with other profile types

### ISSUE THREAD

**Issue by AndrewTwydell** [zowe/vscode-extension-for-zowe#1387]
**Describe the bug**

There is currently no way to register an API that is not of type MVS, Job or USS.

**To Reproduce**

When an API is registered for a new tree using one of the available options, the profiles used in the new tree are shown under the old tree. 

**Expected behavior**

It would be super useful if there was a `registerExtenderAPI()` method or something similar where one can register an API with Zowe Explorer that is not of type MVS, Job or USS.

**Screenshots**

Below is the result of adding a new Profile to datasets view after registering a tree that reads CICS profiles.

![image](https://user-images.githubusercontent.com/43643821/125065023-364c5880-e0a9-11eb-89e1-7e132dd85528.png)

As you can see, it displays the CICS profiles on the system as well as Zosmf profiles.

**Comment by jellypuno** [comment]
Objective: I am an extender and I want to use Profiles loaded/cached by Zowe Explorer

Request:
- Want the ability to register via ICommon.
- Andrew needs to connect to ProfilesCache without going to any tree
- 2 new methods to implement. One in Refresh and another in initialization
- New method where you can register a new profile type

Open Questions:
- Can you access a new tree view without registering?
- Performance Issue especially about initialization?
