### ISSUE TITLE
Publish a VSIX to zowe.org

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#1388]
**Is your feature request related to a problem? Please describe.**

Some sites may be unable to download from either the VSCode Marketplace (unlikely) or OpenVSX based on company policies.

**Describe the solution you'd like**

A stable VSIX file that can be downloaded from zowe.org

**Describe alternatives you've considered**

The alternative is to build the extension from source if they had access to GitHub

**Additional context**

There may be security consideration involved here.
See #1389

**Comment by jellypuno** [comment]
Can we do this via Technical Preview Download Page?

**Comment by zFernand0** [comment]
> Can we do this via Technical Preview Download Page?

it could be done in both.
https://www.zowe.org/download.html
In the Client-Side Component Installer (for the LTS versions) and in the Technical Preview section for the vNext compatible version. 😋

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
