### ISSUE TITLE
Avoid re-prompting for credentials when using the same unsaved-credentials profile between Favorites and non-Favorites

### ISSUE THREAD

**Issue by lauren-li** [zowe/vscode-extension-for-zowe#1393]
**Is your feature request related to a problem? Please describe.**
In Zowe Explorer 1.16.1, if you use a no-credentials profile to do a search (USS or Data Sets) and click “Do not save” after entering your credentials at the prompts, when you then try to expand your favorites for that same no-credentials profile, it will ask for your credentials again.

**Describe the solution you'd like**

As different views (e.g. Data Sets, USS, Jobs) with the same profile added currently do not re-prompt for credentials after I have entered credentials at the prompts for the first view used, I would like Favorites to also be able to skip prompting for credentials once I have entered my credentials earlier in the session.

**Describe alternatives you've considered**
The current user experience for this is workable but not optimal.

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
