### ISSUE TITLE
Support Multiple Instances

### ISSUE THREAD

**Issue by adambattenburg** [zowe/vscode-extension-for-zowe#140]
@Colin-Stone, @zFernand0 

## Issue:

When creating a new window, VSCode will clear the temp directory which affects all windows. This makes sense as each window is entirely independent of each other, and will call `deactivate` on startup and closing. Obviously this is not ideal, as all local files being worked with in the original window, are deleted as well. 

My recent temp directory PR however, introduced error messages when it tries to move the `temp` folder and it doesn’t exist. Functionally everything works fine (as in the same as before the PR), but it now introduces false error messages.

## Proposed Solution:

The `context.globalState` syncs across [multiple windows](https://github.com/Microsoft/vscode/issues/55834), so I would like to use that to track the number of active instances. `activate` will add `+1` to the instance counter, and `deactivate` will subtract one. If the number is greater than 1, the extension will not clear the `temp` folder on activate/ deactivate. The `moveTemp` function will also exit after the first time it’s run, so as not to trigger the error messages. 

I looked for an API that gets the current number of windows (instead of implementing a counter), but couldn’t find anything. We could get all workspaces, but it’s possible to have a window without an assigned workspace. If anyone has a suggestion for a better API or needs me to clarify the issue, just let me know. I'm planning to only work on this today, so hopefully I have a fix soon 🤞

**Comment by Colin-Stone** [comment]
That method will work and is better than losing the temp folder when it is still in use. However maybe it would be better to popup a dialog if Windows>1 to tell the user that erasing the temp folder could have serious consequences and that they should close other windows before applying?.

**Comment by adambattenburg** [comment]
Thanks Colin, I can see this as a good solution as well. We could make the extension not activate on startup up, but instead only when they click the "zowe" tab. This means we could kick users out of the extension each time they try to use multiple zowe instances. Users could still have multiple VSCode windows open, which is what I was more concerned about. 

Which solution would you rather? The user doesn't know that `activate`/`deactivate` erases the temp folder, so I think we should either support multiple instances or lock it at one. It would be difficult to explain this in a popup dialog. Locking instances to one feels like a regression to me, but I can see how it would be less error prone.

**Comment by Colin-Stone** [comment]
More complicated than I thought. The activate on clicking zowe tab option is interesting as some issues with startup performance have been registered. 
Otherwise I would vote for your original proposal adding and subtracting until you get to 1

**Comment by adambattenburg** [comment]
@Colin-Stone, unfortunately I'm not able to use the `extension.context.globalState` in the deactivate function apparently. This means I'll need to use something like a `lock` file in the `temp` folder to log instances. I can describe more what I mean later, but I think it's going to be a large undertaking.

In the short term, I'm going to create a PR to tackle the extra error messages that appear with multiple instances. As nothing is breaking (and it's not different then the original functionality) I think it would be best to deliver that incrementally.
