### ISSUE TITLE
Cannot retrieve Favorite datasets with *

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1402]
**Describe the bug**

Error is encountered when you try to use your favorited search with *

**To Reproduce**

1. Add a favorited search with an `*`. For example HLQ1.*
2. Go to favorites and click that dataset
3. It should retrieve the search results
4. Click the > button
5. This error appears

![image](https://user-images.githubusercontent.com/45042840/126480817-80fe5b53-3870-4b3e-98d0-9f3664c4ae97.png)

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/45042840/126480827-d0a9c232-11a9-480d-b6ff-6f3e5afe47ae.png)

**Desktop (please complete the following information):**

- OS: Windows
- Zowe Explorer Version: Latest
- (Optional) Zowe CLI Version: Latest
- (Optional) Are you using Secure Credential Store? No

**Additional context**

**Comment by jellypuno** [comment]
Error happens around [Line 274  onwards:](https://github.com/zowe/vscode-extension-for-zowe/blob/master/packages/zowe-explorer/src/dataset/ZoweDatasetNode.ts#L274)

![image](https://user-images.githubusercontent.com/45042840/126481691-e4fa674d-6077-4152-83d3-79d4e34f5604.png)

**Comment by JillieBeanSim** [comment]
may be related to https://github.com/zowe/vscode-extension-for-zowe/issues/1164

**Comment by JillieBeanSim** [comment]
Retested this scenario with ZE 2.13.0 and no longer an issue, works as expected now 

https://github.com/zowe/vscode-extension-for-zowe/assets/49491949/fe30401a-ec4f-4aac-92b3-7cc14c664c4b
