### ISSUE TITLE
Refresh view does not consistently reset profile status

### ISSUE THREAD

**Issue by lauren-li** [zowe/vscode-extension-for-zowe#1403]
**Describe the bug**

Clicking on the "Refresh Data Sets View" does not reset all profile status icons.

**To Reproduce**

1. Use a connected (active, validated) profile with credentials to perform a search in the Data Sets view.
2. Click the the "Refresh Data Sets View" button
3. Observe that the status icon for the profile used in Step 1 does not reset.

**Expected behavior**

Clicking on Refresh Data Sets View should reset the status icons for all profiles to the empty, gray Unverified circle.

**Screenshots**

![ze-refreshIcon](https://user-images.githubusercontent.com/45975633/126635413-70122750-db7b-40dd-a5cf-58cd916b8609.gif)

**Desktop (please complete the following information):**

- OS:
- Zowe Explorer Version: 1.17.0

**Comment by katelynienaber** [comment]
Hi, this seems to be working for me.

Unrelated issue, my FTP profiles are not being validated at all. When they are valid or invalid, the icon doesn't change, and there is no validation check before ex. searching. Is this by design? If not I will open another issue.

**Comment by lauren-li** [comment]
> Hi, this seems to be working for me.
> 
> Unrelated issue, my FTP profiles are not being validated at all. When they are valid or invalid, the icon doesn't change, and there is no validation check before ex. searching. Is this by design? If not I will open another issue.

@katelynienaber Thanks for reviewing this PR! The Zowe Explorer FTP extension does not yet have profile validation implemented. We have issue #1284 open to work on it.

**Comment by katelynienaber** [comment]
@lauren-li I will approve it, I figured there wasn't much point in doing a review unless changes were requested :) Thanks for addressing it!
