### ISSUE TITLE
Address issues opened related to the validation of the `@next` version

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1406]
As a Zowe Explorer developer, I would like to address open issues that is related to the validation of Zowe CLI's `@next` version. 

Recent Zowe CLI release: v7.0.0-next.202106291335

**Comment by jellypuno** [comment]
Latest CLI version: July 13
- Change all createBasicZosmf to createSessfromArg
- Abstract the creation of session. Cleaning up session in ZE code > Use node.profile instead of session.
- Validate extenders if it works with this new function
- Any non duplicate profiles whether it is project or global will appear in CLI.

**Comment by JillieBeanSim** [comment]
@crawr have we completed this list of items and can close this issue?
