### ISSUE TITLE
@zowe/cli dependency on ZoweExplorerApi

### ISSUE THREAD

**Issue by dkelosky** [zowe/vscode-extension-for-zowe#1410]
**Describe the bug**

This [line](https://github.com/zowe/vscode-extension-for-zowe/blob/master/packages/zowe-explorer-api/src/profiles/ZoweExplorerZosmfApi.ts#L12) has:
```typescript
import * as zowe from "@zowe/cli";
```

However, `@zowe/cli` does not appear to be a dependency in [`package.json`](https://github.com/zowe/vscode-extension-for-zowe/blob/master/packages/zowe-explorer-api/package.json).

**To Reproduce**

**Expected behavior**

Should this be a dependency?  Can the dependency be on the required pieces of the Zowe SDK rather than the entire `@zowe/cli` package? 

**Screenshots**

Error when using `"@zowe/zowe-explorer-api"` as a dependency in `package.json`
```
node_modules/@zowe/zowe-explorer-api/lib/profiles/ZoweExplorerApi.d.ts:1:23 - error TS2307: Cannot find module '@zowe/cli' or its corresponding type declarations.

1 import * as zowe from "@zowe/cli";
```

**Additional context**

**Comment by jellypuno** [comment]
We have it here: https://github.com/zowe/vscode-extension-for-zowe/blob/master/package.json#L21

**Comment by jellypuno** [comment]
Maybe you need to run build first?

**Comment by dkelosky** [comment]
thanks @jellypuno - in my case though, I'm using `@zowe/zowe-explorer-api` as a dependency within another project outside of this monorepo.  it seems like the [dependencies](https://www.npmjs.com/package/@zowe/zowe-explorer-api) for `@zowe/zowe-explorer` should include `@zowe/cli` (or the appropriate) Zowe SDK.

**Comment by AndrewTwydell** [comment]
Hi all, Jeffin and myself are also running into this issue when working on the CICS Extension, and @lauren-li has also confirmed she gets the same error when testing. 

Was there a fix found for this bug, or is there something I can do to get round it?? It's preventing us from building the most up-to-date VSIX file 🤔

**Comment by phaumer** [comment]
Yes, the dependency is in the parent package, but for publishing it to npm we should have redundantly included it. 
As extenders would include zowe/cli anyway in their code I guess that there should also be a tsconfig setting to prevent this error.
