### ISSUE TITLE
Next Steps for vNext

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1413]
### Discussed in https://github.com/zowe/vscode-extension-for-zowe/discussions/1412

<div type='discussions-op-text'>

<sup>Originally posted by **jellypuno** July 29, 2021</sup>
For Zowe Explorer V2, we are targeting for the following:
1. Approved v1 Conformance Criteria
2. Support for team configuration where users can create their own initial team-config file via ZE and load existing team-config file created via CLI

Once this MVP is released and available, we want to implement the following
1. v2 Conformance Criteria
2. Management of team config (Update and Delete)

I am opening this discussion so we could have a channel to talk about our next steps regarding team-config. We have lots of open questions and it would be great if we could start discussing them now.

Open Questions:
1. Are we going to allow updating of the team-config via VSCode dialog boxes or Web Views? Right now, we are opening the team-config file and we are asking users to refresh VSCode so the changes will take effect. This is a workaround and we would need a better solution for this
2. Are we going to handle multi-root workspace of team-config?
3. How about tokens?
4. Are we deprecating our old profile management? (creating of yaml files)</div>

**Comment by zFernand0** [comment]
Will continue conversations in the discussion #1412
