### ISSUE TITLE
Error in edit Session

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1418]
**Describe the bug**

Error appears when I cancel the Update Profile

**To Reproduce**

1. Click Update Profile
2. Press ESC to Cancel
3. Error appears:
![image](https://user-images.githubusercontent.com/45042840/127663919-4292a132-f0a0-4127-9362-641f19b494c4.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Zowe Explorer Version: Latest
- (Optional) Zowe CLI Version: 7.0.0-next.202106012053
- (Optional) Are you using Secure Credential Store? No

**Additional context**

**Comment by JillieBeanSim** [comment]
Closing, this was fixed in https://github.com/zowe/vscode-extension-for-zowe/pull/1426
