### ISSUE TITLE
Encoding is not considered - descriped in issue #1171 

### ISSUE THREAD

**Issue by jHeidenberger** [zowe/vscode-extension-for-zowe#1420]
**Describe the bug**

I'm sorry but the problem still occurs with us. With version 1.8 the encoding is taken into account when opening files. Also with version 1.17 I have to explicitly select "pull from mainfraim" to change the encoding from 1047 to IBM-1141.

**To Reproduce**

see #1171

**Desktop (please complete the following information):**

- OS: Windows 10 
- Zowe Explorer Version: 1.17
- (Optional) Zowe CLI Version: 1.23 
- (Optional) Are you using Secure Credential Store? no 

**Additional context**

**Comment by jHeidenberger** [comment]
@JillieBeanSim thx a lot for your support! Do you have an explanation why this no longer works for us since 1.8? Is it possible to do something wrong with ZOWE profiles or whatever? 
Best regards, Joerg

**Comment by JillieBeanSim** [comment]
Hello @jHeidenberger this fix should go out in 1.18.0. Once that is released would you mind re-testing, and if the situation has been addressed close this issue?

**Comment by jHeidenberger** [comment]
Hello @JillieBeanSim, 
thank you very much, we will do it that way. I am looking forward to testing the new version.

**Comment by JillieBeanSim** [comment]
@jHeidenberger 1.18.0 is in the marketplace now.  Let me know if this is fixed now please.

**Comment by jHeidenberger** [comment]
@JillieBeanSim Hello, great job! Seems the problem is fixed now. Thx a lot and best regards

**Comment by JillieBeanSim** [comment]
> @JillieBeanSim Hello, great job! Seems the problem is fixed now. Thx a lot and best regards

@jHeidenberger that is awesome news.  Thanks for verifying the fix =)
