### ISSUE TITLE
Better error message for locked data sets and members

### ISSUE THREAD

**Issue by plavjanik** [zowe/vscode-extension-for-zowe#1422]
**Is your feature request related to a problem? Please describe.**

I am editing a member in a data set and I am not able to save it.

I am getting this error:

![image](https://user-images.githubusercontent.com/7644758/127986343-de1ce8b7-bb0e-4473-8352-2125c44ac88b.png)

```
z/OSMF REST API Error: Rest API failure with HTTP(S) status 500 category: 6 rc: 8 reason: 513 message: Enqueue for QNAME=SPFEDIT failed details: - ISGENQ obtain for SPFEDIT/ADCD.Z24C.TCPPARMS TLSPOLY1 failed: RC/REASON=0x40404
```

Note: As a mainframe developer that has used the ISGENQ service in the past, I know that this means that someone has already exclusively opened the member. But for other people, this message can be cryptic.

**Describe the solution you'd like**

Display message like: _Not able to save member DATASET.NAME(MEMBER) because it is already exclusively opened/locked by user USERID._

**Describe alternatives you've considered**

Alternatives are guessing what it can mean, or spending time in IBM documentation to find out what the return codes mean.

**Additional context**

**Comment by jellypuno** [comment]
@MikeBauerCA I need your advise. Originally we decided to not manipulate the z/OSMF messages and just display them in ZE. Do you think that this still applies? 

If ever, we agree that we should re-format the messages, I suggest to do it in the SDK so that all client who uses the SDK can have those messages rather than Zowe Explorer will do the parsing.

**Comment by MikeBauerCA** [comment]
@plavjanik do you believe these error messages should be intercepted and improved by the client technologies or should we open an RFE with z/OSMF to improve such messages across the board?

**Comment by plavjanik** [comment]
@MikeBauerCA In this case, I would open an RFE first. The message looks quite unstructured so its parsing can be problematic and difficult to maintain. In the REST APIs, we usually provide better messages ourselves but there we have programmatic and stable APIs to access various return and reason codes. Is z/OSMF returning error details in a JSON format decribed in https://www.ibm.com/docs/en/zos/2.4.0?topic=zdsfri-json-document-specifications-zos-data-set-file-rest-interface-requests#RESTFILES_JSONDocumentSpecifications__ErrorReportDocumentContents_4RESTfile?

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
