### ISSUE TITLE
Open solution for default file allocations settings

### ISSUE THREAD

**Issue by FALLAI-Denis** [zowe/vscode-extension-for-zowe#1425]
**Is your feature request related to a problem? Please describe.**

The solution allowing to define the default parameters of allocation of the files is "closed" and foresees only address some use cases.
These use cases do not necessarily make sense for a site.

**Describe the solution you'd like**

The solution for defining default file allocation parameters should be "open", which means that the site is free to define its file allocation models, to meet its requirements.

In the settings, instead of defining objects "Zowe-Default-Datasets-Binary", "Zowe-Default-Datasets-C", "Zowe-Default-Datasets-Classic", "Zowe-Default-Datasets-PDS", "Zowe-Default-Datasets-PS", which are "closed" declarations with imposed names, it would rather be necessary to declare an array of allocation models, and the user (the site) would be free to define the different models of his choice, with the names of his choice.

```
    "Zowe-Default-Dataset-Allocations": [
       "PDS-FB-80": {
          "name": "Fixed blocked LRECL=80 library",
          "dsorg": "LIBRARY",
          "alcunit": "CYL",
          "primary": 1,
          "secondary": 1,
          "dirblk": 0,
          "recfm": "FB",
          "blksize": 0,
          "lrecl": 80
       },
       "PDS-VB-256": {
          "name": "Variable blocked LRECL=256 library",
          "dsorg": "LIBRARY",
          "alcunit": "CYL",
          "primary": 1,
          "secondary": 1,
          "dirblk": 0,
          "recfm": "FB",
          "blksize": 0,
          "lrecl": 80
       },
       "Loadlib": {
          "name": "Loadlib for program object",
          "dsorg": "LIBRARY",
          "alcunit": "CYL",
          "primary": 10,
          "secondary": 10,
          "dirblk": 0,
          "recfm": "U",
          "blksize": 32760,
          "lrecl": 27998
       },
       "Report": {
        "name": "Sysout capture for LRECL=133",
        "dsorg": "PS",
        "alcunit": "CYL",
        "primary": 10,
        "secondary": 10,
        "dirblk": 0,
        "recfm": "FBA",
        "blksize": 0,
        "lrecl": 133
     }
  ]
```

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by FALLAI-Denis** [comment]
I think the defaults values and the naming of the allocation models used in Zowe Explorer are an inheritance of the same information managed in Zowe CLI "core".

The Zowe Explorer extension must overcome the Zowe CLI on this point.

And besides, the fact that Zowe CLI offers allocation models poses the same problem as in Zowe Explorer: not necessarily consistent with the operation of the site, especially in the presence of default values such as for example on the blocksize which come into conflict with automatic management by DFHSMS or ACS declared on site.

**Comment by MikeBauerCA** [comment]
I agree with this also being beneficial for Zowe CLI users. Perhaps these custom allocation models could be placed in the new shared config file (`zowe.config.json`). For CLI, we could add an option (perhaps `--template`) on the `zowe files create ds` command to accept custom models.
