### ISSUE TITLE
[next] Error handling and User/Pass Prompting for Config File Profiles

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#1456]
**Describe the bug**

on the `next` branch we have noticed that while using new style profiles in the config file:
- if user/pass not stored user is prompted for all missing args vs just user & pass
- if user's credentials are incorrect only `No Data Sets` is displayed vs having the `Check Credentials` pop up.  No error message or anyway of knowing that it failed from bad credentials
- if the config file doesn't have host stored unclear errors pop up

**Expected behavior**

- when prompted for credentials, only be prompted for credentials
- when credentials are incorrect and 401 returned have the `Check Credentials` pop up show and when button is clicked be prompted for correct credentials 
- if host name is not stored in the config file an error pops up explaining that host is missing and open the config file for the user to add it.

**Comment by lauren-li** [comment]
With regards to the "missing host" portion of this PR, a related issue I was seeing with extender profiles (from testing PR #1448) was for new-style profiles, if I only follow the user/password prompts upon typing zowe config init in Zowe CLI, and do not add anything else to the config file, the extender profiles do not load on Zowe Explorer/extender activation (only the z/OSMF profile loads). However, once I add a hostname into the config file and reload the VS Code window, all extender profile types load without issue upon activation.

**Comment by JillieBeanSim** [comment]
> With regards to the "missing host" portion of this PR, a related issue I was seeing with extender profiles (from testing PR #1448) was for new-style profiles, if I only follow the user/password prompts upon typing zowe config init in Zowe CLI, and do not add anything else to the config file, the extender profiles do not load on Zowe Explorer/extender activation (only the z/OSMF profile loads). However, once I add a hostname into the config file and reload the VS Code window, all extender profile types load without issue upon activation.

@lauren-li this situation isn't handled in this PR.  We will need to investigate if this is being caught in the add session or if the error is just being returned to the extender.
