### ISSUE TITLE
Error message: Options with treeDataProvider is mandatory

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#146]
After including a fix for https://github.com/zowe/vscode-extension-for-zowe/issues/133 I noted that I subsequently received a red message "Options with treeDataProvider is mandatory".

VSCode is not failing nicely when something goes wrong so we should investigate if whatever step causes this should not fail more gracefully.

@lauren-li  would you be able to assess please?.

**Comment by lauren-li** [comment]
@Colin-Stone Yes, I can take a look at the `Options with treeDataProvider is mandatory` error. I had noticed this error occurring at the same time as the massive error message from #133, but wanted to prioritize the message from #133 since that one seemed to have a bigger impact.
