### ISSUE TITLE
GHA: Release PR should only require a top-level package.json version bump

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#1465]
**Desired solution:**

Simplify the Version Bump PR to only the top level package.json file

Also, the [`Preparing for a Release`](https://github.com/zowe/vscode-extension-for-zowe/wiki/Preparing-for-a-release) wiki page will need to be updated

_Originally posted by @zFernand0 in https://github.com/zowe/vscode-extension-for-zowe/issues/1463#issuecomment-906458220_

**Comment by lauren-li** [comment]
Incremental step towards addressing #1464.

**Comment by t1m0thyj** [comment]
Resolved in #2115 - now we only need to bump the version in the top-level lerna.json file, and our deployment automation handles the rest. The wiki page has also been updated.
