### ISSUE TITLE
GHA: Allow `deployment.yml` to be run manually to prevent creating a Release PR

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#1466]
**Desired Solution:**

Simplified Release process where the only requirement is to run the workflow manually (via workflow_dispatch) and provide the version to be published.

Also the [`Preparing for a Release`](https://github.com/zowe/vscode-extension-for-zowe/wiki/Preparing-for-a-release) wiki page may be removed.

We will need to save the note about the Token expiration date though.

_Originally posted by @zFernand0 in https://github.com/zowe/vscode-extension-for-zowe/issues/1463#issuecomment-906458220_

**Comment by t1m0thyj** [comment]
#2115 added support for manually triggering the deployment workflow. However we left the `workflow_dispatch` trigger commented out for now due to security-related concerns.

**Comment by t1m0thyj** [comment]
Closing for now, the updated deployment workflow can be triggered with a `workflow_dispatch` event should we choose to enable that in the future.
