### ISSUE TITLE
Deleting a member while the PDS remaining selected will delete the whole PDS

### ISSUE THREAD

**Issue by tanto259** [zowe/vscode-extension-for-zowe#1470]
**Describe the bug**

If a user select on a PDS, and then right-click on a member and press "Delete Member", the whole PDS will be deleted.

**To Reproduce**

1. Set up a profile
2. Click on any dataset (e.g. Z99998.TEST.JCL)
3. Right click on a member within the data set (e.g. Z99998.TEST.JCL(TEST))
4. Press "Delete Member"

**Expected behavior**

Only the member will be deleted.

**Video**

https://user-images.githubusercontent.com/13640520/131326372-2c3095ab-1614-4430-a955-cf55b0f182b4.mp4

**Desktop**

- OS: Windows 10
- Zowe Explorer Version: 1.18.1
- VSCode Version: 1.59.1
- Node Version: 14.17.5

**Additional context**

Additionally, if a user decide to click on a member, and right-click a PDS then press "Delete Data Set", only the member gets deleted.

**Comment by JillieBeanSim** [comment]
after investigating, it's not adding the member that the right click is happening on to the list to be delete, only the highlighted items

**Comment by JillieBeanSim** [comment]
I have a proposal as a quick fix until we decide a final solution in our discussion https://github.com/zowe/vscode-extension-for-zowe/discussions/1130

If a member and the parent are both selected/highlighted the parent is removed from the list to be deleted.  I also propose a different view for the confirmation that will include listed data sets and members that will be deleted if confirmed.

![delete-proposal](https://user-images.githubusercontent.com/49491949/132738602-1f1da02d-d4ba-4fb0-af88-a9774cc13b1e.gif)

**Comment by JillieBeanSim** [comment]
I also have another proposal where (like in vsc tree) if items are selected and the right click option is done on an unselected node then only that node that was right-clicked -> delete is the one deleted
The above can still apply or we can remove the check I put in for member parent in selected items and only remove the member not the parent.

![delete-pickup-node](https://user-images.githubusercontent.com/49491949/132749642-3e216ede-5587-40ee-ae7c-f13313ff5dda.gif)

**Comment by lauren-li** [comment]
> I also have another proposal where (like in vsc tree) if items are selected and the right click option is done on an unselected node then only that node that was right-clicked -> delete is the one deleted
> The above can still apply or we can remove the check I put in for member parent in selected items and only remove the member not the parent.

I like this proposal as it matches what VS Code does in the same scenario. Generally speaking, I prefer to try and follow the VS Code behavior as closely as possible, just to maintain a consistent UX. I believe it should be possible to even have the info message with the list of items be a modal (similar to how VS Code does theirs for multi-select).

I'll also note that in VS Code, if you select a parent folder and one child file (out of many) for deletion, it will proceed with trying to delete the parent folder and all its children - but first ask you to confirm. Perhaps we can try to do it this way in Zowe Explorer, as well:

<img width="731" alt="Screen Shot 2021-09-09 at 2 19 16 PM" src="https://user-images.githubusercontent.com/45975633/132753853-9b4e5799-e34f-4266-b60a-db96f5ff0d09.png">

**Comment by JillieBeanSim** [comment]
We can do that, no formatting though like above
![image](https://user-images.githubusercontent.com/49491949/132755842-b3de9eff-7062-4267-aaad-82b5a0012faf.png)
