### ISSUE TITLE
Missing grammar files for Spool Output

### ISSUE THREAD

**Issue by crshnburn** [zowe/vscode-extension-for-zowe#148]
PR #142 sets the language for the JESJCL, JESSYSMSG and JESMSGLG spools but opening them still opens the files in plaintext as there are no grammar files available either in this extension or another extension in the market place.

It would aid usability if the grammar files were included in this extension or another which could be referenced in the README.

**Comment by Colin-Stone** [comment]
Kristina is anyone able to provide these files currently or should we pull the changes for now?

**Comment by kristinochka** [comment]
I'm investigating on how to provide the grammar files.

**Comment by kristinochka** [comment]
The intent of the PR was to enable the possibility to assign grammars in third party extensions as well as opening it up for future code donations

**Comment by Colin-Stone** [comment]
Is there a way that these languages can be associated with the jcl and log language extensions?

**Comment by Colin-Stone** [comment]
The function is not referenced and is the only function in jesNode Actions. Suggest the file is deleted.
