### ISSUE TITLE
Deleting a data set or member causes a Debug Console error

### ISSUE THREAD

**Issue by lauren-li** [zowe/vscode-extension-for-zowe#1489]
**Describe the bug**

When running Zowe Explorer in the Extension Development Host, when I delete a data set or member, the delete still goes through successfully, but I get the following error in the Debug Console:

<img width="611" alt="Screen Shot 2021-09-14 at 10 42 30 AM" src="https://user-images.githubusercontent.com/45975633/133286368-c7098a43-e6af-4ad0-b48e-2a080d838164.png">

**To Reproduce**

1. Right-click a data set or PDS member, and select *Delete* from the context menu.
2. At the confirmation prompt, select *Delete*.
3. The data set/member gets deleted, but the error message appears in the Debug Console.

**Expected behavior**

No Debug Console error when deleting a data set or member.

**Desktop (please complete the following information):**

- OS: MacOS and Windows
- Zowe Explorer Version: 1.18.1
- (Optional) Zowe CLI Version: 6.33.1

**Comment by traeok** [comment]
I did some testing with this and found that these debug console errors no longer occur with the latest version of ZE. Will bring this up during next stand-up to confirm and close the issue if resolved.

**Comment by traeok** [comment]
Hi @lauren-li ,

Just to follow up: I tried to reproduce this error again (with the latest changes in `main`, as of today) and tested w/ 4 scenarios:

- Deleting an unfavorited dataset
- - Deleting an unfavorited dataset
- - Deleting an unfavorited dataset

**Comment by lauren-li** [comment]
@traeok I tested again in the Extension Development Host with the `main` branch (as of today, commit [c2e1625](https://github.com/zowe/vscode-extension-for-zowe/commit/c2e16258118e5854ed42687709153bd12cd4a61c)), and I no longer see the error message appearing in the Debug Console for any of the four scenarios you listed.

I will go ahead and close this issue, as it appears to now be resolved. Thanks @traeok for following up on this issue!
