### ISSUE TITLE
Quick-key `Delete` not working in USS tree

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#1510]
**Describe the bug**

In the USS tree selected items cannot be deleted using the delete keyboard key, only the right-click menu option to delete.  Data Sets and Jobs trees work using both methods.

**Expected behavior**

Selected item in USS tree should present the user with a confirmation box for deletion if the delete key is pressed like it does with the right-click delete option chosen.

**Desktop (please complete the following information):**

- OS: Windows
- Zowe Explorer Version: master branch
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by KutluOzel-b** [comment]
Missing implementation of the same feature for jobs as well. We will take care of this as a part of this issue.
