### ISSUE TITLE
Unable to query datasets with `#` in the name

### ISSUE THREAD

**Issue by macjabeth** [zowe/vscode-extension-for-zowe#1511]
**Describe the bug**

When attempting to search for datasets that include a `#` in the name, it fails with a 400 Bad Request.

Requests to other datasets work fine.

**To Reproduce**

1. Go to Data Sets in Zowe Extension
2. Create your profile (if not already created)
3. Click the magnifying glass to search a new dataset
4. Search for a dataset that includes `#` in its name
4. See the 400 error

**Expected behavior**

Searching for these datasets should return a proper response without error.

**Screenshots**

![image](https://user-images.githubusercontent.com/8473052/135539941-836bfafb-0f45-47de-8be3-379c4e5cf0ab.png)

**Desktop (please complete the following information):**

- OS: macOS Big Sur (11.6)
- Zowe Explorer Version: v1.19.0
- (Optional) Zowe CLI Version: N/A
- (Optional) Are you using Secure Credential Store? N/A

**Additional context**

Replacing `#` with `%23` fixes the issue (temporarily) so the datasets can be searched for. However, it still doesn't let me open the datasets after searching them.

**Comment by jellypuno** [comment]
@macjabeth Is this still happening to you? I tried it with v1.19 and it was okay.
![Untitled](https://user-images.githubusercontent.com/45042840/142452185-da882839-ef65-47c3-9451-9cd46511d8b1.png)

**Comment by macjabeth** [comment]
@jellypuno Just tried it and I'm still getting errors, unfortunately.

![image](https://user-images.githubusercontent.com/8473052/142501428-29a1cb17-862b-426d-9556-3f0ea3a0e674.png)

Doesn't work with `#`. When I replace # with `%23`, it loads the results as expected _but_ doesn't let me open any of them (presumably b/c it queries for `#` again behind the scenes).

**Comment by macjabeth** [comment]
Any updates on this? Or ideas on how to fix it? I'm still having the issue, both with the VSCode extension and the Zowe CLI.

**Comment by JillieBeanSim** [comment]
special char support fixed with PR #1977
