### ISSUE TITLE
Error messages in Zowe Exporer

### ISSUE THREAD

**Issue by INEGOFS** [zowe/vscode-extension-for-zowe#1512]
Sometimes In ZOWE Explorer Error messages are not very explicit.
In this example I tried to create a file with an incorrect z/OS name (containing Quotes)
The error was :

_Error running command zowe.ds.createDataset: Running the contributed command: 'zowe.ds.createDataset' failed.. This is likely caused by the extension that contributes zowe.ds.createDataset._

And then in an other window :

_Error encountered when creating data set! z/OSMF REST API Error: Rest API failure with HTTP(S) status 500 category: 8 rc: 860 reason: 2 message: Dynamic allocation Error Error: z/OSMF REST API Error: Rest API failure with HTTP(S) status 500 category: 8 rc: 860 reason: 2 message: Dynamic allocation Error_

Is it possible to have a more explicit message like in ISPF : 
 
                          ‘Invalid DSN : Dsname contains embedded blanks, parentheses or apostrophes ‘

Zowe explorer screenshots :

![image](https://user-images.githubusercontent.com/73526794/135885300-5aab40a2-4418-4e68-8d02-41c7b86582ee.png)

![image](https://user-images.githubusercontent.com/73526794/135885319-37209bcb-e955-4f04-8e89-2f35f5f470c2.png)

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
