### ISSUE TITLE
[next] Research how to automatically refresh the ZE tree when you create a team config file

### ISSUE THREAD

**Issue by crawr** [zowe/vscode-extension-for-zowe#1514]
@crawr I think a separate PR would be fine, not sure if create, update, and delete will work though since it just opens the config file but having it work for this and view's refresh button would be a great start.  That way after create, update, and delete actions are done by the user on the config file they could just click the refresh button and those changes will be seen without restarting VSC.

_Originally posted by @JillieBeanSim in https://github.com/zowe/vscode-extension-for-zowe/pull/1472#discussion_r710031307_

**Comment by jellypuno** [comment]
Today, after creating a team config file via ZE, there's a prompt that asks you to reload the VSCode session to load the information from the team config file. I would like to have a better way to update the ZE tree once the team config is updated.  Ideally, I would like to leverage the refresh button in refreshing the ZE profile information
