### ISSUE TITLE
[next] Issue TSO Command not picking up information from config file's TSO profile

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#1515]
**Describe the bug**

`Issue TSO Command` isn't recognizing the TSO profile information like acct number from the config file.

Noticed the behavior testing https://github.com/zowe/vscode-extension-for-zowe/pull/1509

**Comment by jellypuno** [comment]
Note: There is an  RFE to allow the TSO account number for REST files to be passed in and it will become available in December
