### ISSUE TITLE
Allow extenders to update the team configuration file schema

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1528]
Today, if you are an extender and you want to create a new profile in the team config, you have to edit the schema manually to include the details of your schema. We would like to have a way to automatically add an extenders schema once installed in VSCode.

**Comment by crawr** [comment]
We should be able to use the new `zowe config update-schema` command for this enhancement. This is available in the `5.0.0-next.202110071645` version of imperative.

**Comment by JillieBeanSim** [comment]
@crawr do you think we should do 2 PRs with this, where the 1st is the update of the CLI version with fixes for breaking changes and then the 2nd handle the actual extender config work?

**Comment by crawr** [comment]
@JillieBeanSim Yes, I think this is a good idea. I can work on that first PR so we can use that when we talk about the strategy for the extender work

**Comment by JillieBeanSim** [comment]
I have the Zowe Explorer adding the extenders that use the ZoweInit() to the config file && the Zowe Explorer is independent of the CLI! Woohoo!
![extender-config-no-cli](https://user-images.githubusercontent.com/49491949/148793737-cbe74a49-6236-47c2-99b0-6420a08a95a4.gif)

**Comment by JillieBeanSim** [comment]
This is a good start to remove the Zowe CLI dependency and includes extenders that use the initForZowe() extender API passing their schema information during our creation of config files.

I think the next step will be to add something to the initForZowe() to check for an existing config file that may need to be updated with the new extender information.  What do you think about this plan @crawr @jellypuno ?

**Comment by JillieBeanSim** [comment]
To be discussed:

Would it be a good enhancement to allow an automatic update of the global team config when an extender registers with Zowe Explorer and their configuration isn't already in the config file?

We wouldn't want to do this for any team config files to avoid automatic changes to a file related to a repository.

**Comment by jellypuno** [comment]
@JillieBeanSim An info message indicating that the global config schema was updated would be helpful as well

**Comment by MikeBauerCA** [comment]
This direction is similar to how CLI handles it. If a CLI plug-in is installed, only the global schema is updated. Project schemas must be updated via a separate command (either re-init the config or use the `zowe config update-schemas` command)

**Comment by JillieBeanSim** [comment]
new issue for continued work discussed above https://github.com/zowe/vscode-extension-for-zowe/issues/1642
