### ISSUE TITLE
ability to Compare/Select files to Compare in ZE

### ISSUE THREAD

**Issue by dezkolakatus** [zowe/vscode-extension-for-zowe#1533]
**Is your feature request related to a problem? Please describe.**
As a user i would like to easy involve comparing of files in Zowe Explorer.

**Describe the solution you'd like**
 (with a right click or a button). I want to select the files which i want to compare and those will be open in editor with highlighted differences.

**Describe alternatives you've considered**
Using standard workaround in VS code is not so native for MF Developers.

**Additional context**
Request opened on behalf of Morgan Stanley team

**Comment by zFernand0** [comment]
It seems like 6-7 people are interested in this feature.
For now, please refer to #246 for details.
