### ISSUE TITLE
Allow users to use their APIML instance to initialize a team configuration file

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1536]
As a Zowe Explorer User that leverages the team config file, I would like to ability to create a new config file based on my APIML set-up. This capability is possible in Zowe CLI `@next` using `zowe config auto-init` command

**Comment by jellypuno** [comment]
Sample User flow:

![image](https://user-images.githubusercontent.com/45042840/140733943-125e6861-65b3-4d48-8844-b618a60e0700.png)

Ways to check the APIML instance:

- Call `https://systemx.acme.net:1234/gateway/api/v1/version`  to find out if I am talking with to an API ML gateway and if it is a supported version
- Call `https://systemx.acme.net:1234/gateway/api/v1/services` to find out if the service that I am calling supports SSO

**Comment by jellypuno** [comment]
Open Questions: 

- The APIML Auth Service is not available in the SDK so should we add that?
- IS it okay to expose that API to extenders? If yes, how?

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
