### ISSUE TITLE
Change Password using Zowe CLI APIs

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1538]
As a Zowe  Explorer User, I would like to have the ability to change my password for the mainframe through Zowe Explorer. 

dependency on Zowe CLI making use of the z/OSMF APIs:
z/OSMF implemented a REST API auth service that will make this enhancement possible:  https://www.ibm.com/docs/en/zos/2.4.0?topic=services-zosmf-authentication

**Comment by jellypuno** [comment]
Tried it today an it works 😸 

![zosmf](https://user-images.githubusercontent.com/45042840/142008403-ca9e26ce-78fe-4c03-a87b-2bff0865e0cf.png)

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.

**Comment by JWaters02** [comment]
CLI work started: https://github.com/zowe/zowe-cli/pull/2682

> Research does zosmf accepts change password for revoke IDs

No it doesn't. Maybe this is a site-based setting - but both on my work system and on the zxplore system, revoked user ID passwords must be reset via online portals.
