### ISSUE TITLE
Multiple job select for downloading spools

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1551]
As a ZE User I would like to select multiple job spools and download its contents

Possible UX:
1. Select multiple job spools
2. Right-click > Download Spool
3. The jobs will be downloaded 
     - I believe that the SDK will create separate folders based on the JobID. Same should happen in ZE

**Comment by KutluOzel-b** [comment]
This feature is completed via : https://github.com/zowe/vscode-extension-for-zowe/pull/1917
