### ISSUE TITLE
Limit TSO/MVS in DS tree only

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1557]
Revisit where the option is presented. I believe we should only present the option within the Data Sets view and not within all tree views. This may allow the validation of profiles icon to be present upon validation and remove some duplicate code I put in when first implemented this.

**Comment by JillieBeanSim** [comment]
After a discussion, it was mentioned to only remove the Issue Command option from the USS tree view.

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
