### ISSUE TITLE
Save commands in settings

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1558]
Possibly separate the saved commands in the settings. At this time TSO & MVS commands are saved together under one section.
```
"Zowe Commands: History": {
    "persistence": true,
    "history": [],
    "fileHistory": [],
    "sessions": [],
    "searchHistory": [
      "PROFILE",
      "D T"
    ]
  },
```

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
