### ISSUE TITLE
Error running command zowe.ds.pasteMember: Running the contributed command: 'zowe.ds.pasteMember' failed.. This is likely caused by the extension that contributes zowe.ds.pasteMember.

### ISSUE THREAD

**Issue by Kumar2106** [zowe/vscode-extension-for-zowe#1567]
**Describe the bug**

I am trying to copy JCL2  from ZXP.PUBLIC.JCL and paste it in ZXXXXXX.JCL, it is successfully getting copied from ZXP.PUBLIC.JCL but when i am pasting it in ZXXXXXX.JCL  it is giving me the error.

**To Reproduce**

**Expected behavior**

**Screenshots**

![zowe ds pasteMember](https://user-images.githubusercontent.com/34748576/139365054-4cbf8cca-7af0-4595-8600-0c7fe5de8d2b.png)

**Desktop (please complete the following information):**

- OS: Window 11
- Zowe Explorer Version: v1.20.0
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store? No

**Comment by jellypuno** [comment]
@Kumar2106 Is it possible for you to create a video/gif of the issue so we can re-create it? Or maybe write a step-by-step process here?
