### ISSUE TITLE
Make Zowe a verified publisher on VS Code Marketplace

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/vscode-extension-for-zowe#1570]
Starting November 15, extension publishers can become verified on the Marketplace to get a checkmark badge next to their publisher name. It would be nice for ZE to have this 🙂 
![image](https://user-images.githubusercontent.com/22344007/140402260-3a6e6748-98de-4f9b-9a7f-66253b293a2f.png)

The process to become verified is documented here: https://code.visualstudio.com/api/working-with-extensions/publishing-extension#verify-a-publisher

**Comment by MarkAckert** [comment]
DNS records in zowe.org were updated and verified, waiting for Microsoft to review and give final approval (<5 business days per doc).

**Comment by MarkAckert** [comment]
As of 5/20, we have the verified icon 😃
