### ISSUE TITLE
(Doc) Deprecated Associate Profile feature note

### ISSUE THREAD

**Issue by IgorCATech** [zowe/vscode-extension-for-zowe#1572]
**Is your feature request related to a problem? Please describe.**

Around Feb 2022, ZE V2 should be released. This release will remove the Associate Profile feature from the extension.

**Describe the solution you'd like**

The documentation both in Readme and Zowe Docs needs to reflect this change by adding a note explaining that the feature is deprecated in the V1 versions of the extension to the appropriate sections. Customers can still use it but we do not recommend doing this. 

**Describe alternatives you've considered**

Once V2 is out, we will remove the entire section with the Associate Profile feature description.

**Additional context**

Just a reminder. Let's keep in mind that this issue will need to be revisited in February 2022.

**Comment by IgorCATech** [comment]
At this point, information about the Associate Profile feature is about to be removed from the ReadMe in the `next` branch. Here are the issue and PR that address this change https://github.com/zowe/vscode-extension-for-zowe/issues/1280 and https://github.com/zowe/vscode-extension-for-zowe/pull/1569

**Comment by IgorCATech** [comment]
@crawr Can you please specify from what version of ZE, the feature is deprecated?

**Comment by crawr** [comment]
> @crawr Can you please specify from what version of ZE, the feature is deprecated?

It was marked as deprecated for the extenders with the v1.18.0 release
