### ISSUE TITLE
Base profile not being used

### ISSUE THREAD

**Issue by gdcooman** [zowe/vscode-extension-for-zowe#1574]
**Describe the bug**

I have a base profile that contains my username, password (both stored using SCS) and sets reject unauthorized to false. I then also have a zOSMF profile that contains a hostname and port. When using the zOSMF profile with the Zowe CLI, the credentials from the base profile get used. Zowe Explorer however prompts me for a username and password, instead of falling back to the base profile.

I know this should work with the API ML tokens in a base profile, but I would rather not use that.

Is this intended behavior? Or am I missing something?

**To Reproduce**

1. Create a base profile that contains a username and password.
2. Create a zOSMF profile that contains a hostname and port.
3. Try to search for a dataset using the created zOSMF profile.
4. Get prompted for a username and password.

**Expected behavior**

Zowe Explorer should fallback to the base profile for unspecified values, and only prompt for them when they're also not found in the base profile.

**Desktop (please complete the following information):**

- OS: Windows 10
- Zowe Explorer Version: 1.20.0
- (Optional) Zowe CLI Version: 6.35.0
- (Optional) Are you using Secure Credential Store? Yes

**Comment by jellypuno** [comment]
We need to re-visit the flow of base profiles

**Comment by zFernand0** [comment]
Hey @gdcooman, does the issue persist in ZE V2 ?

**Comment by gdcooman** [comment]
I have tested it with a zosmf profile, and that seems to be using the base profile correctly.

This seems to be resolved at first glance 👍
