### ISSUE TITLE
OnSave Options

### ISSUE THREAD

**Issue by GhettoKiwi** [zowe/vscode-extension-for-zowe#1578]
Everytime Im doing a ctrl + s (OnSave) I am not able to archive any information about the save on the host. (My issue is specifically meant for Datasets only)

I would like a solution where I can hook myself onto/add a listener to the current save function and await the status - If the save is executed without errors, I would like to execute a function, a program or something else. (Preferably call a REXX)

A workaround for me, would be making my own "vscode.workspace.onDidSaveTextDocument"-function and give it a pause of 10 seconds, to hopefully "await" the save function from the Zowe Explorer - This has issues, since there are no way of cancelling the "archive"-event if the save went wrong.

**Comment by jellypuno** [comment]
I need more clarification on this. Do you mean like you want to save a program in mainframe and once it is successful then you call on to the REXX program? Can you do it via a script and use zowe cli commands? similar to this one: https://github.com/jellypuno/Cobol-Made-Easy/blob/COVID-19/scripts/upload.ts

**Comment by GhettoKiwi** [comment]
Yes - When the save of a program to the mainframe is DONE I want to be able to then run a REXX or something else afterwards to archive data for legal reasons. 

I could probably do something similar to what you suggested, but the main issue is, that I don't see a way of deactivating the original save-function in the zowe explorer - That solution could probably also be an easier "fix" than to add a hook into the original save function.

Original save function begins here: https://github.com/zowe/vscode-extension-for-zowe/blob/master/packages/zowe-explorer/src/extension.ts L: 166
Then it determines wether it is a dataset or an USS file to then execute the save command for said file. (Example for dataset save: vscode-extension-for-zowe/blob/master/packages/zowe-explorer/src/dataset/actions.ts L: 1318)

**Comment by jellypuno** [comment]
@GhettoKiwi In my opinion, this is a very specific scenario for you. My suggestion is to look at Zowe Scripts or [VSCode tasks](https://code.visualstudio.com/docs/editor/tasks). This VSC feature could help you assign some common tasks that you do everyday and trigger it via scripts or keybinding.  This [blog](https://medium.com/zowe/streamline-your-mainframe-development-with-zowe-explorer-zowe-cli-a-series-part-2-cobol-4f7cc4125acd) from @Alexandru-Dumitru  allowed me understand more about tasks and helped me set it up:
