### ISSUE TITLE
Copy/paste USS files (including multi-select) for different profiles

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1587]
As a ZE User, I would like to have the capability of copy and pasting files and directories inside another directory to different profiles.

Goal:

- Copy/Paste files and directories across multiple profiles

Possible UX:

1. The user will select multiple files or directories
2. Right-Click > Copy
3. Select a different profile > Right-Click on another directory > Paste
4. All selected items are copied to the new directory
   - This will only cover copy/paste. Move is a different issue
   - Can we use Ctrl + C and Ctrl + V?

**Comment by JillieBeanSim** [comment]
done with PR #1549
