### ISSUE TITLE
Move USS files

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1588]
As a ZE User, I would like to have the capability of copy and pasting files and directories inside another directory.

Goal:

Move files and directories within 1 profile or across different profiles

Possible UX:
1. The user will select multiple files or directories
2. Right-Click > Move
3. Select a different profile > Right-Click on another directory > Move Here
4. All selected items are moved to the new directory
    - This will cover move functionality
    - Can we use Ctrl + C and Ctrl + V?

**Comment by FALLAI-Denis** [comment]
Hi,

I don't understand the need to use multiple profiles ... are these profiles in the Zowe sense?
Or is the need just to move USS files from one folder to another? This can be done with a single profile.

To move files, you should instead use the keyboard shortcuts Ctrl + X (cut), Ctrl + V (paste).

A "drag and drop" operation with Ctrl or Shift key combination would also be welcome.
- Shift key + simple drag and drop: move
- Ctrl key + drag and drop: copy

**Comment by JillieBeanSim** [comment]
[across profile actions are deferred](https://github.com/zowe/vscode-extension-for-zowe/issues/1587) for now as we would need the work done on the CLI side for moving/copying files across LPARS
for the copy/paste in USS can we close this in favor of https://github.com/zowe/vscode-extension-for-zowe/issues/1549 @KutluOzel-b @zFernand0

**Comment by JillieBeanSim** [comment]
this could also be part of the support drag and drop enhancement https://github.com/zowe/vscode-extension-for-zowe/issues/2046

**Comment by JillieBeanSim** [comment]
copy/paste uss files has been completed, closing issue
