### ISSUE TITLE
Incorrect file extensions

### ISSUE THREAD

**Issue by PrasangAPrajapati** [zowe/vscode-extension-for-zowe#159]
### Issue

Here I want to cover some issues that are occurring because of having file extensions from dataset name. 

**What it is doing right now:** 
   When you open a member from dataset, now that member has a file extension which is inheriting from the dataset name. 
   
**_Example: 1_** 

Dataset: ZOWEPAP. SAMPLE.TEST & It has member SAM1. 
Now when you open a member SAM1, now it will be opened as SAM1(ZOWEPAP.SAMPLE.TEST).test

This doesn't satisfy conditions all the time. My member SAM2 is COBOL file actually but it is considered as a `.test` file extension. 

**_Example: 2_** 

Dataset: ZOWEPAP. SAMPLE.CLASS & It has member SAM1. 
Now because of adding a file extension automatically from dataset name, SAM1 is being considered as `.class` file (which is JAVA language) because when you open a member, a file name will be `SAM1(ZOWEPAP.SAMPLE.CLASS).class`. But In fact that member is a COBOL file.  

### Solution:

We should not add file extension to the member of dataset automatically. 

VSCODE has a preference settings called `files.associations` where you can add a full dataset name and the add the language id to set the language for all the members under that dataset name. For example: 

```
  "files.associations": {
   "*.COBOL*": "cobol",
   "*ZOWEPAP.SAMPLE.CLASS*" : "cobol"
}
```
A file name which has a string `ZOWEPAP.SAMPLE.CLASS` or `.COBOL` will be considered as a cobol fiile. A language id, user can find it from the bottom Status Bar from where you can change/select language for the active file. So we should let user add the preference in the settings file.

**Comment by phaumer** [comment]
We could use this as the default and have settings to switch it back off or even to provide patterns to match (that are covered by file.associations).

**Comment by Colin-Stone** [comment]
This feature is working as designed and would as Peter says be the default behavior. The intention was not to have users having to think about settings and associations. The local file structure was broken (defects against it) so needed reviewing and this function makes available some of the z/OS based syntax highlighters. Overriding as described may be an option for you.
