### ISSUE TITLE
FTP extension creating files that shouldn't be tracked running tests

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#1594]
**Describe the bug**

I didn't see this until I was on a different branch and ran the tests after https://github.com/zowe/vscode-extension-for-zowe/pull/1582 was merged.

![image](https://user-images.githubusercontent.com/49491949/143878774-91bbe3e5-dc3e-443d-aa1a-496db2a394fa.png)

**To Reproduce**

**Expected behavior**

these files should be ignored 

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Zowe Explorer Version:
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by tiantn** [comment]
Thanks @JillieBeanSim ! I will put the coverage file in .gitigore. Thank you! 😊

**Comment by JillieBeanSim** [comment]
@tiantn I have a PR for this fix https://github.com/zowe/vscode-extension-for-zowe/pull/1596, would you mind reviewing it?
