### ISSUE TITLE
Automate post-release versioning updates

### ISSUE THREAD

**Issue by lauren-li** [zowe/vscode-extension-for-zowe#1614]
Automate the snapshot versioning updates that currently need to be done manually after every release. This includes:
- Create a PR to update the master branch with snapshot versioning
- Create a PR to update the release branch with snapshot versioning

The current process for doing this is documented in the wiki for [Preparing for a release](https://github.com/zowe/vscode-extension-for-zowe/wiki/Preparing-for-a-release)

**Comment by zFernand0** [comment]
Snapshot version updates are done automatically as part of the release process.
