### ISSUE TITLE
Handle profile creation/update for ZE extender profiles requiring credentials when the user leaves them blank

### ISSUE THREAD

**Issue by lauren-li** [zowe/vscode-extension-for-zowe#1619]
**Describe the bug**

If a user has the Secure Credential Store (SCS) plug-in for Zowe CLI installed, and is attempting to create a no-credentials (i.e. no username or password) profile for a Zowe Explorer extender whose profile type specifies that username and password are required, they will see an error about secure fields upon profile creation. The next time they restart VS Code, Zowe Explorer activation fails with the same error.
* This issue also occurs when updating this type of extender profile to have no username or password.

I first saw this issue when testing the Zowe Explorer Extension for FTP, but when @jellypuno and I modified the extender's `zftp_meta.yaml` file to set `required: false` for the `user` and `password` properties, the issue went away and we were able to successfully create no-credentials zFTP profiles in Zowe Explorer with SCS installed.

**To Reproduce**

1. Ensure you have the latest versions of Zowe CLI and the Secure Credential Store for Zowe CLI (SCS) plug-in installed.
2. In VS Code, install Zowe Explorer (v1.21.0) and Zowe Explorer Extension for FTP (v1.21.0).
3. Create a zFTP profile with no credentials (i.e. no username or password).
4. See the following error pop up:
        <img width="450" alt="Screen Shot 2021-12-21 at 10 02 43 AM" src="https://user-images.githubusercontent.com/45975633/147102480-85186409-6c91-4104-a27f-f30b09a53819.png">
5. Upon the next restart of VS Code, Zowe Explorer activation will fail and show the same error.

**Expected behavior**

- Zowe Explorer:
  - If a Zowe Explorer extender's meta YAML file specifies that username and password are required, perform input validation to enforce that the user must enter values for these fields.
  - If the user somehow has a no-credentials profile for a Zowe Explorer extender whose meta YAML file requires username and password, then gracefully handle this upon activation (i.e. without an error that causes Zowe Explorer activation to fail).

- Zowe Explorer Extension for FTP/z/OS FTP Plug-in for Zowe CLI:
  - Reconsider if the username and password fields are truly required, or if they can be made optional.

**Desktop (please complete the following information):**

- OS: MacOS and Windows (Thanks @jellypuno for helping me test!)
- Zowe Explorer Version: 1.21.0
- (Optional) Zowe CLI Version: Tested with Zowe CLI 6.33.1 (MacOS) and 6.37.0 (Windows)
- (Optional) Are you using Secure Credential Store? Yes, version 4.1.5

**Comment by JillieBeanSim** [comment]
we could have a validation check of the input using the extenders schema to see if the field value is required and notify the user that this is a required field presenting the text box again similar to the check we have for the host value

**Comment by lauren-li** [comment]
> we could have a validation check of the input using the extenders schema to see if the field value is required and notify the user that this is a required field presenting the text box again similar to the check we have for the host value

@JillieBeanSim Sounds good to me!

**Comment by KutluOzel-b** [comment]
I followed the steps to repro but I couldn't and deleted v2 tried only with v1 and still no luck. 
It is likely that I done something wrong while try to repro it ( I'm a new contributor ) but I started to wonder if this is still an issue. 
Does anyone still able to reproduce it ? Any help is appreciated

**Comment by KutluOzel-b** [comment]
No longer an issue as a result of the removal required fields in config schema. 

Please refer to : [imperative.ts](https://github.com/zowe/zowe-cli-ftp-plugin/commit/c2af28e326d9c386afcc635dd53df65417065400#diff-11bcffde17775d5cce3f9ad665bde2bf3eb4607451e6291abbaa2f7b8a53203f)

see the changes. 

Hence closing this issue.
