### ISSUE TITLE
Zowe Explorer should respect the prompt keyword in profiles

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/vscode-extension-for-zowe#1622]
**Is your feature request related to a problem? Please describe.**
Zowe Explorer does not leverage the prompt phrase appropriately.

**Describe the solution you'd like**

In Zowe CLI, when the prompt phrase is stored in a profile, the user is prompted for input each time that value is used. The prompt phrase is `prompt*` by default but can be changed via the `ZOWE_PROMPT_PHRASE` env var. More details are available [here](https://docs.zowe.org/stable/user-guide/cli-usingcli/#using-the-prompt-feature). When Zowe Explorer encounters the prompt phrase, it should also prompt for user input. Today, Zowe Explorer tries to use the prompt phrase as the input value.

**Describe alternatives you've considered**

An alternative is to not use the prompt phrase at all. In most cases, this has been used to prompt for user/password. Today, if those values are not supplied, both the CLI and Zowe Explorer prompt for these values. However, I still see a use case for `prompt*` in a base-profile. This would work well in the scenario where you don't want to store your password on disk but it is the same for multiple LPARs. Then, Zowe Explorer would prompt once for the password and you could access data sets on multiple LPARs.
 
**Additional context**

This was reported by a customer.

**Comment by jellypuno** [comment]
@MikeBauerCA honestly this doesn't makes sense to me. The CLI should not allow the word "prompt*" to be stored in the profile. It should only be used when added as part of a command. It was created for that purpose anyway. What if I want to use prompt* as a password? I think we need to discuss this more.

**Comment by MikeBauerCA** [comment]
If you truly wanted to do that, then you could change the prompt phrase to be something different. However, I see your point on only using it as part of a command and that was the original reason it was created. If we decided that is the route that we want to go, then the CLI should be changed to not be influenced by such values in a profile. I agree we should discuss this more 👍

**Comment by jellypuno** [comment]
Additional thoughts that we can add in the future discussion: 

- how will other vscode extensions (not ze extenders) that only uses the zowe sdk handle this? Will it make sense to add it in the sdk?

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
