### ISSUE TITLE
Getting Cannot set property 'encoding' of undefined errors 

### ISSUE THREAD

**Issue by Rune-Christensen** [zowe/vscode-extension-for-zowe#1627]
When working with Zowe Explorer our users from time to time get a "Cannot set property 'encoding' of undefined" error, when trying to save a file to Z.
![image](https://user-images.githubusercontent.com/26797797/148514034-7a608699-344f-479e-aabc-2d8c4425a343.png)

The consequence of this is that the files they were working on, is not updated and they potentially lose whatever they have written since last save.
The only way to get rid of this error is to restart VS Code.

**To Reproduce**
This is a problem, we have no clear way of reproducing this. 
Sometimes it happens immediately after startup of VS Code, and sometimes it happens after hours of work.
There is no clear pattern to reproduce the issue.

**Expected behavior**
We expect files to be saved to the mainframe.

**Desktop (please complete the following information):**

- OS: Windows 10
- Zowe Explorer Version: 1.21.0 with Zowe Explorer for CICS v1.2.0
- (Optional) Zowe CLI Version: 6.32.0
- (Optional) Are you using Secure Credential Store? Yes

**Additional context**
zowe zosmf check status
Returns:
![image](https://user-images.githubusercontent.com/26797797/148514681-9c04d673-92c2-46bb-b7c8-d785391d5b4f.png)

Any help to debug this is appreciated.

**Comment by FALLAI-Denis** [comment]
Hi @Rune-Christensen 

For me this has been fixed in version 2.0.2 of ZE.

**Comment by zFernand0** [comment]
Thank you @FALLAI-Denis 😋 

Hey @Rune-Christensen, 
Do you plan to stay on ZE v1 ?
If so, please let us know if the problem still persists on 1.22.1 😋

**Comment by zFernand0** [comment]
I'm afraid I could not reproduce the issue with 1.21.
@Rune-Christensen, were you able to update to 2.0.2 ?
Or will you plan to continue on v1, (1.22.1) ?

**Comment by Rune-Christensen** [comment]
I am not able to reproduce so far with 2.0.2
I will reopen, if the issue reappears.
Thanks :-)
