### ISSUE TITLE
Document the latest supported version of Node

### ISSUE THREAD

**Issue by crawr** [zowe/vscode-extension-for-zowe#1639]
taking away the 10.x from `zowe-explorer-ci.yml` and `zowe-explorer-ftp-ci.yml` would resolve this but does this mean we can't support node 10 with our 1.x releases anymore? @zFernand0 
We already do not support it with our 2.x

_Originally posted by @JillieBeanSim in https://github.com/zowe/vscode-extension-for-zowe/issues/1635#issuecomment-1021216189_

I can understand the concern, but I believe Node 10's End-of-Life was around April 2021.
I can't find anywhere if Node 10 will still be supported in z/OS though :cry:

_Originally posted by @zFernand0 in https://github.com/zowe/vscode-extension-for-zowe/issues/1635#issuecomment-1021228758_

**Comment by JillieBeanSim** [comment]
@IgorCATech I added you as well since I am not sure if the Zowe.org docs will need to be updated as well as the READMEs in the repo.  READMEs are updated in the attached PR
