### ISSUE TITLE
FR: Make Safe Save as the Default 

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#164]
I recommend that we make Safe Save the default when saving files in the VS Code plugin. This would simplify the interaction so that we wouldn't need a second option in the context menu. Safe Save ensures there are merges whereas the default save (ctrl+s) will overwrite a changed file. IMHO, it is better to merge than not. 

![image](https://user-images.githubusercontent.com/3207260/61722318-11357280-ad38-11e9-9be4-8fb692a6e424.png)

In the short term, sticking with what we have, I recommend changing the text in the context menu by replacing the dash with a comma. With the comma, users are likely to read the two words as one, for example safe SaveMerge if necessary. A comma is read as a pause to separate phrases. 
* Safe Save - Merge if necessary 
* Safe Save, Merge if necessary 

Here is an humorous example where a dash can be mis-read. 
![image](https://user-images.githubusercontent.com/3207260/61722353-21e5e880-ad38-11e9-9294-2e9ec5ec4698.png)

**Comment by dkelosky** [comment]
@Colin-Stone - does "safe save" use [Etag](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.1.0/com.ibm.zos.v2r1.izua700/IZUHPINFO_API_RESTFILES.htm)?

**Comment by Colin-Stone** [comment]
No it's a little peculiar. Just looking at the code it pulls the file back down again and VSCode appears to take over and realizes that the files are different. It the lets you decide if you want to open the compare editor which is neat.

**Comment by zFernand0** [comment]
done

**Comment by jelaplan** [comment]
FWIW, this is what the user sees when trying to save and the system detects a merge conflict wherein a change was made to the MF in the meantime. This gives them a avenue to resolve the conflicts. I'm a little uncertain about the message "The content of the file is newer" because it sounds like the local file is newer but I'm guessing it is the remote file. 

![image](https://user-images.githubusercontent.com/3207260/71123919-c23e1d00-21b1-11ea-9cc4-470c16bde899.png)

**Comment by MikeBauerCA** [comment]
It looks like the warning and error message should be combined... perhaps change the text of the error message to:
`Failed to save 'DUMAL01.TEST1' because the remote file has been modified. Please compare your changes with the current remote version.`

**Comment by Alexandru-Dumitru** [comment]
I only added the `warning` message. The `error` message is generated automatically by VS Code. Need to look into that if we want to change the wording 😄

**Comment by jelaplan** [comment]
I like Mike's suggestion for the warning.
