### ISSUE TITLE
(Doc) V2 documentation impact

### ISSUE THREAD

**Issue by IgorCATech** [zowe/vscode-extension-for-zowe#1644]
This issue aims to collect information about upcoming changes in Zowe Explorer in connection to V2. Given that there will be changes to the major Zowe components, including ZE, we'll need to make sure that we keep the doc up to date. 

I'll start listing the sections that need to be updated/deleted but I might not capture everything, That said, I'd like to ask you to help me identify what features will/will not make into V2, which of the current features will be deprecated etc.. I'll edit the description as I gather more information.

Thank you!

**Comment by IgorCATech** [comment]
@MikeBauerCA @crawr @lauren-li @JillieBeanSim Tagging you guys for awareness. Also, feel free to throw in items here. I'll then consolidate everything and start working on the docs.

**Comment by lauren-li** [comment]
@IgorCATech Our current documentation to track Zowe Explorer V2 impacts are collected in the following documents:
- [Changes affecting extenders](https://github.com/zowe/vscode-extension-for-zowe/blob/next/docs/Early%20Access%20-%20Changes%20Affecting%20Extenders.md)
- [Using Global Profile Configuration](https://github.com/zowe/vscode-extension-for-zowe/blob/next/docs/Early%20Access%20-%20Using%20Global%20Profile%20Configuration.md)

Additionally, we need to remove the deprecated Associate Profile functionality from Zowe Explorer (both the documentation and the code itself).

**Comment by JillieBeanSim** [comment]
> Additionally, we need to remove the deprecated Associate Profile functionality from Zowe Explorer (both the documentation and the code itself).

I believe this is already removed from the code in the next branch, @crawr correct me if I am wrong.

**Comment by lauren-li** [comment]
> > Additionally, we need to remove the deprecated Associate Profile functionality from Zowe Explorer (both the documentation and the code itself).
> 
> I believe this is already removed from the code in the next branch, @crawr correct me if I am wrong.

@JillieBeanSim I think you are right; @crawr removed it in https://github.com/zowe/vscode-extension-for-zowe/pull/1569, along with our repo's docs on it. Thanks for catching that!

@IgorCATech We willl need to remember to also update Zowe's doc site with the change upon V2 release (if it's not already removed in their V2 branch as well).

**Comment by zFernand0** [comment]
With the completion of #1696 and Zowe V2 being released, I believe we can close this issue.
New doc issues can be opened as we find things to improve 😋
