### ISSUE TITLE
Allow users to update expired credentials 

### ISSUE THREAD

**Issue by crawr** [zowe/vscode-extension-for-zowe#1647]
**Is your feature request related to a problem? Please describe.**

Related to #1228

When a user's credential has expired, they should be able to update the stored credentials via Zowe Explorer.

**Describe the solution you'd like**

I would like an API in Zowe Explorer that can be called by extenders, that will handle expired credentials.

**Additional context**

The API to determine that credentials have expired is not present in SDKs yet

**Comment by JillieBeanSim** [comment]
closing since covered in #1228 for local updates and #1538 mainframe update
