### ISSUE TITLE
Align all the QuickPick selector cancellation messages

### ISSUE THREAD

**Issue by roman-kupriyanov** [zowe/vscode-extension-for-zowe#1651]
## Describe the bug

Together with fixing up the TSO command cancellation issue, there are a bunch of other inputs which cancellation messages might be improved.
Currently, all of the operations that use a `QuickPick`, being cancelled prompting the `No selection made.` message. A proposal is to improve messages to `No selection made. Operation cancelled.` to be in consistency throughout the codebase.

For example, some of the modules that are using an updated `resolveQuickPickHelper` function:
- _MvsCommandHandler.ts_: shows a message:
  https://github.com/zowe/vscode-extension-for-zowe/blob/f215d6dc1d79f57abda110007a4f9e9e5cc1a0df/packages/zowe-explorer/src/command/MvsCommandHandler.ts#L207
- _DatasetTree.ts_: same message for filter selection:
  https://github.com/zowe/vscode-extension-for-zowe/blob/f215d6dc1d79f57abda110007a4f9e9e5cc1a0df/packages/zowe-explorer/src/dataset/DatasetTree.ts#L914
- And others. There is an list:
  
  ![image](https://user-images.githubusercontent.com/91762867/151823173-dbc61182-a306-46fd-b43c-a1cafe82dfb4.png)

## To Reproduce

1. Start using one of functionalities specified above (e.g. _MVS command issue_).
2. When the vscode selector of some values (e.g. filters, commands, profiles, etc.) appear, hit `Esc` key to cancel the input.
3. The `No selection made.` info message is shown up.

## Expected behavior

The `No selection made. Operation cancelled.` user messages to appear instead.

## Desktop

- OS: any
- Zowe Explorer Version: the release, which will include changes from PR https://github.com/zowe/vscode-extension-for-zowe/pull/1645

## Additional context

See https://github.com/zowe/vscode-extension-for-zowe/pull/1645#issuecomment-1025920716

**Comment by chinmaym07** [comment]
Can I work on this ?

**Comment by JillieBeanSim** [comment]
Hey @chinmaym07, you sure can.  We welcome any help.  Thank you.
Here is some helpful [information for contributors](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance)
