### ISSUE TITLE
[next] Custom secure properties not loaded

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#1663]
**Describe the bug**

The ZE extension won't load a profile (i.e. fails to validate) when provided with a team config that has a profile required property (host, port) in the `secure` array.

**To Reproduce**

1. Copy the `zowe.config.json` (see below) into a new workspace
2. Open the Zowe Explorer on the above workspace
3. Profile gets automatically added, but it's practically unusable 😢 
```json
{
    "$schema": "./zowe.schema.json",
    "profiles": {
        "ibmzosmf": {
            "type": "zosmf",
            "properties": {
                "basePath": "/ibmzosmf/api/v1"
            }
        },
        "base": {
            "type": "base",
            "properties": {
                "port": 1234,
                "rejectUnauthorized": true,
                "tokenType": "apimlAuthenticationToken"
            },
            "secure": [
                "host",
                "tokenValue"
            ]
        }
    },
    "defaults": {
        "zosmf": "ibmzosmf",
        "base": "base"
    },
    "autoStore": true
}
```

**Expected behavior**

All properties are loaded regardless of whether or not they are stored securely

**Screenshots**

![image](https://user-images.githubusercontent.com/37381190/153213398-5cd92553-f449-478a-980a-89874069e1b9.png)

**Desktop (please complete the following information):**

- OS: Windows
- Zowe Explorer Version: #1637 
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

Using a VSIX from #1637

**Comment by JillieBeanSim** [comment]
@zFernand0 without the host in the config you will receive the error shown for missing host. isn't that expected behavior?

**Comment by zFernand0** [comment]
I guess I would expect Zowe Explorer to work the same way as the CLI here, and be able to look for the host in the vault.
And if it's not set (in the vault or in the config file) then it can ask for it, and store it back (depending on the config file)

**Comment by JillieBeanSim** [comment]
That could be a great enhancement to add after v2 goes out! :grin:

**Comment by zFernand0** [comment]
The prompting for missing properties I agree that it could be an enhancement after v2 (as a 2.1).
However, I do believe that storing port or host securely and not reading it from ZE could be a patch release (e.g. 2.0.1)

**Comment by JillieBeanSim** [comment]
@zFernand0 when you test my [PR](https://github.com/zowe/vscode-extension-for-zowe/pull/1729) could you check again and see if it's grabbing the secure values? It should if stored securely.

**Comment by zFernand0** [comment]
Will do! 😋

**Comment by zFernand0** [comment]
I'm still seeing the _`host` must not be blank_ issue in the [PR](https://github.com/zowe/vscode-extension-for-zowe/pull/1729)
I'm fine if we want to do this as a patch release after v2 goes out 😋

**Comment by JillieBeanSim** [comment]
@zFernand0 we are using this snippet of code to get all knownArgs from imperative and checking for secure items to get the info
```
const mergedArgs = mProfileInfo.mergeArgsForProfile(profAttrs);
            for (const arg of mergedArgs.knownArgs) {
                // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
                profile[arg.argName] = arg.secure ? await mProfileInfo.loadSecureArg(arg) : arg.argValue;
            }
```
should we look into imperative to see why we aren't getting all of the secure items?

**Comment by zFernand0** [comment]
FYI, there is a `getSecureVals` options that we can pass to the `mergeArgsForProfile` method to avoid the extra loop on our end 😋 

In my testing, I was confused thinking it wasn't extracting values from the secure vault, but it was due to the CLI storing them  under `Zowe/secure_config_props` and ZE storing things under `Zowe-Plugin/secure_config_props`.

I'll retest the `host` bit again. 😋 
Thanks!

**Comment by zFernand0** [comment]
This seems to be a problem.

Even though ZE is reading form the same `Zowe/secure_config_props` vault property, it can't find custom properties.

However, when using the ProfileInfo APIs outside of ZE (e.g. sample project, or small VSCE) it's able to load any custom properties.

That makes me believe that somewhere in ZE we are only considering the user and password as secure fields.

Same thing is happening with the APIML Token (#1713)

**Comment by JillieBeanSim** [comment]
@zFernand0 I removed pending closure tag, is that enough of an activity along with comment to keep it from auto-closing?

**Comment by zFernand0** [comment]
I believe so, 👍

**Comment by zFernand0** [comment]
I'm considering disabling the auto-close-issue bot 😋

**Comment by zFernand0** [comment]
I'm still seeing this error 😢 
![image](https://user-images.githubusercontent.com/37381190/188647421-5ae485ae-ce62-4296-84d7-bbdb341fb577.png)

**Comment by KutluOzel-b** [comment]
As a result of the tests I have made , I came up with a conclusion that the Issue is no longer exists.

Any securely stored profile attribute on schema can be loaded under the the scenarios I have tested are : base profile, nested profile, profile that overrides base profile and regular profile. 

If you can reproduce this issue please provide the steps to repro so I can test again.

Awaiting for inputs to make a final decision about this issue ...

**Comment by zFernand0** [comment]
Thank you for retesting! 
you are correct, ZE behaves as expected when there are custom properties stored securely now
