### ISSUE TITLE
zowe profiles create zosmf-profile allow specification of --console-name 

### ISSUE THREAD

**Issue by MikeKoester** [zowe/vscode-extension-for-zowe#1667]
When creating a zosmf profile it would be nice if it also supported allowing the user to specify the z/OS extended MCS console to direct the commands to. Right now it defaults to 6 characters of the user name with CN appended. If you have the same user name for all of your zosmf profiles (which is common as most systems you use the same userid) you will get IKJ error messages if the console name you are trying to go to is already active.  The zowe zos-console issue command already allows you to be able to specify console name so the logic is already there in zowe.  Thank You.

**Comment by MikeBauerCA** [comment]
@zFernand0 do you know if the V2 tech preview of ZE supports custom profiles as I mentioned above? If not, we should make the change to support this and also consider adding the `consoleName` to the profile definition to get intellisense when editing `zowe.config.json`.

**Comment by MikeKoester** [comment]
Hi Mike,

the change I am asking for hopefully would be easy to implement for the existing zosmf profile creation. When I create it with the CLI or through the VSC Zowe explorer extension that would be the optimum place to have it as that is straight  forward. Thank you for looking at this.

**Comment by zFernand0** [comment]
> @zFernand0 do you know if the V2 tech preview of ZE supports custom profiles as I mentioned above? If not, we should make the change to support this and also consider adding the `consoleName` to the profile definition to get intellisense when editing `zowe.config.json`.

Hey Mike,
The ZE doesn't support customer profiles like mentioned in Dan's blog.
It doesn't deviate from the default properties defined by the schema file.

**Comment by zFernand0** [comment]
After some discussion in the Zowe Explorer standup (Nov 8th, 2022) we decided to go with the following approach:
- Update the Imperative `ProfileInfo` APIs to return all values in the profile
- Forward all applicable values to the corresponding SDK methods

**Comment by recaph** [comment]
is there any ETA for this issue?

**Comment by t1m0thyj** [comment]
> is there any ETA for this issue?

@recaph This enhancement will be published in the next feature release of Zowe Explorer (2.16.0).
