### ISSUE TITLE
Persistent Dataset Filter Pools

### ISSUE THREAD

**Issue by peterpk** [zowe/vscode-extension-for-zowe#1672]
**Is your feature request related to a problem? Please describe.**

Coming from IBM Developer for z/OS, one thing I miss is filter pools, named groups of saved dataset filters which would always appear in the explorer tree for a given connection profile, and be easily available to click through.

**Describe the solution you'd like**

1. Expand the existing dataset search functionality so that filter results (dataset names) are grouped under a single parent (the filter string they match, by default). 
2. Add a context menu option to that parent entry that allows it to be saved, optionally under a new name, optionally under a filter pool for further organization. 
3. Add context menu options to such saved filters allowing them to be renamed and/or moved between pools.
4. Add a context menu option to the profile entry to create a new filter pool.

**Describe alternatives you've considered**

Clicking the search button does show a list of recent filters. I considered whether we could add a "Manage filters" option to that menu, which shows them in a window where things could be done to them... but I think I like the filter pools better.

**Additional context**

**Comment by zFernand0** [comment]
A quicker way to open the `settings.json` file maybe is `Ctrl + ,` and click the ![image](https://user-images.githubusercontent.com/37381190/157274782-f9c5c649-ba60-4306-a470-310f183074f7.png) icon in the top-right corner 😋

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
