### ISSUE TITLE
Group Favorites section based on profile

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#168]
It'd be nice if the favorites section was grouped/collapsible by profile instead of having the format of `[profile-name]: HLQ.DATASET.LLQ` or `[profile-name]: uss/path/to/dir-or-file`

Feedback by: @AHumanFromCA

**Comment by Colin-Stone** [comment]
@zFernand0 would you be able to show me the type of structure you are thinking of?.
