### ISSUE TITLE
Zowe Explorer does'nt work with Toxsocks after upgrade VS Code

### ISSUE THREAD

**Issue by Josema-Kyndryl** [zowe/vscode-extension-for-zowe#1688]
**Describe the bug**

Hi everyone

I was using (under RHEL 8.5) the version 1.61.2 of VS Code with Zowe Explorer v1.22.0 and the extension worked perfectly

However after performing an upgrade from VS Code to 1.64.2 it has stopped working; when I tried to recover files, jobs, ... it stays eternally with the message "Get Dataset list command submitted." and finally shows the message ...

Retrieving response from zowe.List Error: Zowe REST Operations API Error:
http(s) request error event called
Error: connect ETIMEDOUT 192.168.48.41:6800

In view of that message .... I use toxsocks-3.5.7-3.el8.x86_64 to tunnel network traffic through a particular proxy server. Is it possible that something has changed and now toxsocks will not be able to intercept the traffic?

Any idea?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: RHEL 8.5
- Zowe Explorer Version: v1.22.0
- (Optional) Zowe CLI Version: v6.31.0
- (Optional) Are you using Secure Credential Store? Yes

**Additional context**

**Comment by JillieBeanSim** [comment]
Hey @Josema-Kyndryl, this will need more investigation since the normal setup without proxy worked fine in this environment during our discussion in the OMP Zowe CLI slack channel.

A work around to get you going agian until this can be investigated can be found [here](https://stackoverflow.com/questions/49346733/how-to-downgrade-vscode) to roll back the VSC version and stop the auto update.

@zFernand0 FYI

**Comment by Josema-Kyndryl** [comment]
Hi Billie

I replaced toxsocks-3.5.7-3 by redsocks-0.5-1 (the configuration migration is not direct, but isn't very dificult) and after upgrading to code-1.66.0-1648620680 the Zowe Explorer extension works fine

For me we can close the matter

**Comment by Josema-Kyndryl** [comment]
Hi Billie

I replaced toxsocks-3.5.7-3 by redsocks-0.5-1 (the configuration migration is not direct, but isn't very dificult) and after upgrading to code-1.66.0-1648620680 the Zowe Explorer extension works fine

For me we can close the matter

**Comment by JillieBeanSim** [comment]
Hey @Josema-Kyndryl that is awesome news, thanks for the update!
