### ISSUE TITLE
Log4js disrupts Zowe Explorer's initialization process in Eclipse Che

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#1692]
**Describe the bug**

The recent switch of the log4js version from v3 to v6 break activation of Zowe Explorer in Eclipse Che.
`ERROR:Activating extension 'Zowe Explorer' failed:TypeError: Cannot read property 'name' of undefined`

- For more information, see https://github.com/zowe/vscode-extension-for-zowe/pull/1661

**To Reproduce**

✋ Help wanted here!

**Expected behavior**

- Zowe Explorer successfully activates

**Desktop (please complete the following information):**

- OS: N/A
- Zowe Explorer Version: 1.22.0
- (Optional) Zowe CLI Version: N/A
- (Optional) Are you using Secure Credential Store? N/A

---

**Possible debugging approach**
- Create a minimal extension that only does logging and try to rebuild Zowe Explorer to see where it fails to activate
- Remove all logging and try to add it back incrementally

**Note**
- Consider the possibility of contributing a PR to `log4js-node`
- More info: https://github.com/log4js-node/log4js-node/issues/968

**Comment by MarkAckert** [comment]
There is a tested and confirmed workaround by setting Zowe Explorer Log4js resolution to 6.3.0.

Some details about the error condition:

In the UI, the user is presented with:

```
Activating extension 'Zowe Explorer' failed: Cannot read property 'name' of undefined
```

The call chain leading to the error appears to be:

`coreAppenders.set('file', __webpack_require__(/*! ./file */ "../../node_modules/log4js/lib/appenders/file.js"));`
 (Repeat for 'fileSync' and 'dateFile')

Load file.js -->
`const streams = __webpack_require__(/*! streamroller */ "../../node_modules/streamroller/lib/index.js");`

...eventually leading to

`exports.realpath.native = u(fs.realpath.native)`, where fs.realpath.native is undefined. The "u(fs.realpath.native)" call is defined here:

```
exports.fromCallback = function (fn) {
  return Object.defineProperty(function (...args) {
    if (typeof args[args.length - 1] === 'function') fn.apply(this, args)
    else {
      return new Promise((resolve, reject) => {
        fn.call(
          this,
          ...args,
          (err, res) => (err != null) ? reject(err) : resolve(res)
        )
      })
    }
  }, 'name', { value: fn.name })
}
```
