### ISSUE TITLE
Update Docs for V2 release

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#1696]
Update to docs, internal (GH repo) and external (zowe.org), for V2 updates including use of team config files

**Comment by JamesBauman** [comment]
These are the articles that require a review for V2:


**Getting Started**
[Information Roadmap for Zowe Explorer | Zowe Docs](http://localhost:3000/stable/getting-started/user-roadmap-zowe-explorer)

**Setup**
[Installing Zowe Explorer | Zowe Docs](https://docs.zowe.org/stable/user-guide/ze-install)
[Zowe Explorer Profiles | Zowe Docs](https://docs.zowe.org/stable/user-guide/ze-profiles)

**Using**
[Using Zowe Explorer | Zowe Docs](https://docs.zowe.org/stable/user-guide/ze-usage)
[Using Zowe Explorer CICS Extension | Zowe Docs](https://docs.zowe.org/stable/user-guide/ze-cics)

**Extend**
[Extending Zowe Explorer | Zowe Docs](https://docs.zowe.org/stable/extend/extend-ze/ze-extensions)
This article links to: [vscode-extension-for-zowe/README-Extending.md at master · zowe/vscode-extension-for-zowe (github.com)](https://github.com/zowe/vscode-extension-for-zowe/blob/master/docs/README-Extending.md) 

**Troubleshoot**
​[Troubleshooting Zowe Explorer | Zowe Docs](https://docs.zowe.org/stable/troubleshoot/ze/troubleshoot-ze) ​
​ [Known Zowe Explorer issues | Zowe Docs](https://docs.zowe.org/stable/troubleshoot/ze/known-ze) ​ (The 2nd issue is missing the solution)
​[Raising a Zowe Explorer issue on GitHub | Zowe Docs](https://docs.zowe.org/stable/troubleshoot/ze/ze-issues) ​


**​FAQ page**
[Frequently Asked Questions | Zowe Docs](https://docs.zowe.org/stable/getting-started/freqaskques/#zowe-explorer-faq) (7 faqs)

**Comment by JamesBauman** [comment]
@zFernand0 re the API adoption topic.  There is no topic named 'Zowe ... Practices ... in doc site.

Did have something in mind?

**Comment by JamesBauman** [comment]
@zFernand0 - please review:  

- Am i going in the right direction?  I am not 100% sure which step is a "prereq" or a "step."  
- Also, what happens after the current step two? Save the file to initialize keytar?
- Open question from previous commit: **"There is no topic named 'Zowe ... Practices in the doc site. Did you have something in mind?"**

For your viewing pleasure: https://github.com/zowe/vscode-extension-for-zowe/blob/jabauman-vsc-misc-edits/docs/extenders/SecureCredentials.md

thx

**Comment by zFernand0** [comment]
> re the API adoption topic. There is no topic named 'Zowe ... Practices in the doc site.
> 
> Did you have something in mind?

Maybe something like what the CLI has (Topic: [Managing Credential Security](https://deploy-preview-1961--zowe-docs-master.netlify.app/stable/user-guide/cli-using-global-managing-credential-security)) but for Zowe Explorer

**Comment by JamesBauman** [comment]
The latest doc is here:

https://deploy-preview-1961--zowe-docs-master.netlify.app/stable/user-guide/cli-using-using-team-profiles
