### ISSUE TITLE
Saving file gets FTP error and deletes file on mainframe side

### ISSUE THREAD

**Issue by MikeKoester** [zowe/vscode-extension-for-zowe#1707]
I pull a data set member from mainframe and edit it on VSC. Now when I try to save it I get the following:

File transfer failed. File contains records that are longer than the LRECL of the new file. Transfer aborted due to file error.

And when I go to the data set on the mainframe that member has now been deleted and is no longer in the data set.

I am connected through your zftp extension

**Comment by tiantn** [comment]
Hi @MikeKoester , I tried to recreate the problem but failed. My procedure is as following:
- I create a test member in a PDS dataset which is fixed 80 length.
- write one line in the member from TN3270.
- opened the member in VSCode and add one line with 240 length.
- saved it. The message show upload successfully.
- check the member in TN3270. The content is truncated.
Could you provide your steps if it's convenient? Thank you very much!

**Comment by MikeKoester** [comment]
this is the data set layout

 Record format . . . . FB       
 Record length . . . . 80       
 Block size  . . . . . 9040     
 Data set name type    PDS   

I have a member in the data set that is 2,680 lines I even removed the sequence numbers. I am attached to the system in VSC through ZFTP. I bring the member into VSC, edit it and then save it.  That is when I get the following

File transfer failed. File contains records that are longer than the LRECL of the new file. Transfer aborted due to file error.

and now when I go back to the mainframe the member is no longer in the data set.

**Comment by tiantn** [comment]
Hi @MikeKoester , thank you for your details description. I recreate it today.

Like the document said (https://www.ibm.com/docs/en/zos/2.3.0?topic=4rc-451-file-transfer-failed-file-contains-records-that-are-longer-than-lrecl-new-file), when I change my ftp options to NOTRUNcate and NOWRAPrecord, and the contents longer than LRECL, the transfer failed with this information. And the member become empty.

So you can check your reccords'length to confirm the length is not longer the setting. And if you accept the truncated, set the ftp option to TRUNCATE.

We consider add some warning messages in zowe ftp extension to give user a note before their execution. Thank you very much!

**Comment by zFernand0** [comment]
I believe this was fixed in #1746
