### ISSUE TITLE
22PI2 PI Planning

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#1717]
<details>
 <summary>Additional Issues Post V2</summary>

- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1732
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1701
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1780
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1789
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1774
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1776
- [x] FTP: https://github.com/zowe/vscode-extension-for-zowe/issues/1813
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1801
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1803
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1811
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1819
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1824
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1823
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1822
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1821
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1665
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1840
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1827
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1804
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1826
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1751
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1799
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1842
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1841
- [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1837
</details>

### BugFixes

- Zowe Explorer:
  - [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1750
  - [x] https://github.com/zowe/vscode-extension-for-zowe/issues/754
  - [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1510
  - [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1692
  - [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1619
  - [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1781
  - [x] [STRETCH] https://github.com/zowe/vscode-extension-for-zowe/issues/1484

- FTP:
  - [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1707
  - [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1196

### Enhancements

- Zowe Explorer:
  - [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/1326
  - [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/1568
  - [ ] [STRETCH] https://github.com/zowe/vscode-extension-for-zowe/issues/1537
  - [ ] [STRETCH] https://github.com/zowe/vscode-extension-for-zowe/issues/1053
  - [ ] [STRETCH] https://github.com/zowe/vscode-extension-for-zowe/issues/1297
  - [ ] [STRETCH] https://github.com/zowe/vscode-extension-for-zowe/issues/1782
  - [ ] [DEFERRED] https://github.com/zowe/vscode-extension-for-zowe/issues/1286
  - [ ] [DEFERRED] https://github.com/zowe/vscode-extension-for-zowe/issues/1642
  - [ ] [DEFERRED] https://github.com/zowe/vscode-extension-for-zowe/issues/1536
  - [ ] [DEFERRED] https://github.com/zowe/vscode-extension-for-zowe/issues/1538
  - [ ] [DEFERRED] https://github.com/zowe/vscode-extension-for-zowe/issues/246

- CICS:
  - [x] https://github.com/zowe/vscode-extension-for-cics/issues/191
    - _Web Service_
    - _TCP/IP Service_
    - _URI Maps_
    - _Library_
    - __Note_: May need to enhance CICS CLI capabilities for these additional resources_
  - [ ] [STRETCH] https://github.com/zowe/vscode-extension-for-cics/issues/189
    - _Update the course to add the VSCode CICS plugin_
    - _Install CICS in the zCOBOL system_
  - [ ] [STRETCH] https://github.com/zowe/vscode-extension-for-cics/issues/190
    - _Include 'help' tab that gives more information about attributes._
  - [ ] [DEFERRED] https://github.com/zowe/vscode-extension-for-cics/issues/92)

### Technical Debt

- Zowe Explorer:
  - [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1570
    - **Dependency:** Help needed to get DNS
  - [x] https://github.com/zowe/vscode-extension-for-zowe/issues/1482
  - [ ] [STRETCH] https://github.com/zowe/vscode-extension-for-zowe/issues/1705

- CICS: 
  - [x] https://github.com/zowe/vscode-extension-for-cics/issues/64
  - [ ] [DEFERRED] https://github.com/zowe/vscode-extension-for-cics/issues/4
  - [ ] [DEFERRED] https://github.com/zowe/vscode-extension-for-zowe/issues/1540

**Comment by FALLAI-Denis** [comment]
Hi,

For CICS, add support for LIBRARY resources.

Thanks.

**Comment by JillieBeanSim** [comment]
@JeffinSiby :point_up:

**Comment by JillieBeanSim** [comment]
Re-opening for easy find during the PI.  Can close at the start of next PI

**Comment by JillieBeanSim** [comment]
@zFernand0 do we want to close this now?

**Comment by zFernand0** [comment]
yeah, we can close it for now 😉
