### ISSUE TITLE
Emulate vscodes "workbench.action.quickOpenNavigateNextInFilePicker" (ctrl+p on windows) file picker in data set list

### ISSUE THREAD

**Issue by tucker01** [zowe/vscode-extension-for-zowe#172]
I hope this isn't a duplicate issue. I think this idea has been discussed before. 

In vscode, using `ctrl+p` (the command is `workbench.action.quickOpenNavigateNextInFilePicker`) I'm presented with a dialog box that allows me to type the name (or part) of a file to quickly open/navigate:

![image](https://user-images.githubusercontent.com/37446232/61891770-6d36fd00-aed8-11e9-9f04-301fb20533f3.png)

This is normally how I navigate a project I'm familiar with. 

It would take some design/thinking, but it would be great if I could apply this concept to data-sets. For example, I could type something like:
```
jcl ie
```

And the file picker would show the following for selection:
```
DATA.SET.JCL(IEFBR14)
DATA.SET.JCL(IEBCOPY)
PROJECT.JCL(IEBGENER)
```

Then selecting one would open the member.

**Comment by ChrisBoehmCA** [comment]
:fire:

**Comment by katelynienaber** [comment]
Looks like shortcuts can be added like [this](https://code.visualstudio.com/api/references/contribution-points#contributes.keybindings). I'll give it a try next week ^^

**Comment by katelynienaber** [comment]
@tucker01 We talked about this today.

It seems this functionality is available in z/OS using `searchfor`, but there's no API for it.

Would it be possible for someone at IBM to build this API at some point? From your perspective is there a more effective way of running this search?

**Comment by jellypuno** [comment]
@tucker01 Do you think this VSC feature will suffice to fix this issue? Or file picker is still better?

![VSC Search](https://user-images.githubusercontent.com/45042840/73541487-dde44680-4432-11ea-9ea0-61eda7bf516c.gif)

![VSC Search 2](https://user-images.githubusercontent.com/45042840/73541494-e3da2780-4432-11ea-926d-e6d7f5c067c5.gif)

**Comment by tucker01** [comment]
This seems like a good alternative to the file picker. However, if it was possible, I'd definitely prefer the file picker method.

Would this method work for data sets in my list that I haven't expanded the member set for?

**Comment by jellypuno** [comment]
> Would this method work for data sets in my list that I haven't expanded the member set for?

@tucker01 If you haven't expanded the dataset, it will only search on the list of datasets that you have. I think it is searching in the list that is available in the node. Which will be the same if we use the file picker right? We need to obtain the list in the node first before we do the search?
