### ISSUE TITLE
Refresh Zowe Explorer cmd pallete options and quick-keys broken

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#1720]
**Describe the bug**

The command pallete option `Refresh Zowe Explorer` and the `alt`+`z` quick-keys not working

![image](https://user-images.githubusercontent.com/49491949/161110495-b4354735-7c11-4bbf-9f60-c3e4fff2fd50.png)

**Comment by zFernand0** [comment]
I believe I ran into this and was able to work around it in #1699 by doing:
https://github.com/zowe/vscode-extension-for-zowe/pull/1699/files#diff-c9774d7e90269519b0cbaaa822a6dcdbc61e13cdc9eda42ee26c8ec18d4a3057R100-R107

**Comment by zFernand0** [comment]
As a possible enhancement, it will be nice to investigate how we can add an indicator to the vscode taskbar similar to the Restart TS Server
![image](https://user-images.githubusercontent.com/37381190/161259410-19f09987-0a11-4659-9fa8-dd6fec3dc02e.png)

**Comment by zFernand0** [comment]
I know this scenario won't happen very often, but I've been experiencing a few issues when switching from v2 to v1 profiles.
For eaxmple, the extRefresh command fails with an imperative error becuase we are trying to perform a V1 profile operation when a V2 config is "in use" (i.e. we are not reloading ProfilesCache from disk even though `ImperativeConfig.instance.config?.exists` will).
