### ISSUE TITLE
Issues after prompt credentials with v1 profiles

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#1738]
Having a v1 profile without creds and doing an action will prompt the user for the credentials as expected.  But, after the prompting errors are popping up and the credentials are automatically stored in the keystore.  Not sure if autostore for v1 is expected results and we definitely shouldn't get the errors.  Have to click the view refresh to update the profile so it is usable. 
Errors:
![image](https://user-images.githubusercontent.com/49491949/162432576-6aad44f3-794f-43fb-8a2b-c6048d343e84.png)

**Comment by zFernand0** [comment]
It might be good to check if this issue was partially resolved by #1743 
Also, is it normal to still see the error (missing creds) if the operation was cancelled?

**Comment by zFernand0** [comment]
This may be related to #1799  😋

**Comment by JillieBeanSim** [comment]
this issue was addressed with https://github.com/zowe/vscode-extension-for-zowe/pull/1823
