### ISSUE TITLE
Zowe Explorer FAQ Future Updates

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#1741]
Consider adding the following questions to the [Zowe Explorer FAQ](https://deploy-preview-1961--zowe-docs-master.netlify.app/stable/getting-started/zowe_faq#zowe-explorer-faq)
- How can I switch between **team** profiles in a multi-root workspace?
- How can I prevent Zowe Explorer from storing my credentials?
- How can I disable Secure Credential Storage of credentials?

**Comment by anaxceron** [comment]
@zFernand0 - can we close this issue and have you open up a new issue re: multi-root workspaces?

**Comment by anaxceron** [comment]
Second and third question addressed in [PR 2995](https://github.com/zowe/docs-site/pull/2995)
