### ISSUE TITLE
Refresh required after Login operation

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#1750]
- [ ] ZE: After login, an extension refresh is required to be able to use the profile (since the config might have gotten updated)
- [ ] #1839
- [ ] #1838

_Originally posted by @zFernand0 in https://github.com/zowe/vscode-extension-for-zowe/issues/1743#issuecomment-1100440496_

**Comment by MikeBauerCA** [comment]
@zFernand0 regarding the first one, is the refresh also required if you update credentials via right-click? For now, could we just trigger a refresh after the login action? Or is this only an issue if the login is done externally via the CLI?

**Comment by zFernand0** [comment]
I believe it's both.
When login happens in the CLI, you need a tree-refresh.
And when login is done in ZE, I believe a `> Zowe Explorer: Refresh Zowe Explorer` is needed
