### ISSUE TITLE
Remove 30 day limit to get sufficient upvotes

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/vscode-extension-for-zowe#1767]
**Is your feature request related to a problem? Please describe.**

A bot is going to respond to this issue with the following:

Thank you for raising this issue.
The community has 30 days to upvote 👍 the issue.
If it receives 10 upvotes, we will move it to our backlog. If not, we will close it.

Does the bot automatically close the issue? Do we really need to make this time-bound?

**Describe the solution you'd like**

I'd like the bot to respond with:
Thank you for raising this issue.
The community can upvote 👍 the issue to increase its priority.

**Comment by JTonda** [comment]
We have increased the limit to 90 days across all repos.
