### ISSUE TITLE
If directory has a file or folder with special characters the whole directory fails to load in USS

### ISSUE THREAD

**Issue by kristinochka** [zowe/vscode-extension-for-zowe#1769]
<img width="531" alt="image" src="https://user-images.githubusercontent.com/14590297/165343857-6a0b91c0-809e-427e-b861-e66afd660af8.png">

Steps to re-create
1) Create a file or folder with special characters in the name. This can be done through terminal in zOS. Special character can be added accidentally by users and should not cause ZE to break. 
2) Go to Zowe explorer USS section and try loading the directory containing the file created above
Expected:
USS directory loads and is not broken
Actual:
The whole directory fails to load.

**Comment by JTonda** [comment]
May be related to #1849

**Comment by kristinochka** [comment]
I think this issue has been fixed.
