### ISSUE TITLE
Rework of README file

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#177]
Missing numerous new functions. Restructure to present use cases

**Comment by MikeBauerCA** [comment]
Most of the GIFs are outdated as well. 

During the rework, we should focus on the most popular use cases in the README and reference additional use cases and user documentation in another location. The information in the README should be of high value to most users.

**Comment by Colin-Stone** [comment]
Suggest we have three sections or sub page links. Would like to have gifs for each funtional area but describe menu options in text so the description can be expanded upon. For example Safe save with merge needs more explanation.

First page show the overall container with three views and a highlighted file in editor
## Generic view function
Dynamic Gifs...
- Add profile
- Refresh all

Separate page for each section as described below....
After the links to the separate sections maybe we should have 
### Integrated function
Dynamic gif showing JCL being submitted from Datasets view. Popup showing Job submitted link, click on link and see job spool output in Jobs view

## USS 
Populated USS list view. (Static Gif)
### Menu functions
Dynamic Gif..
- Create new file or directory
Describe the function of:
- Pull from mainframe
- Safe Save - Merge if necessary
- Toggle Binary
- Add favorite
- Rename
- Delete
- File open describe how files are opened by clicking on them and show a static (part) view of a file highlighted with syntax (For example a log file or shell script. 

### Searching
Dynamic Gifs and description...
Entering a root path
Selecting from history recall
### Favorites
Show the creation and demonstrate the use of a file, folder and search.

## Datasets 
Populated Datasets list view. (Static Gif)
### Menu functions
Dynamic Gif..
- Create new Dataset
Describe the function of:
- Create new member
- Upload new member (+Dynamic Gif)
-Show Dataset attributes (+ Static Gif)
- Delete
- File open describe how files are opened by clicking on them and show a static (part) view of a file highlighted with syntax (For example a JCL file or cobol file. 

### Searching
Dynamic Gifs and description...
Entering comma separated dataset patterns 
Selecting from history recall
### Favorites
Show the creation and demonstrate the use of a dataset, member and search.

## Jobs 
Populated Jobs list view. (Static Gif)
### Menu functions
Describe the function of:
- Get JCL
- Issue modify command
- Issue Stop Command
Describe the function of:
- Create new member
- Upload new member (+Dynamic Gif)
- Delete Job
- Download spool
- Issue TSO Command (Cmd-shift-P) May want to rethink this function
