### ISSUE TITLE
Error when migrating ZE to V2 with a TSO profile created in CLI V2

### ISSUE THREAD

**Issue by tanto259** [zowe/vscode-extension-for-zowe#1772]
**Describe the bug**

When updating Zowe Explorer to V2, the following two errors show up if the user have a TSO profile set-up through Zowe CLI V2:
```
Error running command zowe.ds.pattern: Cannot read
properties of undefined (reading 'status'). This is likely caused
by the extension that contributes zowe.ds.pattern.
```
```
Error encountered in checkCurrentProfile.optionalProfiles! 
Error: Internal error: Tried to call a non-existing MVS API in API register: TSO
```
However, removing the existing profiles and re-creating them on Zowe Explorer 2.0.0 and Zowe CLI 7.0.2 will work perfectly.

**To Reproduce**

1. Install Zowe Explorer 1.22.1, set-up a z/OSMF profile as usual
2. Create a TSO profile via Zowe CLI 7.0.2 for the system with the same name as the z/OSMF profile
3. Update Zowe Explorer to 2.0.0, reload page when prompted to update settings
4. Gets prompted to re-enter username and password (which are put in plain-text to the TSO profile yaml file), then error message show up

**Expected behavior**

No error and profile is usable.

**Screenshots**

<img width="500" alt="image" src="https://user-images.githubusercontent.com/13640520/165652970-da4de31c-bcff-44eb-b629-1ef56c164e7b.png">

**Desktop (please complete the following information):**

- OS: Windows
- Zowe Explorer Version: 2.0.0 (and 1.22.1)
- (Optional) Zowe CLI Version: 7.0.2 

**Additional context**

This may seems to be an edge case that is happening for a subset of the IBM Z Xplore course takers. As they are first instructed to create a z/OSMF profile through Zowe Explorer, and then only later creating a TSO profile through Zowe CLI (on which they are instructed to do `npm i -g @zowe/cli`, obtaining the `latest` version.

Assuming that someone creates their z/OSMF profile before V2 is out, and then a TSO profile with CLI v7, they will got this error when their Zowe Explorer installation got updated. However, the issue does not seems to be available when they create the TSO profile with CLI v6.

**Comment by JillieBeanSim** [comment]
@tanto259 I was able to replicate the issue from 1.22.1 to 2.0.0 but retested updating from 1.22.1 to 2.0.1 and I don't see the issue anymore.  FYI @zFernand0

**Comment by zFernand0** [comment]
Hey @JillieBeanSim, Thanks for testing the from 1.22.1 to 2.0.1.
@tanto259, Please let us know if you are still having TSO-profile related issues in 2.0.2 😋 
Closing for now 😉

**Comment by tanto259** [comment]
Thanks! I haven't got the chance to test this again.

But what I can tell you is that I haven't heard about any TSO-profile related issues for a while from the end-users. So, hopefully, their profile migration went well :)
