### ISSUE TITLE
doc(ze-v1): Document `How to stay on Zowe Explorer v1`

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#1796]
User may need to know how to easily stay on the ZE v1 release line.

Here are the steps they can follow to accomplish this. 😋 

1. [Opt out of extension updates](https://code.visualstudio.com/docs/supporting/FAQ#_opt-out-of-extension-updates)
2. Install a specific version:
    - If they don't have ZE installed: [Install a previous version](https://code.visualstudio.com/updates/v1_30#_install-previous-versions)
    - If they have ZE installed: 
      - Click the dropdown arrow in the `uninstall` button.
      ![image](https://user-images.githubusercontent.com/37381190/167673604-0197a65d-d17d-4a41-90e0-75f50589b86f.png)

**Comment by anaxceron** [comment]
Closing w/ [PR 2409](https://github.com/zowe/docs-site/pull/2409)
