### ISSUE TITLE
Update Credentials does not load new password into profiles cache with v2 profiles

### ISSUE THREAD

**Issue by phaumer** [zowe/vscode-extension-for-zowe#1799]
**Describe the bug**

Password was updated in Zowe Explorer and stored correctly, but not loaded into profiles cache so queries keep failing.

**To Reproduce**

- Password was updated on z/OS
- Zowe Explorer shows correctly that my credentials are invalid
- Right-click Update Credentials
- Enter new password
- Try running a query: still invalid credentials
- Try Refresh button and run a query: still invalid credentials

Only workaround is to Reload Window.

**Expected behavior**

After entering the new password it should be used by the trees without Refresh or Reload.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Win10
- Zowe Explorer Version: 2.0.1
- (Optional) Zowe CLI Version: 7.1.1
- (Optional) Are you using Secure Credential Store? y

**Additional context**

**Comment by JillieBeanSim** [comment]
@phaumer & @zFernand0 I was able to replicate this in VSC with marketplace version.  `Check Credentials` error prompt and `Update Credentials` ends up needing a restart of ZE or VSC for the new credentials to be picked up.  This is a regression from v1 and needs fixing.
