### ISSUE TITLE
Project profiles loaded when no workspace folder is open

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#1802]
**Describe the bug**

A Team profile in `~` (e.g. `/root/zowe.config.json`) may be treated as a project configuration file when no workspace is open on VSCode.

**To Reproduce**

1. Create a valid `zowe.config.json` (and schema) file in `/root` 
2. Open VSCode (and make sure no folders are open)
3. Open Zowe Explorer
4. Notice that profiles from the team config (step 1) are loaded as project profiles.

**Expected behavior**

No project profiles being loaded if there is no workspace open.

**Screenshots**

![temp](https://user-images.githubusercontent.com/37381190/168145686-b4ff687e-ba56-4a9e-934e-03a4807e17af.gif)

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Zowe Explorer Version: 2.0.1
- (Optional) Zowe CLI Version: 7.1.3
- (Optional) Are you using Secure Credential Store? y

**Additional context**

The gif above is from this comment https://github.com/zowe/vscode-extension-for-zowe/issues/1777#issuecomment-1124870664, which introduces environmental variable support (more details? #1777)

**Comment by KutluOzel-b** [comment]
This issue can be reproduced and same thing happens in opposite way if root directory has zowe config file. When workspace is open at the explorer instance, it behaves like a project config file and when no workspace is open it behaves like global config file. The error seems to be not related with `ZOWE_CLI_HOME` env variable but  the order of the prioritized profiles. one can be seen at mLayers variable zowe.config.json exists parameter should be false:  

![image](https://user-images.githubusercontent.com/104970275/188910143-b788bcc9-39bf-43d4-a242-b7b423bf1b59.png)

We think not much can be done on the zowe explorer side to let imperative api know about this situation. Hence we are going to investigate it on there. @zFernand0 👍  thanks for discussion and pointing out the problem.
