### ISSUE TITLE
Cannot read properties of null (reading 'getSessionNode')

### ISSUE THREAD

**Issue by jguillaumes** [zowe/vscode-extension-for-zowe#1809]
**Describe the bug**

I get the error message "Cannot read properties of null (reading 'getSessionNode')" everytime I try to interact with Zowe Explorer. Zowe explorer doesn't work at all for me.

**To Reproduce**
 
Try to do anything (get an USS directory, get a DSN list...) using a V1 profile. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Zowe Explorer Version: 2.0.1
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store? No

**Additional context**

I uninstalled VSCode and reinstalled from scratch. I also deleted all the .code direcrories I was able to find. Nothing worked.

**Comment by zFernand0** [comment]
Similar to #1805

**Comment by zFernand0** [comment]
Hey @jguillaumes,
I'm trying to reproduce this on my Win10 environment, and I'm able to use ZE 2.0.1 with v1 yaml profiles and no SCS
Are you seeing this issue on Eclipse Che by any chance (as described in #1805) ?

```yaml
host: lpar1.broadcom.net
port: 443
rejectUnauthorized: false
user: myuser # plain text
password: mypass # plain text
```

Just to confirm, your `C:\Users\<user-id>\.zowe\settings\imperative.json` looks something like this:
```json
{
  "overrides": {
    "CredentialManager": false
  }
}
```

---

To provide a few pointers to the code (for developer's reference) the only possible offender I could find was in the USS tree:
https://github.com/zowe/vscode-extension-for-zowe/blob/056655f321167c76d9bd2e6a7ac26c3496724a2d/packages/zowe-explorer/src/uss/ZoweUSSNode.ts#L126-L128

As you can see, it doesn't not provide a safeguard with the assumption that there will be a session on the node or there will be a parent node with one. as opposed to the other trees
https://github.com/zowe/vscode-extension-for-zowe/blob/056655f321167c76d9bd2e6a7ac26c3496724a2d/packages/zowe-explorer/src/dataset/ZoweDatasetNode.ts#L241-L243
https://github.com/zowe/vscode-extension-for-zowe/blob/056655f321167c76d9bd2e6a7ac26c3496724a2d/packages/zowe-explorer/src/job/ZoweJobNode.ts#L210-L212

**Comment by jguillaumes** [comment]
Hello.

I'm not using Eclipse Che, just plain Visual Studio Code. The only "special" thing I do is to run VSC under WSL2.

I've downgraded to the previous version (1.22.1) using the VSIX file and it works perfectly. I really need my VSC running now, so I cannot do extensive testing.

**Comment by zFernand0** [comment]
Thank you for the info.
I was able to test on WSL as well with ZE 2.0.1 and Plain text credentials.
It also worked there (and on SSH remote, and Theia as well)

Let's get back to this when you have more availability then.
Regardless, thank you very much for opening the issue. 😋 

As for downgrading, we will be putting some doc together pretty soon.
But you should be able to get a previous version right form the marketplace (and not have to install from a VSIX)
More information can be found on the issue below 😋 
- https://github.com/zowe/vscode-extension-for-zowe/issues/1796

**Comment by jguillaumes** [comment]
Hello,

Just a quick update. Tried the extension in another computer (a Mac M1 machine) and got the same results. That makes me think the problem _could_ be in the mainframe side. Right now we are running ZOWE version v. 1.15.0+20200828, under z/OS 2.4. This is a quite outdated version (although, as far as I know, it is labelled as "LTS"). Unfortunately I cannot update ZOWE by myself (the sysprog guys take care of that, and right now they have their hands full).

**Comment by zFernand0** [comment]
Hey @jguillaumes,
Thanks for double checking that the issue happens on another machine 😋 
I'm curious if you were able to update to Zowe Explorer v2.0.2? 
If so, do you still experience the problem ?

**Comment by jguillaumes** [comment]
Hello, I'm in 2.0.2.
Reloading the extension after logging in fixes this problem, thanks.

**Comment by zFernand0** [comment]
Thank you for confirming! 
We are looking into ways of not requiring a reload after a login operation, (or `Update Credentials`) 
- #1750 

Closing for now! 😋
