### ISSUE TITLE
Dataset/files access via ZOWE Explorer don't honor codepage settings.

### ISSUE THREAD

**Issue by bsc55753** [zowe/vscode-extension-for-zowe#1815]
Since the update of all profiles to v2 structure the codepage property has no more effect on the dataset representation in VScode. The conversion of datasets/members seems to be done with IBM-1047. This behaviour prevents us to use Zowe Explorer v2 because all datasets in our site were encoded with IBM-1141. This was no problem with ZOWE Explorer V1.*.

my zowe.config.json looks like:
```
{
    "$schema": "./zowe.schema.json",
    "profiles": {
        "zosmf": {
            "type": "zosmf",
            "properties": {
                "port": 443,
                "codePage": "1141",
            },
            "secure": []
        },
        "tso": {
            "type": "tso",
            "properties": {
                "account": "",
                "codePage": "1141",
                "logonProcedure": "IZUFPROC"
            },
            "secure": []
        },
        "ssh": {
            "type": "ssh",
            "properties": {
                "port": 22
            },
            "secure": []
        },
        "base": {
            "type": "base",
            "properties": {
                "host": "zosmf.enterprise.de",
                "codePage": "1141",
                "rejectUnauthorized": true
            },
            "secure": [
                "user",
                "password"
            ]
        }
    },
    "defaults": {
        "zosmf": "zosmf",
        "tso": "tso",
        "ssh": "ssh",
        "base": "base"
    },
    "autoStore": true
}
```

- OS: Windows 10
- Zowe Explorer Version: 2.0.1
- Zowe CLI Version: 7.0.2

Kind regards,
Björn

**Comment by FALLAI-Denis** [comment]
Hi @bsc55753 

Can you try with `encoding` property instead of `codePage` property?

See #1789

**Comment by bsc55753** [comment]
Hi @FALLAI-Denis,
thank you for the quick response. You're right. "encoding" ist the property key to go. It works like expected.
I've created the config via zowe-cli: `zowe config init` 
Should I open a case against the zowe-cli component? I would guess the codePage parm is confusing, isn't it? Or whats the purpose of 'codePage'?

**Comment by FALLAI-Denis** [comment]
Hi @bsc55753,

I'm not a member of Zowe CLI team 😉.

I create zowe.config.json by migration of Zowe CLI V1 profiles.

**Comment by MikeBauerCA** [comment]
@bsc55753 we discussed this yesterday. We use "encoding" for z/OSMF type profiles. However, "codePage" is on the TSO type profiles. I would agree with the direction of deprecating "codePage" in favor of "encoding". However, we can't immediately remove it in the current release as it would be a possible breaking change.

**Comment by zFernand0** [comment]
Thanks for the discussion.
Please refer to https://github.com/zowe/zowe-cli/issues/1430 for details on the deprecation 😋

**Comment by FALLAI-Denis** [comment]
Hi @bsc55753 

Missing `characterSet` 695 on your tso profile?
