### ISSUE TITLE
Support "copy path" in USS explorer

### ISSUE THREAD

**Issue by ChrisBoehmCA** [zowe/vscode-extension-for-zowe#182]
On right click, it would be cool if I could copy the full path of a USS file or directory as you can in the main VSCode file explorer. I might use this to CD to a directory in ssh or use in a Zowe CLI command/script 

![image](https://user-images.githubusercontent.com/42545737/62312440-30c94b00-b45c-11e9-9ec4-4e2f9cbb45c0.png)

**Comment by Colin-Stone** [comment]
Great idea, is this the full remote path or local path?.

**Comment by ChrisBoehmCA** [comment]
In my opinion, the full remote path would be more useful

**Comment by lauren-li** [comment]
Trying to keep consistent with VS Code's [native categorization](https://code.visualstudio.com/api/references/contribution-points#Sorting-of-groups), our UX team has suggested we add "Copy Path" into its own new category, placed above modification.

With this update, the complete list of context menu groupings would be as follows:

`0_mainframeInteraction`:
- Pull from Mainframe
- Safe Save - Merge if Necessary
- Get JCL

`1_create`:
- Create New Member
- Upload Member...
- Create Directory
- Create File
- Upload Files...

`2_information`:
- Show Data Set Attributes

`3_systemSpecific`:
- Submit Job
- Toggle Binary
- Toggle Text
- Issue Modify Command
- Issue Stop Command

`4_workspace`:
- Add Favorite
- Remove Favorite

`5_copyPath`:
- Copy Path

`6_modification`:
- (0) Rename
- (1) Delete/Delete Data Set/Delete PDS/Delete Member

**Comment by MikeBauerCA** [comment]
@jelaplan offered a suggestion to change "Safe Save - Merge if Necessary" to "Safe Save, Merge if Necessary" in issue #164. Although outside the scope of this issue, I agree with the suggestion in #164 to make "Safe Save" the default behavior of the save operation if possible.

**Comment by lauren-li** [comment]
@MikeBauerCA Thanks for notifying me of this suggestion! Although I'm not currently addressing issue #164, I can go ahead and change the dash to a comma in the context menu command for "Safe Save". I've updated the list of context menu groupings above to reflect this, as well.

**Comment by t-o-m-e-k** [comment]
There are other VSCode File Explorer actions which would be nice to have in Zowe extension:
- Allow opening file in a separate tab with double click.
- Add compare actions ( Select to compare/ Compare with selected)

**Comment by Colin-Stone** [comment]
Hey Tomasz, great ideas, thanks. The first one in particular has been mentioned before so we need to start capturing ideas like these. Would you be happy raising these as separate issues?.. 
Thanks

**Comment by MikeBauerCA** [comment]
Copy path is now supported. Closing

**Comment by ChrisBoehmCA** [comment]
Awesome :D
