### ISSUE TITLE
Display PROCSTEP in the Jobs tree view

### ISSUE THREAD

**Issue by plavjanik** [zowe/vscode-extension-for-zowe#1832]
**Is your feature request related to a problem? Please describe.**

I am submitting a JCL (e.g. to compile some code using COBOL or another compiler). The procedure has multiple steps (e.g. COBOL, LKED, GO). These steps can have the same DD names.

**Describe the solution you'd like**

When I work in 3270, SYSVIEW shows me PROCSTEP so I know which output I am opening. In Zowe Explorer the PROCSTEP is missing so I have to guess and try to open multiple files before I have the one that I want.

<img width="230" alt="image" src="https://user-images.githubusercontent.com/7644758/172391230-a04801e8-e8e1-4d41-b406-1525b30b651e.png">

<img width="184" alt="image" src="https://user-images.githubusercontent.com/7644758/172391383-73392d63-3979-4529-bcc2-aeaa2c57678c.png">

**Describe alternatives you've considered**

I have not found a good alternative.

**Comment by zFernand0** [comment]
I guess the name could get kind of long, but if it's available to us (from the SDKs calls), we could append to the name
So it will look something like this:
```
JES2:JESMSGLG(2)
JES2:JESJCL(2)
JES2:JESYSMS(4)
HELLO:SYSPRINT(101) - COBOL
HELLO:SYSPRINT(102) - LKED
HELLO:SYSOUT(106)   - GO

**Comment by JillieBeanSim** [comment]
Hey @plavjanik as @zFernand0 mentioned the name could get pretty long with all info listed.  I am wondering if creating a hover feature will work where the procstep is shown when the mouse hovers over the Spool file name?

**Comment by plavjanik** [comment]
I will speak for myself. Since I know ISPF, I would expect to see it and it will not occur to me to hover over each item. Since my goal is to quickly identify the correct item to open just by looking at the tree, hovering will not help much because I will have to hover over each item. Procstep is up to 8 characters and is optional so it will not make it much longer. I would rather omit the ID number in parentheses that do not provide me any value (`(106)`). 

Displaying other details like the ID, class, records, or bytes in hover is a great idea.
