### ISSUE TITLE
Missing translation hook

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#185]
Missing translation 
![Screenshot 2019-08-05 at 11 58 50](https://user-images.githubusercontent.com/30794003/62459922-75b0f280-b778-11e9-9fa5-001040c0062f.png)

**Comment by evannwu20** [comment]
Should have been added in most recent localization pr. 
<img width="382" alt="Screen Shot 2019-08-05 at 9 49 29 AM" src="https://user-images.githubusercontent.com/51461375/62469564-7fc9f580-b766-11e9-8cdc-950f10e65291.png">

**Comment by Colin-Stone** [comment]
Thanks Evan this is fixed along with the USS one. Please don't close issues straight away as someone still has to verify/review it.
