### ISSUE TITLE
ZE: create all `.zowe` subfolders needed (e.g. `~/.zowe/settings`)

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#1850]
We would still want to have the means of creating all other missing folders (`~/.zowe/settings`)

_Originally posted by @zFernand0 in https://github.com/zowe/vscode-extension-for-zowe/issues/1830#issuecomment-1161834205_

**Comment by JillieBeanSim** [comment]
@zFernand0 is there a way we can just use/pass the setting like we did before with SCS when installed instead of requiring the file?
