### ISSUE TITLE
Zowe Explorer is not working in Codespaces

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1854]
**Describe the bug**

I am trying Github Codespaces and I installed Zowe Explorer. The extension loaded but I am not sure that it activated properly. There are no error message whatsoever. There are no buttons and if I try using the commands, it doesn't work.

**To Reproduce**

Activate Codespaces and Install ZE

**Expected behavior**

It should work similarly as the Desktop or theia

**Screenshots**

![zeCodespace](https://user-images.githubusercontent.com/45042840/174983334-2d815442-2982-49d8-9f04-4e1714a19167.gif)

**Desktop (please complete the following information):**

- OS: Windows 11 
- Zowe Explorer Version: latest
- (Optional) Zowe CLI Version: N/A
- (Optional) Are you using Secure Credential Store? none

**Additional context**

**Comment by jellypuno** [comment]
I also don't know where to find the logs 😢

**Comment by jellypuno** [comment]
It works in Codespaces desktop

**Comment by traeok** [comment]
Wondering if this issue was specific to GitHub codespaces? I just tried installing Zowe Explorer in Codespaces (web) and it seems to be functional. The missing "+" button is now showing, the favorites nodes are back under each section. Will do some further testing and report back.

**Comment by JillieBeanSim** [comment]
I opened the web version of Github Codespaces and installed the Zowe Explorer extension and was able to create a v1 profile but wasn't able to connect to the host.  Found where in the workspace we are storing the profile information
`./home/codespace/.zowe`

![Screen Shot 2023-01-18 at 9 34 46 AM](https://user-images.githubusercontent.com/49491949/213199556-3002b3b6-3836-4a3e-81b5-646286e031f6.png)

![Screen Shot 2023-01-18 at 9 35 54 AM](https://user-images.githubusercontent.com/49491949/213199584-b10ce694-31b8-4a63-9378-8a9561716d96.png)

**Comment by JillieBeanSim** [comment]
we are seeing the same outcome as with https://github.com/zowe/vscode-extension-for-zowe/issues/1798 @zFernand0 do we want to handle the same way? FYI @anaxceron

**Comment by zFernand0** [comment]
yeah, we should handle them the same way.
if we don't document unsupported ENVs then we should close both as not planned (for now) 😋

**Comment by zFernand0** [comment]
Given that we only document environments that we support...
Let's close this issue (as not planned - for now) since we can't claim we support this particular one yet.
We can revisit these connectivity/firewall challenges later on.
