### ISSUE TITLE
JCL1 member not generated

### ISSUE THREAD

**Issue by JHLLOR** [zowe/vscode-extension-for-zowe#1860]
Issue Type: <b>Feature Request</b>

Hello:
My name is Juan Hernandez, I am from Mexico City.
Can you help me with the following problem? :
I am trying to run ´JCL1 challenge 3´ in ´Foundamentals´ but JCL1 member is not defined in ZXP,PUBLIC.JCL.
My Username is: Z14245.
I thank you in advance for your support.

Extension version: 2.1.0
VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by jellypuno** [comment]
@JHLLOR This is specific for the IBM Xplore course or the OMP Cobol programming course. please post this issue in Slack. You will be supported there.

**Comment by tanto259** [comment]
Hi @JHLLOR, do post your queries on the IBM Z Xplore forum over at https://ibmzxplore.influitive.com, and we'll help you to solve it over there.

Thank you!
