### ISSUE TITLE
using base config profiles causes extension failure while loading profiles and API

### ISSUE THREAD

**Issue by tucker01** [zowe/vscode-extension-for-zowe#1863]
I am using the new team config and I generated the default config with `zowe config init`. In other words, I have a default `zosmf` profile with just the port, and a `base` profile that contained the host, user, and password.

This configuration caused the extension to fail during initialization with `Internal error: Tried to call a non-existing MVS API in API register: base`. 

Looking thru the code for a split second, it looks like when it attempts to register the default "ZosmfMVSAPI" it expects that the profile type is `zosmf`. However, as the message indicates, the extension is attempting to pass a profile of type `base`. I'm not sure why. 

The "fix" is to abandon using `base` profiles in favor of `zosmf`. However, this is inconvenient because then I'm duplicating info.

**Comment by tucker01** [comment]
The hang is not related to ZE, its due to a problem with the zosmf status endpoint on our LPAR.

**Comment by JTonda** [comment]
Closing since issue is not related to Zowe Explorer.
