### ISSUE TITLE
Add a dataset/uss link to Job Output result

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#1864]
**Is your feature request related to a problem? Please describe.**

I was playing with z/OSMF today and I saw this nice feature:
![image](https://user-images.githubusercontent.com/45042840/177563871-39a4e8aa-6013-4d10-b4d1-af541767e7f6.png)
 

**Describe the solution you'd like**

I would like to have the capability to open datasets/uss location when I am viewing a job output. It would be a great feature and it is very helpful when investigating issues. 

**Describe alternatives you've considered**

**Additional context**

**Comment by zFernand0** [comment]
This might be related to:
- #1795
