### ISSUE TITLE
[zftp] Expect saving dataset/file serially to avoid conflict error in short time with multiple times saving.

### ISSUE THREAD

**Issue by tiantn** [zowe/vscode-extension-for-zowe#1868]
Currently, saving dataset and file are execurated in parallel that results the conflic error sended if saving multiple times in a short time.(The previous saving not completed and the new save request started.) 

So, we expect doing save action in serially to avoid the conflict and improve user experience. Thank you!

**Comment by JillieBeanSim** [comment]
@tiantn please check that this is still needed, we did some work around saving in 2.2.0 release on the Zowe Explorer side https://github.com/zowe/vscode-extension-for-zowe/pull/1859

**Comment by tiantn** [comment]
Thank you @JillieBeanSim! I will try and verify it. Thanks!

**Comment by tiantn** [comment]
Hi @JillieBeanSim , I tested with #1859. It solved the problem partially. However, sometimes the save action happens to occur after the upload completion and before the return etag(usually the last save of multiple saves), and the saved content will not be uploaded successfully. 

@std4lqi and I have a propose based on Zowe Explorer code. We added a savingQueue to let the save requests queued in it then handle them one by one. It works as expected now. The following is the propose code in vscode-extension-for-zowe/packages/zowe-explorer/src/utils/workspace.ts. 

```
const savingQueue = [];
let latestSavedFile: vscode.TextDocument;
let ongoingSave = false;
export async function handleSaving(
    uploadRequest: (document, provider) => Promise<void | string>,
    savedFile: vscode.TextDocument,
    fileProvider: IZoweTree<IZoweUSSTreeNode | IZoweDatasetTreeNode>
): Promise<void> {
    const saving = {
        savedFile,
    };
    savingQueue.push(saving);
    if (ongoingSave) {
        return;
    }
    ongoingSave = true;
    while (savingQueue.length !== 0) {
        latestSavedFile = savingQueue.shift().savedFile;
        await uploadRequest(latestSavedFile, fileProvider);
    }
    ongoingSave = false;
}
```
Could you help to review it? Thank you! 

Thank you @std4lqi to work with me and guide me kindly. Thank you!

**Comment by tiantn** [comment]
Hi @JillieBeanSim , is there any comments about the proposal？
