### ISSUE TITLE
ZE API registerCustomProfileType throws an error when team config file is in use.

### ISSUE THREAD

**Issue by uzuko001** [zowe/vscode-extension-for-zowe#1870]
**Describe the bug**

Using the ZE API ProfilesCache().registerCustomProfileType() throws an error when team config file is in use since the folder `os.homedir()}/.zowe/profiles/${profileTypeName}` does not exist.
This means that the external profile type is not added and that makes them unreadable.

Trying to `initForZowe()` first does not help either, since it checks if team config file is in use before creating the folder specified above.

**To Reproduce**
1. Convert existing v1 profiles using zowe-cli (renames existing os.homedir()}/.zowe/profiles folder to profiles-old)
2. Try using rofilesCache().registerCustomProfileType() 

- OS: Windows 10
- Zowe Explorer Version: 2.1.0

**Additional context**
As extenders going for v2 conformance in our next release this is a major issue.

**Comment by nickImbirev** [comment]
I upvote for the issue, this is a show stopper for our extension to adopt the ZE APIs in the upcoming release and to be conformant as well.
