### ISSUE TITLE
Incompatibility of Zowe CLI V1 and zowe.config.json files --> revocation of accounts on z/OS system

### ISSUE THREAD

**Issue by FALLAI-Denis** [zowe/vscode-extension-for-zowe#1871]
**Describe the bug**

When Zowe CLI V1 is installed on the workstation, and a `zowe.config.json` file is present in the workspace, if the z/OS remote account password is changed, then the mechanisms for password resynchronization at Zowe Explorer level does not work, and z/OS remote account is revoked.

It would seem that in the presence of a `zowe.config.json` file in the workspace, (or in .zowe folder in home user folder), Zowe Explorer considers that it works in V2 mode, regardless of the Zowe CLI version actually installed on the workstation, which causes then malfunctions in the management / update of profiles and credentials.

We have Zowe CLI V1 workstations and Zowe CLI V2 workstations.
Both groups should access the same workspaces created from the same Git repositories.
We have chosen to store the `zowe.config.json` files in the Git repositories to avoid users having to create them (without any other solution than to directly edit the file, without any input control...).

**To Reproduce**

1. Install Zowe CLI V1 on workstation
2. Copy a zowe.config.json in workspace, or in .zowe folder of user home directory
3. Change password on remote z/OS
4. Open workspace in VS Code
5. Try to access remote z/OS (edit a COBOL source file with a COPYBOOK and search for COPYBOOK on remote z/OS)
6. Zowe Explorer (or Z Open Editor wich delegate ressource access to Zowe Explorer) trigger a "401", and ask for credentials
7. Provide the credentials
8. Save the credentials
9. Repeat steps 5 to 8
10. After a certain number of authentication failures (3 for us), the z/OS remote account is revoked...

**Expected behavior**

Zowe Explorer should not work based on the presence of a `zowe.config.json` file, but must test the Zowe CLI API version of the workstation.

**Screenshots**

See [Revocation of remote user account in presence of a zowe.config.json file in a Zowe CLI V1 context](https://github.com/IBM/zopeneditor-about/issues/255)

**Desktop (please complete the following information):**

- OS: Windows 10 20H2
- Zowe Explorer Version: 2.1.0
- (Optional) Zowe CLI Version: V1 (6.x.x)
- (Optional) Are you using Secure Credential Store? Yes

**Comment by JillieBeanSim** [comment]
Hey @FALLAI-Denis we do not support Zowe CLI v1 (6.x.x) and Zowe Explorer v2 working together.  If the workstation needs to stay v1 we have some steps outlined in https://github.com/zowe/vscode-extension-for-zowe/issues/1796 that will be published soon to Zowe.org or you could update all pieces to v2 (CLI at 7.x.x)
