### ISSUE TITLE
Incorrect encoding page for USS files 

### ISSUE THREAD

**Issue by Yuliya-Kirkorava** [zowe/vscode-extension-for-zowe#1877]
Hi,

I uploaded some local files with --ec 273  and -- ec 1047 to USS:

zowe zos-files upload file-to-uss --ec 273 "git-test/ISPPLIB/pe32act0.pnl" "/u/KIRJU/git-test/ISPPLIB/cmd273.pnl"
zowe zos-files upload file-to-uss --ec 1047 "git-test/ISPPLIB/pe32act0.pnl" "/u/KIRJU/git-test/ISPPLIB/cmd1047.pnl"

I see that tags are not set in such case:
- untagged    T=off -rw-r--r--   1 BLK      SYS1        4535 Jul 20 07:12 cmd1047.pnl
- untagged    T=off -rw-r--r--   1 BLK      SYS1        4535 Jul 20 07:12 cmd273.pnl

When I display these files under ISPF, symbols are correct there (for both files):
![image](https://user-images.githubusercontent.com/96059205/180177670-05ac84e7-2e58-481c-8372-aeb678c6cff0.png)

Then I want to open such files under USS in Zowe Explorer symbols are displayed incorrectly for IBM-273 file:

![image](https://user-images.githubusercontent.com/96059205/180177990-783f4928-65b1-4ec8-879c-51f79756cf76.png)

But for file wih IBM-1047 encoding page symbols are correct:

![image](https://user-images.githubusercontent.com/96059205/180178343-f50c755b-cedb-4018-bbe4-fddaf3e532f7.png)

--------------------------------
After that I try to set a tag for cmd273.pnl with the correct encoding page and expected that Zowe Explorer would download the file  with the correct encoding page (273). But still incorrect symbols are in the file:

- untagged    T=off -rw-r--r--   1 BLK      SYS1        4535 Jul 20 07:12 cmd1047.pnl
t IBM-273     T=on  -rw-r--r--   1 BLK      SYS1        4535 Jul 20 07:12 cmd273.pnl 

![image](https://user-images.githubusercontent.com/96059205/180179275-5487c9a4-b6aa-4717-8ff2-04bb165b78ab.png)

I also tried to specify encoding parameter in the profile. It also doesn't work in my case.

Can I display file with IBM-273 encoding in USS correctly ? Can I edit such file locally and save it back with IBM-273 encoding?

- Zowe Explorer Version: v2.1.0
- Zowe CLI Version: 7.2.2

**Comment by JillieBeanSim** [comment]
Hey @Yuliya-Kirkorava, what profile type are you using for the action? zosmf, ftp, etc.

**Comment by Yuliya-Kirkorava** [comment]
Hi,
I use zosmf profile.

**Comment by Yuliya-Kirkorava** [comment]
Hi,
Do you have any progress here?

**Comment by JillieBeanSim** [comment]
Hey @Yuliya-Kirkorava no update yet, I don't believe the file is tagged via the zOSMF api call when uploaded.  @zFernand0 this seems to be an issue with the CLI as well so this may need to be addressed at a different level then adopted by ZE?

**Comment by Yuliya-Kirkorava** [comment]
Hi,
  I have already opened another ticket for Zowe CLI team: https://github.com/zowe/zowe-cli/issues/1479. They are going to fix the problem with tags and encoding.
  But I am wondering if I tag the file with correct encoding manually (as I described above), why you are not using this information when you download the file? Is it possible to check file's tag and download it with the corresponding encoding:
zowe zos-files download uss-file --ec 273 "/a/ibmuser/my_text.txt" -f ./my_text.txt ?

Thanks!

**Comment by zFernand0** [comment]
Once https://github.com/zowe/zowe-cli/issues/1479 is resolved, we can revisit this from a ZE perspective. 😋

**Comment by Yuliya-Kirkorava** [comment]
Hi All,
Seems [zowe-cli#1479](https://github.com/zowe/zowe-cli/issues/1479) was resolved in Zowe 7.6.0. 

When do you plan to add the support of encoding (based on tags) for USS download/upload commands?

Thanks, Yuliya

**Comment by FALLAI-Denis** [comment]
Hi,

Using z/OSMF Zowe CLI profile with **IBM-1147** default encoding.
Using Zowe Explorer "USS View" to edit an **IBM-1047 explicitly tagged** USS file.
On download: file is incorrectly converted, convert form **IBM-1147** to UTF8, characters like {, }, [, ] are not well converted!
On upload: file is converted from UTF8 to **IBM-1147** and **USS file is (re)tagged IBM-1147** (and as USS file is a script, it is no longer executable).
