### ISSUE TITLE
Incorrect profile name in favorites crashing Zowe extension

### ISSUE THREAD

**Issue by gplambert** [zowe/vscode-extension-for-zowe#188]
When navigating to the Zowe Extension in VS Code, the Favorites and zosmf-profile do not show up on any of the tabs, data sets, uss, or jobs. Instead, you get the following message: There is no data provider registered that can provide view data.

Steps to Reproduce

    Create a zosmf-profile
    List datasets and/or USS files
    Select a 'favorite', I had one for both Data sets and USS
    Delete the zosmf-profile
    Create new zosmf-profile with a new name
    Open Zowe view
    Should see the error message listed above

Looking at the Persistent Favorites in the settings.json, I see the zosmf-profile name is still pointing to the old profile.

Expected behavior

I should still be able to see the new profile and use it regardless of the profile name tagged in the favorites. Maybe some error message indicating the profile name used in the favorites is no longer found so that I know to change it. Regardless, the current message give no help as it is a generic VS Code message.

Screenshots
zoweCLI profile was deleted.
![62644219-9a8f9c00-b917-11e9-81a5-8a76b9c80431](https://user-images.githubusercontent.com/43450888/62647891-9bc4c700-b91f-11e9-89f9-2e23ff0734e2.png)

Logs
If applicable, add server logs collected at the time of your problem.

Details

    Version and build number: [e.g. 0.4.4-SNAPSHOT build # 155]
    Test environment: [e.g. zD&T, zPDT, MONOPLEX, SYSPLEX, z/OS Rev 2.2, TSS, RACF, ACF2, or any other germane detail]

Web Browser Details (if the bug relates to Zowe Desktop usage):

    OS: [e.g. macOS, Windows]
    Browser [e.g. Chrome, Safari]
    Version [e.g. 71.0.3578.98]

REST API client (in case of REST API issue):

    Technology: [e.g. Spring Boot, Node.js, Postman]
    OS: [e.g. Windows 10]

Shell Environment Details (if the bug relates to CLI):

    Technology: [e.g. zsh, cygwin, cmd, powershell, bash]
    OS: [e.g. MacOS 10.13, Windows 10, Ubuntu 16.04 LTS]

Additional context

**Comment by lauren-li** [comment]
Planned fix results: When the user has a favorite with an invalid profile name...
- Tree data for Data Sets, USS, and Jobs will still load.
- Favorites with valid profile names will still load in the tree.
- Favorites with invalid profile names will *not* load in the tree.
- The user will receive an error message for either USS or Data Sets depending on which setting(s) contains the invalid favorites.

Proposed error messages for USS and Data Sets invalid profile name:
<img width="459" alt="Screen Shot 2019-08-19 at 10 56 13 AM" src="https://user-images.githubusercontent.com/45975633/63300883-41285500-c2a7-11e9-9134-2ee6b05b04ef.png">

**Comment by MikeBauerCA** [comment]
@lauren-li can you confirm this issue has been resolved and close if appropriate?

**Comment by lauren-li** [comment]
@MikeBauerCA This issue is mostly resolved, except the message is specific for VS Code. (It was resolved before we started thinking about bringing the extension into Theia.):

<img width="515" alt="Screen Shot 2019-11-13 at 2 34 02 PM" src="https://user-images.githubusercontent.com/45975633/68797633-f65a7700-0622-11ea-85d5-7fcae6e96d67.png">

I can add a variable in the message to customize the message to VS Code vs Theia based on the environment being used, but it would probably have to be have to be after I finish work on the webpack issue (#74).
