### ISSUE TITLE
Year Long Roadmap

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#1888]
template: https://github.com/zowe/community/issues/1633

items to be added:

existing Epics?
Bring back profile associations as Extender APIs?
Cross tree actions Extender APIS?
Hex support?
Jes view to incorporate hyperlinks into USS or DS view to open items listed in spool files?

**Comment by RASakach** [comment]
@JillieBeanSim for the roadmap items, can we use what you have listed here and complete each of them as follows:
(1) What problem are you solving
(2) What are you doing to solve it
(3) When do you plan to start the work
(4) When do you plan to deliver the solution

So for example the first entry will be: 
(1) Users are asking for APIs ..... (or whatever)....

**Comment by JillieBeanSim** [comment]
some epic outlines to be discussed Tues Aug 23rd

1. Users are submitting issues about Zowe Explorer not working in different environments.
	First we plan to create a maintained list of supported environments.  This work has already begun with our discussion, Zowe Explorer Supported Environments https://github.com/zowe/vscode-extension-for-zowe/discussions/1691.
We plan to deliver this work in the 3rd quarter PI of 2022.
	Secondly, we plan to consider other environments requested by users, this will require research and depending on the research we will decide if support is feasible.  Research will being in the 3rd quarter PI of 2022 and decisions made to continue the work will happen in the 4th quarter PI of 2022.

2. Users would like better Loggins from Zowe Explorer to help troubleshoot issues.
	We plan to start this work in the 3rd quarter PI of 2022 with additional logging added to log files and look into adding the logs to Zowe Explorer’s Output view as well so users don’t have to leave the VS Code space to see logging.
Plan to deliver ?

3. Extenders would like more robust Extensibility APIs to adopt for their VS Code Zowe Explorer extensions.
	We have a long list of requested extensibility APIs for extenders and plan to start the work in the 3rd quarter PI of 2022.
Plan to deliver the epic as a whole ?

4. Users would like to see less pop up notifications from Zowe Explorer to lessen the distractions that they cause in VS Code.
	We plan to start this work in the 3rd quarter PI of 2022.
	We plan to deliver this work ?

5. Users would like more tree view actions in Zowe Explorer to have multi-select functionality.
	This work has already begun, but is a large amount of work to do across all 3 tree views within Zowe Explorer.
We plan to deliver this as a whole complete epic by ?

**Comment by JillieBeanSim** [comment]
@zFernand0 community file is updated https://github.com/zowe/community/blob/master/Project%20Management/PI%20Planning/22PI3%20Planning/Zowe%20Explorer%20Objectives.md#roadmap
