### ISSUE TITLE
Show the record count for job files in the JOBS view

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/vscode-extension-for-zowe#1889]
**Is your feature request related to a problem? Please describe.**

the Zowe Explorer Jobs view shows the list of files together with their id, which is a unique identifier.  

<img width="388" alt="image" src="https://user-images.githubusercontent.com/28100302/181355301-a2dbc924-a5fb-448e-8bc6-85f96416fb4e.png">

**Describe the solution you'd like**

As well as the ID, show the record count of the file.  This is similar to what SDSF does.  The reason it's good to show the record count is that at a glance you can see whether a file has contents (for example STDERR has 0 record below) or whether the file is very large.  

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/28100302/181355402-b2d315d9-12b3-40fc-a523-5934b8d158ae.png">

**Additional context**

The z/OSMF REST API for listing files does return the record count

**Comment by zFernand0** [comment]
Will adding the Record-count as part of the hover details be good enough ?
We could consider adding it to the label itself, but there has already been a request made to make other modifications to it 😋 
- https://github.com/zowe/vscode-extension-for-zowe/issues/1832
