### ISSUE TITLE
Hidden profile shows up after restart

### ISSUE THREAD

**Issue by kristinochka** [zowe/vscode-extension-for-zowe#1894]
**Describe the bug**

**To Reproduce**
1. Create Global Team config profile
2. Add an extender profile, for example rse
3. Add default zosmf and rse profiles
4. Hide zosmf profile and zosmf profile goes away
5. Refresh VS Code
6. zosmf profile comes back

**Expected behavior**
zosmf profile should be gone

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Zowe Explorer Version:
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by JTonda** [comment]
Closing in favor of issue #829
