### ISSUE TITLE
Question - Is the installation of Zowe CLI on the workstation still a prerequisite for using Zowe Explorer? 

### ISSUE THREAD

**Issue by FALLAI-Denis** [zowe/vscode-extension-for-zowe#1898]
Hi,

In the past, we always installed the Zowe CLI component on workstations before installing Zowe Explorer.
This with Zowe CLI V1.

It would seem, and this is conditional, that Zowe Explorer can work without installing Zowe CLI V2, when a` zowe.config.json` file in the Zowe CLI V2 standard is present either in the Workspace, or in the User's Home Directory.

Can you tell us if the installation of Zowe CLI on the workstation is still a prerequisite for the operation of Zowe Explorer?

If Zowe CLI is not installed on the workstation, but a zowe.config.json file is present, what Zowe Explorer features would be impacted?

Thanks.

**Comment by JillieBeanSim** [comment]
Hey @FALLAI-Denis, we working to make Zowe Explorer independent of the CLI installation with this [PR](https://github.com/zowe/vscode-extension-for-zowe/pull/1993)
