### ISSUE TITLE
ZE FTP - Doc: Add a `zftp` snippet to the `Create a Team Configuration File` topic

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#1899]
**Is your feature request related to a problem? Please describe.**

Users that already have a `zowe.config.json` file before installing the ZE FTP extension may find it helpful if there was a `zftp` skeleton in the readme file

**Describe the solution you'd like**

Adding the below snippet of code to the [Create a Team Configuration File](https://github.com/zowe/vscode-extension-for-zowe/tree/master/packages/zowe-explorer-ftp-extension#create-a-team-configuration-file) topic.
```json
        "zftp": {
            "type": "zftp",
            "properties": {},
            "secure": []
        }
```

**Comment by zFernand0** [comment]
Related: https://github.com/zowe/vscode-extension-for-zowe/pull/1893

**Comment by anaxceron** [comment]
Closed with [PR 2298](https://github.com/zowe/vscode-extension-for-zowe/pull/2298)
