### ISSUE TITLE
Fix Broken Hyperlinks to Repo

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#1903]
After changing our default branch from master to main all hyperlinks to our repo that had master in it are broken on zowe.org

**Comment by anaxceron** [comment]
Found no hyperlinks in Zowe.org repo that included "master" in them. We did fix several hyperlinks w/in Zowe Docs that included "master," see the following PR:
https://github.com/zowe/docs-site/pull/2374
