### ISSUE TITLE
Zowe Explorer does not refresh on custom .zowe directories

### ISSUE THREAD

**Issue by rudyflores** [zowe/vscode-extension-for-zowe#1913]
**Describe the bug**

When setting a `ZOWE_CLI_HOME` environment variable a custom `.zowe` directory location, Zowe Explorer will not refresh the profiles in the tree since the watcher will only view the default directory.

**To Reproduce**

1. Create `ZOWE_CLI_HOME` environment variable to a custom path (e.g ~/Desktop/.zowe)
2. Close terminal and VS Code and re-open VS Code to see changes
3. Create team config profile and make changes
4. save changes
5. profiles should not appear in the tree because refresh is not performed

**Expected behavior**

profiles should be displayed on the tree after saving team config profile upon creation.

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS Monterrey 12.3.1
- Zowe Explorer Version: 2.2.1
- (Optional) Zowe CLI Version: 7.4.1
- (Optional) Are you using Secure Credential Store? no

**Additional context**

**Comment by reallyrachett-hue** [comment]
https://github.com/zowe/zowe-explorer-vscode/issues/1913

**Comment by reallyrachett-hue** [comment]
https://github.com/zowe/zowe-explorer-vscode/issues/1913
