### ISSUE TITLE
Zowe V1: Needs a way to specify the region size for a TSO command

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#1921]
**Is your feature request related to a problem? Please describe.**

Zowe Explorer is dependent on the CLI for updating the TSO region size value when using V1 profiles only

**Describe the solution you'd like**

A way for editing the default V1 TSO profile right from Zowe Explorer

**Describe alternatives you've considered**

Using the CLI to update the tso.yaml file 😢 

**Additional context**

**Comment by JillieBeanSim** [comment]
Closing as won't do since we are no longer adding new v1 specific capabilities
