### ISSUE TITLE
Create New Team configuration option messes up existing team configurations file

### ISSUE THREAD

**Issue by kristinochka** [zowe/vscode-extension-for-zowe#1922]
**Describe the bug**

**To Reproduce**
1. Create a new team configuration file (in this case I created Global config)
2. Update it with unique named profiles and connection details
3. Add profile names to "default" section and save the file
4.  Click "Create New Team configuration" which opens the Global profile again

**Expected behavior**

Expect it to simply open existing profile for editing. Another option would be to update menus to only allow profile editing.

**Actual Behavior**
It adds the default empty profile options and adds new defaults to the bottom of the profile without any warning. Afterwards, I need to go and clean my profile file and remove necessary template text and re-add my defaults. 

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Zowe Explorer Version:
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by JillieBeanSim** [comment]
This works as intended atm by merging any new default information from ZE extenders with an existing team configuration.  #1923 will bring in the option for users to move forward with the merge or keep existing team configuration file as is and open it.
