### ISSUE TITLE
File watcher is causing errors during login & logout

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#1924]
**Describe the bug**

When login and logout are used and the file watcher kicks off the refresh of ZE and errors are being presented to users about the command/id being registered.

**Screenshots**

logout:
<img width="465" alt="Screen Shot 2022-08-26 at 8 48 25 AM" src="https://user-images.githubusercontent.com/49491949/186907205-91d7a953-034a-4b2d-bd99-65c9b20c0870.png">

after logout the sessions are removed from tree and needed user to refresh tree view for them to come back

login:
<img width="465" alt="Screen Shot 2022-08-26 at 8 48 46 AM" src="https://user-images.githubusercontent.com/49491949/186907225-a4fcaac1-f1f3-4b3d-9483-8454b7a866d5.png">

**To Reproduce**

1. right click and select login on appropriate profile
2. enter credentials when prompted
3. see errors but login is successful, actions after are successful using the tokens
4. right click and select logout on same profile
5. see errors but logout is successful

**Expected behavior**

No errors shown is login or logout is successful

**Desktop (please complete the following information):**

- OS: mac os
- Zowe Explorer Version: main branch
- (Optional) Zowe CLI Version: 7.4.2
- (Optional) Are you using Secure Credentials? yes

**Additional context**

**Comment by kristinochka** [comment]
One option to fix this is to looks at the difference between previous config file and new config file. If the changes have to do with login/logout or new credentials, refresh is not needed.
