### ISSUE TITLE
Zowe explorer writes logs into the wrong folder

### ISSUE THREAD

**Issue by kristinochka** [zowe/vscode-extension-for-zowe#1926]
**Describe the bug**
I expected Zowe Explorer to write logs to the following folder: /Users/kristinamayo/.zowe/zowe/logs
However, it's not the case. On my computer Zowe Explorer writes logs in the following folders:

`/Users/kristinamayo/wazi/vscode-extension-for-zowe/packages/zowe-explorer/Users/kristinamayo/wazi/vscode-extension-for-zowe/packages/zowe-explorer/Users/kristinamayo/wazi/vscode-extension-for-zowe/packages/zowe-explorer/Users/kristinamayo/wazi/vscode-extension-for-zowe/packages/zowe-explorer/Users/kristinamayo/wazi/vscode-extension-for-zowe/packages/zowe-explorer/Users/kristinamayo/wazi/vscode-extension-for-zowe/packages/zowe-explorer/Users/kristinamayo/wazi/vscode-extension-for-zowe/packages/zowe-explorer/logs/zowe.log
/Users/kristinamayo/wazi/vscode-extension-for-zowe/packages/zowe-explorer/Users/kristinamayo/wazi/vscode-extension-for-zowe/packages/zowe-explorer/Users/kristinamayo/wazi/vscode-extension-for-zowe/packages/zowe-explorer/Users/kristinamayo/wazi/vscode-extension-for-zowe/packages/zowe-explorer/Users/kristinamayo/wazi/vscode-extension-for-zowe/packages/zowe-explorer/Users/kristinamayo/wazi/vscode-extension-for-zowe/packages/zowe-explorer/Users/kristinamayo/wazi/vscode-extension-for-zowe/packages/zowe-explorer/Users/kristinamayo/wazi/vscode-extension-for-zowe/packages/zowe-explorer/logs/zowe.log`

It’s duplicating path to zowe-explorer (/Users/kristinamayo/wazi/vscode-extension-for-zowe/packages/zowe-explorer) many times and then logging there. 

I deleted the nested folders above and now it’s creating nested folders in here:
`/Users/kristinamayo/.vscode/extensions/zowe.vscode-extension-for-zowe-2.2.0-SNAPSHOT/Users/kristinamayo/wazi/vscode-extension-for-zowe/packages/zowe-explorer/Users/kristinamayo/wazi/vscode-extension-for-zowe/packages/zowe-explorer/Users/kristinamayo/wazi/vscode-extension-for-zowe/packages/zowe-explorer/Users/kristinamayo/wazi/vscode-extension-for-zowe/packages/zowe-explorer/Users/kristinamayo/wazi/vscode-extension-for-zowe/packages/zowe-explorer/Users/kristinamayo/wazi/vscode-extension-for-zowe/packages/zowe-explorer/Users/kristinamayo/wazi/vscode-extension-for-zowe/packages/zowe-explorer/Users/kristinamayo/wazi/vscode-extension-for-zowe/packages/zowe-explorer/logs/zowe.log`
For every new zowe.log, it creates a nested folder with a long path

**To Reproduce**

**Expected behavior**
I expected Zowe Explorer to write logs to the following folder: /Users/kristinamayo/.zowe/zowe/logs and not duplicate the directory path

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Zowe Explorer Version:
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by JillieBeanSim** [comment]
@kristinochka is this only an issue when using Dev Host or also when the vsix is installed?

**Comment by t1m0thyj** [comment]
We could investigate writing logs into the same folder as VS Code:
![image](https://user-images.githubusercontent.com/22344007/225412819-2aa09283-4b82-4385-b548-40aea66f1b8c.png)

**Comment by kristinochka** [comment]
@t1m0thyj VS Code puts their logs in a place that's difficult to navigate to or find if you're not a VS Code developer and it does create new folders for each session. If we add it there, user needs to be able to find it easily. There is a ticket to create Zowe Explorer output window in VS Code. Logs could be printed to the Output window and it would print the location of the log file on disk.
Like the screenshot below:
![image](https://user-images.githubusercontent.com/14590297/225936341-7c080849-c488-489f-b8b4-48bab25418e9.png)

@JillieBeanSim has plans to work on this feature.

**Comment by JillieBeanSim** [comment]
This has been fixed with the introduction of the Zowe Explorer output logger, now the location while running Extension Development Host ./packages/zowe-explorer/logs and installation in VS Code writes to default vscode location for the extension or the setting zowe.files.logsFolder.path.  Location of the log is displayed in the second line of Zowe Explorer output logger during activation
<img width="332" alt="Screen Shot 2023-09-08 at 3 40 03 PM" src="https://github.com/zowe/vscode-extension-for-zowe/assets/49491949/e2cb3f1b-73bd-4da4-bd04-79d6e11bfd6e">
