### ISSUE TITLE
Revocation of z/OS account on PDS member access

### ISSUE THREAD

**Issue by FALLAI-Denis** [zowe/vscode-extension-for-zowe#1931]
**Describe the bug**

After changing the z/OS account password directly on the z/OS mainframe system, launch VS Code and go to Zowe Explorer.

The password saved by Zowe CLI is the old password and is outdated.

In Zowe Explorer, request to access a PDS file: Zowe Explorer asks to verify credentials --> OK

The password is communicated to Zowe Explorer (which does not ask if to save it, but the zowe.config.json file says to save them).

Note: Zowe Explorer does not continue with opening the requested PDS file (the current request is apparently aborted).

New access request to the same PDS file, no credential request --> OK

Zowe Explorer opens the PDS: the password is therefore valid and was saved during the first access attempt.

PDS Member Access: Again, Zowe Explorer asks for credentials verification --> it shouldn't since it supposedly saved the credentials.

The password is communicated again, access to the PDS member failed.

Credentials are requested again, provided again, again there is a failure when accessing the PDS member.

Three failures, z/OS account revoked...

**To Reproduce**

I didn't try because the procedure to reactivate a z/OS account takes a long time to process...

1. Change the password of your z/OS account
2. Connect to VS Code and activate Zowe Explorer 
4. Search for a PDS, open it (Zowe Explorer must ask for credentials)
5. Search for a member, opent it (Zowe Explorer should not ask for credentials)

**Desktop:**

- OS: Windows 10 x64 20H2
- Zowe Explorer Version: 2.2.1
- Zowe CLI Version: 7.4.0

**Comment by JillieBeanSim** [comment]
@FALLAI-Denis is this still an issue with 2.3.0?

**Comment by FALLAI-Denis** [comment]
Hi @JillieBeanSim 

The problem could not be reproduced in version 2.3.0.

We will consider it solved and I close this issue.

Thanks.
