### ISSUE TITLE
Bring up test coverage for project to 90%

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#1946]
Bring apx 75% coverage to 90%

![Screen Shot 2022-10-04 at 3.37.01 PM.png](https://images.zenhubusercontent.com/5caf658116e44025d19266b8/012d6697-80fe-4376-96e1-8f54077ba1d9)

**Comment by zFernand0** [comment]
Please follow the steps in this https://github.com/zowe/vscode-extension-for-zowe/issues/1965#issuecomment-1387247589 for details on how confirm that this issue can be considered complete
