### ISSUE TITLE
Job Class not accurately reflected in Zowe Explorer

### ISSUE THREAD

**Issue by ATorrise** [zowe/vscode-extension-for-zowe#1951]
**Describe the bug**
ZE does not reflect the correct class of jobs. In the pictures below you'll see that ZE is displaying JOB04921 as class B when it is actually class A (verified with SYSVIEW)

**To Reproduce**
This bug was identified by creating a zowe command to change the class of a job that has yet to run via [zosmf](https://www.ibm.com/docs/en/zos/2.4.0?topic=interface-change-job-class)

**Expected behavior**
ZE should reflect the actual class of a job

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- Zowe Explorer Version: 2.3.0
- (Optional) Zowe CLI Version: 7.6.1
- (Optional) Are you using Secure Credential Store? Yes

**Comment by JillieBeanSim** [comment]
@rudyflores  can you also confirm that job class is no longer reflected in the job name or description when hovered over.  Once confirmed we can close

**Comment by rudyflores** [comment]
I am no longer seeing this issue within Jobs submitted, I will go ahead and close this issue. Thanks for also confirming this as well @JillieBeanSim !
