### ISSUE TITLE
JOBS section refresh & multiple tabs 

### ISSUE THREAD

**Issue by mohit28290** [zowe/vscode-extension-for-zowe#1952]
**Describe the bug**

Active Job refresh
- Active job doesn't refresh automatically unlike USS and Datasets.
- need to refresh manually and every time click same sysprint/joblog  after refresh opens new tab  

**To Reproduce**

Submit long running active job 
go to > Jobs > active job > sysprint
refresh manually > select updated sysprint 5-10 times > end up having 5-10 tabs with same updated sysprint

**Expected behavior**

- Active job refresh should be automatic
- should update/refresh the same tab with the new sysprint info/log

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Zowe Explorer Version: 1.72
- (Optional) Zowe CLI Version: 7.5.1
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by zFernand0** [comment]
A few routes we could take are:
1. Pressing `Enter` while viewing (focused on) the spool file will trigger a `Pull From Mainframe` action
2. Polling with a configurable interval. (requires new setting - default: 10 seconds)
3. Request for a z/OSMF enhancement to support sockets (or similar mechanism to allow for active communication)
