### ISSUE TITLE
USS command fails when JCL submitted via VScode

### ISSUE THREAD

**Issue by ghost** [zowe/vscode-extension-for-zowe#1958]
**Describe the bug**

Same USS related JCL submitted through VScode fails with RC=0012.

**To Reproduce**

1. Go to job, submit mount zfs JCL as sample below

 //MOUNT    EXEC PGM=IKJEFT01,REGION=0M,COND=(0,LT)
//SYSEXEC  DD DISP=SHR,DSN=SYS1.SBPXEXEC
//SYSTSPRT DD SYSOUT=*
//SYSTSIN  DD *
  PROFILE MSGID WTPMSG
  oshell umask 0022; +
    mkdir -p /z/mg894880/zs20/pax
  MOUNT +
    FILESYSTEM('MG894880.ZS20.ZFS') +
    MOUNTPOINT('/z/mg894880/zs20/pax') +
    MODE(RDWR) TYPE(ZFS) PARM('AGGRGROW')
//*

2. go to jobs and see error log with RC=12

**Expected behavior**

Job should complete 
with RC=00

**Screenshots**

![image](https://user-images.githubusercontent.com/114663645/195069759-f1bf17ae-0329-41e0-bf4c-f263648eff56.png)

![image](https://user-images.githubusercontent.com/114663645/195069849-854eee59-ae3b-4904-9599-79d3043acf8d.png)

![image](https://user-images.githubusercontent.com/114663645/195069681-8163885d-7536-42da-b348-93392b31a644.png)

**Desktop (please complete the following information):**

OS: Windows 10
Zowe Explorer Version: 1.72
(Optional) Zowe CLI Version: 7.5.1
(Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by zFernand0** [comment]
hey @mohit28290, 
Could you submit the same job with the CLI?
Curious if this is something that's happening due to a common SDK method between CLI and ZE

**Comment by mohit28290** [comment]
This works with explorer and CLI both
I found that it reads from sysin from column no. 9  in the jcl

**Comment by zFernand0** [comment]
Hey @mohit28290 
Thanks for confirming and closing the issue! 😋

**Comment by mohit28290** [comment]
But why explorer and cli don't recognise stuff for columns 1-8
should we keep this issue open and work on it
or the workaround is fine for this issue and open another issue regarding the same

**Comment by zFernand0** [comment]
Hey "Ghost",
I believe we should open another issue regarding this.
