### ISSUE TITLE
Increase coverage of project to 80% branch coverage

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#1965]
To gain the Golden CII Badge we need to increase coverage of project to 80% branch coverage

**Comment by zFernand0** [comment]
To make sure this is complete, we need to:
- Go to the [latest main build](https://github.com/zowe/vscode-extension-for-zowe/actions/workflows/zowe-explorer-ci.yml?query=branch%3Amain) 
- Either download the results from the summary or navigate to any build's `yarn test` step
- Look for the test report (example below) and verify that it meets the requirements of the issue.
```
-------------------------------|---------|----------|---------|---------|
File                           | % Stmts | % Branch | % Funcs | % Lines |
-------------------------------|---------|----------|---------|---------|
All files                      |   73.01 |    65.07 |   62.21 |   73.96 |
```
