### ISSUE TITLE
FTP: Job search with a prefix longer than 8 characters does not throw an error

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#1971]
**Describe the bug**

The following scenario seems a bit inconsistent with z/OSMF.

**If**: your prefix is longer than 8 characters,
**When**: searching for jobs,
**Then**: you don't get any errors 

**To Reproduce**

1. Go to the Jobs tree
2. Click on the search icon (next to a `zosmf` profile)
3. Enter `*` and `test12345` for the owner and prefix respectively
4. See the following error
    ![image](https://user-images.githubusercontent.com/37381190/195663573-5e02a06e-bd69-4762-9084-1c0abae7a290.png)
5. Click on the search icon (next to a `zftp` profile)
6. Enter `*` and `test12345` for the owner and prefix respectively
7. See the results of the search being `Owner: * , Prefix: <Your-ID>`

**Expected behavior**

Even though the error may not be super descriptive, I was expecting to see an error since that's not a valid search filter.

**Screenshots**

![temp](https://user-images.githubusercontent.com/37381190/195669086-fcd64263-ffa0-4691-82a0-ae610a8c4d09.gif)

**Desktop (please complete the following information):**

- OS: Any
- Zowe Explorer Version: 2.3.0
- Zowe Explorer - FTP Extension Version: 2.3.0
- (Optional) Zowe CLI Version: N/A
- (Optional) Are you using Secure Credential Store? N/A

**Additional context**

Thanks @anaxceron for finding this one 😋

**Comment by tiantn** [comment]
Hi @zFernand0, @anaxceron, I had a test for prefix longer than 8 characters. Yes, it is not throw an error but it will list nothing. For the current design, that's behavior is expected and consistent with zowe cli ftp plugin. Thank you!

https://user-images.githubusercontent.com/23715327/200232121-1ee2dc53-6c86-4109-b70a-261014d29a7b.mov

**Comment by zFernand0** [comment]
Hey @tiantn,
Thanks for the feedback.
After some discussion, we determined that it will be ideal to have validation on both ends 😋

**Comment by tiantn** [comment]
Thank you @zFernand0! We plan to add the checking on zos node accessor so that ftp plugin and ftp extension can be benefit automatically.

**Comment by kristinochka** [comment]
Works as expected.

**Comment by zFernand0** [comment]
Thanks @tiantn for updating the plugin! 😋 
- https://github.com/zowe/zowe-cli-ftp-plugin/pull/126

**Comment by tiantn** [comment]
Hi @zFernand0 , @KutluOzel-b , I met a problem when using the Create job search filter. I suppose the job owner, prefix and status all should be submit as a search query. But I can only change the prefix and confirm it to search. When I changed the owner or status I can't confirm it after press "Enter" key. It had not any response. See the gif file below:
![job owner and job status can't confirm](https://user-images.githubusercontent.com/23715327/216890372-9462acad-ac4c-4d45-b2b5-64193ec55e20.gif)

It maybe not related to the issue directly. I am not sure if it is a bug or I missed something. Could you help to try it? Thank you very much!
