### ISSUE TITLE
ZE: `allocate-like` does not respect the `blksz` parameter

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#1974]
**Describe the bug**

The `blksz` seems different in the new dataset (compared to the original).
This may not be expected by end users.

**To Reproduce**

1. Go to the ZE's Dataset tree
2. Right-click on a `zosmf` profile and search for an existing `data-set`
3. Right-click on the `data-set` and select `Show Data Set Attributes`
4. Right-click on the `data-set` and select `Allocate Like...`
5. Provide name for the new data set (e.g. `data-set-like`)
6. Right-click on the `data-set-like` and select `Show Data Set Attributes`
7. Compare the two `blksz` properties

**Expected behavior**

I believe the user would expect the `blksz` to be the same between `data-set` and `data-set-like`

**Screenshots**

![temp](https://user-images.githubusercontent.com/37381190/195883092-1fd6318f-94a1-4e62-a59c-eae6aa6ac83e.gif)

**Desktop (please complete the following information):**

- OS: Windows 10
- Zowe Explorer Version: 2.3.0
- (Optional) Zowe CLI Version: N/A
- (Optional) Are you using Secure Credential Store? N/A

**Additional context**

FYI, the GIF also showcases the following issue:
- #1973

**Comment by traeok** [comment]
Seems like this issue is coming from z/OSMF's REST API Client - after fixing the anomaly bug in #1973, all attributes seem to be copied to the new dataset, as intended, w/ the exception of `blksz`.

Did some debugging on our calls to z/OSMF REST Client and the only attribute that we pass is an `options` object structured like so:

`{ like: 'USER.DATASET.ALLOC.LIKE' }`

Will soon report this through the necessary pipeline for z/OSMF issues.

**Comment by traeok** [comment]
Going to reopen this as we will be addressing the API-specific issue with the z/OSMF team.

**Comment by traeok** [comment]
We received a response back from the z/OSMF team confirming that the 'LIKE' API function used for the 'Allocate Like' feature does not support copying the blksz parameter. As the API does not support the required functionality to fix this issue, this issue will be closed.

https://www.ibm.com/docs/en/zos/2.4.0?topic=statement-like-parameter
