### ISSUE TITLE
The REDEFINES clause must begin in Area B

### ISSUE THREAD

**Issue by ROBIN-Olivier** [zowe/vscode-extension-for-zowe#1975]
Hello,
The VSCode parser indicates a problem when using the REPLACING clause with a REDEFINES on some copies.
The compilation is going well.

**To Reproduce**

add a copy to a program
add below the same copy with the REPLACING clause and the word REDEFINES in the target area

whatever the copy, the anomaly appears

**Screenshots**
![REDEFINES AREA B](https://user-images.githubusercontent.com/103997342/195886192-4cd31cbc-8013-467a-95c6-2aa15acfbc78.PNG)

**Desktop (please complete the following information):**

OS: Windows
Zowe Explorer Version: v2.3.0

**Comment by zFernand0** [comment]
Hey Robin, thanks for opening the issue.
This seems related to the COBOL Language Support
https://github.com/eclipse/che-che4z-lsp-for-cobol
I 'm afraid I'm not able to transfer the issue though.

Please open future issues regarding the COBOL Language Support in the lsp-for-cobol repository.
https://github.com/eclipse/che-che4z-lsp-for-cobol/issues/new/choose
Closing for now! 😋
