### ISSUE TITLE
Running a saved search causes a duplicate profile to be created

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#198]
If you have specified several save searches in the datasets view, running save search can create a duplicate profile to be spawned that is the same as the existing one

**Comment by MikeBauerCA** [comment]
@Colin-Stone is this still an issue?

**Comment by Colin-Stone** [comment]
Fixed by https://github.com/zowe/vscode-extension-for-zowe/pull/247
