### ISSUE TITLE
Error running command zowe.ds.pattern: Cannot read properties of undefined (reading 'status'). This is likely caused by the extension that contributes zowe.ds.pattern.

### ISSUE THREAD

**Issue by plaidshirtakos** [zowe/vscode-extension-for-zowe#1983]
**Describe the bug**

I have used Zowe Explorer a few weeks ago. I just updated VS Code to version 1.72.2. Zowe extension isn't working after that.

**Screenshots**
![image](https://user-images.githubusercontent.com/30076100/197963410-38fec470-b60c-45c1-9f36-b49710e624d7.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Zowe Explorer Version: 2.3.0
- (Optional) Zowe CLI Version: 7.7.0

**Comment by traeok** [comment]
Hello @plaidshirtakos ,

Just wanted to follow up on this bug report 🙂 

Typically this problem arises when there is an issue with validating existing profiles. When using a valid `zowe.config.json` I am unable to reproduce the problem with the latest version of Zowe Explorer (2.6.0) as well as 2.3.0.

Are you still experiencing this issue? If so, would it be possible to supply the config file that is being used? (with hosts and credentials removed) No worries if it is not possible to provide a config.

Finally, if possible I would recommend updating Zowe CLI and Zowe Explorer to the latest release versions - this might also mitigate the problem as a result of new bug fixes.

Thanks!

**Comment by JillieBeanSim** [comment]
@traeok @t1m0thyj @zFernand0 can this be closed since no feedback or recreation steps provided?

**Comment by traeok** [comment]
@JillieBeanSim I believe this can be closed - I'm still unable to reproduce this issue.

**Comment by zFernand0** [comment]
yeah, I think it'd be ok to close for now. 😋
