### ISSUE TITLE
Minimize the activate() function to have less chance of failure

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#1985]
There is a lot of stuff happening in the activate() function.  It would be good to minimize the function for start up then process the profiles and trees possibly when user clicks the Zowe Activity Bar Icon

**Comment by zFernand0** [comment]
we should consider doing the same for the FTP extension! 😋

**Comment by JillieBeanSim** [comment]
closing with PR https://github.com/zowe/vscode-extension-for-zowe/pull/2611
