### ISSUE TITLE
Can’t connect nor addSession onZowe

### ISSUE THREAD

**Issue by nannanli** [zowe/vscode-extension-for-zowe#2005]
@IMackie22 commented on [Fri Oct 21 2022](https://github.com/zowe/vscode-extension-for-zowe/issues/2019)

Hello I’m having trouble reconnecting with my Zowe profile. After I submitted a job, I received this following error
![3CDDB7F9-B3AB-4EC5-8C4D-CCB33C93BDCE](https://user-images.githubusercontent.com/87789451/197048017-25ed3beb-4f06-41d1-9577-f1988acd869a.jpeg)

I tried deleting my .zowe file/removing and uninstalling the program. I still have the same issue.

---

@nannanli commented on [Mon Nov 07 2022](https://github.com/zowe/vscode-extension-for-zowe/issues/2019)

@JillieBeanSim Hi Billie, any suggestions or advice regarding this issue? Feel free to move it to the Zowe Explore repo as needed. Thank you! 

---

@JillieBeanSim commented on [Mon Nov 07 2022](https://github.com/zowe/vscode-extension-for-zowe/issues/2019)

Hey @nannanli I don't see the option to move to our repo, I may not have the permissions.  I am not sure what is causing the issue but will investigate, thanks.

**Comment by zFernand0** [comment]
Closing in favor of the transferred issue 
- #2019
