### ISSUE TITLE
Can’t connect nor addSession onZowe

### ISSUE THREAD

**Issue by IMackie22** [zowe/vscode-extension-for-zowe#2019]
Hello I’m having trouble reconnecting with my Zowe profile. After I submitted a job, I received this following error
![3CDDB7F9-B3AB-4EC5-8C4D-CCB33C93BDCE](https://user-images.githubusercontent.com/87789451/197048017-25ed3beb-4f06-41d1-9577-f1988acd869a.jpeg)

I tried deleting my .zowe file/removing and uninstalling the program. I still have the same issue.

**Comment by zFernand0** [comment]
Hey @IMackie22,
Could you please verify if you still see the same problems with the latest release (v2.4.1)?

**Comment by zFernand0** [comment]
This issue has been addressed and we even have an error message that should help with errors in the zowe.config.json file
![image](https://user-images.githubusercontent.com/37381190/219456477-dade81fe-f4a4-4924-8afe-4d930128e829.png)
