### ISSUE TITLE
`Show Attributes` context/menu option should not be present for migrated datasets

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#2033]
**Is your feature request related to a problem? Please describe.**

There seems to be no way to retrieve attributes for a migrated dataset unless you recall it first.

**Describe the solution you'd like**

Don't show the option if it doesn't work as expected

**Describe alternatives you've considered**

Recall the dataset before showing attributes

**Additional context**

N/A

**Comment by JillieBeanSim** [comment]
fixed with PR https://github.com/zowe/vscode-extension-for-zowe/pull/2444
