### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by parthamaiti-hub** [zowe/vscode-extension-for-zowe#208]
[Zowe.vscode-extension-for-zowe-unresponsive.cpuprofile.txt](https://github.com/zowe/vscode-extension-for-zowe/files/3534370/Zowe.vscode-extension-for-zowe-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `vscode-extension-for-zowe`
- Extension Version: `0.24.1`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.37.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\pmaiti\Zowe.vscode-extension-for-zowe-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jellypuno** [comment]
I experienced this one today:

![Capture](https://user-images.githubusercontent.com/45042840/75333137-e2f7b280-5885-11ea-8208-0a3684ec9e4c.PNG)

**Comment by Colin-Stone** [comment]
@jellypuno This is the one that I had experienced. You should probably have a look at https://github.com/microsoft/vscode/wiki/Performance-Issues but I think I may have already addressed this issue and it was associated with the additional process spawning we needed for the secure credentials. That has now been removed. 

8 seconds does seem a  long time to activate so would be interested to know how you go tthe image above

**Comment by jellypuno** [comment]
I experienced it when I tried to debug Branch  Fix-Issue-370

**Comment by Ashish1981** [comment]
I got this issue while installing installing the extension.
![image](https://user-images.githubusercontent.com/20042870/75924543-27d6a700-5e8d-11ea-889e-57a3c866a0e2.png)

**Comment by jellypuno** [comment]
@Ashish1981 That is a different issue.

**Comment by zFernand0** [comment]
> @Ashish1981 That is a different issue. Do you have NodeJS installed?

Let's continue discussions in https://github.com/zowe/vscode-extension-for-zowe/issues/588

**Comment by sandeep-sparrow** [comment]
facing a similar issue, syntax highlight and other features are not working in the editor

**Comment by sandeep-sparrow** [comment]
![image](https://user-images.githubusercontent.com/61901052/81715542-fa623700-9495-11ea-8be4-3c25a1511500.png)

**Comment by jellypuno** [comment]
@sandeep-sparrow If you are using Z Open Editor, Please open the issue on their part. Also, syntax highlighting works depending on your file extension (*.cbl) or the language mode specified on the bottom right of VSCode

![Capture](https://user-images.githubusercontent.com/45042840/81715968-1c998c00-9479-11ea-96e2-6aafe63d723d.png)

**Comment by sandeep-sparrow** [comment]
Thank you
