### ISSUE TITLE
Zowe Explorer API's dataSetsMatchingPattern error found on Che

### ISSUE THREAD

**Issue by rudyflores** [zowe/vscode-extension-for-zowe#2084]
**Describe the bug**

An error was found when performing a filter search on a Che environment for the DS view.

**To Reproduce**

1. Create unsecure team config profile on a Che environment
2. Reload window
3. click on a profile and perform a filter search on the DS view
4. enter credentials when prompted
5. do any filter search e.g User.*
6. error should appear

**Expected behavior**

Should display items when performing a filter search successfully

**Screenshots**

<img width="501" alt="Screen Shot 2023-01-13 at 1 18 58 PM" src="https://user-images.githubusercontent.com/68666202/212392752-c2d8156e-85cb-41a9-ae6c-a9604ec3d80a.png">

**Desktop (please complete the following information):**

- OS:
- Zowe Explorer Version:
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

Could be potentially related to #2038 
@zFernand0

**Comment by JillieBeanSim** [comment]
@zFernand0 looks like the introduction of new api is a breaking change for extenders since it doesn't revert to old api call if not found
