### ISSUE TITLE
Folder or directory expansion not working correctly in theia environment

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#209]
Subsequent to version 0.24.1 the expansion of certain leaves aren't working correctly. 

This started with the new icon swapping functionality. When expanding or collapsing and the way that events generated are handled differently in the VSCode implementation versus a theia. In the case of theia this can be avoided by not implementing the icon swapping and therefore avoiding the extra events but this does mean the content is not as dynamic. 

To implement this we require a new configuration setting for example zowe.environment. If undefined or set to anything but theia the swapping function is left as is but if set to theia the code is bypassed.

**Comment by Colin-Stone** [comment]
The issue is caused because the mechanism "flipState" responding to the onDidExpand (or Collapse event updates the icon and fires an element data changed event. This is received correctly by VSCodes treeview getChildren method but under theia the treeview getChildren method receives undefined rather than the element which causing the root element to be sent the getChildren request. As a work around I have introduced a setting Zowe-Environment.framework that can be set to theia. If set the code responding to the onDid.. events is not activated

**Comment by phaumer** [comment]
https://github.com/zowe/vscode-extension-for-zowe/pull/214

**Comment by phaumer** [comment]
@Colin-Stone thanks a lot for making it work. I submitted a PR that would not require setting, but automatically detects if we are in Theia or VS Code: https://github.com/zowe/vscode-extension-for-zowe/pull/219
