### ISSUE TITLE
Can't connect to mainframe in Theia

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/vscode-extension-for-zowe#2095]
**Describe the bug**

In Theia 1.33.0, attempts to connect to mainframe with ZE result in this error: "Failed to establish a socket connection to proxies"

**To Reproduce**

1. Start Theia in a Docker container: `docker run -it --init --name theia -p 3000:3000 t1m0thyj/theia-alpine`
2. Copy ZE VSIX into the container: `docker cp dist/vscode-extension-for-zowe-2.6.0-SNAPSHOT.vsix theia:/home/theia/plugins`
3. Go to Theia (http://localhost:3000) and install ZE from VSIX
4. Open Zowe Explorer panel and add a new profile
5. Try to search for data sets and see the error in the screenshot below

**Expected behavior**

Should be able to search for data sets as long as the profile contains valid connection info.

**Screenshots**

![image](https://user-images.githubusercontent.com/22344007/214331389-0ba53553-cad8-40fc-a5bd-d21168f4fbb4.png)

**Desktop (please complete the following information):**

- OS: Theia 1.33.0
- Zowe Explorer Version: 2.6.0-SNAPSHOT

**Additional context**

This is likely caused by a bug in Theia: https://github.com/eclipse-theia/theia/issues/11911
Perhaps we can comment on that issue to provide additional info.
Also, a workaround may be to downgrade to an older version of Theia.

Interestingly, Zowe CLI successfully connects to the mainframe in the Theia terminal with these commands:
```
mkdir test && cd test && npm init -y && npm install @zowe/cli
npx zowe files ls ds SYS1.PARMLIB
```

**Comment by t1m0thyj** [comment]
Confirmed this seems to be a Theia bug, and left a comment on the linked Theia issue.

Until it is fixed, a workaround is to set `http.proxySupport` to `off`:
![image](https://user-images.githubusercontent.com/22344007/223560157-f6291ee2-ce5a-49f7-8c9f-7a65d2d08444.png)

**Comment by t1m0thyj** [comment]
@anaxceron Can we add this to the list of ZE known issues [here](https://docs.zowe.org/stable/troubleshoot/ze/known-ze)?

## Theia Mainframe Connection Error

**Symptom:**

When performing any action that requires a mainframe connection like searching for data sets you see a proxy error.

**Sample message:**

"z/OSMF REST API Error" that includes `Failed to establish a socket connection to proxies`

![image](https://user-images.githubusercontent.com/22344007/228298373-2fc63c22-689c-4ca8-b94f-4a119dac3c66.png)

**Solution:**

In Theia settings, search for "proxy" and change the `http.proxySupport` setting to `off`:
![image](https://user-images.githubusercontent.com/22344007/223560157-f6291ee2-ce5a-49f7-8c9f-7a65d2d08444.png)

**Comment by anaxceron** [comment]
Added this as a known issue to the [Known Zowe Explorer Issues](https://docs.zowe.org/stable/troubleshoot/ze/known-ze/) article w/ [PR 2777](https://github.com/zowe/docs-site/pull/2777)
