### ISSUE TITLE
Interacting with services through APIML

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/vscode-extension-for-zowe#21]
When I attempt to interact with z/OSMF through the API Mediation Layer from the Zowe VSCode Extension (e.g. list data sets), I receive the following error message:

Retrieving response from zowe.List Error: z/OSMF REST API Error: Rest API failure with HTTP(S) status 404 messages: - messageType: ERROR messageNumber: MFS0103 messageContent: The endpoint you were looking for '/zosmf/restfiles/ds' could not be located

The endpoint does not include my basePath

Note that I can list data sets using the CLI to interact with z/OSMF via APIML in my integrated terminal.

Zowe Extension version 0.8.1
Zowe CLI version 2.0.0-next.201811131824

**Comment by crshnburn** [comment]
Just tried this with version 0.8.3 and it works as expected. It would be worth making sure that you have the latest version installed as the extension has to use it's own bundled version of the CLI code rather than the version installed on the machine.

**Comment by MikeBauerCA** [comment]
Awesome, it does work! Thanks
