### ISSUE TITLE
Persistence of added profiles

### ISSUE THREAD

**Issue by tjohnsonBCM** [zowe/vscode-extension-for-zowe#210]
When profiles are added to any of the tree views in the extension, they do not persist after restarting VS Code. It would be a nice enhancement if non-default profiles were remembered across restarts, instead of needing to be added repeatedly.

**Comment by Colin-Stone** [comment]
I think this makes sense and should be a requirement for GA

**Comment by MikeBauerCA** [comment]
It would also be nice if filters were remembered across restarts.

**Comment by Colin-Stone** [comment]
> It would also be nice if filters were remembered across restarts.

Filters will persist. I have already coded that, just not committed yet

**Comment by Colin-Stone** [comment]
I'm restructuring the ProfileLoader code for this issue and considering https://github.com/zowe/vscode-extension-for-zowe/issues/208 and https://github.com/zowe/vscode-extension-for-zowe/issues/212 in the process
