### ISSUE TITLE
Profile context menus get stuck in multi-select mode

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/vscode-extension-for-zowe#2105]
**Describe the bug**

After selecting multiple profiles and issuing the "Hide Profile" command, right-clicking a single profile still shows the context menu in multi-select mode.

**To Reproduce**

1. Add at least 3 profiles to one of the trees:
![image](https://user-images.githubusercontent.com/22344007/215804958-108a8114-bb7a-4b1b-96c9-d5f7c5dc40b5.png)
2. Select 2 of the profiles and right-click them, then select "Hide Profile" from the context menu:
![image](https://user-images.githubusercontent.com/22344007/215804639-638a1bed-0de2-4b77-989c-7f56a8af363c.png)
3. Right-click on a single profile that remains and notice there are fewer options than expected:
![image](https://user-images.githubusercontent.com/22344007/215804825-e50e79d2-f0df-4874-9d6e-1a5ae64fac40.png)

**Expected behavior**

Right-clicking a single profile should always open the full context menu.

To work around the issue, click on another tree node to expand/collapse it. This seems to reset the context menu state.

**Comment by t1m0thyj** [comment]
This issue seems to have reappeared. 😢 

Also, the Paste option should not appear when right-clicking multiple items in the Data Sets tree:
![image](https://user-images.githubusercontent.com/22344007/225986227-a2ed9d9b-ec70-46a2-b08d-a01a809ae70c.png)

**Comment by traeok** [comment]
Update: Turns out the function call that fixes this bug was moved in between updates/merges. Will push out a fix for this and get a PR up on Monday.
