### ISSUE TITLE
Group common methods into Singleton classes

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#2109]
**Is your feature request related to a problem? Please describe.**

In an effort to reduce the maintenance efforts of Zowe Explorer, it might be convenient to group related methods under a single class.  This should help streamline how imports are handled when developing new features and how tests are written for these new methods.

**Describe the solution you'd like**

Ideally we will use singleton classes 😋 

**Describe alternatives you've considered**

We can consider using:
- Classes with static methods:  may have its own [drawbacks](https://softwareengineering.stackexchange.com/a/98093) (not all of which may apply in our case)
- [Namespaces](https://www.typescriptlang.org/docs/handbook/namespaces.html): may cause issues when writing jest-tests for method that are not explicitly exported ([medium](https://medium.com/jspoint/typescript-namespaces-f43cd002c08c))

**Additional context**

Suggestion: 
- https://github.com/zowe/vscode-extension-for-zowe/pull/2080#discussion_r1094598607
  - Another conclusion on the same PR was to use named exports instead of `default` whenever possible 😋

**Comment by zFernand0** [comment]
We could address [this comment](https://github.com/zowe/vscode-extension-for-zowe/pull/2244#discussion_r1196914836) at the same time we handle this issue. 😋

**Comment by JillieBeanSim** [comment]
Closing with the merge of #2698
