### ISSUE TITLE
Refreshing job list more than once doesn't collapse tree node

### ISSUE THREAD

**Issue by tjohnsonBCM** [zowe/vscode-extension-for-zowe#211]
Steps to reproduce:
1. Add a profile to the Jobs tree that contains several jobs and expand it.
2. Click the Refresh button next to the profile name. The job list collapses and must be expanded again, which I believe is expected behavior.
3. With the job list expanded, click the Refresh button again. Now the list disappears, but the arrow next to the profile node is still expanded. Now I need to click twice, once to collapse the node and again to expand it. If this step is repeated, the same strange behavior occurs.

**Comment by Colin-Stone** [comment]
The rule I applied across the three views was if you collapse and then expand a node e.g. the root, the content stays as it was as in every child that was expanded remains expanded. No server calls made. Alternatively if you perform a refresh I treat is as a clean slate and remove all child elements from the node being refreshed. This avoids multiple calls to the server to reinstate the same situation as before. 

The Jobs view is slightly different to the other views (having an additional refresh button) I do intend to align it with the other two views

**Comment by tucker01** [comment]
Thanks @Colin-Stone. I think the key oddity here, was that once you hit refresh, you had to close the folder, then open it again to see the list. 

I think the former version refreshed the list in place, so no additional user action was required to see the jobs.

**Comment by Colin-Stone** [comment]
I can't recreate this issue. Maybe some code has addressed this already. Could you try again with the 0.25+ version please?.

**Comment by tjohnsonBCM** [comment]
I'm also no longer to reproduce this issue, it appears to have been fixed. Thanks :)

**Comment by Colin-Stone** [comment]
"Back of the net...." Thanks Timothy.
