### ISSUE TITLE
Provide support for changing file tags within Zowe Explorer

### ISSUE THREAD

**Issue by turnerm92** [zowe/vscode-extension-for-zowe#2113]
When working with Git repositories on zOS in particular, tagging of files with the correct encoding is important if those repos are linked to an enterprise repository like Gitlab/Github. When you create a new file using Zowe Explorer you can't set the encoding of that file, and you can't change the existing tag if it is wrong. 

It would be good to be able to :

1.  Define the tag/encoding when creating a new file
2. Change the tag of an existing file using the right click context menu against a file.

The only options currently are to either use an ISPF session, ssh into the host and issue the chtag command, or run a zowe cli command. These don't provide the seamless user experience required.

**Comment by traeok** [comment]
> We could support chmod/chown/chtag operations in ZE through this z/OSMF API: https://www.ibm.com/docs/en/zos/2.4.0?topic=interface-zos-unix-file-utilities#IZUHPINFO_API_PutUnixFileUtilities

And [here's](https://github.com/zowe/zowe-cli/blob/e4a5b2b5bb410a46143f7780337d8aca63245ac3/packages/zosfiles/src/methods/utilities/Utilities.ts#L36) the relevant CLI function :yum:

**Comment by t1m0thyj** [comment]
In addition to changing a file's tag, it would be nice to have an option to convert the file contents to another encoding.
The IntelliJ version of Zowe Explorer supports this 😋 
However it may be more difficult to implement because the z/OSMF APIs doesn't seem to support it.
