### ISSUE TITLE
Regression in job-search through favorites

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#2122]
There might be a slight issue with the updates made to the labels.
Based on @adam-wolfe's comments during yesterday's call, we looked into things a bit closer regarding favorites and found that the updated labels break the searching capabilities from a favorited job-search.
![temp](https://user-images.githubusercontent.com/37381190/218100003-76e4bfcd-eec0-48af-ba89-e1fcd9c02549.gif)

_Originally posted by @zFernand0 in https://github.com/zowe/vscode-extension-for-zowe/issues/2064#issuecomment-1425772824_

**Comment by adam-wolfe** [comment]
A simple resolution may be to move the filter info into the description rather than the label.
