### ISSUE TITLE
Double-clicking node in Datasets view opens document in preview mode

### ISSUE THREAD

**Issue by traeok** [zowe/vscode-extension-for-zowe#2125]
**Describe the bug**

Currently, when double-clicking on a node in one of the tree views (data set members) to open it, the document is always opened in preview mode. This is inconsistent with VScode's standard behavior, where a single-click will open the document in preview mode, and a double-click operation will open a new permanent tab. 

This also results in subsequent double-click events to replace the current preview tab, which makes it difficult to open multiple data set members at once.

**To Reproduce**

1. Execute a search query for the data sets
2. Double-click on a data set member
3. Notice that the document view is still in preview mode.
4. Double-click on another data set member
5. Notice that the current preview tab has been replaced with the other node and its contents, rather than creating a new permanent tab.

**Expected behavior**

Double-clicking a data set member node should open a new, permanent tab that is not replaced after performing the same operation on another node.

**Desktop (please complete the following information):**

- OS: Windows 10
- Zowe Explorer Version: 2.6.0

**Comment by zFernand0** [comment]
GH seems to be having problems with closing issues linked to merged PRs
