### ISSUE TITLE
VS Code extensions for Zowe Explorer (README): broken links

### ISSUE THREAD

**Issue by sosadchuk** [zowe/vscode-extension-for-zowe#2128]
Hi,

Small readme issue.

[This doc](https://github.com/zowe/vscode-extension-for-zowe/blob/main/docs/README-Extending.md) has one of the links broken:
![image](https://user-images.githubusercontent.com/45584158/218729785-bc40161e-a40e-4fa5-b4ae-cb9b491147dc.png)

My guess it should lead to [V2 Conformance criterias](https://github.com/zowe/vscode-extension-for-zowe/blob/main/docs/Conformance%20Criteria/README-Conformance%20Criteria%20V2.md).

Upd:
Security API link under [getting started](https://github.com/zowe/vscode-extension-for-zowe/blob/main/docs/README-Extending.md#getting-started-with-extending-zowe-explorer) is also 404:
![image](https://user-images.githubusercontent.com/45584158/218755759-8873894e-f85a-4aac-8480-eea017b19856.png)

Upd2:
`ZoweVsCodeExtension.promptCredentials()` - this method marked as deprecated, I believe it should be replaced with `updateCredentials`.

Also some profile metadata examples look unclear due to `CoreUtils` class usage which is not a common component, I would anticipate and example based on `ICommandProfileTypeConfiguration[]` from `@zowe/imperative`.

Thanks,
Sergei.

**Comment by sosadchuk** [comment]
Thx @zFernand0!
Do you think it makes sense to update the following two references as well?

![image](https://user-images.githubusercontent.com/45584158/235907456-c49c81c9-b263-4597-88f7-01ad3944e467.png)

**Comment by zFernand0** [comment]
Hey @sosadchuk,
I do not think it makes sense to update those references or `promptCredentials(...)`.

The method that contains the call to `updateCredentials(...)` is indeed the `promptCredentials(...)`. Also, its hyperlink should highlight the following portions of the code.
https://github.com/zowe/vscode-extension-for-zowe/blob/5f8def3bbef90a2905068953c23fdab332889e2a/packages/zowe-explorer/src/Profiles.ts#L873-L883
