### ISSUE TITLE
Investigate displaying messages in status bar

### ISSUE THREAD

**Issue by ghost** [zowe/vscode-extension-for-zowe#213]
When editing a dataset in VS Code, a notification appears every time it saves that says "Dataset uploaded successfully." The frequency of these notifications seems undesirable when making a lot of edits, as they keep on popping up.

Perhaps this message could be showed in the status bar at the bottom of the screen instead. This would make the info less distracting, while still visible for users who want to see it.

**Comment by anokhikastiaIBM** [comment]
I am working on this issue.

**Comment by lauren-li** [comment]
@anokhikastiaIBM @JillieBeanSim @lauren-li will look into a systematic review of different actions across the Data Sets, USS, and Jobs view.

**Comment by lauren-li** [comment]
@anokhikastiaIBM For a starting point to review different Zowe Explorer actions, you can check out the Zowe Explorer usage documentation here: https://docs.zowe.org/stable/user-guide/ze-usage
