### ISSUE TITLE
Update Git command in top level readme

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/vscode-extension-for-zowe#2151]
The Git command in [the readme](https://github.com/zowe/vscode-extension-for-zowe#build-locally) is unnecessarily complex:
`git clone --origin=upstream --branch=main --single-branch https://github.com/zowe/vscode-extension-for-zowe.git`

* For `origin`, there is no need to override the user's default remote name.
* For `branch`, the "main" branch is the default one that will be cloned.
* The `--single-branch` flag creates a shallow clone. A deep clone is likely preferable unless you really know what you're doing.

The command could be simplified to:
`git clone https://github.com/zowe/vscode-extension-for-zowe.git`

**Comment by kushalnl7** [comment]
Can I move forward with solving this and creating a PR for it?

**Comment by t1m0thyj** [comment]
@kushalnl7 Sure, I've assigned you to the issue 🙂
