### ISSUE TITLE
Update info about deleting profiles in Zowe Explorer readme

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/vscode-extension-for-zowe#2152]
The usage tips in [the readme](https://github.com/zowe/vscode-extension-for-zowe/tree/main/packages/zowe-explorer#usage-tips) are outdated because the "Delete a profile" section only describes the behavior for v1 profiles. It should be updated to include v2 profiles.

**Comment by anaxceron** [comment]
Closing w/ [PR 2309](https://github.com/zowe/vscode-extension-for-zowe/pull/2309)
