### ISSUE TITLE
Unable to retrieve job info with special characters in jobname

### ISSUE THREAD

**Issue by juleskreutzer** [zowe/vscode-extension-for-zowe#2175]
**Describe the bug**
When retrieving job outputs for a job containing a special character in its jobname, for example an `#`, a HTTP 400 - Bad Request is returned. The underlying issue for this is probably the same as described in [zowe-cli#1596](https://github.com/zowe/zowe-cli/issues/1596). An API ML issue has already been created for this: [api-layer#2800](https://github.com/zowe/zowe-cli/issues/1651).

Both the Zowe CLI and API ML squad are already aware of this issue and community issue [community#1858](https://github.com/zowe/community/issues/1858) has been created for this.

**To Reproduce**
Submit a job like the following:
```jcl
//KT#ZOWE JOB NLD999910001,'KREUTZER,J. G1501065',CLASS=F,MSGCLASS=1,
// MSGLEVEL=(1,1),                                                    
// NOTIFY=ROSPHD,                                                     
// TIME=(00,40)                                                       
//TEST    EXEC PGM=IEFBR14";
```
Then try to retrieve job output for this job using Zowe Explorer.
When searching for jobs using the prefix filter `KT#*` this will return HTTP 400 error. When using filter `KT*` and opening the job `KT#ZOWE` this will also result in the HTTP 400 error.
See screenshot below for an example

**Expected behavior**

Job output can be retrieved in Zowe explorer

**Screenshots**
![image](https://user-images.githubusercontent.com/9107254/223706484-3227fda3-dc77-4883-8c39-781c08919479.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Zowe Explorer Version: V2.6.1
- (Optional) Zowe CLI Version: 7.10.4
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by zFernand0** [comment]
Thanks for sharing.
Once the CLI issue is address we should be able to update Zowe Explorer and get the fix in a future release 😋 
For now, I believe the CLI is using this Epic/issue to track the overall Special Character efforts
- https://github.com/zowe/zowe-cli/issues/1633

**Comment by VitGottwald** [comment]
The issue in cli https://github.com/zowe/zowe-cli/pull/1663 has been fixed.
