### ISSUE TITLE
host must not be blank

### ISSUE THREAD

**Issue by LeeMC2020** [zowe/vscode-extension-for-zowe#2179]
Type: <b>Bug</b>

Error: Profile Name Zosmf is inactive. Please check if your Zowe Server is active or if the URL and Port in your profile is correct.

Required parameter 'Host' must not be blank.

Extension version: 2.6.2
VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.86GB free)|
|Process Argv|--crash-reporter-id 5475f837-8c4a-4ee9-8445-274b6287719b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
vsctsb:30677850
pythonb192:30669360
funwalk2:30682974
pythonms35cf:30680985

```

</details>

**Comment by zFernand0** [comment]
Hey @LeeMC2020,
We appreciate the level of detail you provided, but I believe we do not require that much information in order to help with the issue.

Could you share the steps to reproduce this issue?

**Comment by LeeMC2020** [comment]
Profile/Dataset was corrupt. Thanks for your fast response!
