### ISSUE TITLE
USS file icon disappears after "Toggle Binary" action

### ISSUE THREAD

**Issue by t-o-m-e-k** [zowe/vscode-extension-for-zowe#218]
When browsing USS files the file icon will disappear after "Toggle binary" action. When toggled back to text it reappears.

**Comment by Colin-Stone** [comment]
Hi Tomasz. 
I think this is fixed already but I like to change the icon subtly at some stage so it is more obvious what the state is

**Comment by t-o-m-e-k** [comment]
Hi Colin,
Thank you for fixing it 👍
I like your idea of making the state visible.

**Comment by t-o-m-e-k** [comment]
Fixed
