### ISSUE TITLE
Jobs root folder not expanding automatically when search run [Consistency]

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#220]
The Job view is inconsistent with the other two Zowe views because it does not automatically expand when it has criteria applied to it. Either as owner/prefix or by manually applying search criteria. The user instead has to manually activate the twistie to see the results.

**Comment by Colin-Stone** [comment]
Seen this issue before. VSCode not refreshing root tree nodes because the label stays the same. Label is analgous to id btw. SO fix is to kid it into thinking it has changed to a different object. 

Jobs now working the same as USS/Datasets

**Comment by zFernand0** [comment]
Thanks Colin! 👍
