### ISSUE TITLE
Investigate ZE support for Multi-Factor Authentication

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#2210]
Zowe CLI show they support MFA in the [docs](https://docs.zowe.org/stable/user-guide/cli-using-integrating-apiml/).  Do we also support this and what is our User experience like if we do?

**Comment by kristinochka** [comment]
Also need to consider how Zowe CLI fits into the picture

**Comment by JillieBeanSim** [comment]
From testing:

example zosmf profile using API ML:

"port": 7554,
"basePath": "ibmzosmf/api/v1"

example base profile:

"host": "host.com",
"rejectUnauthorized": true

MFA to be used with API ML with JWT tokens

UX experienced:

1. User starts up VSC and Zowe Explorer then right clicks profile and selects login.
2. User is prompted for user/pass : MFA token to be entered as pass here
3. If successful, JWT token return and profile can be used.

**Comment by JillieBeanSim** [comment]
I have tested multiple scenarios with the zosmf profile and API ML.  
1. login return JWT token for further authentication ✅ 
2. use MFA token as password in profile ✅ 

Both of these scenarios worked well in Zowe Explorer and in the CLI.
To close this story, I think we need to document the support of MFA authentication with zosmf profiles when in use with API ML.
Another thing we could look at doing is make the prompt for password more generic, but I haven't found the word to cover all password, passphrase, passticket, JWT token, MFA token, and so on lol
