### ISSUE TITLE
Use Progress indicator wrapper around longer running function

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#223]
Consider using Progress Indicator around all search functions. Apart from anything else this is useful for showing that a search has indeed been kicked off rather than "Did it, Didn't it" situation.
Difficult to Unit test however so will require additional integration testing

**Comment by zFernand0** [comment]
Suggested items:
- Prevent subsequent requests to the same service if the initial one was not done.
- Add a temporary message that does not get logged on the notifications log (:bell: bottom right corner)

**Comment by Colin-Stone** [comment]
Implementing for all getList operations to begin with
