### ISSUE TITLE
USS FIles and Folders are not being populated into the Zowe menu

### ISSUE THREAD

**Issue by Murph1014** [zowe/vscode-extension-for-zowe#2232]
![Screenshot (183)](https://user-images.githubusercontent.com/125142140/231808680-e07558fd-4ff1-4347-ac14-4f29e597744a.png)
Type: <b>Performance Issue</b>

USS FIles and Folders are not being populated into the Zowe menu. I was in the middle of completing the CODE1 challenge and now all of the files in the  USS section of Zowe have disappeared. I keep getting a REST API error message that says the path is not valid. I've followed all of the steps 4 times to reestablish the link to Z. I've exited and reloaded the VS Code app. I've uninstalled the VS Code app from my local machine and nothing seems to work. The admins for this ZXplore program are very unhelpful and seem very uninterested in assisting me with this issue.

Extension version: 2.7.0
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.79GB (0.74GB free)|
|Process Argv|--crash-reporter-id 8eca49ee-3d06-4714-9793-556fbc8cae1e|
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    94	  8492	code main
    0	    69	   276	fileWatcher [1]
    0	   128	  2376	   gpu-process
    0	    91	  2836	   window
    0	    87	 14208	shared-process
    0	    72	 17684	     ptyHost
    0	   162	 14332	window [1] (Welcome to Z Open Editor - Visual Studio Code)
    0	    39	 14592	   utility-network-service
    0	    88	 17136	window [2] (Issue Reporter)
    0	   141	 20024	extensionHost [1]
    0	    73	 13240	     electron-nodejs ("C:\Users\cmur1\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\cmur1\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=20024)
    0	    26	 21176	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
vsccsb:30705552
functionswalk:30687959
pythonms35:30701012

```

</details>

**Comment by JillieBeanSim** [comment]
Hey @Murph1014, sorry for the delayed response.  The screen shot looks like the search filter is `z31396,zxp`.  When searching USS can you try entering a UNIX path for the search and see if that works, ie. `/u/userid`? Not sure if a UNIX path was given for the search in the challenge.

**Comment by JTonda** [comment]
Closing out.  Have not received response > 90 days.
