### ISSUE TITLE
zowe.ds.createDataset error - include dsname

### ISSUE THREAD

**Issue by ibmrcruicks** [zowe/vscode-extension-for-zowe#2236]
inexperienced users attempt to allocate datasets using un-/poorly-qualified names and receive VSCode error like

![image](https://user-images.githubusercontent.com/25483279/148052057-9823ff68-5d1f-4fca-82e1-dd32e8d26833.png)

this is difficult to diagnose and fix as the error does not specify the dsname causing the error

in some cases this is because the error is being generated from matser catalog update attempts for 'JCLLOG' instead of 'tsouser.JCLLOG'

can the offending dsname be included in the error message?

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
