### ISSUE TITLE
LOGON TERMINATED

### ISSUE THREAD

**Issue by LukeG-96** [zowe/vscode-extension-for-zowe#2241]
When trying to access and use USS files, at certain times I will get the following error:
![image](https://user-images.githubusercontent.com/126080946/233656180-4d9d6fb8-083d-4871-9def-af9a09cc4e06.png)

Can anyone help with why I might be getting this?

**Comment by JillieBeanSim** [comment]
Hey @LukeG-96 could we get a bit more information on the situation please.
What version of Zowe Explorer are you running?
Are you using user/password or token authentication and is the authentication methods being secured? Credentials managed securely is a default setting.
You mention this happens at certain times, are there any steps we can take to recreate the error?

**Comment by LukeG-96** [comment]
Hi @JillieBeanSim, thanks for responding! Currently we are running version 2.7.0. I am seeing this error also for the .json file
![image](https://user-images.githubusercontent.com/126080946/233688408-a272cd55-8c23-4c1c-9939-ba99da5da1c3.png)

![image](https://user-images.githubusercontent.com/126080946/233688438-937a2568-59b6-4932-937d-6a6b6afc004a.png)

I'm using user/password authentication.

This seems to happen when I try and click into a directory and sometimes when I try to click on a file to load. It will act like it's loading, and then throw that error. What's also weird is I can still edit some files and they will save.

Also, I'm only noticing this happens when trying to access USS through the zowe extension. I can access my Datasets and run jobs just fine.

**Comment by JillieBeanSim** [comment]
Hey @LukeG-96 we pushed out a fix for the setting value type, would you mind testing with 2.8.2 and let me know if you still are seeing these issues?

**Comment by LukeG-96** [comment]
Hello! So I believe I discovered the issue. We have an ACF2 Exit that is set up in our system. We have disabled that to test this and I am now able to use the USS portion on the zowe explorer in VSCode just fine!

Thank you for the support and being willing to help me through the issues!

**Comment by JillieBeanSim** [comment]
Thanks @LukeG-96 for the update, closing issue
