### ISSUE TITLE
Local filtering of JOBS tree

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#2256]
Zowe Explorer allows you to filter / select jobs when retrieving from the remote z/OS server.
For job administration needs, it could be interesting to add a local filtering at the display level in Zowe Explorer.
For example, filtering jobs that have a return code greater than or equal to 8.

**Comment by FALLAI-Denis** [comment]
[JOBS - Enhance management / new Zowe Explorer Extension for JOBS ](https://github.com/zowe/vscode-extension-for-zowe/issues/1597)

**Comment by JillieBeanSim** [comment]
Hey @FALLAI-Denis we were working on a generic type of local filtering to start but was curious about the example shared for jobs that have a return code greater than or equal to 8.  We are wondering if this would be presented from user via a regular expression or possibly another way you are envisioning?  TIA

**Comment by FALLAI-Denis** [comment]
Hi,

Regarding the use case for return codes greater than 8, here is a practical case:
- I have to recompile an entire application
- I submit dozens or hundreds of jobs
- I only want to be interested in error compilations
- so I only want to be interested in jobs with a return code greater than or equal to 8.
This case could be handled either by a filter (only make visible jobs which have a return code greater than or equal to 8), or by sorting (sort in descending order on the return codes).
What is important is to provide a means of finding these jobs in the mass of jobs.
I understand that a filter based on a regular expression can be complex to implement to filter on a "greater than or equal" expression.
Sorting on the return code will provide the same service.
