### ISSUE TITLE
Sort Jobs in Jobs tree

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#2257]
The list of jobs can be long and each user can have their preferences for finding / administering their jobs.
Some prefer to sort their jobs on the jobname, others on the jobid, others on the submission time (read time), others on the start time, others on the return code, and each JES QUEUE can be sorted on different criterias.
Job sorting must be local to Zowe Explorer and must not require a new job retrieval from the remote z/OS server.

**Comment by FALLAI-Denis** [comment]
[JOBS - Enhance management / new Zowe Explorer Extension for JOBS ](https://github.com/zowe/vscode-extension-for-zowe/issues/1597)

**Comment by JillieBeanSim** [comment]
closing with PR #2462
