### ISSUE TITLE
Prevent users being locked out when session has invalid credentials

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/vscode-extension-for-zowe#2262]
**Steps to Reproduce**
1. Add a profile to Zowe Explorer that has an invalid or expired password.
2. Try to perform an action like searching for data sets with this profile.

**Actual Behavior**
An error message is shown, but I can easily get locked out of my MF account if I try to perform more actions with the same profile. If I click the "Cancel" button, the error message may reappear several times indicating that ZE kept using the invalid credentials for subsequent API calls.
![image](https://user-images.githubusercontent.com/22344007/235136725-3d28f47f-1d6f-458c-b74e-146370e05bb6.png)

**Expected Behavior**
1. The "Check Credentials" button is renamed to "Update Credentials" to make it clearer and more consistent with the rest of the UI.
2. For actions that perform multiple API calls (e.g., list archived data sets), hitting an Invalid Credentials error should fail fast and abort the remaining API calls.

Split this into enhancement request #2374 
3. For sessions with invalid credentials, we could show a 🔒 overlay on the tree icon. This "locked" state could be stored persistently in VS Code, so it is remembered after restarting. When attempting to perform an action with a locked session, a prompt could be shown with 2 options: "Update Credentials" to update them in ZE or "Unlock" if the credentials have been updated elsewhere.

**Comment by phaumer** [comment]
I see this problem as well. It does not allow me to use any other profile either. Every time I click another profile it keeps prompting me about that expired one again. Workaround is to click Refresh.

**Comment by JillieBeanSim** [comment]
@t1m0thyj I am going to pull #3 out of this into its own enhancement and have this follow bug fix.  Will mention this in enhancement request for locking

**Comment by phaumer** [comment]
This is still not working for me. I am using 2.9.2 in Eclipse Che in which I do not want to store my password in the team config file, but use tokens. 
- I have two profiles and log on to both with tokens and run queries on both
- Then I log out of one 
- It immediately prompts me again for credentials
- When I click cancel it prompts me again when I use the other profile in any way. Then it become an endless loop that I cannot get out of. 
- When I give in an enter my credentials they are store in the the config file. If I used only tokens before that should somehow not happen and I should get warned about it. Perhaps, we need a setting in the profile that only allows storing tokens, but not credentials?
