### ISSUE TITLE
wrong team configuration file made and need to delete and replace it

### ISSUE THREAD

**Issue by hannahfltx** [zowe/vscode-extension-for-zowe#2269]
Type: <b>Bug</b>

trying to do the IBM, Learning COBOL Programming with VSCode, and into lab 2 it needs me to set up the team config file to their system and when I tried it created the wrong file, in attempting to fix it I copied the 

C: > Users > Admin > .zowe > {} zowe.config.json > {} profiles > {} ssh

and I think I broke it. Uninstalling and reinstalling the app/extention did not seem to fix it

Extension version: 2.8.0
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700 Eight-Core Processor           (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.91GB (26.29GB free)|
|Process Argv|--crash-reporter-id 3b42fd99-fa8c-4ed9-8321-c4f30785cc20|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30730054
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttextcf:30716743
fixshowwlkth:30730052

```

</details>

**Comment by JillieBeanSim** [comment]
Hey @hannahfltx, if the file is corrupted you can delete the file and start over.  Did you try deleting and creating a new?

**Comment by hannahfltx** [comment]
That wirked!

**Comment by JillieBeanSim** [comment]
awesome, glad to hear.  Thanks @hannahfltx
