### ISSUE TITLE
Corrupted text in USS Explorer

### ISSUE THREAD

**Issue by pablocarle** [zowe/vscode-extension-for-zowe#2270]
**Describe the bug**

In large directories the text can become corrupted, making it difficult to understand (screenshot attached)

**To Reproduce**

1. Open a directory with a large structure (levels, files, etc)
2. Open different levels

Screenshot:

![image](https://user-images.githubusercontent.com/3085193/236149588-71fb7a44-49a1-4e6d-9580-210ed093b455.png)

**Expected behavior**

It should not corrupt the text.

**Screenshots**

![image](https://user-images.githubusercontent.com/3085193/236149654-188ba9f4-080e-436d-80cd-5664ce09b0ec.png)

**Desktop (please complete the following information):**

- OS: MacOS 13.3.1
- Zowe Explorer Version: 2.8
- VSCode Version: 1.77.0
- (Optional) Zowe CLI Version: 7.10.3
- (Optional) Are you using Secure Credential Store? Yes

**Additional context**

It doesn't happen always, I don't have a 100% reliable way of reproducing the behaviour.

**Comment by adam-wolfe** [comment]
I believe this issue has been resolved. Please reopen the issue if the problem persists.
