### ISSUE TITLE
Provide VSX file via JFrog repository

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/vscode-extension-for-zowe#2274]
**Is your feature request related to a problem or limitation? Please describe.**
The VSX file for the Visual Studio Code Extension of Zowe is served mainly via the VS Code Marketplace. Some of the users are unable to download from the VS Code Marketplace. Currently, we were depending on the Open VSX repository, which was another option for our users to get the VSX. The Open VSX has issues with funding and will probably close as such we have to find a solution that allows us to serve the VSX file to users not able to access VS Code Marketplace. 

**Describe the experience you'd like**
When I find that I can't download from the VS Code Marketplace I will find in a documentation explanation on how to obtain the file from Zowe artifactory and the VSX file will be available there. 

**Describe alternatives you've considered**
- Figuring a way to support the Open VSX registry itself. 
- Provide the VSX file within the Release on the GitHub. 

**Additional context**
This request comes as a result of https://github.com/zowe/community/issues/1861 which outlines the information about the shutdown of the Open VSX registry.

**Comment by t1m0thyj** [comment]
Based on the https://blogs.eclipse.org/post/john-kellerman/emerging-open-vsx-working-group it seems like the Open VSX registry will be staying around 🙂 Closing this issue for now - we can reopen it in the future if finding an alternative to Open VSX becomes necessary again.
