### ISSUE TITLE
Allow users to type search query without having to first click "Specify Filter"

### ISSUE THREAD

**Issue by lauren-li** [zowe/vscode-extension-for-zowe#228]
Saved searches are working great, but our current implementation makes users go through an extra (and arguably unintuitive) step where they have to first click on "Specify Filter" before typing a new query:
<img width="601" alt="Screen Shot 2019-09-03 at 3 01 30 PM" src="https://user-images.githubusercontent.com/45975633/64201184-10761d00-ce5c-11e9-9030-202fa077e626.png">

It would be nice if we could create and run a new search query by default if the user just starts typing without having first clicked anything.

**Comment by Colin-Stone** [comment]
I agree this is not ideal but I don't see any alternative VSCode dialog available unless we consider having multiple menu items. One to directly access the specify filter dialog and another the history. Personally I feel what has been implemented is the best we could do.

**Comment by Colin-Stone** [comment]
One possibility is to fall into line with the jobs view which has the context menu to directly go to an editor. So the magnifying glass will link to the combined dialogs with QuickPick and Input Box and for quickly adding a search criteria we would have a menu say "Set Root folder" for USS or "Set Pattern" for datasets  
<img width="186" alt="Screenshot 2019-09-05 at 08 19 01" src="https://user-images.githubusercontent.com/30794003/64320235-fc463300-cfb5-11e9-9c5d-097299874dba.png">

**Comment by zFernand0** [comment]
I believe this was already addressed by the QuickPick functionality.
@Colin-Stone any thoughts?

**Comment by Colin-Stone** [comment]
Yes this functionality is now provided however Theia didn't support it so I had to leave the Theia implementation in the "unintuitive" way. 
However I believe there is a new update of Theia which may have addressed some of the discrepancies between it and VSCode. I know @phaumer was going to check into this.

**Comment by jellypuno** [comment]
This is working for theia

**Comment by zFernand0** [comment]
Any idea for the milestone on this one?
