### ISSUE TITLE
Submit Job from current VS Code Editor

### ISSUE THREAD

**Issue by VitGottwald** [zowe/vscode-extension-for-zowe#2295]
**Is your feature request related to a problem? Please describe.**

When I have a job open in a VS Code Editor, I would like to to submit the job right away.

**Describe the solution you'd like**

A context menu item "Submit Job" and/or command palette item "ZOWE Explorer: Submit Job". To submit the job from the currently open editor.

**Describe alternatives you've considered**

I can look up the job in the DATA SETS view, right click it and do the submit.

**Additional context**

Having to look up the job member in the DATA SETS view is inconvenient, it takes focus from the work being done in the editor. Also the user might have done a different search in the mean time in which case it has to set up the search through which it found the JCL currently in editor.

**Comment by VitGottwald** [comment]
The current content of the of the editor should be submitted without saving the PDS member.

**Comment by zFernand0** [comment]
Thanks for confirming @deltatager 
Knowing this information, is it ok to close the issue as completed?
cc: @VitGottwald

**Comment by zFernand0** [comment]
Happy to re-open the issue if there is an additional enhancements around this that we would like to consider.

**Comment by VitGottwald** [comment]
This is great, thank you @zFernand0 ! There are two more details:

- Since ZOWE Explorer knows where this dataset is being edited from, I would expect the submit not to prompt me at all. For submitting on a different LPAR I would expect to use a different command like `Submit JCL on ...`.
- Also submitting is a basic operation and it would be nice if it could be available as a button directly in the editor UI, for example like the SQL "Run" button in google cloud SQL editor https://storage.googleapis.com/gweb-cloudblog-publish/images/new_ui.max-900x900.png . Any thoughts about that?

I can open separate enhancement requests for this.
