### ISSUE TITLE
Add support for editing Zowe DS/USS/Jobs History on Local Storage

### ISSUE THREAD

**Issue by rudyflores** [zowe/vscode-extension-for-zowe#2304]
**Is your feature request related to a problem? Please describe.**

Once Zowe Explorer moves over to using local storage for storing persistent data such as History, it would be nice for Zowe Explorer to have the capability of editing the history values in a way where we can delete certain history items or clear the history entirely.

**Describe the solution you'd like**

A UI based solution for removing certain history items or all of them through a webview or editible JSON file

**Describe alternatives you've considered**

I tried editing the SQLite DB for local storage manually, but it is not as intuitive for a user to do this.

**Additional context**

**Comment by JTonda** [comment]
Related to #2418

**Comment by rudyflores** [comment]
Closing since the History webview was added to perform these changes to history items on Zowe Explorer
