### ISSUE TITLE
Add z/OS System Name (SMFID) to Zowe Explorer Jobs View

### ISSUE THREAD

**Issue by cybersorcerer** [zowe/vscode-extension-for-zowe#2308]
Hi,
if you need to monitor started tasks on a bigger sysplex it is currently hard to tell on which system in the sysplex the STC is running. Have a look at the screen shot below
![jobs-01](https://github.com/zowe/vscode-extension-for-zowe/assets/33680802/74c05920-e307-4860-b8e0-aa7eb3f0d884)
The STC AMICTL is running on 12 Members of the sysplex. If i need to have a closer look on one of them running on a certain LPAR, i have a hard time to find it. When you add the exec-data=Y flag to the z/OSM REST API request you will get among other useful data the field exec-member back. This will contain the name of the Plexmember (smfid) Take the contens of this field and add it to the jobs view for example like so:

JOBNAME(JOBID) - MEMBERNAME - STATUS
AMICTL(STC11223) - SYSX - ACTIVE

Thanks in advance

**Comment by awharn** [comment]
exec-data was added to the z/OSMF API's as part of 2.4.0 - if an earlier version of the API is used, it may cause errors. Something to keep in mind for this implementation, as it is passed as a query parameter on the URI.
https://www.ibm.com/docs/en/zos/2.4.0?topic=interface-list-jobs-owner-prefix-job-id

**Comment by cybersorcerer** [comment]
@awharn yes you are right, but this is IMHO not even a deal at all ... it is no problem to chrck the z/os version!

**Comment by SanthoshiBoyina** [comment]
Created PR - https://github.com/zowe/vscode-extension-for-zowe/pull/2629/
