### ISSUE TITLE
Safe Save Can Sometimes Fail

### ISSUE THREAD

**Issue by dkelosky** [zowe/vscode-extension-for-zowe#231]
Spun off from looking at #164. 

If I use "Safe save" and get a merge conflict:

![image](https://user-images.githubusercontent.com/14940561/64279456-16800280-cf1d-11e9-8412-71a96c8602b1.png)

Then edit the file in ISPF:

![image](https://user-images.githubusercontent.com/14940561/64279429-0536f600-cf1d-11e9-973f-6c97359256a9.png)

Then resolve the merge conflict, my ISPF edits are overwritten:

![image](https://user-images.githubusercontent.com/14940561/64279682-9d34df80-cf1d-11e9-88d3-26c14997a346.png)

**Comment by dkelosky** [comment]
Likewise, making a 1 char change in ISPF:
![image](https://user-images.githubusercontent.com/14940561/64279765-c3f31600-cf1d-11e9-9b5f-1f9dc505e99b.png)

Then doing a VS Code update:
![image](https://user-images.githubusercontent.com/14940561/64279798-d0776e80-cf1d-11e9-891e-bbb3868d9914.png)

The overwrite takes place without presenting a merge option.  

Perhaps we should look to enhance the API methods for the z/OSMF ETag usage.

**Comment by zFernand0** [comment]
Etag are now used.
Done!
