### ISSUE TITLE
Adjust Save Functionality

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/vscode-extension-for-zowe#232]
This issue should address #231 and #164. There are possible scenarios where data sets / USS files may be accidentally overwritten. Below is one suggestion on how to resolve this:

There should be one save operation and the operation should work as follows:
1. When a data set or USS file is retrieved, our VSCode extension should store the entity tag (for more information, search ETag on https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.1.0/com.ibm.zos.v2r1.izua700/IZUHPINFO_API_RESTFILES.htm).
2. Edit the file locally and click save
3. The extension should then push the data set or USS file back to the mainframe and supply the entity tag. If the resource has been unchanged, the ETag will match, and the update request will be completed.
4. If the resource has been changed, the ETag will not match, and the request will fail. The VSCode Extension could then pull the file locally (thus retrieving the new ETag) and allow the user to compare.
5. Upon the resolution of the issue, the VSCode extension then repeats the process starting at step 3.

Note: This issue may require additional development of the Zowe CLI node APIs.

- [ ] Research ETag
- [ ] Change the default Ctrl+S action to execute the safe save
- [ ] Remove the cloud upload icon + right click option
- [ ] Implement the ETag to the Node.js API + VScode extension
- [ ] Test in Node.js API
- [ ] Test in VScode

**Comment by zFernand0** [comment]
Done
