### ISSUE TITLE
next: Resolve circular dependency between `ZoweExplorerApiRegister` and `ZoweExplorerExtender`

### ISSUE THREAD

**Issue by traeok** [zowe/vscode-extension-for-zowe#2329]
**Is your feature request related to a problem? Please describe.**

With #2320 most of the circular dependencies have been resolved with the exception of a couple, namely the circular dep. between `ZoweExplorerApiRegister.ts` and `ZoweExplorerExtender.ts`. Since the one class is designed to provide an instance of the extender, and the extender class references functions in the API register, the circular dependency is difficult to remove without refactoring both classes and potentially breaking extenders.

**Describe the solution you'd like**

Refactor said classes to resolve the circular dependency - ideally in a way that doesn't break extenders.

**Comment by JillieBeanSim** [comment]
@traeok hasn't this been addressed on next branch?

**Comment by traeok** [comment]
@JillieBeanSim Yes, it looks like this was resolved on `next` - I'll mark this as completed 👍
