### ISSUE TITLE
VSC Compare function, not working with Favorites from Zowe Explorer

### ISSUE THREAD

**Issue by Felix-Braun** [zowe/vscode-extension-for-zowe#2335]
**Describe the bug**

The feature of Visual Studio Code to compare 2 files, if the file on the mainframe has changed in the meantime, doesn't work if you open a Member under Favorites. It overrides the file automaticly.
The Warning from Zowe Explorer does show up:

![image](https://github.com/zowe/vscode-extension-for-zowe/assets/125555172/cc0ce39b-893b-4c04-818b-3028d1dbb6dd)

**To Reproduce**

**Expected behavior**

Open Dialog to Compare the two Member.

**Desktop (please complete the following information):**

- OS: Windows 10
- Zowe Explorer Version: 2.8.2
- (Optional) Zowe CLI Version: 7.16.4
- (Optional) Are you using Secure Credential Store? Yes

**Additional context**

**Comment by Felix-Braun** [comment]
I believe I found the Problem.  It was caused by the Extension Zowe Explorer. I'm closing this Bug.

**Comment by Felix-Braun** [comment]
I'm sorry, I didn't look in which repo I was. I thougt I was in the IBM/vscode repo. Could you reopen the issue please.  This was my fault

**Comment by JillieBeanSim** [comment]
Hey @Felix-Braun can you verify if this was fixed with 2.9.0 release please?

**Comment by Felix-Braun** [comment]
Hello @JillieBeanSim no it was not fixed with release 2.9.0. But now if you open a Member over a Profile, it didn't ask me if I would Overrite or Compare, now it opened the Compare window automatically.

**Comment by JillieBeanSim** [comment]
Thanks for verifying @Felix-Braun.  Are you using zOSMF profiles or another profile type?

**Comment by Felix-Braun** [comment]
You're welcome @JillieBeanSim. Yes I'm using zOSMF profiles

**Comment by Felix-Braun** [comment]
Hello @JillieBeanSim what's the status of this issue?

**Comment by JillieBeanSim** [comment]
> Hello @JillieBeanSim what's the status of this issue?

Hey @Felix-Braun, just attached it to the PR for fix.

**Comment by Felix-Braun** [comment]
Perfect, thank you
