### ISSUE TITLE
Allow data sets and data set members to be renamed

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/vscode-extension-for-zowe#234]
Depends on zowe/zowe-cli#520

**Comment by jalel01** [comment]
#262 contains mockups for RENAME suggested by John Laplante

**Comment by MikeBauerCA** [comment]
Thanks to PR #314 I can now rename data sets. However, it appears that I still cannot rename PDS members. @CForrest97, please confirm.

**Comment by CForrest97** [comment]
Yeah I can confirm that renaming members hasn't been added yet. I will create a PR shortly for the zowe-cli to add API support for this before I add it here
