### ISSUE TITLE
Frequently unable to create a new PDS member using the FTP Plugin in VSCode

### ISSUE THREAD

**Issue by BJostmeyer** [zowe/vscode-extension-for-zowe#2350]
**Describe the bug**

I am using the Zowe FTP Plugin within VSCode to work with PLI code. When I need to create a new member in my "USER.TBENCH.CODE" Partitioned Dataset and try the "Create member" function in the VSCode popup menu - I frequently (not always) am unable to - and get an Error Message:

Error running command zowe.ds.createMember: A system error occured (read ECONNRESET). 
This is likely caused by the extension that contributes zowe.ds.createMember.

I have no clue how to fix - not how to debug. Opening another member in the same PDS still works at that time.

**To Reproduce**

Click on "Create new member" in the DATA SET section after selecting a Dataset (in my case USER.TBENCH.CODE)

Again - sometimes it works. But then it stops working. Even rebooting my Laptop does not help. I was thinking it is some issue with a missing session keep-alive , but then it would work after I reboot my Laptop. 

So - I am stuck. What can I provide to debug? Can you tell me the location of logs/traces that might help`?

**Expected behavior**

I need that calls like creating a dataset (member) works reliable

**Screenshots**

![image](https://github.com/zowe/vscode-extension-for-zowe/assets/36626099/dbc12c17-c916-4de6-acce-7be0c29ea83d)

![image](https://github.com/zowe/vscode-extension-for-zowe/assets/36626099/0eadd55f-6609-4773-93e9-c472e4bde3a5)

![image](https://github.com/zowe/vscode-extension-for-zowe/assets/36626099/376bdaf7-d5c0-44e3-8a96-f712a54b2a8e)

**Desktop (please complete the following information):**

- OS: Windows
- Zowe Explorer Version: 2.9.0
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store? Yes

**Additional context**

**Comment by BJostmeyer** [comment]
Hi.

I am still strugglinh with this plugin - its not only the above mentioned problem. I also found that changes to an existing file are not saved from the VS Edit dislog pressing Ctrl+s.

However - when I type the "zowe zos-ftp ..." command from the terminal window of the same editor instance - it works: 
![image](https://github.com/zowe/vscode-extension-for-zowe/assets/36626099/30f5bd90-5dee-426a-9f63-4265db6d47f4)

So - I can download the PDS member from the VSCode "Zowe Explorer" Window, Edit the file and save it with the "zowe zos-ftp ..." command from the same VSCode application instance

That is strange....

**Comment by VitGottwald** [comment]
I am running into this consistently in my environment. Willing to help with the reproduction scenario when someone from the squad would be interested in taking a closer look at this.
