### ISSUE TITLE
Zowe extension and side window isn't showing in VS code 

### ISSUE THREAD

**Issue by lnginyard** [zowe/vscode-extension-for-zowe#2369]
**Describe the bug**

<p> I utilize <strong>VS Code Insiders</strong> for my code editing experience and have successfully used the Zowe extension without any issues in the past but for some time now, the Zowe extension has not been showing up on the side window in VS Code Insiders, which would allow me to easily search data sets, add profiles, submit JCL, etc. I confirmed that the Zowe extension is installed globally and also updated to its latest version and can even view the IBM Z Open Editor Welcome window on start-up. Still, I would love to be able to utilize the features that the side window enables because it's super convenient for me. Also, the Zowe extension isn't showing up in my extension list on the side window either but I confirmed that it was installed and enabled globally. I checked the settings, disabled and re-enabled and also uninstalled and reinstalled but still no Zowe in the extension list nor on VS code side window.</p>

**Expected behavior**

I expect the Zowe extension to show on the side window so I can search data sets and add new profiles, etc. and I also hope to see the extension in my extension list.

**Screenshots**

<img width="1280" alt="vscodeinsiders" src="https://github.com/zowe/vscode-extension-for-zowe/assets/69459871/7327f6fb-1c30-4620-a907-0b7852dd4aee">

**Desktop (please complete the following information):**

- OS: MacOS
- Zowe Explorer Version: 2.9.1
- (Optional) Zowe CLI Version: 7.16.4
- (Optional) Are you using Secure Credential Store? 

**Additional context**

**Comment by recaph** [comment]
@lnginyard Given there are too many icons in the side bar.. just wondering if Zowe explorer icon got hidden under 3 dots icon (Additional Views) in side bar… (probably after a new vs code extension was installed)

You can click the 3 dots icon on side bar and choice zowe explorer. It will be added back to sidebar… VS Code hides icons when space is not sufficient 

I too use insiders but don’t see the issue.

**Comment by JillieBeanSim** [comment]
Hey @lnginyard, with this being the insiders release it may have something to do with the removal of keytar shim that we use for credentials storage.  We were [notified](https://github.com/zowe/vscode-extension-for-zowe/issues/2348) by the VS Code team around 2 weeks ago about the removal and are working as fast as we can to put out a fix before the August stable release.

**Comment by JillieBeanSim** [comment]
Hey @lnginyard I did grab the [latest insiders](https://code.visualstudio.com/insiders/) and installed z Open Editor and Zowe Explorer and don't see any issues atm, but the issue linked above could be disruptive for insiders users once released.

![Screen Shot 2023-07-07 at 3 05 04 PM](https://github.com/zowe/vscode-extension-for-zowe/assets/49491949/d6d24c43-798f-4060-9818-a940b3b574a4)

![Screen Shot 2023-07-07 at 3 05 45 PM](https://github.com/zowe/vscode-extension-for-zowe/assets/49491949/f8a887c8-86e9-4d1e-968e-24e57f261727)

**Comment by lnginyard** [comment]
@recaph

> @lnginyard Given there are too many icons in the side bar.. just wondering if Zowe explorer icon got hidden under 3 dots icon (Additional Views) in side bar… (probably after a new vs code extension was installed)
> 
> You can click the 3 dots icon on side bar and choice zowe explorer. It will be added back to sidebar… VS Code hides icons when space is not sufficient
> 
> I too use insiders but don’t see the issue.

<p> Of course the first thing I did was check to see if the Zowe Explorer extension was hidden under the three dots but sadly it is not. I also utilize VS Code and is able to see the Zowe Explorer extension on that platform but I prefer to use VS Code's Insider edition since I find it more compatible with my code edits and developing.
</p>

**Comment by lnginyard** [comment]
<p> @JillieBeanSim Thanks for sharing but this issue has been going on for quite some time for me and since I've exhausted all of my resources to fix the problem I have finally decided to open an issue about it. But I will try uninstalling and reinstalling the Insiders edition and see if that will finally rectify the issue. </p>

<p> I'll return with my result once I have completed the process.</p>

**Comment by lnginyard** [comment]
<p> After uninstalling VS Code-Insiders and reinstalling I am now able to utilize Zowe Explorer via the side window. Seems like an easy fix but I promise it didn't work when I tried it previously. Anyway, thanks for all of your help everyone!

**Comment by lnginyard** [comment]
Reopening this issue because as soon as VS Code-Insiders load and stabilize the Zowe explorer side window disappears again. I tried closing and reopening, still nothing so I uninstalled and reinstalled and was able to see the Zowe Explorer side window again but once the VS code Insiders loads all of the extensions the side window then disappears again. I can easily go and use Zowe Explorer's side window in VS Code but I continue to have to start a bisect and Zowe Explorer seems to be the extension causing the problem. It's really frustrating that I cant figure this out.

**Comment by JillieBeanSim** [comment]
@lnginyard can you look at the extension tab and see if vs code is disabling the extension? above you mentioned that it isn't showing in the kabob (3 dots), I am wondering if with the keytar shim removal if they check for it and disable extensions that use it.  The removal is planned for early July for insiders and in August's stable release.  Also, the insiders edition is nightly builds and vulnerable to breakages where the stable releases shouldn't.  If this is keytar shim related please keep an eye on the linked issue for release of the fix.

**Comment by lnginyard** [comment]
I can now see Zowe on the side window, it's odd that it's listed under my Tabnine extension, but at least I can locate and use it, so I'm closing this issue.
