### ISSUE TITLE
Tree refresh options broken in Jobs tree

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#2370]
**Describe the bug**

tree will not refresh with multiple options: view refresh, right-click refresh on session, close and open session, & redo search filter all broken and won't update tree

**To Reproduce**

1. open a search filter in Jobs view
2. submit job
3. try to refresh jobs view to show new job submitted
4. see it won't update with any way available

**Expected behavior**

video of behavior in v2.9.0

https://github.com/zowe/vscode-extension-for-zowe/assets/49491949/8a866bf2-aade-4172-9ec1-311daf81dc4f

**Desktop (please complete the following information):**

- OS: mac
- Zowe Explorer Version: 2.9.1
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by traeok** [comment]
@JillieBeanSim I made a quick PR to fix this because I don't want this to affect user productivity: #2371
