### ISSUE TITLE
Job tree applies filter before user submits filter criteria

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/vscode-extension-for-zowe#2376]
**Describe the bug**

When a user clicks the magnifying glass to apply a filter to a jobs tree node, a filter is applied before the user makes a selection or enters filter criteria.

**To Reproduce**

(I think the user needs to have some filter history for the jobs tree for this to happen)

1. Start VS Code
2. In the Zowe Explorer jobs tree, click the triangle to expand a session node (there should be no jobs listed)
3. Click on the node's magnifying glass to apply a filter
4. The filter menu will be shown in the VS Code entry bar/command palette area, but a filter will be applied immediately to the jobs tree node without the user selecting anything

**Expected behavior**

It should wait for the user to select/specify a filter to apply.

**Screenshots**

I click the magnifying glass, then the jobs tree immediately applies a filter and lists jobs:
![JobQueryIssue](https://github.com/zowe/vscode-extension-for-zowe/assets/122040687/426a443d-3ff3-4e1c-ace6-40fcfc9df278)

**Desktop (please complete the following information):**

- OS:
- Zowe Explorer Version: 2.9
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by traeok** [comment]
@adam-wolfe , just curious: does [this branch](https://github.com/zowe/vscode-extension-for-zowe/tree/fix/job-tree-fix) resolve your issue? I removed a redundant refresh call in the searchHistory function, and I wasn't able to replicate the behavior on that branch.

**Comment by adam-wolfe** [comment]
@traeok I am seeing this issue happening with the fix/job-tree-fix branch.

**Comment by traeok** [comment]
@adam-wolfe I found that there was another issue with the filtered flag being set too early. I tried testing with the expanded node and I'm hoping that it should be resolved in that branch with commit ebaf1ed4.

**Comment by adam-wolfe** [comment]
@traeok ebaf1ed resolved the issue.

**Comment by traeok** [comment]
> [ebaf1ed](https://github.com/zowe/vscode-extension-for-zowe/commit/ebaf1ed405b9bcc77c6b784f2a239878770ef314) resolved the issue.

@adam-wolfe Thanks for testing, much appreciated! I've linked it to #2371 .
