### ISSUE TITLE
Notify extenders when a change has been made to team config profiles

### ISSUE THREAD

**Issue by rudyflores** [zowe/vscode-extension-for-zowe#2385]
**Is your feature request related to a problem? Please describe.**

Our current Zowe Explorer code has a watcher for listening for any creation, update, or deletion of a team configuration profile which allows to pickup the latest changes when any of these actions are performed. For extenders this can cause issues since we don't provide a way for them to know if a change has occured on a Zowe Explorer profile.

**Describe the solution you'd like**

I would like for Zowe Explorer API to provide a watcher that extenders can subscribe to in order to receive the latest updates on available Zowe profiles, e.g: return the latest instance of the ProfilesCache upon making an update to a team config profile.

**Describe alternatives you've considered**

**Additional context**

**Comment by phaumer** [comment]
I would not expose a VS Code watcher directly, but abstract it by perhaps adding an optional operation to `ZoweExplorerApi.ICommon` for extenders to register a callback function for when the files change. That callback could provide a simple data parameter with an enum for the type of change etc.
