### ISSUE TITLE
Link to job not working

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/vscode-extension-for-zowe#239]
When submitting a job via right click -> submit job, I receive the following popup:
![image](https://user-images.githubusercontent.com/35504792/64528185-22e2d180-d308-11e9-8f75-684f376ce3d5.png)

However, clicking the link currently does nothing.

Zowe VSCode Extension Version 0.24.1

**Comment by Colin-Stone** [comment]
https://github.com/zowe/vscode-extension-for-zowe/pull/247

**Comment by zFernand0** [comment]
@Colin-Stone, should the job be expanded upon clicking the JOBID?

**Comment by MikeBauerCA** [comment]
Confirmed this is fixed with 0.25.0. Thank you!!
