### ISSUE TITLE
Extension not compatible with plugins that override CredentialManager

### ISSUE THREAD

**Issue by kubasobek** [zowe/vscode-extension-for-zowe#24]
When plugin which overrides CredentialManager is installed, profiles cannot be retrieved.  Used API gets securely stored fields from profiles as plain text.

Note form @AHumanFromCA on possible fix:
You will need to initialize the PluginManagementFacility to load the plugins and then you will need to pass some of the configuration variables into the OverridesLoader. There isn't a clean way to do this via the API.
The only advice I can give is that the VS code extension might just have to call Imperative.init and then everything might work.

**Comment by Colin-Stone** [comment]
@ChrisBoehmCA Was there a plan for this one?.

**Comment by ChrisBoehmCA** [comment]
It should be working now. I think we can close this
