### ISSUE TITLE
Remove `isTheia` function from ProfileUtils

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/vscode-extension-for-zowe#2412]
> I believe the `isTheia` function may be duplicate code, since we already have `globals.ISTHEIA` that can be checked to determine whether we're running in a Theia environment.
> Would it make sense to remove the `isTheia` function from this file and replace it with `globals.ISTHEIA`?

_Originally posted by @t1m0thyj in https://github.com/zowe/vscode-extension-for-zowe/pull/2410#discussion_r1283256379_

**Comment by ArvindParekh** [comment]
Hi! Is this still needed? I'd be happy to give this a go.

**Comment by traeok** [comment]
Hi @ArvindParekh - we're still looking to remove this function, so all contributions are welcome!

**Comment by ArvindParekh** [comment]
Understood, I'll get right on it.
