### ISSUE TITLE
[Placeholder] Support Migration Utility for Remote Credentials for Zowe Secrets SDK

### ISSUE THREAD

**Issue by awharn** [zowe/vscode-extension-for-zowe#2429]
Note: This is a placeholder enhancement request to gauge interest and collect feedback.

**Is your feature request related to a problem? Please describe.**

With the change to the Zowe Secrets SDK, I am no longer able to access all of my previously used credentials and it is prohibitively difficult for me to fill in all of the credentials again.

**Describe the solution you'd like**

I would like a migration utility extension that would allow the credentials on my local machine to be migrated to the remote machine so I can continue using them without needing to fill them in again.

**Describe alternatives you've considered**

I could fill in all of my credentials again, but it is prohibitively difficult to do so. Alternatively, I could work without storing credentials, or store them insecurely, but those are not permitted in my environment.

**Additional context**

**Comment by JTonda** [comment]
Issue left for several months with no updates so closing out as not planned.
