### ISSUE TITLE
Do we have unnecessary options in our context menus?

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/vscode-extension-for-zowe#243]
The following options may be unwanted in the context menus for data sets and USS files.
- Pull from Mainframe
- Safe Save, Merge if Necessary

`Pull from Mainframe` is available via a clickable icon. This action is also performed when clicking a file for the first time. If we want to keep the context menu option, perhaps we could remove the button that appears on hover.
`Safe Save, Merge if Necessary` is available via a clickable icon. This option will likely go away once #232 is resolved.

**Comment by zFernand0** [comment]
Should we consider people that don't use a mouse here?
I believe most/all the icons appear while hovering over the row. And I don't know what the behavior is when tabbing through the panel (datasets members for instance)

**Comment by MikeBauerCA** [comment]
Closing, will raise again if this becomes a larger issue.
