### ISSUE TITLE
Remote-SSH: Unable to load profiles on Zowe Explorer

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#2430]
**Describe the bug**

Unable to load profiles in Zowe Explorer due to loacked keyring on VSCode over Remote SSH

**To Reproduce**

1. Start a VSCode Remote SSH, Dev Container, or Tunnel where the keyring might be locked
2. Notice the following error when ZE loads
    ![image](https://github.com/zowe/vscode-extension-for-zowe/assets/37381190/ec3def53-69fc-47b0-beb2-7672f9bad051)

**Expected behavior**

I would expect ZE to be able to use the unlocked keyring that the terminal is using

**Desktop (please complete the following information):**

- OS: Headless Linux
- Zowe Explorer Version: 2.10.0 (`main` branch)
- (Optional) Zowe CLI Version: Any
- (Optional) Are you using Secure Credential Store? Yes

**Additional context**

This only applies to people using ZE in VSCode over Remote SSH

Also, this might help us figure out what to say in the Wiki and/or zowe-docs/ze-troubleshooting page(s)
- To automatically use the same unlocked keyring:
  - Export the `DBUS_SESSION_BUS_ADDRESS` in your `.bashrc`
  - Note: if this ENV variable changes, you will have to issue the following commands from the VSCode command palette:
    -  `> Remote-SSH: Kill Current VS Code Server`, and
    - `> Developer: Reload Window`
  - Source: https://stackoverflow.com/a/67403476 
  
---

- A better solution (which may not require a server kill):
  - Add the following lines to your `.bashrc` 
    ```shell
        export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/0/bus
        export GNOME_KEYRING_CONTROL=/run/user/0/keyring
        echo root | gnome-keyring-daemon -r --unlock --components=secrets
    ```
  - Both, Zowe Explorer and the Terminal should be able to access secrets in the same unlocked keyring

**Comment by VitGottwald** [comment]
I am not sure about the logic of using secure credential store, but I am running into this issue and all of my _secure_ sections are an empty array `secure: []`.

**Comment by VitGottwald** [comment]
Thank you @zFernand0 . This checkbox is not available in cloud IDEs like Strong Network due to the scope specification. I talked with @traeok about it yesterday and I believe he has a fix in mind to address it.

**Comment by zFernand0** [comment]
> Thank you zFernand0 . This checkbox is not available in cloud IDEs like Strong Network due to the scope specification. I talked with `@traeok` about it yesterday and I believe he has a fix in mind to address it.

The scope of the secure-setting was changed in this PR:  (thank you, Trae!)
- https://github.com/zowe/vscode-extension-for-zowe/pull/2438

As for the keyring doc, we will be adding something to the wiki and/or zowe docs-site.
