### ISSUE TITLE
Add ability to download/view/upload Datasets/Members/USS files in non-standard codepage

### ISSUE THREAD

**Issue by awharn** [zowe/vscode-extension-for-zowe#2435]
**Is your feature request related to a problem? Please describe.**

Sometimes, I have datasets, members, and untagged USS files that are not in my default 1047 codepage, and I am frustrated when I need to change my configuration to specify the encoding, then immediately remove it once I download my respective file.

**Describe the solution you'd like**

The ability to right click a dataset or USS file and download/open in a different codepage, and upload with the same codepage.

**Describe alternatives you've considered**

- Modify the configuration file, reload VSCode, download the dataset/member/USS file, remove the configuration file modification, reload VSCode again, and resume work
- Create a second profile targeting the same system with a different codepage

**Additional context**

**Comment by FALLAI-Denis** [comment]
Hi @awharn 

See also:
* #1589 

For USS files, Zowe Explorer should/must use the tagging declared on the file:
- no tag: IBM-1047 encoding apply
- presence of a tag: encoding declared by the tag apply, (to see if the auto-convert option must also be taken into consideration)

For datasets, Zowe Explorer should/must allow the user to specify the encoding when downloading and uploadling the dataset.
If the data set has been previously downloaded the uploading should be done with the same encoding as the downloading, but to see if it is necessary to authorize a change of encoding between downloading and uploading.

Zowe Explorer should also take into account the presence of a .zosattributes file or a .gitattributes file if the workspace is a cloned git repository.

**Comment by AnthonyGiorgio** [comment]
This behavior prevents me from editing files that are in ASCII format via zowe.  The [z/OS Open Tools](https://github.com/ZOSOpenTools/) team has their git repo setup to clone in ASCII format, meaning that I can't use zowe to work on that code directly.
