### ISSUE TITLE
VS Code-Zowe - Uploading zip file (binary) fails without error msg

### ISSUE THREAD

**Issue by englandl** [zowe/vscode-extension-for-zowe#244]
In VSCode 1.38.1, I have USS available in the Zowe tree and took the following actions 
* place focus on the directory 'newDirectory' 
* right mouse button to display the action pull-down 
* click on 'Upload files ...' 
* in the explorer that opened, I selected a simple text file (text.txt) 
* clicked on the 'Upload Files' button
* Ta-da! the text file was uploaded to the appropriate directory. (Although, there was no message confirming the operation.) 

HOWEVER! 
Doing the exact same set of steps as above, I selected a zip file (binary) instead of a text file, and the upload did not work! There was no error message stating it failed. Nor did the file ever reach my USS file system. 

Some side questions - I was surprised that there was an automatic conversion of ASCII to EBCDIC when the text file was transferred. Not all 'text-based files' such as XML, should be converted. 
Next, there was no confirmation of my action when uploading the text file, and no error msg when attempting to upload the binary file -- and no way to indicate it is a binary file and should be moved as such. 

Details of my VSCode level
Version: 1.38.1 (system setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by Colin-Stone** [comment]
Thanks for finding this issue @englandl . It certainly is a valid use case we would like to provide for. We have previously provided function for download which allows a user to switch to treat a file as binary but we need to come up with something that allows for uploads before the file is actually uploaded. Although I have indicated bug this is probably an enhancement but either way I think it's going to be very useful.

**Comment by stepanzharychevbroadcom** [comment]
Hello there, fix is done in the following PR, please, take a look.
https://github.com/zowe/vscode-extension-for-zowe/pull/459

**Comment by zFernand0** [comment]
This issue should be resolved in the upcoming release. 👍

**Comment by jellypuno** [comment]
PR #459
