### ISSUE TITLE
Double-click to open file in separate tab action

### ISSUE THREAD

**Issue by t-o-m-e-k** [zowe/vscode-extension-for-zowe#245]
Currently it's very hard to open and view files in separate tabs when working with VSCode Zowe extension.
In VSCode file explorer it is simply done by double clicking on a file.
It would be nice to have same functionality in the Zowe extension.

**Comment by zFernand0** [comment]
What a coincidence :smile:
https://github.com/zowe/vscode-extension-for-zowe/pull/242
Thanks for reporting @t-o-m-e-k
