### ISSUE TITLE
missing data set member attributes for rse type profile

### ISSUE THREAD

**Issue by patricktiu** [zowe/vscode-extension-for-zowe#2455]
**Describe the bug**

Only the member name is shown for the data set member attributes for rse type profile. Other attributes are missing.

<img width="778" alt="rse" src="https://github.com/zowe/vscode-extension-for-zowe/assets/24280442/9d67bf20-a890-4fa9-b411-1c054dfd1574">

**Expected behavior**

At least the following member attributes should be shown:
- member  name 
- creation Date
- modified Date and Time
- last modified by
- line count

**Screenshots**

Show member info from ISPF:

<img width="948" alt="ispf" src="https://github.com/zowe/vscode-extension-for-zowe/assets/24280442/5361be21-5cf2-4d32-8f98-9b430cf96809">

Showing PDS data set member attributes from zosmf type profile:

<img width="784" alt="zosmf" src="https://github.com/zowe/vscode-extension-for-zowe/assets/24280442/d7683654-7222-462b-8f08-0e0045c27b49">

**Desktop (please complete the following information):**

- OS: MacOS
- Zowe Explorer Version: 2.10.0
- (Optional) Zowe CLI Version: 
- (Optional) Are you using Secure Credential Store?

**Additional context**

rse api `/dataset/{pdsName}/memberAttrs` response for pds member attributes:
```
{
      "memberName": "SLEEP",
      "creationDate": "Thu Sep 22 00:00:00:000 EDT 2022",
      "lastModifiedDate": "Wed Jul 12 10:26:34:000 EDT 2023",
      "lastModifiedBy": "FEKUNI5",
      "lineCount": 7,
      "revision": "03",
      "lockOwner": ""
    }
```

**Comment by JillieBeanSim** [comment]
Hey @patricktiu thanks for raising the issue but this is extender specific as we only support zosmf and zftp profile types with this repository, IBM Z Open Editor is the extender that will cover rse profile support
