### ISSUE TITLE
Add compare actions for USS files and Data Sets

### ISSUE THREAD

**Issue by t-o-m-e-k** [zowe/vscode-extension-for-zowe#246]
The VSCode file explorer allows to compare files with 2 simple actions :
Right click on a file + "Select for Compare" / "Compare with Selected"

It would be really nice to have the same functionality directly in the Zowe extension.
Very useful for analysing configuration files / option members / code / ... for changes.

**Comment by MikeBauerCA** [comment]
As a workaround in the interim, once you have the files in an open editor tab, this functionality is available in the OPEN EDITORS section of the native VS Code Explorer. 

I agree it would be ideal to have this feature directly available in the Zowe extension.

**Comment by jelaplan** [comment]
I like the idea that @t-o-m-e-k wrote about. I agree there are workarounds but it seems like jumping through hoops. 

In VS Code Explorer, I can click on a file in a Workspace that isn't open and I can right click and select to compare.
<img width="254" alt="image" src="https://user-images.githubusercontent.com/3207260/75714385-9bb05e00-5c99-11ea-919c-4d80a1188a03.png">

In VS Code Explorer, I can click on a file or a data set in the Open Editors section and right click and select to compare.
<img width="265" alt="image" src="https://user-images.githubusercontent.com/3207260/75714241-57bd5900-5c99-11ea-9466-6b4ea7238aa6.png">

The latter provides a mechanism to compare a data set to another data set or to a file. But, I can't do this from the Zowe Explorer. If I right click on a data set, there is no option to select to compare. 

<img width="259" alt="image" src="https://user-images.githubusercontent.com/3207260/75714655-1ed1b400-5c9a-11ea-9455-586445769389.png">

**Comment by zFernand0** [comment]
Discussion outcome:
- We could start with Job output comparison.

**Comment by FALLAI-Denis** [comment]
See [File compare - Remote comparison based on "Super Compare" utility: ISRSUPC](https://github.com/zowe/zowe-cli/issues/1502)
