### ISSUE TITLE
Run a job from local JCL (from main Explorer View on Primary sidebar)

### ISSUE THREAD

**Issue by tbattiva** [zowe/vscode-extension-for-zowe#2475]
Hello there... 

I missed a lot this capability on my mainframer tasks.. what do you think about this suggestion?

**Is your feature request related to a problem? Please describe.**

As an editor working on JCLs on local machine the VS Code + Zowe Explorer has no way to run a job from a local machine JCL file on a z/OS system.
On a "distributed world", VS Code as a source code editor increases a lot the productivity and centralizes resources of a developer or even of a team running it locally. As a mainframer I can't run JCLs locally, but I believe it would be nice to have a way to explore this capability, sending local JCLs to execution direct from my local workspace (send the entire JCL, not just the action to execute one JCL saved on a dataset on a z/OS system).

**Describe the solution you'd like**

The solution enables to run a JCL direct on a z/OS system from the main Explorer View on Primary sidebar, from a context menu for example. It would be helpful because it is a quick way to create, update and execute local personal JCLs or even JCLs of processes of a team, hosted in a file server or in a repository. 

**Describe alternatives you've considered**

The following image illustrates it.

The "Z" folder opened on VS Code window can be any personal folder or a team's folder hosted in a file server. From a context menu the analyst/specialist can submit jobs directly on a default system or select the second option which would opened a Quick Pick to the user select a system from a list.

![image](https://github.com/zowe/vscode-extension-for-zowe/assets/45949559/ea61a57c-e441-4443-a09c-4d5816749a35)

**Comment by JillieBeanSim** [comment]
Hey @tbattiva we do have a way to run local JCL as a submitted job.  
In VS Code with a local JCL in the editor, open the command pallete (cmd+shft+p/ctrl+shft+p) and start typing Zowe to get the command `Zowe Explorer: Submit JCL` and select the profile to be used to submit the JCL and it will submit the local file as a JOB

**Comment by tbattiva** [comment]
Thank you @JillieBeanSim 
I didn't know it already exists. Very nice.
This was a little bit hidden. (lol)

**Comment by JillieBeanSim** [comment]
your welcome, going to reopen and add the menu items for better visibility on the functionality 😄
