### ISSUE TITLE
USS tree not updated with changes

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#2479]
**Describe the bug**

in the USS tree view can test any scenario with an expected change to the tree and see the tree doesn't update.  Can try delete file, copy/paste, etc.

- OS: macos
- Zowe Explorer Version: 2.11.0
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by traeok** [comment]
Completed in #2481
