### ISSUE TITLE
Remove CODEOWNERS

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/vscode-extension-for-zowe#2497]
**Describe the bug**

The repository contains a file named CODEOWNERS which is no longer valid for this project. It should be either updated or removed.

**Comment by zaidmstrr** [comment]
I want to work on the issue.

**Comment by zFernand0** [comment]
Hey @zaidmstrr,
thanks for showing interest in contributing to the codebase.
Feel free to submit a PR for this 😋
