### ISSUE TITLE
Ensure Extension works in Eclipse Theia

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/vscode-extension-for-zowe#251]
Eclipse Theia directly supports VS Code extensions. The Zowe extension should function properly in the Theia environment and this is a prereq to the VSCode GA1.0 MVP milestone. I understand some work has already been done in this area and we would like to claim ongoing support for this objective.

- [x] Test extension in Theia environment and open issues for any incompatibilities

- [ ] Document how to include the extension in a Theia environment as part of the README

Please discuss any findings on this thread.

**Comment by MikeBauerCA** [comment]
@phaumer, would you be able to assist with this initiative?

**Comment by Colin-Stone** [comment]
> Just an FYI. There are 2 theia environments that we should be testing on. 1 is the theia browser and the other one is the theia inside the che workspace. They yield different results.

@jellypuno Thanks for highlighting this. Does this mean the observed behavior of the extension is different between the two environments or simply that we have two different scenarios?.

**Comment by jellypuno** [comment]
> @jellypuno Thanks for highlighting this. Does this mean the observed behavior of the extension is different between the two environments or simply that we have two different scenarios?.

@Colin-Stone What we have seen so far is that the behavior of the extension is different between the two environments.

**Comment by MikeBauerCA** [comment]
Created separate issue for documentation #343.
