### ISSUE TITLE
Submit as JCL context menu option bugs

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#2541]
1. shows in context menu of OUTPUT channel, expect it not to.
2. shows with multi-select, expect it not to. it will open all selected in editor then it only submits the first chosen

<img width="724" alt="Screen Shot 2023-11-03 at 4 37 10 PM" src="https://github.com/zowe/vscode-extension-for-zowe/assets/49491949/708825d1-6027-4274-af22-e89af079a2a0">

**Comment by traeok** [comment]
Fixed in #2542
