### ISSUE TITLE
CTRL + Y no longer works as expected in VS Code

### ISSUE THREAD

**Issue by jirimosinger** [zowe/vscode-extension-for-zowe#2543]
**Describe the bug**

Edit History tab opens whenever I try to use a default VS Code shortcut for Redo (CTRL + Y).

**To Reproduce**

1. Open any text file in VS Code
2. Write any letter
3. Hit `CTRL + Z` for undo
4. Hit `CTRL + Y`
5. Redo operation doesn't happen anymore. `Edit History` tab opens instead.

**Expected behavior**

When pressing `CTRL + Y`, the default VS Code shortcut for redo should work instead of Edit History tab being opened

**Desktop (please complete the following information):**

- OS: Windows 10
- Zowe Explorer Version: v2.12.0

**Comment by traeok** [comment]
Fixed in #2545
