### ISSUE TITLE
Sorting by date/time shows "current" date for members without ISPF stats

### ISSUE THREAD

**Issue by VitGottwald** [zowe/vscode-extension-for-zowe#2552]
When I open a PDS that has members that do not have ISPF stats, the sorting feature in ZOWE Explorer will show the "current" date for such members.

**To Reproduce**

1. Open a PDS with members that do not have ISPF stats
2. Sort them by 'Date Modified'

**Expected behavior**

Members without ISPF stats do not show the date/time greyed out text at all

**Screenshots**

<img width="1205" alt="image" src="https://github.com/zowe/vscode-extension-for-zowe/assets/19686979/caba5d22-9ad6-4e0e-acbe-a62db2adbe1b">

**Comment by traeok** [comment]
This was a side-effect of passing `undefined` to the `dayjs` date parser instead of passing `null` when the date is invalid. Since this was a quick change, I've addressed this in PR #2553 and the fix will be included with 2.12.1

**Comment by VitGottwald** [comment]
Wow, that was quick @traeok . Thank you very much!
