### ISSUE TITLE
`next`: Localized strings are no longer visible in Theia

### ISSUE THREAD

**Issue by traeok** [zowe/vscode-extension-for-zowe#2558]
**Describe the bug**

I've been investigating the failing Theia tests on the `next` branch and have found the source of the issue.

Commits ef72d44 and before work fine in Theia - localized strings show as expected.
When testing commit https://github.com/zowe/vscode-extension-for-zowe/commit/3edd22fd8676fc60504f163b3f4de4e04b46432d, the strings in Theia are broken. Any commit after this one exhibits the same behavior.
 
**To Reproduce**

- Build commit ef72d44 and install the VSIX in Theia
  - Notice that strings show as expected with this commit's VSIX
- Build any commit >= 3edd22f
  - Notice that the placeholder strings for localization are now showing (e.g., `%displayName%, %zowe.ds.explorer%`) instead of the localized strings themselves

**Expected behavior**

Localized strings should show in Theia without any placeholders.

**Screenshots**

| <= ef72d44 | >= 3edd22f |
| --------- | --------- |
| ![image](https://github.com/zowe/vscode-extension-for-zowe/assets/86500639/d2bcad44-d1a4-41c3-859c-940c1231ac57)| ![image](https://github.com/zowe/vscode-extension-for-zowe/assets/86500639/f01a85cd-680e-4e46-b3f1-7853886f66ae) | 

**Additional context**

This seems related to the package.json import statement in `ZoweLocalStorage.ts` in commit 3edd22f.

**Comment by JillieBeanSim** [comment]
closing as we decided to drop Theia IDE support with v3
