### ISSUE TITLE
Loading profiles not working when Zowe CLI is installed via MSI

### ISSUE THREAD

**Issue by tucker01** [zowe/vscode-extension-for-zowe#256]
If you have installed Zowe CLI via the MSI and do NOT have a version of Node.js installed on your machine, the vscode extension cannot load profiles. 

**Technical details:**
To enable the usage of the secure credential store, the vscode extension spawns a node process to load profiles. In summary, Keytar is used to access the operating systems secure credential vault and is built locally for the version of Node.js you have installed. vscode (electron) packages a version of Node.js that is most likely different than the version you have installed globally. This is why spawning a Node process is necessary to access the credentials. 

**Workaround:**
If you globally install the same version of Node.js that is packaged with the MSI installer, you can get around the problem.

**Comment by MikeBauerCA** [comment]
Note that this appears to be true even if you are not using the secure credential store.

**Comment by pdubz3** [comment]
I've had this problem and done some testing of different scenarios when installing the latest version via the MSI.  My conclusion is that the VS Code Extension appears to work just fine as long as I don't use the secure credential store plugin to manage my credentials.  I've also concluded that even having node pre-installed at the same version packaged with the MSI installer (10.16.1) the VS Code Extension will not work properly when SCS is used.  It works fine without SCS.

**Comment by Colin-Stone** [comment]
The current version of the VSCode extension incorporates the `@brightside` version of CLI rather than `@zowe` which I believe provides the SCS plugin. Should we reconsider this situation and could this also have an impact?.

**Comment by zFernand0** [comment]
> The current version of the VSCode extension incorporates the `@brightside` version of CLI rather than `@zowe`. Should we reconsider this situation and could this also have an impact?. We did have a similar problem before.. #157

It makes sense why someone could think that this issue is similar to #157 since there is no way of telling what version of the CLI is installed when using the MSI unless someone explicitly says it.

As a matter of fact, **the MSI being reference in this issue is installing `@brightside/core@lts-incremental`**

Apologies in advance for the confusion

**Comment by jellypuno** [comment]
@zFernand0 I wonder if this is still an issue since we removed the CLI dependency?

**Comment by zFernand0** [comment]
You are absolutely right.
No CLI dependency and not brightside/core anymore.
Closing!
