### ISSUE TITLE
Ctrl + Y ("redo") Keyboard Shortcuts has no "When" Close

### ISSUE THREAD

**Issue by dkelosky** [zowe/vscode-extension-for-zowe#2563]
In code editors (and most applications), `Ctrl + Z` and `Ctrl + Y` are "undo" and "redo" respectively.  It looks like Zowe Explorer has added a Keyboard Shortcut to overtake `Ctrl + Y` without a When clause specified:
![image](https://github.com/zowe/vscode-extension-for-zowe/assets/14940561/95486e18-23a6-45b6-86ae-9fa59591d83d)

When editing a file that has no connection to Zowe Explorer (or mainframe), if you use `Ctrl + Y`, the "Edit History" window now loads:
![image](https://github.com/zowe/vscode-extension-for-zowe/assets/14940561/a7f7e22a-57f1-497c-89ef-d53a06a88f92)

I believe a different Keyboard Shortcut or a When clause should be added in this case.

**Comment by slavek-kucera** [comment]
#2543 #2545

**Comment by zFernand0** [comment]
I agree that the default should be something that won't impact common operations (like redo Crtl+Y, or Replace Ctrl+H, or ReplaceAll Ctrl+Shift+H)

How about `crtl+alt+H`? 😋

**Comment by rudyflores** [comment]
@dkelosky by any chance do you still have `v2.12.0` installed? This shortcut was changed to `ctrl/cmd + alt + Y` in `v2.12.1` to resolve this issue :)

**Comment by adam-wolfe** [comment]
This should be resolved by the 2.12.1 release.
