### ISSUE TITLE
Schema parameter not really optional

### ISSUE THREAD

**Issue by gejohnston** [zowe/vscode-extension-for-zowe#2575]
**Is your feature request related to a problem? Please describe.**

When a ZE extension uses an existing API to register its profile types, a 'schema' parameter is identified as optional. Unless that 'schema' parameter is specified, the ZE extension cannot later retrieve its profiles.

**Describe the solution you'd like**

Clarify the API requirements.

**Describe alternatives you've considered**

- Make the schema parameter required.
- If there are legitimate use-cases for not supplying the 'schema' parameter, document the API to identify when and why the caller should supply a 'schema' parameter. 

**Additional context**

**Comment by JillieBeanSim** [comment]
adding v3 label since change from optional to required will be a breaking change but agree it should be done
