### ISSUE TITLE
When Copy's in Member not found, ABEND S2222

### ISSUE THREAD

**Issue by Felix-Braun** [zowe/vscode-extension-for-zowe#2589]
**Describe the bug**

When I open a member and have in the zapp.yaml multiple Librarys for the Copy's / Includes, the profile created in SPOOL gives the RC: ABEND S222 and creates a new Profile until the right Library is found. (Sometimes, multiple librarys and copy's are searched in one Profile, but most of the time only one member, is searched in one Library). 

e.g. I opened a COBOLE Member, and it searched for a copy in a library, after that, the JOB gave a RC: ABED S2222 and created a new one, and searched the next library.

![image](https://github.com/zowe/vscode-extension-for-zowe/assets/125555172/61aecd03-5fec-4386-b430-9f039c5f3f64)

**To Reproduce**

1. Login to Zowe
2. Open a Library then a Member.
3. Go to SPOOL
4. See the Output

**Expected behavior**

Creating one Profile in SPOOL

**Screenshots**
The 3 active JOBS are one from TSO and the other 2 created by ZOWE. All the other ones with ABEND S222 were created by ZOWE in a span of seconds:
![image](https://github.com/zowe/vscode-extension-for-zowe/assets/125555172/0f3767b7-b0c2-4066-a481-c7521ba4ec60)

![image](https://github.com/zowe/vscode-extension-for-zowe/assets/125555172/b25c27ce-3f65-4388-a0e8-42fe3ff8fd6f)

**Desktop (please complete the following information):**

OS: Windows 10
Zowe Explorer Version: 2.12.2
(Optional) Zowe CLI Version: 7.18.9
(Optional) Are you using Secure Credential Store? Yes

**Comment by Felix-Braun** [comment]
Which information do you need? @adam-wolfe

**Comment by adam-wolfe** [comment]
Hi Felix, @JillieBeanSim found this issue in the Z Open Editor repository that provides an explanation of the problem and a potential workaround: https://github.com/IBM/zopeneditor-about/issues/27#issuecomment-595605984 

Please let us know if this is different from the behavior that you are seeing.

**Comment by JTonda** [comment]
An issue was raised with zosmf api team and a fix will be issued from them.

**Comment by Felix-Braun** [comment]
Hello,
I found the Solution in [ibm/](https://github.com/IBM/zopeneditor-about/issues/134#issuecomment-1515039725).
It's due to the parallel downloading of Copybooks and Includes.

So this Issue can be closed.
