### ISSUE TITLE
Dataset creation fails when specifying `secondary` space

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#2591]
**Describe the bug**

z/OSMF throws an error when `secondary` space is provided via Zowe Explorer

This happens if we send the secondary parameters as a string in the payload.

**To Reproduce**

Create a dataset and modify the value of the secondary space

**Expected behavior**

To be able to create the dataset

**Screenshots**

```
        'HTTP(S) error status "500" received.\n' +
        'Review request details (resource, base path, credentials, payload) and ensure correctness.\n' +
        '\n' +
        'Protocol:  https\n' +
        'Host:      my.cool.host\n' +
        'Port:      12345\n' +
        'Base Path: \n' +
        'Resource:  /zosmf/restfiles/ds/USER..PUBLIC.TEST\n' +
        'Request:   POST\n' +
        'Headers:   [{"Accept-Encoding":"gzip"},{"X-CSRF-ZOSMF-HEADER":true}]\n' +
        `Payload:   '{"alcunit":"CYL","dsorg":"PS","primary":1,"recfm":"FB","blksize":6160,"lrecl":80,"secondary":"1"}'`
```

![image](https://github.com/zowe/vscode-extension-for-zowe/assets/37381190/df84eaa5-9cda-492b-a1a0-8b569926afe8)

**Desktop (please complete the following information):**

- OS:
- Zowe Explorer Version:
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

[#zowe-explorer-vsce comment](https://openmainframeproject.slack.com/archives/CUVE37Z5F/p1700577739241689) by _**Sakshi Bobade**_

Hi all,
I have been working on [this](https://jira.rocketsoftware.com/secure/CustomerView.jspa#caseDetail/500Do00000EtAJkIAN) customer case where the customer is not able to create the dataset in vscode extension
I have been experimenting with certain combinations of attributes and I find that TRK and CYL are the only allocation units supported in the vscode extension.
And we get the error creating the dataset whenever we try to set the secondary quantity.
```
Error encountered when creating data set. Error: z/OSMF REST API Error: |
 Rest API failure with HTTP(S) status 500 | category: 7 | rc: 261 | reason: 0 | |
```
Any dataset(TRK/CYL) without the secondary quantity is successfully created.
Does anyone have an idea about this.
I would appreciate any help on this.
Thank you.

**Comment by zFernand0** [comment]
@t1m0thyj suggested that it might be due to the fact that `secondary` is not part of the default templates, but `primary` is 😋

**Comment by timgerstel** [comment]
Any update on this @zFernand0 ? Thank you!

**Comment by zFernand0** [comment]
Hey @timgerstel,
Apologies for the delay, the PR was just opened, and we might be able to include it in the next Zowe Explorer release 😋

**Comment by timgerstel** [comment]
Thank you very much Fernando! Really appreciate the update and the fix🙏
