### ISSUE TITLE
Problems with local name of files.

### ISSUE THREAD

**Issue by jgomezle** [zowe/vscode-extension-for-zowe#26]
When attempting to run a shell task, the following error occurs due to the profile name in square brackets:

Line: 1 Char: 114
+ ... -extension-for-zowe-0.8.3\resources\temp\SIS.JGL.FTES(HELLOW)[zoszdt]
+                                                                   ~
Array  index expression is missing or not valid
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingArrayIndexExpression

Opearating System is Windows 10

**Comment by ChrisBoehmCA** [comment]
Hi, 

Can you explain a little more about when you encounter this error? Do you get this in your terminal, or in a VS Code pop up error? if It's in your terminal, does surrounding the filename with quotes help?

**Comment by jgomezle** [comment]
This error appears in the Visual Studio Code terminal window when I try to run a test task, defined in tasks.json as follows:
    "tasks": [
        {
            "label": "pruebas",
            "type": "shell",
            "command": "type",
            "args": [
                "${file}"
            ],
            "presentation": {
                "clear": true,
                "reveal": "never"
            },
            "problemMatcher": []
        },
It is a simple test that should show the source code reading the local file corresponding to a member of a PDS. 
When a shell task is defined in tasks.json,  Windows uses the Powershell command interface, which is the one that has the problem with the profile name in brackets.

**Comment by ChrisBoehmCA** [comment]
I'm not that familiar with creating tasks. Is it possible for you to try surrounding the file argument with quotes like `"\"${file}\""` or will that break your task?

**Comment by jgomezle** [comment]
No, it is not possible to add quotes. It does not recognize it as a filename.
It clearly seems an incompatibility of the nomenclature with Powershell.
Fortunately I have found out that I can use "process" instead of "shell" with the right changes and then it works.

**Comment by Colin-Stone** [comment]
Will be addressed by https://github.com/zowe/vscode-extension-for-zowe/issues/50

**Comment by Colin-Stone** [comment]
Addressed for dataset files in v0.23.0
