### ISSUE TITLE
Improve the CLI error messages for wrong password

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#261]
The following shows the message that a user gets when they try to call a CLI command against z/OSMF and use an incorrect password. By reading this, it isn't apparent that that is the problem.  It seems like we could add a basic message to the top that says incorrect password or called it a password error instead of a command error. 

$ zowe files list ds "johndoe.public.*"
**Command Error:**
z/OSMF REST API Error:
Rest API failure with HTTP(S) status 500
rc:       16
reason:   1141
category: 2
message:  login: _msg_rcv_timed() error on: TsoServerConnection(USER=IZUGUEST, ASID=0x01d9, QID=0x0034003a), QID=0x0034003a

**Error Details:**
HTTP(S) error status "500" received.
Review request details (resource, base path, credentials, payload) and ensure correctness.

Host:      lapar123.lvn.xcom.net
Port:      1443
Base Path: 
Resource:  /zosmf/restfiles/ds?dslevel=johndoe.public.*
Request:   GET
Headers:   [{"X-IBM-Max-Items":"0"},{"X-CSRF-ZOSMF-HEADER":true}]
Payload:   undefined

**Comment by ChrisBoehmCA** [comment]
Just wanted to note, if z/OSMF is configured correctly, you get a 401 response always for incorrect passwords. The 500 error here is due to z/OSMF configuration problems.

**Comment by VitekVlcek-Broadcom** [comment]
@ChrisBoehmCA are there any details on what could be wrong?

**Comment by spufidoo** [comment]
I'm getting the exact same message when using the VS Code extension, but using the CLI, I can connect perfectly.
Why would this be?

**Comment by dogboydog** [comment]
Hi @spufidoo . Have you restarted VSCode  since making any changes to your profile? Can you issue the  `zowe files ls ds "hlq.here"` command or are you just trying `zowe zosmf check status` ? Please note, `zowe zosmf check status` does not check the validity of your credentials. Only your other connection  details like host, port, etc.

**Comment by spufidoo** [comment]
Yes, I can do zowe files ls ds "hlq.here" successfully from the command line, but when I click on the magnifying glass against an LPAR in the Zowe extension in VSC, I get that error message popping up.

**Comment by ChrisBoehmCA** [comment]
Can you try the same command with the `-a` flag and see if it works?  `zowe files ls ds "hlq.here" -a`. That's the exact API that the extension uses

**Comment by spufidoo** [comment]
> Can you try the same command with the -a flag and see if it works?  zowe files ls ds "hlq.here" -a. That's the exact API that the extension uses

Yep - that worked, no problem.
I was wondering whether it was a VSC json config file issue.
