### ISSUE TITLE
Allow Copy and Rename members in the VS Code 

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#262]
I created some wireframes around copying and renaming data-set members in VS Code. I put these in Box. I'd love to get feedback - love it, hate it, change it, etc. 
https://ent.box.com/s/cejdls7bl0ab1nlnjlu8iahoit25kpoa

**Comment by MikeBauerCA** [comment]
Thank you for the wireframes!! 
We have linked to this issue from the related issues. Closing as duplicate.
