### ISSUE TITLE
Submit as JCL: check for profile before presenting quick pick

### ISSUE THREAD

**Issue by traeok** [zowe/vscode-extension-for-zowe#2628]
**Is your feature request related to a problem? Please describe.**

Currently, the "Submit as JCL" in-editor context menu option does not check if the file in the editor is a part of Zowe Explorer's temp files. We also show the quick pick even if a user only has one profile in their Zowe config.

**Describe the solution you'd like**

Since we store temp. files based on their profile, we could determine the profile without spawning a quick pick for user input.

In addition, for users with only one profile in their config: Since the user would only have one profile, we could avoid the quick pick altogether and just use their single profile to submit the job.

**Additional context**

_Quick pick w/ only one profile:_
![image](https://github.com/zowe/vscode-extension-for-zowe/assets/86500639/a033c618-3529-4066-8857-40c218d5f3e5)

**Comment by zFernand0** [comment]
- Fixed by #2646
