### ISSUE TITLE
Filters behavior wording and reworking

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#263]
Feedback from https://github.com/zowe/vscode-extension-for-zowe/issues/102

~~1. For consistency, should label "Search for Jobs using attributes" be "Search Jobs Using Attributes"?
   Compare to casing and style of "Search Data Sets by Entering Patterns".
2. Label "Choose "Create new..." to define a new filter alternatively select a previously defined filter" needs to have a comma, be two sentences or rephrased
   eg. "Choose "Create new..." to define a new filter or select a previously defined filter".~~
3. When creating a new filter and entering the owner, it allows for multiple words eg. "COCKERM BLA" when only one word is actually used.

**Comment by Colin-Stone** [comment]
Reworded for points 1 and 2 rather than miss them later. Issue still good as a first issue adding the callback function

**Comment by thushanwasa** [comment]
Can I call

**Comment by parschina** [comment]
[واردات از چی](https://parschina.ir/)

**Comment by katelynienaber** [comment]
Changes were pushed today (pull request [#435](https://github.com/zowe/vscode-extension-for-zowe/pull/435))
