### ISSUE TITLE
Offer a file transfer tool not linked to "data sets", "Unix System Services", "Jobs" tree view explorers - Alternative to IND$FILE

### ISSUE THREAD

**Issue by FALLAI-Denis** [zowe/vscode-extension-for-zowe#2635]
**Is your feature request related to a problem? Please describe.**

Most 3270 terminal emulations provide one or more file transfer functions between the mainframe and the workstation, most often based on IND$FILE, sometimes on FTP.

Even if it is completely obsolete, the IND$FILE utility remains quite widely used (at least this is the observation made today in our context).

Using Zowe Explorer requires abandoning a 3270 emulator, therefore the abandonment of IND$FILE which remains linked to the use of a 3270 emulator.
However, the need to transfer files between the mainframe and the workstation continues.

The "Data sets", "Unix System Services" and to a certain extent "Jobs" views do not directly respond to this need, (even if they can indirectly respond to it): it is not a question of editing a mainframe file locally, but of exchanging files between the workstation and the mainframe.

These views are also limited today to the management of "text" files, containing only displayable characters (transposable in various encodings).

**Describe the solution you'd like**

Zowe Explorer should offer a file transfer solution independent of the "Data Sets", "Unix System Services" and "Jobs" views.

Through a dedicated view, probably to be activated by the VS Code command palette, it would be necessary to be able to indicate:
* the direction of the transfer: sending (upload) or receiving (download)
* the name and location of the local file (on the workstation)
* the remote system: either in the form of the identifier of a Zowe profile to use, or in the form of host, port, etc. parameters.
* the type of the remote file: data set, USS file, or even job sysout (only for reception in this case)
* the dataset name, USS file path, job name and sysout identifier
* the encodings to be used both on the mainframe and locally, (not necessarily the encoding declared in a Zowe profile used and not necessarily the UTF-8 encoding locally)
* the characteristics of the file to transfer: RECFM, LRECL, CRLF (if possible)
* This view could allow you to choose the type of flow to use for the transfer (z/OSMF, FTP, etc.). By default this would be a transfer via z/OSMF, and use of zos-files commands

Concretely, this file transfer function should be able to do everything that the IND$FILE utility allows you to do with a 3270 emulator.

See: [Personal Communications - Sending and Receiving Files forme the DOS Command Prompt](https://www.ibm.com/docs/en/personal-communications/15.0?topic=pc3270-sending-receiving-files-from-dos-command-prompt)
* [Using the MVS/TSO SEND Command](https://www.ibm.com/docs/en/personal-communications/15.0?topic=prompt-using-mvstso-send-command)
* [Using the MVS/TSO RECEIVE Command](https://www.ibm.com/docs/en/personal-communications/15.0?topic=prompt-using-mvstso-receive-command)

**Describe alternatives you've considered**

Develop our own extension using Zowe SDK.

Thanks.

**Comment by JillieBeanSim** [comment]
We do have an issue to support drag & drop allowing uploading/downloading from local to host and vice versa https://github.com/zowe/vscode-extension-for-zowe/issues/2046 that we plan to work on.  Having the different profile types determining the upload/download handler we are closing this as not planned.

**Comment by FALLAI-Denis** [comment]
Hi,

Looking at #2644 and illustration by gif animation, this solution seem to be limited to current workspace. 

The file transfer must also be able to manage file out of the workspace. 
It also need to manage options about transfer: 
- binary or codepage conversion 
- options for file creation on upload 
- name of file on target 

A drag and drop solution can do some kind of transfer but probably is not sufficient to deal with all use cases of transfer.
