### ISSUE TITLE
Confirm integration test coverage.

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#265]
Need to ensure we have adequate integration test coverage associated with the main function points provided by the VSCode extension. 

1. Create a list of the Zosmf CLI functions called and relate to the registered commands.
2. Ensure all commands at least have integration tests associated. If we have CLI function not associated with commands we may need to decide if we need to create a command but it should have a test

**Comment by Colin-Stone** [comment]
These are the most obvious functional areas for integration testing

### Datasets
- zowe.List.allMembers
- zowe.List.dataSet x 3
- zowe.Upload.fileToDataset
- zowe.Create.dataSet
- zowe.Upload.bufferToDataSet x 2
- zowe.Delete.dataSet
- zowe.Download.dataSet x 2

### USS
- zowe.List.fileList
- zowe.Upload.fileToUSSFile
- zowe.Utilities.renameUSSFile
- zowe.Delete.ussFile
- zowe.Create.uss
zowe.Download.ussFile

### Jobs
- zowe.GetJobs.getSpoolFiles
- zowe.GetJobs.getJob
- zowe.GetJobs.getJobsByOwnerAndPrefix 
- zowe.GetJobs.getJclForJob

### Misc
- zowe.IssueCommand.issueSimple x 3
- zowe.SubmitJobs.submitJcl
- zowe.SubmitJobs.submitJob
- zowe.Utilities.isFileTagBinOrAscii

**Comment by zFernand0** [comment]
closing in favor of:
- #2103
