### ISSUE TITLE
USS folders are overlapped and difficult to read the folder names 

### ISSUE THREAD

**Issue by Shobhajayanna** [zowe/vscode-extension-for-zowe#2663]
**Describe the bug**

I tried renaming the file in one of the folder and since then all the folder names are overlaped and making it difficult to read them. 

**To Reproduce**

**Screenshots**

![image](https://github.com/zowe/vscode-extension-for-zowe/assets/36433611/798bb080-215a-496e-822f-ef57c2d6a17b)

thanks,
Shobha

**Comment by JTonda** [comment]
This issue should be resolved in 2.14.  PR: #2657
