### ISSUE TITLE
Rename Reject-Unauthized to Accept-Unauathorized

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#267]
Reject-Unauthized is a flag associated with security certificates. This topic is complex and sort of hard to understand. We have this option whereby users can enable command execution by reducing security to telling the mainframe to accept unauthorized certificates. To achieve this a user has to type --reject-unauthorized false. This is sort of like saying don't reject my application to school so you mean I'm accepted? This syntax strikes me as a double negative -x * -y = +z. But, this takes a certain amount of mental gymnastics to feret out the meaning and impact. I would prefer it be --accept-unauthorized true

**Comment by dkelosky** [comment]
It is complex and hard to understand.  The flag is surfaced directly from [Node.js APIs](https://nodejs.org/api/tls.html#tls_tls_createserver_options_secureconnectionlistener).

> If not false the server will reject any connection which is not authorized with the list of supplied CAs. This option only has an effect if requestCert is true. Default: true.

In this case, we're telling the client (not the server/mainframe) to allow certificates which are default-trusted by Mozilla. 

Other Node.js HTTP clients like [request](https://github.com/request/request-promise/issues/225) have used other wording - `insecure`.  However, it's unclear how their `insecure` abstraction translates to the actual Node.js run-time options. 

For both reasons - I favor the existing confusing name 😄

**Comment by jellypuno** [comment]
@MikeBauerCA Is there a resolution for this? Can we close this issue?

**Comment by MikeBauerCA** [comment]
Thanks for bringing my attention to this @jellypuno. For the reasons @dkelosky mentioned combined with the staleness of this issue and the likelihood that the resolution would require changes in profile creation scripts (in the case of the CLI), I am closing this issue.
