### ISSUE TITLE
Error shown when deleting USS directory

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#2675]
**Describe the bug**

Error shown in VSC window after deleting a USS directory, after refreshing USS the delete was successful but the below errors were returned when issuing the action. Deleting of USS files seems to work fine.
<img width="466" alt="Screenshot 2024-01-22 at 1 10 43 PM" src="https://github.com/zowe/vscode-extension-for-zowe/assets/49491949/85537760-e940-4bf2-b037-8099a07ac4af">

**To Reproduce**

1. Go to USS tree view and enter filter search
2. Right-Click on directory
3. Select delete and confirm the deletion of the directory

**Expected behavior**

no error especially if the deletion was succesfull on the host

**Desktop (please complete the following information):**

- OS: MacOS
- Zowe Explorer Version: main 2.14.0
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by adam-wolfe** [comment]
I tested this again. Deleting a directory works without error in 2.13.1, but I do see these errors with the 2.14.0 release in progress.

**Comment by jellypuno** [comment]
I second @adam-wolfe. There are no errors for 2.13.1. I tried both mac and windows.
