### ISSUE TITLE
VS Code Extension - Make the menu options for favorites consistent

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#268]
There are menu options for the connection and for the data-set members for adding to favorites. The former menu reads 'Save Search' and the latter 'Add to Favorites.' We should make both of them read 'Add to Favorites'. 

![image](https://user-images.githubusercontent.com/3207260/66598382-ed334180-eb6e-11e9-87d5-051fab56994f.png)

![image](https://user-images.githubusercontent.com/3207260/66598528-38e5eb00-eb6f-11e9-946c-1e25ba575545.png)

**Comment by sladyn98** [comment]
I would love to work on this issue.

**Comment by jellypuno** [comment]
> I would love to work on this issue.

Go for it! ;)
