### ISSUE TITLE
Sort encoding history with most recent at top and filter out duplicates

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/vscode-extension-for-zowe#2695]
The encoding history should be saved consistently with how we store other historical data like search filters.

Currently we just push the new encoding onto the end of the array:
https://github.com/zowe/vscode-extension-for-zowe/blob/77cff2ed565b6825e767aa203c2418ea75de80e6/packages/zowe-explorer/src/shared/utils.ts#L508

We should first remove the encoding if already present in the array, and then add it at the start of the array.

Perhaps we should also consider providing a way to reset the encoding history in the "Zowe Explorer: Edit History" command.

**Comment by JillieBeanSim** [comment]
Split last item to new issue [Allow reset of the encoding history in the "Zowe Explorer: Edit History" command](https://github.com/zowe/vscode-extension-for-zowe/issues/2747)
