### ISSUE TITLE
Related to closed bug 1970 - issue with http only rse profile

### ISSUE THREAD

**Issue by Thibaut69** [zowe/vscode-extension-for-zowe#2704]
I do have the same issue, Zowe explorer is not working with a RSE account set with HTTP only.

Retrieving response from uss-file-list Error: Zowe REST Operations API Error: | http(s) request error event called | Error: write EPROTO 2242944:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:....\third_party\boringssl\src\ssl\tls_record.cc:231: |

Zowe CLI answer correctly without SSL.

**Comment by traeok** [comment]
Hi @Thibaut69,

I believe this is related to #2703 - posting that issue here for awareness.

**Comment by zFernand0** [comment]
Hey @Thibaut69,
Thank you for opening the issue.

I believe this issue is better suited for the [IBM Z Open Editor](https://github.com/IBM/zopeneditor-about). I have opened it on your behalf.
- https://github.com/IBM/zopeneditor-about/issues/386

Closing!
