### ISSUE TITLE
Fix Medium and High Priority bugs in SonarCloud

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/vscode-extension-for-zowe#2709]
**Describe the bug**

As part of the OpenSSF Badge Best Practices, we agreed to fix the issues with medium and high priority found by static scans.

SonarCloud is showing 8 bugs, with 5 of them being medium or high severity: https://sonarcloud.io/summary/overall?id=zowe_vscode-extension-for-zowe 

**Additional context**

We have a similar issue open in the CLI repository: https://github.com/zowe/zowe-cli/issues/2032

**Comment by JTonda** [comment]
See if we can look into the scanning the zowe v1 lts and next branches as well.
