### ISSUE TITLE
MSG IKJ56486I THE ACCOUNT NUMBER XXXXXX-XXX-XXXX000-000-0 HAS NOT BEEN DEFINED FOR USE

### ISSUE THREAD

**Issue by Camilolferreira** [zowe/vscode-extension-for-zowe#272]
Hello,
I experimenting this issue on zowe-cli when I try to use the command zowe zos-files list ds "ibmXXXX.**" --zosmf-profile zosPROF . It seems like the account number is greater than the maximum value allowed because it was trunked. The real account number is XXXXXX-XXX-XXXX000-000-000-000 .  I can run commands zowe zos-tso, zowe zos-jobs and zowe zos-console with no issue. Have any idea what's going on? Thanks

**Comment by Camilolferreira** [comment]
Sorry, I meant it was truncated (not trunked).

**Comment by jellypuno** [comment]
Hi @Camilolferreira , So what is the issue here? Is it the truncated error message or the IKJ56486I?

**Comment by Camilolferreira** [comment]
Hi Jelly, yes i can. This error happen when I run this command on windows prompt to list files: zowe zos-files list ds "ibmXXXX.**" --zosmf-profile zosPROF.  The error message is not truncated, but the account number on error message seems to be. Following the entire return received:
C:\Users\CamiloFerreira>zowe zos-files list ds "ibm1xxx.**" --zosmf-profile zosPROF
Command Error:
z/OSMF REST API Error:
Rest API failure with HTTP(S) status 500
rc:       4
reason:   2
details:
  - IKJ56486I THE ACCOUNT NUMBER XXXXXX-XXX-XXXX000-000-0 HAS NOT BEEN DEFINED FOR USE
  - IKJ56429A REENTER -
category: 2
message:  login: received unexpected TSO LOGON prompt:TsoServerConnection(USER=IBM1CLF, ASID=0x006f, QID=0x001a0007)


Error Details:
HTTP(S) error status "500" received.
Review request details (resource, base path, credentials, payload) and ensure correctness.

Host:      XXXX.yyyy.com
Port:      10443
Base Path:
Resource:  /zosmf/restfiles/ds?dslevel=ibm1xxx.**
Request:   GET
Headers:   [{"X-IBM-Max-Items":"0"},{"X-CSRF-ZOSMF-HEADER":true}]
Payload:   undefined

Let me know if you need more information. Thanks

**Comment by Camilolferreira** [comment]
Hi Jelly, yes i can. This error happen when I run this command on windows
prompt to list files: zowe zos-files list ds "ibmXXXX." --zosmf-profile
zosPROF. The error message is not truncated, but the account number on
error message seems to be. Following the entire return received:

C:\Users\CamiloFerreira>zowe zos-files list ds "ibm1xxx." --zosmf-profile
zosPROF
Command Error:
z/OSMF REST API Error:
Rest API failure with HTTP(S) status 500
rc: 4
reason: 2
details:
      IKJ56486I THE ACCOUNT NUMBER XXXXXX-XXX-XXXX000-000-0 HAS NOT BEEN
      DEFINED FOR USE
      IKJ56429A REENTER -
      category: 2
      message: login: received unexpected TSO LOGON
      prompt:TsoServerConnection(USER=IBM1CLF, ASID=0x006f, QID=0x001a0007)


Error Details:
HTTP(S) error status "500" received.
Review request details (resource, base path, credentials, payload) and
ensure correctness.


Host: XXXX.yyyy.com
Port: 10443
Base Path:
Resource: /zosmf/restfiles/ds?dslevel=ibm1xxx.**
Request: GET
Headers: [{"X-IBM-Max-Items":"0"},{"X-CSRF-ZOSMF-HEADER":true}]
Payload: undefined


Let me know if you need more information. Thanks



Regards,
                                                                                                       
   Camilo Ferreira                                                                                     
   z/OS System Support                                                                                 
   Certified Technical Specialist Level 1                                                              
   Experienced                                                                                         
                                                                                                       
                                                                                                       
                                                                                                       
                                                                                                       
                                                                                                       
                                                                                                       
                                                                                                       
                                                                                                       
                                                                                                       
   Phone: +55 21 2132-3140 Tieline: 831-3140                                                           
   E-mail: clellis@br.ibm.com                                                                          
   Av. Nossa Senhora da Penha, 1255, Rooms 101/102                                                     
   Vitoria, Brazil                                                                                     
                                                                                                       






From:	jellypuno <notifications@github.com>
To:	zowe/vscode-extension-for-zowe
            <vscode-extension-for-zowe@noreply.github.com>
Cc:	Camilolferreira <clellis@br.ibm.com>, Mention
            <mention@noreply.github.com>
Date:	10/15/2019 05:19 AM
Subject:	[EXTERNAL] Re: [zowe/vscode-extension-for-zowe] MSG IKJ56486I
            THE ACCOUNT NUMBER XXXXXX-XXX-XXXX000-000-0 HAS NOT BEEN
            DEFINED FOR USE (#272)



Hi @Camilolferreira , So what is the issue here? Is it the truncated error
message or the IKJ56486I?


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jellypuno** [comment]
Hi @Camilolferreira ,

This is what I know, IKJ56486I error is a login error. It means that the account number is not defined in the RACF Database. 

> **Explanation**
One of the following conditions occurred:
The entered accounting number is not defined in the RACF® database.
The RACF administrator must first define the accounting number as a RACF resource and then grant the user access using the PERMIT command. (However, if the procedure is not in the procedure library, the logon attempt fails.)

> RACF class ACCTNUM is not active.
> The RACF administrator must activate RACF class ACCTNUM using the SETROPTS command.

Did you use the profile "zosPROF" in testing the other commands?  Also, Can you successfully login in 3270 terminal with that account number?

**Comment by Camilolferreira** [comment]
Hi @jellypuno,

Yes, the message is clear. However, I can login normally on TSO with the
account  XXXXXX-XXX-XXXX000-000-000-00 (29 bytes)  but the account number
that appears on  IKJ56486I message has only 24 bytes .  I don't know if it
was truncated when  zowe is called due some limitation or missing
configuration.

Thank you for your support.

Regards,
                                                                                                       
   Camilo Ferreira                                                                                     
   z/OS System Support                                                                                 
   Certified Technical Specialist Level 1                                                              
   Experienced                                                                                         
                                                                                                       
                                                                                                       
                                                                                                       
                                                                                                       
                                                                                                       
                                                                                                       
                                                                                                       
                                                                                                       
                                                                                                       
   Phone: +55 21 2132-3140 Tieline: 831-3140                                                           
   E-mail: clellis@br.ibm.com                                                                          
   Av. Nossa Senhora da Penha, 1255, Rooms 101/102                                                     
   Vitoria, Brazil                                                                                     
                                                                                                       






From:	jellypuno <notifications@github.com>
To:	zowe/vscode-extension-for-zowe
            <vscode-extension-for-zowe@noreply.github.com>
Cc:	Camilolferreira <clellis@br.ibm.com>, Mention
            <mention@noreply.github.com>
Date:	10/15/2019 10:06 AM
Subject:	[EXTERNAL] Re: [zowe/vscode-extension-for-zowe] MSG IKJ56486I
            THE ACCOUNT NUMBER XXXXXX-XXX-XXXX000-000-0 HAS NOT BEEN
            DEFINED FOR USE (#272)



Hi @Camilolferreira ,


This is what I know, IKJ56486I error is a login error. It means that the
account number is not defined in the RACF Database.


      Explanation
      One of the following conditions occurred:
      The entered accounting number is not defined in the RACF® database.
      The RACF administrator must first define the accounting number as a
      RACF resource and then grant the user access using the PERMIT
      command. (However, if the procedure is not in the procedure library,
      the logon attempt fails.)


      RACF class ACCTNUM is not active.
      The RACF administrator must activate RACF class ACCTNUM using the
      SETROPTS command.


Did you use the profile "zosPROF" in testing the other commands? Also, Can
you successfully login in 3270 terminal with that account number?


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jellypuno** [comment]
@Camilolferreira That is interesting. I will try to investigate more. Are you using a --base-path in your profile?

**Comment by Camilolferreira** [comment]
No, I am not using --base-path in my profile.


Regards,
                                                                                                       
   Camilo Ferreira                                                                                     
   z/OS System Support                                                                                 
   Certified Technical Specialist Level 1                                                              
   Experienced                                                                                         
                                                                                                       
                                                                                                       
                                                                                                       
                                                                                                       
                                                                                                       
                                                                                                       
                                                                                                       
                                                                                                       
                                                                                                       
   Phone: +55 21 2132-3140 Tieline: 831-3140                                                           
   E-mail: clellis@br.ibm.com                                                                          
   Av. Nossa Senhora da Penha, 1255, Rooms 101/102                                                     
   Vitoria, Brazil                                                                                     
                                                                                                       






From:	jellypuno <notifications@github.com>
To:	zowe/vscode-extension-for-zowe
            <vscode-extension-for-zowe@noreply.github.com>
Cc:	Camilolferreira <clellis@br.ibm.com>, Mention
            <mention@noreply.github.com>
Date:	10/15/2019 10:50 AM
Subject:	[EXTERNAL] Re: [zowe/vscode-extension-for-zowe] MSG IKJ56486I
            THE ACCOUNT NUMBER XXXXXX-XXX-XXXX000-000-0 HAS NOT BEEN
            DEFINED FOR USE (#272)



@Camilolferreira That is interesting. I will try to investigate more. Are
you using a --base-path in your profile?


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jellypuno** [comment]
@Camilolferreira ok... as I see it, this issue a problem in the system configuration for your ID in z/OSMF. In VSCode or Zowe CLI, we are simply receiving and passing the information given to us. The only verification that we have is if the account number is a string. So I am sure that there will be no truncation on our end.

How about this, Can you try to issue the request via postman? Just use basic authentication for your credentials? Let me know what are the results.

**Comment by Camilolferreira** [comment]
Hi @jellypuno
You are right,  by postman I've got the same error: I don't know how can I
fix that on z/osmf configuration. Is there another way to configure account
number for ssh requests?

                                                                                                             
                                                                                                             
                                                                                                             
 rc       4                                                                                                  
                                                                                                             
 reason   2                                                                                                  
                                                                                                             
 details                                                                                                     
                                                                                                             
 0        "IKJ56486I THE ACCOUNT NUMBER XXXXXX-XXX-XXXX000-000-0 HAS NOT BEEN DEFINED FOR USE"               
                                                                                                             
 1        "IKJ56429A REENTER -"                                                                              
                                                                                                             
 category 2                                                                                                  
                                                                                                             
 message  "login: received unexpected TSO LOGON prompt:TsoServerConnection(USER=IBM1XXX, ASID=0x006f,        
          QID=0x001f0007)"                                                                                   
                                                                                                             



Regards,
                                                                                                       
   Camilo Ferreira                                                                                     
                                                                                                       
                                                                                                       
                                                                                                       
                                                                                                       
                                                                                                       
                                                                                                       
                                                                                                       
                                                                                                       
                                                                                                       
                                                                                                       
   Phone: +55 21 2132-3140 Tieline: 831-3140                                                           
   E-mail: clellis@br.ibm.com                                                                          
   Av. Nossa Senhora da Penha, 1255, Rooms 101/102                                                     
   Vitoria, Brazil                                                                                     
                                                                                                       






From:	jellypuno <notifications@github.com>
To:	zowe/vscode-extension-for-zowe
            <vscode-extension-for-zowe@noreply.github.com>
Cc:	Camilolferreira <clellis@br.ibm.com>, Mention
            <mention@noreply.github.com>
Date:	10/15/2019 11:56 AM
Subject:	[EXTERNAL] Re: [zowe/vscode-extension-for-zowe] MSG IKJ56486I
            THE ACCOUNT NUMBER XXXXXX-XXX-XXXX000-000-0 HAS NOT BEEN
            DEFINED FOR USE (#272)



@Camilolferreira ok... as I see it, this issue a problem in the system
configuration for your ID in z/OSMF. In VSCode or Zowe CLI, we are simply
receiving and passing the information given to us. The only verification
that we have is if the account number is a string. So I am sure that there
will be no truncation on our end.


How about this, Can you try to issue the request via postman? Just use
basic authentication for your credentials? Let me know what are the
results.


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Camilolferreira** [comment]
Hi @Jellypuno,

The IZUPRMXX member of SYS1.PARMLIB was updated with RESTAPI_FILE ACCT( parameter which has solved my issue. 

Thank you very much for your support.
