### ISSUE TITLE
Upload Member action fails with cryptic message when no file is selected

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#273]
When uploading a member to a data set, the OS File Browser comes up as expected. If you cancel the action, you get:
![image](https://user-images.githubusercontent.com/37381190/66920682-cacb7900-eff1-11e9-812f-e2520b740161.png)

Would it be possible to handle this the same way we do with some (if not all) other inputs?
For example, selecting a filter and leaving the input box by clicking outside, we get:
![image](https://user-images.githubusercontent.com/37381190/66920841-17af4f80-eff2-11e9-9526-b1c89be51459.png)

**Comment by stepanzharychevbroadcom** [comment]
@Colin-Stone @VitGottwald @jellypuno Added fix in: https://github.com/zowe/vscode-extension-for-zowe/pull/632
