### ISSUE TITLE
VSCode CLI dependency to be @zowe

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#295]
Set explicit Zowe explorer dependency latest @zowe rather than lts @brightside

**Comment by Colin-Stone** [comment]
The change to Zowe Explorer is straightforward, i.e changing from `@brightside/core` to `@zowe/cli` and `@brightside/imperative` to `@zowe/imperative`. Are there any other aspects we need to consider and include?.

**Comment by zFernand0** [comment]
In order to get all the functionality into the 1.0.0 MVP of the extension, we need to port some functionality to the master branch of the zowe.cli repo.
See https://github.com/zowe/zowe-cli/issues/596 for more details

**Comment by MikeBauerCA** [comment]
@zFernand0 because the latest version of the CLI package under the `@zowe` scope supports file streaming, do you think this would also improve the performance of the Zowe Explorer when working with large data sets?

**Comment by phaumer** [comment]
@zFernand0 @MikeBauerCA do you know which exact version will be used? Will the dependency be `zowe-v1-lts`, which is currently 6.7.2. Will that version change for the March release to something newer?

**Comment by zFernand0** [comment]
Fixed by #530
