### ISSUE TITLE
Update the Zowe and Microsoft Marketplace docs

### ISSUE THREAD

**Issue by IgorCATech** [zowe/vscode-extension-for-zowe#297]
https://marketplace.visualstudio.com/items?itemName=Zowe.vscode-extension-for-zowe 
https://docs.zowe.org/stable/user-guide/cli-vscodeplugin.html

These docs have to be updated to include more features. Next increment will include:
- Creation of Zowe CLI z/OSMF compatible profiles inside Zowe Explorer.
- (Only Marketplace doc) Updated gifs for the above-mentioned feature and some existing features.

**Comment by MikeBauerCA** [comment]
We should also directly call out z/OSMF as a prerequisite in the README.

**Comment by MikeBauerCA** [comment]
@IgorCATech perhaps this issue could be closed now. I opened #303 for adding the z/OSMF prerequisites in the README.

**Comment by IgorCATech** [comment]
I'll close when the Zowe doc is updated, too. Should happen today.

**Comment by IgorCATech** [comment]
Zowe doc has been published.
