### ISSUE TITLE
Update Tags on Marketplace

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/vscode-extension-for-zowe#299]
Current Tags on Marketplace:
![image](https://user-images.githubusercontent.com/35504792/68697901-becdcb00-054d-11ea-86b6-f5601a8858cf.png)

As the extension has evolved over time, I would suggest adding the following tags (perhaps others have suggestions as well):

z/OS, explorer, unix, uss, jobs, jes, mvs, tso

**Comment by zFernand0** [comment]
Acronyms should be all Caps, USS, JES, MVS, ...
