### ISSUE TITLE
Bug: Pull from Mainframe loses the Toggle binary/text state of the current editor

### ISSUE THREAD

**Issue by JDUNNIN** [zowe/vscode-extension-for-zowe#302]
If you have a file open in the editor and you pull from mainframe to get changes, the editor forgets the binary/text state and reloads the updated file (so it is no longer readable) and you have to press Toggle binary/text again.

The menu item for Toggle binary/text also seems to get out of sync when you've pulled from mainframe.

**Comment by jellypuno** [comment]
@stepanzharychevbroadcom This is already fixed, right?

**Comment by stepanzharychevbroadcom** [comment]
@jellypuno yes, it should be.

**Comment by JDUNNIN** [comment]
Thanks! :)

**Comment by zFernand0** [comment]
@jellypuno @stepanzharychevbroadcom
PR, and Milestone?

**Comment by stepanzharychevbroadcom** [comment]
@jellypuno @zFernand0 Just saw it connected with few binaries. Will do an investigation on latest master and create PR if it will be required.

**Comment by stepanzharychevbroadcom** [comment]
@jellypuno @zFernand0 Fix is here: https://github.com/zowe/vscode-extension-for-zowe/pull/591
