### ISSUE TITLE
Clearly specify prerequisite z/OSMF REST services in the README

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/vscode-extension-for-zowe#303]
Similar to how the exact z/OSMF REST services for the Zowe CLI are documented at https://docs.zowe.org/stable/user-guide/systemrequirements-zosmf.html#z-os-requirements, we should identify the specific z/OSMF REST services that are required for the functionality offered by the Zowe Explorer.

**Comment by IgorCATech** [comment]
Do you think we can just insert a link to that Zowe page? Or should there be an additional separate section specific for Zowe Explorer inside the Readme?

**Comment by zFernand0** [comment]
I tend to believe that duplication of things is never a good approach.
I'd rather recommend adding a link to that specific section, and if there is something that the Zowe Explorer definitely does not require, then we can mention it after the link?
Maybe because I'm not aware of all the details but I do not see an issue if someone wanted to verify/configure all the z/OS requirements on that list. : )

**Comment by zFernand0** [comment]
@MikeBauerCA Could you help me find the z/OS MF requirements on the Zowe CLI?
I'm curious if these will just be a subset of those. 🤔

**Comment by MikeBauerCA** [comment]
@zFernand0 it will be a subset of these: https://docs.zowe.org/stable/user-guide/systemrequirements-zosmf.html#z-osmf-rest-services-for-the-zowe-cli

I believe we require TSO/E address space services, z/OS data set and file REST interface, and z/OS jobs REST interface

**Comment by zFernand0** [comment]
Hey @IgorCATech,
How hard will it be to add another topic to the [Confuguring z/OSMF subject](https://docs.zowe.org/stable/user-guide/systemrequirements-zosmf.html#configuring-z-osmf)?

**Comment by zFernand0** [comment]
Or maybe a column on that table?
@MikeBauerCA any thoughts?

**Comment by MikeBauerCA** [comment]
I think another column on that table makes sense. Perhaps the title could be "Required for Zowe Explorer VS Code Extension" and each entry could be a simple Yes or No.

**Comment by IgorCATech** [comment]
An extra column (or rather a row) in the table sounds good to me. @zFernand0 Can you please consult me on how to populate the description for the Zowe Explorer VS Code Extension requirement?

**Comment by zFernand0** [comment]
resolved on #305

**Comment by IgorCATech** [comment]
the pr305 has been merged.
