### ISSUE TITLE
Validate the z/OSMF Host is a Valid Service

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#309]
Validate connection: The Zowe Explorer today doesn't check the connection to zOSMF when it is created. Instead it attempts to connect when the user first does a search. A validation check would help to detect if zOSMF is alive and ready to use and this is a valuable check for new users to onboard to the Mainframe. This is a compatibility feature for zOS Explorer.

Note this was available in the original z/OS Explorer extension.

**Comment by zFernand0** [comment]
Hey @jelaplan, if you don't mind me asking, but what is this `original z/OS Explorer extension` you are referring to? (just curious) 
`Note this was available in the original z/OS Explorer extension.`

**Comment by MikeBauerCA** [comment]
@jelaplan if the validation check fails, what would you expect to happen? Would the profile still be created? It is possible that users would like to set up their profiles even if z/OSMF is temporarily unreachable.

**Comment by Colin-Stone** [comment]
> @jelaplan if the validation check fails, what would you expect to happen? Would the profile still be created? It is possible that users would like to set up their profiles even if z/OSMF is temporarily unreachable.

I would still create it but set it's context as something as session_inactive. That way you can associate specific menu options and allocate an appropriate icon

**Comment by jelaplan** [comment]
> Hey @jelaplan, if you don't mind me asking, but what is this `original z/OS Explorer extension` you are referring to? (just curious)
> `Note this was available in the original z/OS Explorer extension.`

Fernando
I wonder if you are being cheeky?  z/OS Explorer is another open source extension that Broadcom has built. We decided to focus on the Zowe Explorer and try to incorporate some of the best features.

**Comment by jelaplan** [comment]
> @jelaplan if the validation check fails, what would you expect to happen? Would the profile still be created? It is possible that users would like to set up their profiles even if z/OSMF is temporarily unreachable.

Yes, I think we'd store the connection details in a profile. My expectation would be to show a message.

**Comment by jelaplan** [comment]
![image](https://user-images.githubusercontent.com/3207260/69351627-a34b7a00-0c49-11ea-9f4b-10092d35bc0c.png)

**Comment by MikeBauerCA** [comment]
@Colin-Stone & @jelaplan thanks for the suggestions. I would be in favor of both a temporary message and an icon in the tree representative of the state.

**Comment by phaumer** [comment]
This feature needs to be designed very carefully. Network traffic like this is very expensive and should be initiated by the end user. Such checks should not be done in bulk automatically as they take an unpredictable amount of time especially when the user has dozens of profiles in different regions each requiring different firewall auths etc. 

I see that PR https://github.com/zowe/vscode-extension-for-zowe/pull/787 adds them during activation, which means we cannot predict how long it takes, which is not acceptable for activation as it might break the extension completely or slow down VS Code startup and even could cause Che timeouts. 

I propose to 

- check when a profile is created/edited
- when a profile is used for the first time in a user session such as first Search query
- when a user explicitly requests it via right-click or a menu
