### ISSUE TITLE
Favorites pin. Let people use a pin icon to add items to and remove items from the favorites. 

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#311]
Favorites pin. Let people use a pin icon to add items to and remove items from the favorites. This would make managing them easier. This is meant to make it more palatable to the zOS   Explorer to make it easier to add favorites.

Today, the user adds to favorites with the context menu. 
<img width="463" alt="image" src="https://user-images.githubusercontent.com/3207260/69112797-2eaceb80-0a4f-11ea-95c7-5c2baa1863e6.png">

I'll plan to make a mockup to show how this looks.

**Comment by katelynienaber** [comment]
@jelaplan This one is done on branch [pin-icon-to-fave](https://github.com/zowe/vscode-extension-for-zowe/tree/pin-icon-to-fave), just need a pin icon svg to put on the toolbar ^^''
