### ISSUE TITLE
Add shortcuts to the context menus to allow keyboard access

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#313]
Add shortcuts with icons in the context menus. Many of the actions in the Zowe Explorer are only available through right click context menus. Adding shortcut key combinations and echoing those shortcut key-combinations in the menu provide an alternative and  faster way to interact with the extension. The VS Code built in file explorer has these  shortcuts and icons. I drew up these  design ideas in the mockups I delivered.

_Dataset_
<img width="434" alt="image" src="https://user-images.githubusercontent.com/3207260/69113299-9ca5e280-0a50-11ea-974b-169e0323686e.png">

_Member_
<img width="377" alt="image" src="https://user-images.githubusercontent.com/3207260/69113279-91eb4d80-0a50-11ea-9f17-c95d6da8c5e8.png">

**Comment by katelynienaber** [comment]
Working on this. Seems that if you execute a command from a keybinding, VSCode does not receive the proper context for the focused item in the tree, and any command using the context to decide whether it is allowed to run won't run: https://github.com/microsoft/vscode/issues/72442

Maybe there is a workaround. I will spend some more time on it.

**Comment by lauren-li** [comment]
Even if VS Code issue https://github.com/microsoft/vscode/issues/72442 prevents Zowe Explorer from effectively implementing keybindings at the moment, perhaps we should go ahead and compile a list of keybindings we want to use, so that we'll be ready to implement them when the bug is fixed. Additionally, we can then provide this list to extenders in our conformance criteria to let them know what keybindings to avoid using.

**Comment by lauren-li** [comment]
@tomofbroadcom When you work on a proposed list of keybindings for Zowe Explorer commands, you may want to start with the commands in the below screenshot (from PR #1308), as these would be keybindings we are more likely to be able to implement immediately (i.e. without waiting for the [bug](https://github.com/microsoft/vscode/issues/72442) mentioned above to be fixed):

<img width="599" alt="Screen Shot 2021-05-11 at 4 52 30 AM" src="https://user-images.githubusercontent.com/45975633/117810066-f265e000-b22c-11eb-8140-08a47c2a36b2.png">

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
