### ISSUE TITLE
USS Rename within favorites presents profile and name to the user

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#315]
The rename function pops up an input box with a profile included. It should be a file name only
![image](https://user-images.githubusercontent.com/30794003/69154810-98bda300-0ad8-11ea-8fb6-0b50736b3fce.png)

**Comment by JDUNNIN** [comment]
Looks like ZoweUSSNode.shortLabel should be used instead of ZoweUSSNode.label when vscode.window.showInputBox is called in ussNodeActions.ts.

**Comment by zdmullen** [comment]
Appears to be fixed now.
