### ISSUE TITLE
Merge with original VSCode extension

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#32]
@Colin-Stone commented on [Mon Apr 01 2019](https://github.com/zowe/vscode-uss-extension-for-zowe/issues/7)

Keep all of the Zowe VSCode extensions as one extension

---

@Colin-Stone commented on [Mon Apr 01 2019](https://github.com/zowe/vscode-uss-extension-for-zowe/issues/7#issuecomment-478523982)

Consider creating a joined up taxonomy structured as follows:
```
Zowe
|
| ----Favorites
|
| ---- MyProfile 1
		|
		| ---- Datasets
		|		|
		|		| ---- MYUSER.TEST.JCL
		|		|	:	:
		|		| ---- MYUSER.PROD.JCL
						|
						| ---- COMPARE
						| ---- COPY
		|
		| ---- USS Files
		|		|
		|		| ---- /u/myuser
		|				|
		|				| ---- file1.txt
		|
		| ---- Jobs
				|
				| ---- AJOB1(INPUT)
				| ---- AJOB2(ACTIVE)
				| ---- TSU1(ABEND S222)
```

**Comment by Colin-Stone** [comment]
Counter argument against the above layout came in asking that we retain the separation as it is not usual that a customer uses the features at the same time and the views would become very cluttered with elements not needed all of time. So the proposal is for this.
![Screenshot 2019-04-08 at 13 17 49](https://user-images.githubusercontent.com/30794003/55724975-7c1aa200-5a04-11e9-9b5a-8ceb616d88f6.png)
Maybe we can start with this and reconsider once complete.

**Comment by phaumer** [comment]
Created issue: https://github.com/zowe/vscode-extension-for-zowe/issues/38
