### ISSUE TITLE
Share profile credentials across trees

### ISSUE THREAD

**Issue by jalel01** [zowe/vscode-extension-for-zowe#321]
The first implementation of making user name and passwords optional as part of profile creation results in users needing to enter those credentials once per session for each tree (Dataset, USS, Jobs) with which they wish to interact. Currently each tree is its own distinct node isolated from other nodes and therefore does not share session information such as credentials.

This enhancement would provide a better user experience whereby, if a user authenticates for one tree, they could use the same profile in another tree without needing to re-enter credentials.

**Comment by jellypuno** [comment]
This is already handled by optional profiles
