### ISSUE TITLE
Update Zowe Explorer docs

### ISSUE THREAD

**Issue by IgorCATech** [zowe/vscode-extension-for-zowe#323]
Update the Zowe doc and VSC Marketplace doc to include the following features: 
- rename data sets and USS files
- copy data sets and USS files (might not be part of 1.0)
- 'Safe save' as the default and only save option
- SCS-enhanced profiles (?)
- Profiles creation: make user name and pw optional
- Known issues in Zowe docs -  issue create in the docs-site repo https://github.com/zowe/docs-site/issues/850 

Links
https://marketplace.visualstudio.com/items?itemName=Zowe.vscode-extension-for-zowe
https://docs.zowe.org/stable/user-guide/cli-vscodeplugin.html#zowe-explorer-extension-for-vscode

**Comment by IgorCATech** [comment]
https://github.com/zowe/docs-site/pull/851 for the Zowe docs update

**Comment by zFernand0** [comment]
VSCode readme updated :) 
Closing
