### ISSUE TITLE
Allow programmatic calling of "command": "zowe.issueTsoCmd",

### ISSUE THREAD

**Issue by travatine** [zowe/vscode-extension-for-zowe#324]
Hi,

It'd be great if extensions could utilise the "command": "zowe.issueTsoCmd" by allowing a command string to be as a parameter.

e.g.
I'm writing an extension and want to be able to run TSO commands on the current system / profile that has been opened the jobs view.

Thanks.
Travis Thorne

**Comment by MikeBauerCA** [comment]
For the TSO command you are trying to issue, would it make sense to include it as part of the context menu on a particular job? This is what the menu currently looks like: 
![image](https://user-images.githubusercontent.com/35504792/69431291-6d6bcb80-0d05-11ea-82ca-2948237950bd.png)

Maybe just a generic (Issue TSO command) option would be valuable in case folks were not aware of the ability to run any TSO command via the command palette.

For programmatic usage you could make use of functionality provided by the @brightside/core or @zowe/cli package.

**Comment by Colin-Stone** [comment]
Similar to https://github.com/zowe/vscode-extension-for-zowe/issues/322

**Comment by travatine** [comment]
Hi,
Some more details on what the extension is trying to do;

When a job gets a "bad" return code such as an "abend" , the user could open a job output spool file, such as the JES MSGS, The user could then right click in the downloaded job spool file and run my extension to investigate the abend.

My extension would search the job output for messages known to be emitted by Abend investigation tools,

If such messages were found, my extension would extract details from the messages to use as arguments to a TSO based Abend investigation tool.
Finally the extension would run the TSO command with the extracted arguments.

I was hoping to re-use the existing session / profile that was used to download the job output, so the user is not required to perform additional profile selection or authentication ,

**Comment by travatine** [comment]
I think Mike's suggest of using zowe/cli directly will work for me
