### ISSUE TITLE
Code restructure - Use Interfaces and Abstract Classes 

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#328]
Legacy debt. Zowe Explorer originates from three separate plugins and although a lot of effort has gone in to making all three behave the same there are some areas of inconsistency which need to be ironed out.

To do this I propose creating AbstractZoweNode and AbstractZoweProvider representing nodes and trees respectively and allowing the three sets of classes to converge areas of common function and behavor and rationalize testing.

**Comment by jellypuno** [comment]
@Colin-Stone Can you share with me the architectural approach on how you are going to do this? I want to keep this in mind as I think about issue #354

**Comment by Colin-Stone** [comment]
> @Colin-Stone Can you share with me the architectural approach on how you are going to do this? I want to keep this in mind as I think about issue #354

Hi Jelly. There are two abstract classes we use currently. TreeItem and TreeItemProvider. Each container has extending classes for these. Methods such as getTreeItem and getParent are implemented in the three provider classes and can be pushed to an intermediate anstract class and getChildren may be something we can extract the common function from and put into the intermediate class. 
I don't yet have a definitive list of the methods we would restructure yet but my first pass would be to list the common methods and what function could be moved out.
The second thing I want to look for is standardisation of the way TreeItems are built as the number of parameters on a new call has grown. I think we can do this better and in line with updating of the label handling come up with a solution that applies to each object type

**Comment by jellypuno** [comment]
ok. I see. cool! thank you. 

Is this the same as this one? #75

**Comment by Colin-Stone** [comment]
#75 is changing the three containers into one container. In other words just one tree. That was my original intention to bring everything together. The profile object would still be the root object but you would then have a node that indicated the type and filter. E.g. Datasets "MYHLQ". Some people think it's a nicer way to do it, others don't. But I have never had an opportunity to implement it. Ideally I would have it as a setting you could either have the three containers or the one

**Comment by Colin-Stone** [comment]
This is how I have done this.
1. Create specific Interfaces
`interface IZoweTree<T> extends vscode.TreeDataProvider<T>`
`interface IZoweTreeNode`
`interface IZoweDatasetTreeNode extends IZoweTreeNode `
`interface IZoweUSSTreeNode extends IZoweTreeNode `
`interface IZoweJobTreeNode extends IZoweTreeNode `
2. Add to these the fields and methods that cross class boundaries
3. Push common fields and methods to super class where possible
4. Change Implementing classes to use interfaces in methods
5. Change all references to methods in classes including test cases

Next stage
A. Refactor extension.ts so that commands/functions now reside in correct interface/class
B. Refactor to remove from interface fields/functions that were for allowing extension to class e.g. openUSS etc

Still to do
1. Move test cases from original implementation file to most appropriate one

**Comment by Colin-Stone** [comment]
Created the following type
`export type IZoweNodeType = IZoweDatasetTreeNode | IZoweUSSTreeNode | IZoweJobTreeNode;`

meaning we can now specify the following generic interfaces as operations on `IZoweTree`
>    rename(node: IZoweNodeType);
    open(node: IZoweNodeType, preview: boolean);
    copy(node: IZoweNodeType);
    paste(node: IZoweNodeType);
    delete(node: IZoweNodeType);
    setItem(treeView: vscode.TreeView<IZoweNodeType>, node: IZoweNodeType);
    saveSearch(node: IZoweNodeType);
    saveFile(document: vscode.TextDocument);
    refreshPS(node: IZoweNodeType);
    addHistory(element: string);
    getHistory();
    deleteSession(node: IZoweNodeType): any;
    getTreeView(): vscode.TreeView<IZoweNodeType>;
    filterPrompt(node: IZoweNodeType): any;

so for example: filterPrompt replaces datasetFilterPrompt, ussFilterPrompt and searchPrompt.

This would then require a large operation of moving function out of extension.ts to the tree along with all the associated unit tests

**Comment by Colin-Stone** [comment]
This part of the Epic has been done.
