### ISSUE TITLE
Provide icons representative of z/OS specific concepts

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/vscode-extension-for-zowe#330]
Thanks for the offer. This will be ongoing work so no rush but I would like to have some more document icons at some stage that possibly using decorators subtley represent some z/OS specific concepts.

- Binary file
- Archived or Migrated dataset file or folder
- A dataset alias
- A job
- A job spool
- Possibly Type specific ? asm, cbl, pli, copybook etc

And at the risk of sounding ungrateful/ungracious can I have both light and dark versions please ;-)

_Originally posted by @Colin-Stone in https://github.com/zowe/vscode-extension-for-zowe/issues/310#issuecomment-558324850_

**Comment by jelaplan** [comment]
@MikeBauerCA I can look into this. It seems what you want is file format specific icons. We see that kind of thing in Windows Explorer and Mac Finder.  Tomas Laurinec  had a series of icons for those and I'll reach out to him to see what he has. I have one concern that a listing can begin to look mess with a variety of icons. Colin mentioned a family of icons and we might use that concept to create variations on a theme.

**Comment by JTonda** [comment]
We added a few icons already for binaries and other categories.  Closing for now.  We continue investigating this in the future if more requests come in.
