### ISSUE TITLE
Link to job not working

### ISSUE THREAD

**Issue by ghost** [zowe/vscode-extension-for-zowe#334]
When submitting a job via right click -> submit job, I receive the following popup:
![image](https://user-images.githubusercontent.com/50887074/69673865-4b59ac80-1069-11ea-8e60-4d9e89097400.png)

However, clicking the link currently does nothing.

This was reported before (#239) and fixed, but the issue still remains when using the extension inside Che4z.

**Comment by crawr** [comment]
The issue persists when tested using ZE v1.11.1. In VSCode, if the profile is loaded in the jobs tree, and I click the link, the job is highlighted even id the jobs profile node is collapsed. In Theia, if the jobs profile node is collapsed, it will not highlight the job. 

For both environments, the link to the jobid does nothing if the profile associated with the job is not loaded in the tree.

**Comment by katelynienaber** [comment]
@crawr do you think it would be acceptable to show an error like, "Profile not loaded in jobs tree", or should we load the profile if it's not there?

I guess the profile would only be missing if the user removed it. So maybe we don't want to add it back for them?

**Comment by crawr** [comment]
In my opinion, it would be ok to load the profile if it is not there. I think that if the user submitted the job using that profile, it means that the profile is actively being used, at least for that session. 

The profile could also be missing if it is a new profile and hasn't been loaded in the jobs tree yet.

**Comment by jellypuno** [comment]
> In my opinion, it would be ok to load the profile if it is not there. I think that if the user submitted the job using that profile, it means that the profile is actively being used, at least for that session.
> 
> The profile could also be missing if it is a new profile and hasn't been loaded in the jobs tree yet.

This is not a problem anymore. Let's open an enhancement issue that will automatically add the profile if it is not available on the tree. Closing this issue.
