### ISSUE TITLE
Allow Terse / Unterse of datasets in the zowe.explorer view

### ISSUE THREAD

**Issue by travatine** [zowe/vscode-extension-for-zowe#336]
Hi,

I frequently need to receive datasets in Terse and Unterse datasets.
Today I use ISPF / TSO to run the required commands commands (AMATERSE) .
It'd be great if the same thing could be done from the VS Code UI.

Thanks!
Travis.

**Comment by MikeBauerCA** [comment]
TSO commands can be issued via the command palette
[Extra Feature: Issue TSO Commands](https://github.com/zowe/vscode-extension-for-zowe#issue-tso-commands)

In #322, we are aiming to have this function pinned somewhere handy and add the ability to recall the last ten commands.

@travatine, is this sufficient or would having this in a right-click menu be desired?

**Comment by travatine** [comment]
Yes that'd be great thanks.
