### ISSUE TITLE
Allow Receive of XMIT datasets

### ISSUE THREAD

**Issue by travatine** [zowe/vscode-extension-for-zowe#338]
Hi,

I frequently need to receive datasets in XMIT format;
Today I use ISPF / TSO to run the receive commands .
It'd be great if the same thing could be done from the VS Code UI.

Thanks!
Travis.

**Comment by jellypuno** [comment]
You can issue TSO Commands via command palette

[Extra Feature: Issue TSO Commands](https://github.com/zowe/vscode-extension-for-zowe#issue-tso-commands)

**Comment by zFernand0** [comment]
@travatine, is Mike suggestion good enough?
https://github.com/zowe/vscode-extension-for-zowe/issues/336#issuecomment-562683526

**Comment by travatine** [comment]
Yeah that'll work thanks
