### ISSUE TITLE
Allow users to update password on remote system from extension

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/vscode-extension-for-zowe#341]
@jalel01 I agree with the idea to provide a warning message to prevent folks from getting locked out. Typically, this situation occurs when a user's password has expired and needs updated. It would be ideal to be able to update it from the CLI / VS Code Extension. Will raise as a separate issue.

_Originally posted by @MikeBauerCA in https://github.com/zowe/vscode-extension-for-zowe/issues/320#issuecomment-559078679_

**Comment by jellypuno** [comment]
For reference: https://github.com/zowe/api-layer/issues/280

**Comment by jellypuno** [comment]
Closing the issue because it is not possible to do this. z/OSMF has not provided this kind of capability.

**Comment by zFernand0** [comment]
Thank you Jelly for clarifying offline ❤️ 

> For reference: [zowe/api-layer#280](https://github.com/zowe/api-layer/issues/280)

More specifically: https://github.com/zowe/api-layer/issues/280#issuecomment-482084314
