### ISSUE TITLE
Document how to include the extension in a Theia environment as part of the README

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/vscode-extension-for-zowe#343]
Zowe Explorer is functional in a Theia environment. We should document how to include it in that environment. Perhaps this information could be provided in the docs folder and the README could link to it.

**Comment by phaumer** [comment]
Work is done here for now: https://github.com/phaumer/vscode-extension-for-zowe/blob/theia-doc/docs/README-Theia.md

**Comment by phaumer** [comment]
I created this PR https://github.com/zowe/vscode-extension-for-zowe/pull/359. 

@Colin-Stone @MikeBauerCA do you want to review it?

**Comment by phaumer** [comment]
Closing this one has the merge commit is not signed.

**Comment by phaumer** [comment]
Created new PR: https://github.com/zowe/vscode-extension-for-zowe/pull/360

**Comment by zFernand0** [comment]
This could very well be included in the GA 1.0 : )

**Comment by Colin-Stone** [comment]
Completed. Thanks Peter

**Comment by zFernand0** [comment]
Thanks @phaumer for adding the doc.
In order to close the issue, should we link to the file from the main README.md?

**Comment by phaumer** [comment]
Which one? The readme in docs or even the one at the top? Perhaps the owners of these files could do it?

**Comment by zFernand0** [comment]
@IgorCATech, @BrandonJenkins14, @JamesBauman
Is it possible to add a link on the top level readme file that directs people to `https://github.com/zowe/vscode-extension-for-zowe/blob/master/docs/README-Theia.md`

It could be as simple as updating the Tip on the first section of the Readme. : )
![image](https://user-images.githubusercontent.com/37381190/70535655-6cbb9d80-1b2b-11ea-8ee8-4f88d3f211e7.png)

**Comment by Colin-Stone** [comment]
I quite fancied an image of Zowe Explorer in it's Theia outfit that could be clicked on.
