### ISSUE TITLE
Add VSIX to the GH releases

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#346]
We want to provide another way of getting old versions of the extension in order to make it more accessible to those who may not be familiar with getting them directly from the marketplace.
https://github.com/zowe/vscode-extension-for-zowe/releases

- [x] Update pipeline to create draft release
- [x] Package and upload the corresponding VSIX
- [ ] Add the corresponding changelog to the description of the release
- [ ] Make release public (no-draft)

**Comment by phaumer** [comment]
There are other reasons as well such as Eclipse Che: A Che cluster will continuously download the extension for every new container it creates. Microsoft has a limit to downloads and ban the clusters IP. Github support API keys for that.  Such a direct download from Che would also skew the Marketplace installations counter as you suddenly get many more installs although these are not new users. You can see that all the Redhat VS Code extensions are provided via Github releases as well as they offer them with Che.
