### ISSUE TITLE
Error: You have Zowe Data Set favorites that refer to a non-existent CLI profile named: ztrial. 

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#350]
VSCode detected that I do not have an existing profile even though it is there. I think it is because my profile's name is z**T**rial and favorites saved it as z**t**rial.

![vsc err](https://user-images.githubusercontent.com/45042840/69807325-50dc0180-11e5-11ea-8c05-438d8f01395b.PNG)

![vsc err2](https://user-images.githubusercontent.com/45042840/69807331-53d6f200-11e5-11ea-8ff2-3a6aec9fe018.PNG)

**Comment by jellypuno** [comment]
I refreshed my workspace and I cannot re-create the error again. weird...

**Comment by zFernand0** [comment]
So, would a solution be to just take the profile name as is?
There is a similar issue that talks about profile names and how the some things don't care if it's all caps or not.
https://github.com/zowe/zowe-cli/issues/551

**Comment by jellypuno** [comment]
> So, would a solution be to just take the profile name as is?

maybe. My issue now is that I can name all my profiles like Ztrial, zTrial, ztRial or zTrIaL and all of them will be different profiles 😆

**Comment by katelynienaber** [comment]
Possibly we could...
- Fix Favorites so that profile is saved with proper capitalization
- When working with profiles, always compare `profile.name.toUpperCase()` or `.toLowerCase()`, even if we show the user something else (ie. we show them zTrial, but we compare ZTRIAL)

**Comment by zdmullen** [comment]
So can we consider this issue closed, or should it remain open because of the possibility of editing in the settings.json directly instance?

**Comment by katelynienaber** [comment]
I would consider it closed because if someone chsnges settings.json directly, they will see the error message (the error is handled) but maybe @jellypuno has a more comprehensive solution idk

**Comment by jellypuno** [comment]
"I don't even have a pla" 😆 

You can close it. You are not allowed to have the same name with different cases anyway so this is fine. 😉 

@katelynienaber But what is PR #790 ?

**Comment by katelynienaber** [comment]
Well it tells you in the PR XD That is related to [this comment](https://github.com/zowe/vscode-extension-for-zowe/issues/350#issuecomment-560441976)

**Comment by zFernand0** [comment]
fixed in https://github.com/zowe/vscode-extension-for-zowe/pull/790
