### ISSUE TITLE
VSCode recognise data set as C code

### ISSUE THREAD

**Issue by spufidoo** [zowe/vscode-extension-for-zowe#351]
Hi. I'm using VS Code to program in C on the mainframe, using USER.PROJ.C(*) data sets. How do I get VS Code to recognise the text as C code, and highlight accordingly?

**Comment by zFernand0** [comment]
It seems that `".C(*)" : "c"` works. :smile:
https://openmainframeproject.slack.com/archives/CC08782AG/p1574957583180700?thread_ts=1574953460.179200&cid=CC08782AG

@Colin-Stone, I believe there was a way for the extension to detect these datasets, and save the temporary files with the proper file-extension. Please correct me if I'm wrong.

**Comment by MikeBauerCA** [comment]
Appears to be resolved, closing.

**Comment by Colin-Stone** [comment]
> @Colin-Stone, I believe there was a way for the extension to detect these datasets, and save the temporary files with the proper file-extension. Please correct me if I'm wrong.
Hi @jellypuno It's in a function called appendSuffix in extension.ts. Although that doesn't handle .c files. I'm surprised it is working.
