### ISSUE TITLE
Centralized solution for prompting of credentials

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#354]
Today, prompting of credentials are written in several functions like flipState, datasetFilterPrompt, OpenPS, searchPrompt etc. I would like to have a centralized solution for this so that any new function added in Zowe Explorer  will be validated for credentials.

**Comment by zFernand0** [comment]
I'd recommend trying to get this done by v1.1 since this could result in quite a bit of technical debt. : )

**Comment by jellypuno** [comment]
The change for this issue was implemented on v1.6.0
