### ISSUE TITLE
`Pull from mainframe` doesn't work on USS Favorites

### ISSUE THREAD

**Issue by Alexandru-Dumitru** [zowe/vscode-extension-for-zowe#355]
While clicking the `pull from mainframe` icon in the Favorites of USS Tree, I get the following error:
![err1](https://user-images.githubusercontent.com/45846673/69906617-90ae0f00-13c6-11ea-96da-8477d40d79e5.PNG)

Upon a quick check, I found that this is not implemented here (missing `case (FAVORITE_CONTEXT)`:
https://github.com/zowe/vscode-extension-for-zowe/blob/0c813f2ef7c1ae5e9d2a88b891f578df19f1bf00/src/extension.ts#L1527-L1539

Compared to datasets, which has this case covered:
https://github.com/zowe/vscode-extension-for-zowe/blob/0c813f2ef7c1ae5e9d2a88b891f578df19f1bf00/src/extension.ts#L1483-L1497

Also, function name in error message is wrong. It should be `refreshUSS()` not `refreshPS()`.
https://github.com/zowe/vscode-extension-for-zowe/blob/0c813f2ef7c1ae5e9d2a88b891f578df19f1bf00/src/extension.ts#L1539

**Comment by stepanzharychevbroadcom** [comment]
Added fix in https://github.com/zowe/vscode-extension-for-zowe/pull/658
