### ISSUE TITLE
Regression: Dataset search not working

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#356]
On the current master the Dataset search favorite is returning a Cannot read property getSession of null

**Comment by jellypuno** [comment]
This is addressed in PR #353

**Comment by Colin-Stone** [comment]
Addition of the Optional credentials added a block of code that accesses a nodes session. This had not been populated on a dataset Session object and so when referenced was null.
Quick fix move the lines
`            const sesName = line.substring(1, line.lastIndexOf("]")).trim();
            const zosmfProfile = Profiles.getInstance().loadNamedProfile(sesName);
            const session = zowe.ZosmfSession.createBasicZosmfSession(zosmfProfile.profile);`
above the  `if (favoriteDataSetPattern.test(line)) {`

and then reference further below
`
                const node = new ZoweNode(line.substring(0, line.lastIndexOf("{")),
                    vscode.TreeItemCollapsibleState.None, this.mFavoriteSession, session);
`

**Comment by Colin-Stone** [comment]
> This is addressed in PR #353

But was this considered a GA item?.

**Comment by jellypuno** [comment]
> > This is addressed in PR #353
> 
> But was this considered a GA item?.

Yes. Issue #352 is part of 1.0 :)

**Comment by Colin-Stone** [comment]
Okay I thought it was coming next release as per..
@jalel01 jalel01 added this to the 1.1 Release milestone 3 days ago

**Comment by jellypuno** [comment]
> Okay I thought it was coming next release as per..
> @jalel01 jalel01 added this to the 1.1 Release milestone 3 days ago

yeah. @crawr and I were able to finish it last friday so we told him we can add it in v1.0

**Comment by Colin-Stone** [comment]
Duplicate of  #352
