### ISSUE TITLE
Include integration testing in build

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#357]
Can we do something to incorporate the VSCode integration test with the build or is this not possible?.

**Comment by jellypuno** [comment]
References: 
- https://code.visualstudio.com/api/working-with-extensions/continuous-integration
- https://github.com/Microsoft/vscode-test

**Comment by zFernand0** [comment]
Closing!
Currently we run the suite of integration tests in Theia on every PR.
More tests may need to be added (as described in #265)
