### ISSUE TITLE
Default panel height in Che is not ideal

### ISSUE THREAD

**Issue by ghost** [zowe/vscode-extension-for-zowe#358]
When I open Zowe Explorer after starting a Che workspace, the "Data Sets" panel takes up all available space and the other 2 panels are collapsed. The expected behavior is for each panel to use a third of the available space, which is what happens in VS Code.

| Che (Theia) | VS Code |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/50887074/69974865-17143f00-14f4-11ea-98a3-64295bbb8063.png) | ![image](https://user-images.githubusercontent.com/50887074/69975268-e1238a80-14f4-11ea-820d-7235f2e15aef.png) |

**Comment by t1m0thyj** [comment]
Confirmed this is still an issue with Theia 1.33.0 (using [this Docker image](https://hub.docker.com/r/t1m0thyj/theia-alpine)).

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
