### ISSUE TITLE
Copy a data set or member name

### ISSUE THREAD

**Issue by jalel01** [zowe/vscode-extension-for-zowe#367]
Add the ability to copy a data set or member name.

Right clicking on the data set / member name would offer an option to copy the name to your clipboard.

Use case: i want to create a new dataset using an existing data set name. I copy the name of the existing data set, create a new data set, then paste the name of the existing data set and modify it with a '2' at the end to give it a unique name.

**Comment by Alexandru-Dumitru** [comment]
Hi @jelaplan. 
Could we have your input on this one?
I was looking into it, and VS Code does not provide this functionality in their context menu by default. Is it something we want to add?

By default we have `copy`, `copy path`, `copy relative path`, and if I want to get the file name, I would do `rename` -> this would open the file in edit mode within the tree with the name pre-selected (without the extension), then I can do the `ctrl+c` to get the name in clipboard -> afterwards, I can paste it wherever I need it.

Thank you.

**Comment by katelynienaber** [comment]
Also an additional question...we could add the `copy name` option to the data set, the member, or both...perhaps both would be overkill, and then we should choose one. What do you think?

**Comment by MikeBauerCA** [comment]
Let's run this by @jelaplan. I am cautious about adding unnecessary options to the right-click menu. In the Zowe Explorer, you can already copy the name by clicking rename and copying from there.

**Comment by katelynienaber** [comment]
Okay. I am new to this...do you think he will respond to the pull request
as it is?

Thanks,
-Katelyn Nienaber
+420 725 503 110
katelyn.nienaber@broadcom.com

**Comment by jelaplan** [comment]
Hi Katelyn
Nice to have you join the team. 

I would prefer to not add an additional menu option. A user can use the rename menu option to achieve the same result. While that label maybe not as clear, adding additional menu options makes scanning the menu that much harder so makes it that much harder to use the menu. I think that over time, we will see a push to add additional menu items and I'd like to carefully manage the tension between additional capabilities with cluttering the menu.
