### ISSUE TITLE
"Copy Data Set" and "Paste Data Set" listed twice in Data Set context menu

### ISSUE THREAD

**Issue by lauren-li** [zowe/vscode-extension-for-zowe#369]
- Zowe Explorer v1.0.0
- So far I have only noticed the "Copy Data Set" and "Paste Data Set" duplication occurring for non-favorited sequential data sets:

![Screen Shot 2019-12-05 at 3 35 57 PM](https://user-images.githubusercontent.com/45975633/70271854-3a015600-1775-11ea-863c-c3b5c692724c.png)

**Comment by lauren-li** [comment]
I'm also seeing duplication occurring for the inline `refreshNode` menu item for sequential data sets (both favorited and non-favorited).

Favorited sequential data set:
![Screen Shot 2019-12-06 at 3 06 26 PM](https://user-images.githubusercontent.com/45975633/70352953-4c919300-183a-11ea-9ae9-06d82c718edd.png)

Non-favorited sequential data set:
![Screen Shot 2019-12-06 at 3 06 46 PM](https://user-images.githubusercontent.com/45975633/70353050-7cd93180-183a-11ea-953a-ee800723a5d6.png)

**Comment by zFernand0** [comment]
Thanks @lauren-li
