### ISSUE TITLE
Re-Prompting of Credentials

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#370]
If I'm prompted for credentials and I entered wrong information, I do not know how to correct it. 
A button for Re-Prompting for credentials might be good.

Workaround: refresh the vscode workspace

**Comment by jellypuno** [comment]
It's better to implement #354 first then this one.

**Comment by MikeBauerCA** [comment]
Instead of a button, the user should be automatically re-prompted if the service informs of invalid credentials.

**Comment by sladyn98** [comment]
I could give this a shot, any pointers on how to begin ?

**Comment by zFernand0** [comment]
Hey @sladyn98, 
As @jellypuno mentioned, it'd be ideal to centralize the prompting mechanism so that we don't implement the same logic in multiple places (should we need to).

Also, do we want to re-prompt if we where not able to verify the credentials?

How about the host and port? (could be validated with a `zosmf check status` which doesn't require credentials)

**Comment by sladyn98** [comment]
Thanks @zFernand0 
> Also, do we want to re-prompt if we where not able to verify the credentials?

Yeah it would be good practice to re prompt if we aren't able to verify the credentials.
 
>How about the host and port? (could be validated with a zosmf check status which doesn't require credentials)

I am not too familiar with zowe but is this related to the zowe cli ?

**Comment by zFernand0** [comment]
`zosmf check status` is related to the CLI, but I meant to say the `/zosmf/info` endpoint to verify that the host and port are Ok :)

**Comment by sladyn98** [comment]
Okay so basically we want to reprompt for credentials on these conditions
1) Invalid Credentials
2) Human Error in entering Credentials.

**Comment by jellypuno** [comment]
> `zosmf check status` is related to the CLI, but I meant to say the `/zosmf/info` endpoint to verify that the host and port are Ok :)

Issuing zosmf check status in every profile can result to slowness of the vscode extension. I really do not like using this command to check the host and port. That is why I am leaning more for the edit button or just re-prompt it if 401 is encountered.

**Comment by jellypuno** [comment]
#580
