### ISSUE TITLE
Keypoints:

### ISSUE THREAD

**Issue by yohighness317** [zowe/vscode-extension-for-zowe#371]
Keypoints:
- Look for the `.zowe` config.overrides to make sure that the global CLI is using a credential manager or not.
- Implementation of the keytar module will need to know about the `service` name used either by the plugin, or the default Credential Manager.

_Originally posted by @zFernand0 in https://github.com/zowe/vscode-extension-for-zowe/issues/318#issuecomment-562173376_

**Comment by zFernand0** [comment]
Closing since this is already being discussed on #318
Will re-open it at a later time if we need to cover something in more detail.
