### ISSUE TITLE
Optional Credentials: Prompt* as value for Username and Password

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#373]
I don't want to save my credentials in ZOWE CLI so I created a profile with --user prompt* and --pass prompt* so that whenever i use it, I will be prompted for my credentials. 

The issue is that Zowe Explorer reads it as a regular user and password so I have a 401 error. 

There are 2 possible fix for this:
1. To handle "prompt*" in the validation of promptCredentials()
2. Change the approach of Optional Credentials and create profiles with prompt* as values for user and password. So that whenever you use the profile with Optional Credentials you will be prompted both in Zowe Explorer or Zowe CLI.

**Comment by jellypuno** [comment]
Limitation: prompt* doesn't work in secure credential store 😞

**Comment by zFernand0** [comment]
I added an issue in the secure credential store plugin so that we don't forget about this. Will reference it once the plugin is contributed to Zowe 👍

**Comment by MikeBauerCA** [comment]
The Zowe CLI should be enhanced so that all profile fields are optional and when running a command if an option is not supplied and there is no default option, the user is prompted.

**Comment by jellypuno** [comment]
This issue was handled in v.1.6.0 "Fix failure to load optional secure fields from profiles."

Originally I have an issue with SCS so I wanted to implement this. But since @tjohnsonBCM implemented his change, this is no longer a problem.
