### ISSUE TITLE
Username should be optional in profile

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/vscode-extension-for-zowe#375]
On the 1.0.0 release, I tried to create a profile without a username or password so that I would be prompted for both when using that connection. The prompt indicated username was optional:
![image](https://user-images.githubusercontent.com/35504792/70347901-84470d80-182f-11ea-97a4-4d56d3553f56.png)
However, I receive the following error once I finished entering the profile info:
![image](https://user-images.githubusercontent.com/35504792/70347980-b22c5200-182f-11ea-807c-de102bd41af7.png)

I'll note that it works well for me when I enter a username but not a password.

**Comment by jellypuno** [comment]
Created a fix on PR #378
