### ISSUE TITLE
USS file names should not end with the profile name

### ISSUE THREAD

**Issue by phaumer** [zowe/vscode-extension-for-zowe#38]
When loading a file in USS it gets open as a file with the name such as 
`/Users/user/resources/temp/profile/u/hlq/projects/COBOL/SAMPLE.cbl[profile]`

This is a problem for the editor recognizing the filetype, e.g. it being a COBOL file as it does not end with a proper file extension. The file name needs to end with .cbl and nothing else.

**Comment by Colin-Stone** [comment]
I think this the hlq is the profile reference and is used to identify what profile this files stored on local is associated with when performing an upload. When we address this we will need an alternative technique to associate with the profile.

**Comment by Colin-Stone** [comment]
Reworked the profile information on USS files so it is included earlier in the local file structure
