### ISSUE TITLE
Cyclic dependencies

### ISSUE THREAD

**Issue by phaumer** [zowe/vscode-extension-for-zowe#381]
The extension code currently contains cyclic dependencies that make it very hard to maintain. This is best showcased by several modules importing the `extension` file itself although the extension is creating objects of the modules that import it; for example ZoweNode and DatasetTree.  We should define clean abstractions for the data structures initialized in extension, move all the business logic out of extension and keep it as a pure initializing module only that creates all the other abstractions during activation.

**Comment by zFernand0** [comment]
In order to reduce the amount of circular dependencies, it'd be good if we moved the "Globals" constants (along with the `defineGlobals` function) from `./src/extension.ts` to its own file :smile:
@Colin-Stone @phaumer, any thoughts?

**Comment by Colin-Stone** [comment]
I agree. My focus has been the `move all the business logic out of extension ` aspect of Peter's recommendations by creating the interfaces and implementing in the individual classes as #497 The definition of globals separately from extension.ts makes a lot of sense and should clean up a lot of the circular dependencies

**Comment by zFernand0** [comment]
Closing in favor of #678
