### ISSUE TITLE
Support editing filters

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#386]
The Zowe Explorer extension will list the previous filters that you have created and you can one click the filter and it runs. I'd like to consider not running the filter but instead when picking from the menu, show it in the text box and then have the user press enter to run the filter. This would allow users to edit the filter, append additional filters criteria, etc.

**Comment by MikeBauerCA** [comment]
I like the idea of being able to edit the filter history without navigating into the `settings.json` of the extension. It would be nice if the edit capability could be implemented in such a way that selecting an existing filter would not require an extra key press.

**Comment by zFernand0** [comment]
There is a workaround for this. : )
Steps:
1. Click on the magnifying glass (search) 
2. Click the filter you want to edit (It will run it, I know... just keep reading 😄 )
3. Click on the magnifying glass (notice that the filter you just clicked, moved to the top of the list)
4. Click on `Create a new filter`
5. Edit the filter :+1:
