### ISSUE TITLE
Update Top level Readme Tip with link to docs/Readme-Theia.md

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#392]
Is it possible to add a link on the top level readme file that directs people to `https://github.com/zowe/vscode-extension-for-zowe/blob/master/docs/README-Theia.md`

It could be as simple as updating the Tip on the first section of the Readme. : )
![image](https://user-images.githubusercontent.com/37381190/70535655-6cbb9d80-1b2b-11ea-8ee8-4f88d3f211e7.png)

_Originally posted by @zFernand0 in https://github.com/zowe/vscode-extension-for-zowe/issues/343#issuecomment-564044815_

**Comment by IgorCATech** [comment]
Absolutely, Fernando! Let me see...

**Comment by zFernand0** [comment]
Feel free to open the PR whenever you get a chance :) 
Thanks a lot!
