### ISSUE TITLE
Tree view is not refreshed for PDS member actions

### ISSUE THREAD

**Issue by crawr** [zowe/vscode-extension-for-zowe#398]
The tree view is not updated when the following actions are performed on a PDS:
- Upload Member
- Delete Member

Note: This applies to both Theia and VSCode

**Comment by zFernand0** [comment]
Workaround:
Close and reopen the "folder" (PDS) :)

**Comment by crawr** [comment]
Yep, I agree with this workaround. I raised the issue because Rename Member action refreshes the tree view and I was expecting the same behavior for Upload and Delete actions.

I will tag it as enhancement request :)
