### ISSUE TITLE
Inconsistent behavior for renaming USS files and directories

### ISSUE THREAD

**Issue by crawr** [zowe/vscode-extension-for-zowe#399]
In VSCode, the following error is encountered when trying to rename USS file or directory:

![rename USS](https://user-images.githubusercontent.com/45845502/70549594-c300fe80-1b74-11ea-9d4d-d5c61e33f9a1.PNG)

This works fine in Theia.

**Comment by zFernand0** [comment]
It might be just me, but I cannot perform a single rename operation. whether it's a text file, a binary file or a directory.
Should we look into this?

**Comment by jellypuno** [comment]
> It might be just me, but I cannot perform a single rename operation. whether it's a text file, a binary file or a directory.
> Should we look into this?

Same with me. I can't rename anything in USS.

**Comment by stepanzharychevbroadcom** [comment]
Added fix in: https://github.com/zowe/vscode-extension-for-zowe/pull/550

**Comment by zFernand0** [comment]
Fixed, but I'm still getting a bit of an issue with it. See #567
