### ISSUE TITLE
extension for *.cbl is not there

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#405]
I am not sure why but when I try to edit some of my programs the .cbl extension is not there. But if I open a different profile, the .cbl extension is there.

**Profile 1:**
![Capture](https://user-images.githubusercontent.com/45042840/70713020-712bb600-1ce5-11ea-9a5e-ee1f16762220.PNG)

**Profile 2:**
![Capture2](https://user-images.githubusercontent.com/45042840/70713849-30cd3780-1ce7-11ea-8e49-ef1c42a200cd.PNG)

**Comment by tjohnsonBCM** [comment]
The extension detects COBOL files if the dataset contains any of the following qualifiers: [`["COBOL", "CBL", "COB", "SCBL"]`](https://github.com/zowe/vscode-extension-for-zowe/blob/369e057441db5fbef1346e3c3038bef9444c4345/src/extension.ts#L1298).

The name of the dataset for Profile 1 doesn't contain any of those qualifiers, whereas the name of the dataset shown for Profile 2 contains "COBOL". Based on that, not sure if this is a bug or expected behavior.

**Comment by phaumer** [comment]
The `appendSuffix()` in `extension.ts` code looks only for these substrings: "COBOL", "CBL", "COB", "SCBL". The first data set does not match these patterns.  I personally think that Zowe Explorer should be language agnostic. VS Code users can achieve the same effect with VS Code settings, which are customizable. This hardcoded test is not. I would remove it.

```json
"files.associations": {
        "*.CBL*": "cobol",
        "*.COB*": "cobol",
       ...
}
```

**Comment by jellypuno** [comment]
ok... so maybe not a bug but an enhancement to handle library names? I am not sure. What do you think @MikeBauerCA ?

**Comment by jellypuno** [comment]
@phaumer, even if I try to add SOURCE in the file association, I still do not have the .cbl extension. I have the highlighting but not the extension. 

    "files.associations": {
        "*.COBOL*": "cobol",
        "*.SOURCE": "cobol",

![Capture](https://user-images.githubusercontent.com/45042840/70991579-08b74d00-20c8-11ea-94fe-7e8809be8f1e.PNG)

**Comment by MikeBauerCA** [comment]
> VS Code users can achieve the same effect with VS Code settings, which are customizable

This is certainly valid and if folks choose to do so, their settings should take precedence. Since not all users of the Zowe Explorer are aware of such settings, we currently try to default to the correct language. If we can influence the default file association from the extension without adding a suffix, that might be a better route.

@jellypuno in regards to the .cbl suffix not appearing, I think @phaumer was suggesting the pattern would need to be added to `appendSuffix()` in `extension.ts`. However, `.SOURCE` does not clearly suggest the member is COBOL. The file associations setting only determines what language to use for the match.

**Comment by jellypuno** [comment]
> However, .SOURCE does not clearly suggest the member is COBOL.

@MikeBauerCA yes, I agree. Is it safe to say that this is a limitation? That in order to have the *.cbl extension you need to have a dataset name with COBOL in it?

**Comment by MikeBauerCA** [comment]
I would agree that this is a known limitation and perhaps this issue can be closed for now. Ideally, we would be able to detect the language based on the file contents or something similar rather than relying on the name of the PDS.

**Comment by phaumer** [comment]
Any additional VS Code extension that provides the actual language support should take care of this. The Zowe Explorer should not make any assumptions for these language extension at all as it might have negative side effects. Hence, I would use this issue to actually remove the `appendSuffix()` completely.

**Comment by jellypuno** [comment]
> Ideally, we would be able to detect the language based on the file contents or something similar rather than relying on the name of the PDS.

I somehow do want to close this issue since there is a possibility of enhancing this in the future. It would be great to have this as a placeholder. But if you think that we should close it then I am ok with it.

Just an additional information, The reason that I am keen on having this *.cbl is because of Code4z. Since Zowe Explorer cannot download my programs with an extension then I cannot use the capabilities of Code4z (unless I rename it in the temp folder).

**Comment by Colin-Stone** [comment]
This is code I added based upon recommended IBM dataset naming standards some time back along with a few more extra helpers along the way. The intent was that by recognising default structures automatically and adding a suffix to the file when stored locally it would inherit the default syntax available. It was felt this was particulalry useful to new users of z/OS VSCode as they would be able to see syntax highlighting before concerning themself with updating settings etc

**Comment by jellypuno** [comment]
> The intent was that by recognising default structures automatically and adding a suffix to the file when stored locally it would inherit the default syntax available. It was felt this was particulalry useful to new users of z/OS VSCode as they would be able to see syntax highlighting before concerning themself with updating settings etc

@Colin-Stone I agree it is very useful for me. I would like to expand this feature. Regardless of the dataset naming convention, it would be great if Zowe Explorer can identify the program. 

Do you think we can make use of VSC Language mode in identifying the program and then update the extension of the file? Or it doesn't makes sense?

![Capture](https://user-images.githubusercontent.com/45042840/73081182-70cb3100-3ec7-11ea-94af-616689502174.PNG)

**Comment by Colin-Stone** [comment]
Thanks Jelly. Yes anything we can do to make it more flexible is beneficial. It would be good to see if it is possible to integrate with the language mode. I played a little superficially but didn't get very far investigating. Maybe a "spike" for further investication.

**Comment by Simnbf** [comment]
Hi all, conscious this hasn't been updated in a while. Has any further thought gone into this? Some other extensions require .cbl files in order to function.

**Comment by phaumer** [comment]
@Simnbf can you elaborate more on your use case?

Afaik a file extension is not required in VS Code. With "files.associations" you can map any data set to a language id. A VS Code extension that requires a specific extension is not designed using [the VS Code APIs](https://code.visualstudio.com/docs/languages/overview#_language-identifier) as far I understand it.

For example, if you write associations such as 

"files.associations": {
    "*.SAMPLE.TEST*": "cobol"
}

will map any file that matches this in its path to the `cobol` language id even though the word cobol is not used in the pattern.

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
