### ISSUE TITLE
Blank Command Response when issuing STOP command

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#410]
I issued a STOP command and the Command Response was blank. I am not sure if this is the expected behavior  or not.

![STOP command](https://user-images.githubusercontent.com/45042840/70921978-95f59580-2025-11ea-936c-582293c90899.gif)

![Capture](https://user-images.githubusercontent.com/45042840/70921995-9b52e000-2025-11ea-905d-7b373d7d885f.PNG)

**Comment by zFernand0** [comment]
If the stop command was successful (blank response), should we say something like `Job successfully stopped`?
Also, should we refresh the Job on the tree-view automatically?

**Comment by dkelosky** [comment]
I think depends on how the thing that you `STOP` responds.  The "thing" could be a job, STC, or TSO user.

For example, `STOP`ping CAHCHECK through the CLI gives two messages:
```
C:\dev>zowe console issue command "p cahcheck" --zosmf-p de20
 CAHC161I SHUTDOWN     command 782
 CAHC197I CAHCHECK SHUTDOWN acknowledged
```

Stopping a JVM:
```
C:\dev>zowe console issue command "stop THOJO24$"


```

How does TDMRASA1 respond when you stop it through the CLI or z/OS console or SYSVIEW XMVS?

**Comment by dkelosky** [comment]
Side note, it seems like additional options may sometimes be provided on a `STOP` command that may need to be exposed through the VS Code UI.  

Example, [`STOP QMGR MODE(RESTART)`](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.0.0/com.ibm.mq.adm.doc/q022170_.htm).

**Comment by crawr** [comment]
> If the stop command was successful (blank response), should we say something like `Job successfully stopped`? Also, should we refresh the Job on the tree-view automatically?

I like this idea. This could be a `good first issue`, too.

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
