### ISSUE TITLE
submit JCL in edit window without saving

### ISSUE THREAD

**Issue by Morridt** [zowe/vscode-extension-for-zowe#411]
New enhancement to allow right click in edit window to submit JCL, currently in the edit window, without having to save first.

This will also then allow submit of JCL for jobs where "Get JCL" has been requested.

**Comment by crshnburn** [comment]
This is possible today using the 'Submit JCL' command from the command palette. If you have some JCL open in the current editor and open the command palette (`⌃⌘P` on Mac) and select **Submit JCL** it will then give you a list of profiles to choose from and submit the contents of the editor to the selected server. This also works for the JCL rom the **Get JCL** command.
