### ISSUE TITLE
Abstraction of NodeActions

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#412]
As an extension of #328 

The extension class contains too many functions that are specific to Jobs, USS, MVS. These should be stripped out to the appropriate section either associated with a node or tree. These functions should reside in the ...NodeActions files. 

Since abstracting the tree and node classes we are also able to create a DefaultNodeActions.ts file which may also be a better location for some of the utils function.

The rationale of all of this is that it futher untangles the code and highlights duplication which we can then reduce. It also makes maintainability better and makes it simpler to extend

**Comment by jellypuno** [comment]
@Colin-Stone Can you write a technical document regarding these changes? together with #328? Even if it is just a simple flowchart. I think it would be really helpful for future enhancements. What do you think?

**Comment by Colin-Stone** [comment]
Duplicated and fixed by #652
