### ISSUE TITLE
Cannot Add New Profile by typing the profile name

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#415]
If I clicked the + sign and I type the profile name I should be allowed to either load the profile if existing or create a new one if it does not exist. 

An error message "Could not find profile named: <profile name>" appears instead. 

This is because of the changes in #377. Specifically in line #649 in extension.ts where the chosenProfile is expected to be equal spaces.

@phaumer if we change the code back for the validation of chosenProfile from ` if (chosenProfile === "") {` to  `if (chosenProfile !== choice.label) {` what would be the effect in theia? Can we have a separate process for theia instead?

![CannotAddProfile](https://user-images.githubusercontent.com/45042840/71008925-bab34100-20e9-11ea-8a57-1fdb9d426781.gif)

**Comment by phaumer** [comment]
Thanks. I will have a look.

**Comment by phaumer** [comment]
@jellypuno I cannot reproduce the error you see. If I select that "+ Create a New Connection to z/OS" the test `choice instanceof utils.FilterDescriptor` will be true and the chosenProfile will be set to empty string, which is then used to indicate that a profile needs to be create in line 649.

**Comment by phaumer** [comment]
@jellypuno could you try the fixed I proposed in PR #432?

**Comment by jellypuno** [comment]
Hi @phaumer, It is continuing but I am now entering the connection name twice.

So the enhancement before was that I will search for the profile name in the dialog box. If the name doesn't exist, it will continue to create a new connection . The next dialog box would be the "Enter URL and Port".

If I didn't enter a name and I clicked "Create New Connection" then the dialog box for "Enter a name for the connection" should appear.

**Comment by phaumer** [comment]
@jellypuno oh, isn't that confusing? You are using the same text box for two semantically different operations depending on some context that is not easily discoverable for the end-user without reading documentation. I think the current solution is more transparent.  Also, how would this work if you wanted to create a connection that is a sub-string of an existing connection?

**Comment by jellypuno** [comment]
@phaumer this approach has already been approved in issue #226 and was implemented in v1.0.0. It was only remove when it was fixed for theia. Is it affecting theia if you implement that feature? if yes, then we need to discuss this with UX.

> Also, how would this work if you wanted to create a connection that is a sub-string of an existing connection?

Also, I don't understand what do you mean by this.

-----

@jalel01 @MikeBauerCA @jelaplan Can you please check if the UX for adding profiles is ok now? It looks like this today:

New Process:
1. Search a profile
2. If not found, press enter to create the profile
3. Enter the connection name
4. Enter URL ... and so on.

![addingprofile](https://user-images.githubusercontent.com/45042840/71884158-0df04080-3138-11ea-9470-3d800a1446d4.gif)

Before, the process is like this:
1. Search a profile
2. If not found, press enter to create the profile. The profile you are searching will be used as a profile name.
4. Enter URL ... and so on.

**Comment by crawr** [comment]
The behavior to enter the connection name twice is inconsistent with the rest of the extension. For example, if you want to filter/search a pattern, you start typing and if it doesn't match any of your previous entries, it will take the default action. 

See:  https://github.com/zowe/vscode-extension-for-zowe/pull/287#issuecomment-553866663

**Comment by jalel01** [comment]
@jellypuno  If we can avoid entering the connection name twice then it matches what we agreed on previously under #287. I think that would quickly become frustrating.

**Comment by phaumer** [comment]
Ok, I will revisit it one more time.

**Comment by jellypuno** [comment]
Fix was added in #525
