### ISSUE TITLE
Create Profile: Skip the create new step when there are no profiles to list

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#417]
The goal is to remove a step for the user to make the effort simpler for creating a connection. 

When creating a new connection (e.g., click + button), the system prompts the user to either create a new profile or to choose an existing profile. But, if there are no existing profiles, then the only route is to click the create new option. I'm asking to eliminate that step and go strait to the create-new form.  This would help the user by saving a step and not having to read the instructions. This is a don't make me think kind of change. 

Here is how the dialog/popup appears. 
<img width="725" alt="image" src="https://user-images.githubusercontent.com/3207260/71013644-04d2fd00-20bf-11ea-82bd-8ff20fcee16d.png">

Here is the second step. I'm proposing to go strait here. 
<img width="723" alt="image" src="https://user-images.githubusercontent.com/3207260/71013780-161c0980-20bf-11ea-8c79-8e10ebcf895b.png">

Here is the flow diagram that I created when we started the project. 
![image](https://user-images.githubusercontent.com/3207260/71014998-dce49900-20c0-11ea-83bf-7f79245392ae.png)

**Comment by crawr** [comment]
Hi @jelaplan , this was the behavior implemented in PR #335 . You just start typing and if the connection name is not found, the 'Create a New Connection to z/OS' is the default choice.

This feature was removed when the Theia route was introduced and issue #415 is open for this.

**Comment by jellypuno** [comment]
#580
