### ISSUE TITLE
Don't show an error message when adding a z/OSMF URL until press enter

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#418]
When creating a new connection, the system prompts for a URL. The prompt includes a useful instruction. But as soon as I type a character, the system presents an error message.  This is problematic for two reasons:

1. It announces you made a mistake when no mistake has been made. The user is just typing the URL. We shouldn't be telling people they've made a mistake when they haven't
2. The useful instructions become hidden thus inhibiting a valuable queue to the user

![image](https://user-images.githubusercontent.com/3207260/71016096-a6a81900-20c2-11ea-8aab-773256a64ba7.png)

![image](https://user-images.githubusercontent.com/3207260/71017655-e1ab4c00-20c4-11ea-9bbb-eeb606368c5c.png)

**Comment by katelynienaber** [comment]
Closed in pull request [#436](https://github.com/zowe/vscode-extension-for-zowe/pull/436)
