### ISSUE TITLE
The valid URL error message could include what is a valid URL

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#419]
When a user types in a mal-URL, the system warns the user with a message that says is is not right but doesn't say what is right. 

Here is how it appears today
![image](https://user-images.githubusercontent.com/3207260/71017862-541c2c00-20c5-11ea-82a7-0f0ad00ded7b.png)

Here is an update
<img width="701" alt="image" src="https://user-images.githubusercontent.com/3207260/71017889-68602900-20c5-11ea-996b-1327ccb33535.png">

**Comment by katelynienaber** [comment]
Closed with pull request [#434](https://github.com/zowe/vscode-extension-for-zowe/pull/434)

**Comment by katelynienaber** [comment]
Closed with pull request [#434](https://github.com/zowe/vscode-extension-for-zowe/pull/434)
