### ISSUE TITLE
Add support for API Mediation Layer to the Zowe Explorer Connections to further allow the extension stand on its own

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#420]
When creating a new connection, it is not possible to add the base path value. This base path is needed by the API Mediation Layer. A core goal of the original project to add connections was to make Zowe Explorer stand alone and independent of the Zowe CLI. If a user wants to use the API Mediation Layer with Zowe Explorer, she will need to use the CLI to create a workable profile.

When issuing commands or creating profiles on he Zowe CLI, there is an option for base path (e.g., --base-path).

In Zowe Explorer, I tried adding the base path to the URL when creating a profile. I didn't get an error but the path was not added to the profile. 

Here is how the prompt appears today.
![image](https://user-images.githubusercontent.com/3207260/71019015-934b7c80-20c7-11ea-9780-7a9b415c83fe.png)

Here is a design idea
<img width="650" alt="image" src="https://user-images.githubusercontent.com/3207260/71021530-95640a00-20cc-11ea-8c0e-935292036cb1.png">

A complication is that the additional text in the instruction may make it harder to read (e.g., /basePath). 

Note, both the port and the base path are optional. We don't today convey that the port is optional. If the user doesn't enter a port, the system defaults to 443. Conveying this is tricky because extra instruction text makes it harder to read. Comments?

**Comment by MikeBauerCA** [comment]
In the CLI, the protocol is not part of the profile (it is currently defaulted to `https`). What does entering the protocol in this case do? This might be a separate issue.

We could use more complex syntax to designate default values and optional parameters but I think we should try to stay simple and more human readable.

Placeholder text: `host:port/basePath`
Description: `Enter a z/OSMF URL in the format host:port/basePath. The default port is 443 and basePath only needs specified when using an API mediation layer.`

**Comment by jelaplan** [comment]
@MikeBauerCA I agree that https should be optional. You are proposing excluding it which I think would be better than making it mandatory and would work more like the create profile in the CLI.

**Comment by crawr** [comment]
Closed by PR #717
