### ISSUE TITLE
Streamlining the Job Workflow

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#421]
I tested the job submission process and this is what I found. 

1. I right click on a JCL file and choose Submit Job
2. A message appears in the lower right corner. It contains a link to the job number. 
3. I click on the job number and the job panel is updated to show the job output. 
4. I can go to the job panel and explore the output. 

I'm wondering why we don't just show the output in the job panel without the intermediate step. This situation reminds me of issue [385](https://github.com/zowe/vscode-extension-for-zowe/issues/385) because it anticipates the information that the user will want to see. 

When I tried to delete the job output by clicking the trash icon, I get a message that it has been deleted but the record remains in the job panel. If I click the refresh icon, it disappears from the job panel. I would think the record would disappear when it is deleted. 

https://www.screencast.com/t/rs1FTd1dZt

**Comment by zFernand0** [comment]
> When I tried to delete the job output by clicking the trash icon, I get a message that it has been deleted but the record remains in the job panel. If I click the refresh icon, it disappears from the job panel. I would think the record would disappear when it is deleted.

Should we record this as a separate issue?

**Comment by jellypuno** [comment]
What is the issue here? You don't want to click the JobID in the message?

**Comment by jelaplan** [comment]
@jellypuno Yes, the issue is that I don't want to click the JobID. I want the results to appear. But, I talked to @MikeBauerCA and he said that jobs may take a long time to complete so it may not be reasonable to expect to immediately show the job results or suddenly show them 37 minutes later. So, I'm not sure if this is a good request. But in my situation where jobs run quickly, I'd rather the jobs panel just highlight the results. Part of the odd flow here is that the datasets and jobs are separate trees and the information is loosely connected in the interface but closely connected logically.
