### ISSUE TITLE
Add to filter tip to convey ability to add multiple filters entries. 

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#422]
@morridt commented in [385](https://github.com/zowe/vscode-extension-for-zowe/issues/385) that he didn't realize that the extension supports adding multiple filter strings. To help users to get the most our of search, we could change the tip to inform them. 

![image](https://user-images.githubusercontent.com/3207260/71035402-6314d580-20e9-11ea-8877-5e9a838de96c.png)

**Comment by katelynienaber** [comment]
Cosed in pull request [#437](https://github.com/zowe/vscode-extension-for-zowe/pull/437).

**Comment by zFernand0** [comment]
Should this go under the 1.2 milestone?
