### ISSUE TITLE
Zowe Explorer failed to activate

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#424]
Scenario: 
1. Clean machine without Zowe CLI and Zowe Explorer. 
2. I installed Zowe Explorer for the first time
3. During activation of the extension, the error message appears:

![unnamed (2)](https://user-images.githubusercontent.com/45042840/71077097-141d7d80-2187-11ea-8e6f-312179339636.png)

We have experienced this error before and the fix was to add a validation in Profiles.refresh() so that the error "No Default Profile" will be displayed. I don't know why this is happening again 😢 

```
            if (this.allProfiles.length > 0) {
                this.defaultProfile = (await profileManager.load({ loadDefault: true }));
            } else {
                ProfileLoader.loadDefaultProfile(this.log);
            }
```

**Comment by zimlu02** [comment]
Hi, I face the same issue on Mac.

**Comment by jellypuno** [comment]
#427

**Comment by jalel01** [comment]
I'm still seeing the same error message even when installing 1.1

**Comment by jellypuno** [comment]
Installing NodeJS fixes the problem
