### ISSUE TITLE
zOSMF server. How to get my hands on to one?

### ISSUE THREAD

**Issue by HeinekenBilly** [zowe/vscode-extension-for-zowe#433]
Hello, 

I'm working on a project of my own and I would need this CLI tool to do testing. but unfortunately I can't get access to zosmf. How you guys test this project?

**Comment by katelynienaber** [comment]
Hi Heineken :)

Try this guide, one of our software engineers has written it for just this reason: https://medium.com/zowe/beginners-guide-how-to-access-mainframe-via-zowe-in-10-easy-steps-fbec14ed6ed2

Scroll down to: **10 easy steps to access Mainframe via Zowe**

**Comment by HeinekenBilly** [comment]
Thank you Very Much and Happy new Year.
