### ISSUE TITLE
Standardize on a code formatter and style guide

### ISSUE THREAD

**Issue by phaumer** [zowe/vscode-extension-for-zowe#438]
I see different code formatting in different files. For example, line length and indentation is used differently in different places. Using a code formatter such as the built-in VS Code TS formatter or Prettier seems impossible right now as it would change files completely. The differences and inconsistencies make code hard to read and if developers would apply formatting in a file, merging would become really hard as one cannot see the real changes from formatting changes.

VS Code extensions such as Prettier together with tslint allow standardizing on formatting rules (using prettierrc files and tslint rule files) and enforce those (e.g by requiring a format on save using workspace settings.) After the settings files are committed and voted on we would format all files in one commit to switch over to the new format everywhere at once.

In addition using a style guide for other conventions such as naming modules, types, and variables could be used to improve consistency and maintainability of the code as well.  A written style guide would help reviewers as a checklist to identify issues.

**Comment by phaumer** [comment]
If the team see value in this item I would volunteer to make a proposal.

**Comment by zdmullen** [comment]
Hey @phaumer, is this done? Can we close this issue? Thanks

**Comment by crawr** [comment]
eslint and prettier applied to monorepo
