### ISSUE TITLE
Create vsix deployment pipeline

### ISSUE THREAD

**Issue by katelynienaber** [zowe/vscode-extension-for-zowe#441]
As a Zowe Explorer developer, i want to build and package the latest development version of the Zowe Explorer in the Zowe Artifactory.

**Comment by zFernand0** [comment]
Do we want these snapshots to be taken right after the build?
This way, even if the test fail, you stilll have a snapshot-vsix uploaded to the zowe artifactory for debugging purposes (if needed).

**Comment by katelynienaber** [comment]
Yes I can move it, updates will be in the pull request in like 5 minutes...

**Comment by jellypuno** [comment]
Referencing #456

**Comment by katelynienaber** [comment]
This was addressed in PR #443
