### ISSUE TITLE
Add Support for Code Page Setting

### ISSUE THREAD

**Issue by dkelosky** [zowe/vscode-extension-for-zowe#445]
This issue is a placeholder to track extending https://github.com/zowe/zowe-cli/issues/632 to the VS Code extension for Zowe.

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
