### ISSUE TITLE
Extension updates settings during activation breaking Theia

### ISSUE THREAD

**Issue by phaumer** [zowe/vscode-extension-for-zowe#446]
During the initialization in DatasetTree.ts the extension updates the settings, i.e. writes the user settings file adding/updating a Zowe-DS-Persistent object. 

In Theia activation of VS Code extensions happens late and the file that gets updated in /Users/username/.theia/settings.json after it was already read (started in Theia 13) making Theia prompt the user several times showing the dialog below.

Investigate if that write is needed at during initialize or find a workaround as it breaks the user experience as well as test automation.

![image](https://user-images.githubusercontent.com/4391934/72131106-27f47380-3330-11ea-8c4d-8485f2df9403.png)

**Comment by crawr** [comment]
Hi @phaumer , I don't know if you saw issue #317. I think it could be related. I also opened a linked issue in Theia repository and the Eclipse team is working on a fix.

**Comment by phaumer** [comment]
Duplicate to #317
