### ISSUE TITLE
Manual deletion of a profile blocks Zowe Explorer extension

### ISSUE THREAD

**Issue by zimlu02** [zowe/vscode-extension-for-zowe#455]
1. Manually delete any profile in use in "/.zowe/profiles/zosmf" folder
2. Restart VSC and open Zowe Explorer
3. Error message: "Profile "xxx" of type "zosmf" does not exist."
4. No other existing profiles are shown in ZE, all disappeared 
5. When trying to create a new profile using the "+" button, another error message pops up:  "command 'zowe.addSession' not found"
6. This happens also when the profile was previously "removed" using the UI action or Zowe CLI command, but it remains in Favorites (which is actually also weird behavior). This is how I found this issue - I was trying to clean up the profiles folder and didn't notice they still hang in favorites...

**This defect is probably covered by issues #332 and #423**

**Comment by zimlu02** [comment]
please also check the behaviour of USS and JOBS tab - it behaves but different from Datasets:
if I manually remove the profile used there, it will simply disappear from the list after the restart. Also it reflects manual renaming of the profiles...

**Comment by crawr** [comment]
Solved in v1.5. The Zowe Explorer should still display an error message regarding the missing profile, but it should not block the activation of the extension.

Can you please confirm that this can be closed @zimlu02 ?

**Comment by zimlu02** [comment]
> Solved in v1.5. The Zowe Explorer should still display an error message regarding the missing profile, but it should not block the activation of the extension.
> 
> Can you please confirm that this can be closed @zimlu02 ?

Yes, I do confirm. I like the behavior now, please you can close the ticket.

The only thing I am not sure is this part of the error message:
"To resolve this, you can create a profile with this name, or remove the favorites ..."

If the user creates another profile with the same name but points to a different place, it can possibly bring confusion. Wouldn't it be just safer to leave out this part of the message and keep just the advice to drop the missing favorite item...?

**Comment by crawr** [comment]
Thanks for confirming. Created a separate issue to track the enhancement to the error message
