### ISSUE TITLE
Creating a new member within a new PDS errors

### ISSUE THREAD

**Issue by lauren-li** [zowe/vscode-extension-for-zowe#469]
On the latest version of `master` branch (pulled Jan 24, 2020):
When saving a newly-created and edited member within a new PDS, the error `Cannot read property 'setEtag' of undefined` appears upon saving. Additionally, after saving the edited member and refreshing the Data Sets explorer view, PDS "folders" in the Data Sets explorer do not expand. I did not encounter these issues when trying the same for the USS explorer.

**Recreate steps**:
1. In the Data Sets explorer, create a new partitioned (PDS) dataset. 
2. Under the new dataset, create a new member. (The new member automatically opens in an editor window.)
3. Type some text into the new member’s editor window, and Save.
  - Upon saving, the following error appears: `Cannot read property 'setEtag' of undefined`
  ![Screen Shot 2020-01-24 at 3 43 13 PM](https://user-images.githubusercontent.com/45975633/73103105-55f5be00-3ec1-11ea-8aec-77356fea3d33.png)

4. Refresh the Data Sets explorer by clicking the Refresh arrow icon.
5. In the Data Sets explorer tree, try expanding any PDS “folder”.
  - PDS “folders” do not expand.
  ![Screen Shot 2020-01-24 at 2 45 01 PM](https://user-images.githubusercontent.com/45975633/73103178-7e7db800-3ec1-11ea-98b4-4ddb18e4fcb0.png)

**Comment by zFernand0** [comment]
Similar behavior occurs when Uploading a member.
However, all members get successfully created.

To workaround the issue, Open the PDS (folder) right after creating the member, and you should see all your uploaded and created members 😄

**Comment by zFernand0** [comment]
Not sure, but this might be related to #398

**Comment by jellypuno** [comment]
I create members without any errors

**Comment by zFernand0** [comment]
@lauren-li, could you confirm this is not an issue anymore?

Could we have this in a milestone?

The main reason for asking for milestones is so that in the future, we could look into automating release notes based on milestones alone.
Meaning having the Changelog updated by getting the issues resolved in the milestone and thanking the people assigned to said issue.

@Colin-Stone, @jellypuno, any thoughts on this?

**Comment by jellypuno** [comment]
@zFernand0 I'm okay with that. I tagged it to 1.3.0 temporarily cause that's what I've used to test it. :)

**Comment by lauren-li** [comment]
@zFernand0 I tested and don't see this issue occurring anymore from the latest master branch. I'm okay having this as part of a milestone. Thanks for checking with me about it!
