### ISSUE TITLE
Copy and Rename is taking a long time to re-load

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#470]
This is related to issue #327 

I have a dataset with 30k members. I am able to load and edit it normally but when I tried to copy and rename a member, the re-load for the tree is taking a long time. It took at least 5 mins before this error message appears:

![Capture2](https://user-images.githubusercontent.com/45042840/73161116-16aab580-40eb-11ea-8277-0e5a7b210adc.PNG)

**Comment by stepanzharychevbroadcom** [comment]
@jellypuno With **rename** the reason is we do parent node refresh, instead of just element refresh. So I guess it should be reworked.
`renameDataSet`(of extension.ts) method is the target for such changes.
Also what should be refactored - the fact we do such changes even if rename request has failed, you can see it in the same method.

**Comment by stepanzharychevbroadcom** [comment]
@jellypuno I checked how rename works for the dataset, in the case if it fails further rename operation will be prevented, so only refresh should be refactored.

**Comment by CForrest97** [comment]
Is the issue only when renaming members? If so that is handled by `renameDataSetMember`. The parent node is refreshed here too but it looks like that isn't needed

**Comment by jellypuno** [comment]
@CForrest97 In issue #327 , there is a BOX link (in the end) of the research that I have concerning this.

**Comment by CForrest97** [comment]
@jellypuno Ive created a branch which should fix renaming members for large data sets, once Ive done some more testing I can create a PR for this and take a look at copying too https://github.com/zowe/vscode-extension-for-zowe/tree/470-rename-members-fix-for-large-sets
