### ISSUE TITLE
Extension doesn't load first time Che workspace is started

### ISSUE THREAD

**Issue by tjohnsonBCM** [zowe/vscode-extension-for-zowe#477]
In the Che4z stack, Zowe Explorer doesn't load the first time a workspace is opened. It is necessary to press F5 to refresh the page in order for the extension to load.

This issue seems more likely to happen when there are several other plugins present in the workspace that must also load at startup. The stack used for testing had the following plugins installed:
```
  - type: chePlugin
    reference: 'https://github.com/eclipse/che-che4z/raw/1.0.0/plugins/cobol-language-support.yaml'
    alias: cobol-language-support
  - type: chePlugin
    reference: 'https://github.com/eclipse/che-che4z/raw/1.0.0/plugins/cobol.yaml'
    alias: cobol
  - type: chePlugin
    reference: 'https://github.com/eclipse/che-che4z/raw/1.0.0/plugins/explorer-for-endevor.yaml'
    alias: explorer-for-endevor
  - type: chePlugin
    reference: 'https://gist.github.com/tjohnsonBCM/e6f70262938a3853cdf0e6f33baa4d2a/raw/996fb5efbc7e6f4a1b68ed1d742fa64b2caceff0/rexx-syntax-highlighting.yaml'
    alias: rexx-syntax-highlighting
  - type: chePlugin
    reference: 'https://gist.github.com/tjohnsonBCM/6cf8bca7eaa933a231341db951d47ff5/raw/3d5e213abe04a9385489972102989c4239cb7630/che-typescript-language.yaml'
    alias: typescript
```

**Comment by tjohnsonBCM** [comment]
This issue may be caused by the non-standard way that Zowe Explorer is packaged in the Che4z stack. Research is being done how to bundle Zowe Explorer in a more standard way as a `chePlugin`, will update this issue once more details are known.

**Comment by MikeBauerCA** [comment]
@tjohnsonBCM is this still an issue? I noticed in my recent Che workspaces, the Zowe Explorer loaded initially, but perhaps this had a workaround implemented.

**Comment by tjohnsonBCM** [comment]
I believe this has been fixed, but currently the fix is only present in internal builds and has not been published yet.

**Comment by MikeBauerCA** [comment]
Closing as this is related to packaging the ZE explorer in a Che stack rather than ZE itself.
