### ISSUE TITLE
UX question - why copy member action is called "Copy Data Set"?

### ISSUE THREAD

**Issue by zimlu02** [zowe/vscode-extension-for-zowe#478]
I find it very confusing to right-click a PDS member and have "Copy Data Set" action item.
Could it be changed to "Copy Member"?

**Comment by jelaplan** [comment]
@zimlu02 @jellypuno The copy functionality is incomplete. The original intent was to allow copying and moving both datasets and members. Today, we have copying members which is labeled Copy Data Set. So, I agree with you that the label isn't right. But, we also are lacking the ability to copy  (and move) datasets themselves.  

![image](https://user-images.githubusercontent.com/3207260/73670721-c1851b80-4677-11ea-9df2-ad315d2b99e1.png)

**Comment by jelaplan** [comment]
Here are the stories around copying and moving datasets and members
[262 Allow Copy and Rename members in the VS Code](https://github.com/zowe/vscode-extension-for-zowe/issues/262)
[Copy and Move Members and Datasets](https://ent.box.com/s/lks9dmkxu8z6e2kgoni0q4mdv4sy43d3)
https://github.com/zowe/vscode-extension-for-zowe/issues/233
https://github.com/zowe/vscode-extension-for-zowe/pull/326

**Comment by jellypuno** [comment]
Hi @CForrest97 , Can you take a look at this issue. Do you think it is possible to change it to Copy Member if it is under a PDS?

**Comment by CForrest97** [comment]
Yeah I'd be happy to look at this, it shouldn't be difficult

**Comment by jellypuno** [comment]
> Yeah I'd be happy to look at this, it shouldn't be difficult

@CForrest97 Yey! Will you be able to implement it on the 1.3 release?

**Comment by CForrest97** [comment]
Yeah that should be no problem
