### ISSUE TITLE
Large Dataset pagination handling via Webview

### ISSUE THREAD

**Issue by stepanzharychevbroadcom** [zowe/vscode-extension-for-zowe#479]
As we know currently an extension has heavy problems connected with large datasets (tested on 30k members):

- Very slow loading time;
- Buggy reaction on user's actions (rename, create, etc.), though mainframe manipulates with data properly;
- Extremely unfriendly UX (imagine yourself scrolling 30k members to open something);

Pretty obvious solution is to limit number of members which user can see at once, but it produces another question: how to navigate to something what's not currently available? My suggestion is usage of Webview and custom command so we can create our own navigation and code it as we want. We can start from pagination, but later search is possible as well.

In branch `feature/dataset-member-inspector` I introduced pilot version of such functionality, which covers following scenarios:
1) Initialisation of Webview on-demand (and ability to get existing panel from other places of the code);
2) Showing of the paginated members of the dataset inside of the Webview;
3) Reflection of selected pagination inside of the file tree;
4) Reflection of errors inside of Webview in VSCode;

For better understanding with deps, I have chart:
![TreeWebView](https://user-images.githubusercontent.com/60000150/73465356-900f0600-4380-11ea-9684-7fd3df977c57.png)

Now we need to resolve following things:
1) Desirable UX and UI for this functionality (here we can draw anything, so fill free to suggest);
2) General opening of files: currently it opens in panel which is active, it can break UX, so we need to enforce it to be opened on First Panel;
3) We need to revisit DataSet opening flows and see how the pagination affects them (+ loading logic should be checked, because we call it almost all the time);

Fill free to join the discussion and test the solution.

**Comment by stepanzharychevbroadcom** [comment]
Related to: #470, #471.

**Comment by jelaplan** [comment]
I'll give the design some thought. A few things to consider
1. A single list or columns. When we have the WebView it opens the whole right side panel so a single column may look lonely. It also brings to mind OS files explorers like Windows Explorer and Mac Finder. 
2. The number of members to show at once. The screenshot below shows some things to consider around pagination - changeable number of members, jump to page, pagination arrows etc. 
3. The prospect of search or filtering, especially full text search is attractive. If the dataset truly has 30K members, I agree with Jelly that narrowing the list down is essential. But, simply giving them a larger panel to page through isn't narrowing down the list. 

Do we have any more information on what is in all these members? How do users like Sys Progs interact with these in ISPF? Do they have search etc.?

<img width="839" alt="image" src="https://user-images.githubusercontent.com/3207260/75261589-49fb6580-57b9-11ea-9f81-d215ae1bd3ac.png">

**Comment by stepanzharychevbroadcom** [comment]
File which explains results of this investigation and questions which we need to resolve: 
[Pagination Webview - concept and comments.pdf](https://github.com/zowe/vscode-extension-for-zowe/files/4299311/Pagination.Webview.-.concept.and.comments.pdf)

**Comment by VitGottwald** [comment]
Creating a webview basically means creating a new standalone application rather than fixing a problem we have in the current plugin. Are we sure we want to do this? Just a couple of questions:

1. How do we share functionality between current tree view and the new one?
2. How do we integrate webview to vscode so that it plays nicely with the whole ecosystem?

**Comment by jellypuno** [comment]
@VitGottwald If you are asking me, I don't know the answer to your questions. This issue is simply a proposal to fix issue numbers #327, #470 and #471. If there are other ways to fix the said issues, comments and suggestions are welcome. If you want to check my research, it can be found here: https://ent.box.com/s/nxnde5isjgv2czdc9ch2z7f3zf81n41v

**Comment by stepanzharychevbroadcom** [comment]
@VitGottwald 
1. It won't be the new Tree View, but the grid which extends the current functionality. Without packaging (like webpack) there's no way to inject dependencies in such structure, but still can receive events from there and react on them inside the existing application where we can actually inject such. Proposal is to use just an event sending back to the app, so we can react with existing code. (e.g. If you want to open the dataset, we just send event on click to Tree Webview Wrapper and there send `vscode.sendCommand`);
2. From the UX point of view: we display all the files always in first column (it requires separate task to be done) and webviews always in second. From Code point of view: we have it in sort of resource folder to be able to read it in normal manner and not hardcode as a string (how MS shows in manuals);

Please, take a look to the corresponding branch, it's a draft, but it shows the structure.

**Comment by MikeBauerCA** [comment]
VS Code cautions to use the Webview API sparingly: https://code.visualstudio.com/api/extension-guides/webview 

One alternative would be to make use of the pattern query parameter of the z/OSMF REST interface to list only the desired members of a z/OS data set: https://www.ibm.com/support/knowledgecenter/SSLTBW_2.2.0/com.ibm.zos.v2r2.izua700/IZUHPINFO_API_GetListDataSetMembers.htm. This could be a valuable enhancement to the Zowe CLI as well.

Perhaps, in the Zowe Explorer, PDS's could be searched using this API. Regardless of performance, it is unreasonable to scroll through 30k members to open something. The response would be to narrow your filter.

Perhaps, the default behavior of clicking on a PDS could remain the same (show all members), but hovering over a PDS would reveal the magnifying glass icon which could be used to search for members matching some pattern.

**Comment by jellypuno** [comment]
> Perhaps, the default behavior of clicking on a PDS could remain the same (show all members), but hovering over a PDS would reveal the magnifying glass icon which could be used to search for members matching some pattern.

@MikeBauerCA Maybe Issue #172 can help with this? There is also a [vscode feature](https://github.com/zowe/vscode-extension-for-zowe/issues/172#issuecomment-580726587) that if you click the tree and start typing, you can already filter the dataset.

**Comment by VitGottwald** [comment]
The `start` and `pattern` query parameters of the member endpoint that limit the member names looks like something I had in mind, thanks @MikeBauerCA . I only miss a `limit` option.
By specifying both `start` and `pattern` we can still get list that is either too long or too short (when using a restrictive `pattern`).

**Comment by VitGottwald** [comment]
@jellypuno I like that. Especially if we could hook it up with the `pattern` query parameter to get live filter directly from z/OS instead of downloading everything all the time.

**Comment by jellypuno** [comment]
> @jellypuno I like that. Especially if we could hook it up with the `pattern` query parameter to get live filter directly from z/OS instead of downloading everything all the time.

cool! well, just fyi. @katelynienaber is already implementing this at PR #592 .

**Comment by MikeBauerCA** [comment]
@VitGottwald, regarding a `limit` option, is the slowness primarily due to the REST call or the time to load it into the VS Code tree?

**Comment by jelaplan** [comment]
There maybe other attributes for the members. A ux colleague shared this table with me for another application that pulls down large lists of members. These would give additional things to filter on. 

![image](https://user-images.githubusercontent.com/3207260/76572110-87d1dc80-648f-11ea-847d-63e224928b0e.png)

**Comment by jelaplan** [comment]
Some thoughts on large set of members

- If user knows the name of the record then sort and filter would be valuable. We discuss the filter possibility above. 
- Does the user have a record / member in mind ahead of time? If not then filter isn't that useful. 
- If the user doesn't have a record / member in mind then how do they normally work with these kinds of data bases types of sets?
- Keeping track of recently opened members would allow a user to not have to find members again in the future. This is pertinent if the user often works with the same members. 
- If we can explode records, then display that information tabularly. see my previous post. 
- I'm not aware of the nature of the data in such a large list of members. Are we expecting people to look for a single, a couple, or to operate on many? 
- If this is truly more like a db than a file system, then I'd think people want to do query based operations on the data, much like a SQL update or insert command.  Do they need to repeat the action/task with different records?  And / Or be able to batch edit multiple records?

**Comment by zFernand0** [comment]
We will get back to this once Che and Theia support webviews 😋

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
