### ISSUE TITLE
Icons retrieval logic refactoring

### ISSUE THREAD

**Issue by stepanzharychevbroadcom** [zowe/vscode-extension-for-zowe#480]
Currently all of the icons' paths are generated in `utils.ts` file via huge if-else construction which is not extendable at all. I suggest to fully rework it using strategy pattern: so each icon will define it's own object with methods and properties for retrieving it.

Pilot implementation is provided in #461 and connected PR.

In short each Icon is going to have it's own implementation to search for it + some necessary properties. You can check infographics below to understand:
![Icon Generator](https://user-images.githubusercontent.com/60000150/73469574-dbc4ae00-4386-11ea-80c7-52065cdb9073.png)

So the idea is generator will pick an icon for us, and it should be easily extendable.

**Comment by Colin-Stone** [comment]
I haven't yet seen how we can get away from the fact that we have to hardcode contextvalues with specific values in the package.json file. That is the only place where VSCode allows the definition of the context menus and operations available to a business entity. 
So I read the purpose of the generator as providing the mapping of contextvalue to id and type to state which if you are implementing as a strategy pattern would be much cleaner and nicer than a big if-then block. Is that how you envisage this or do we still have different perspectives?.

**Comment by stepanzharychevbroadcom** [comment]
Created PR to resolve this issue: https://github.com/zowe/vscode-extension-for-zowe/pull/549
