### ISSUE TITLE
USS - File Tree should keep Node state when you reload it

### ISSUE THREAD

**Issue by stepanzharychevbroadcom** [zowe/vscode-extension-for-zowe#483]
Connected to #461.

Currently if you do any manipulations with Node (like download, binary switch, and etc.) it's reflected in your File Tree. Also those variables are used to determine proper download way and some other things. Once you reload the tree (open different path and return back after) you will see that all nodes lost their statuses.

This behaviour is pretty big problem, because it looks like a bug from user's side (also based on @Colin-Stone feedback it can cause other issues, like broken downloaded sometimes). There're, as I see, 2 possible ways for doing it:
1) We should extend **constructor** of USSNode, so it will properly check existence of local file, it's type and download time; (_I personally dislike this approach, because re-reading files from disk all the time can be pretty resource consuming, especially if we talk about big binary files_)
2) We should create **cache** utility, which will track public state of node (downloaded, binary, downloaded_time and etc.), once you do reload of tree it will check if there's something cached and cache will applied on nodes;

I suggest to discuss those changes.

**Comment by zdmullen** [comment]
Let's break this down a bit, first by creating a follow-up design issue.

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
