### ISSUE TITLE
Creating data sets causes tree to loose expand behavior

### ISSUE THREAD

**Issue by phaumer** [zowe/vscode-extension-for-zowe#485]
- Have a connection and filter that shows at least two existing PDS with members
- Expand the first and you see the members listed.
- Create a new data set such as a sequential one.
- Expand the second PDS

--> Nothing happens. The members are not shown. You have to restart VS Code.

**Comment by phaumer** [comment]
This is still a problem in the Zowe 1.2 release. This will probably required an emergency 1.2.1 release.

**Comment by phaumer** [comment]
@katelynienaber the problem seems to be cause by these three lines 876-878. When I comment these out it works again. The tree collapses, but it does not loose it behavior. What is the call to `createTreeView()` intended to do?

```typescript
const newNode = await node.getChildren().then((children) => children.find((child) => child.label === name));
const newNodeView = vscode.window.createTreeView("zowe.explorer", {treeDataProvider: datasetProvider});
newNodeView.reveal(newNode, {select: true});
```

**Comment by katelynienaber** [comment]
Yes this is something I noticed while working on PR [#462](https://github.com/zowe/vscode-extension-for-zowe/pull/462). 

`createTreeView()` allows you to control the tree view's visual properties via a `TreeDataProvider `(I am usually using it to select and expand a data set which has been found in a search)

Apparently there can only be one instance of `TreeDataProvider` at a time, and taking control of it elsewhere in the code causes the previous instance not to work.

In PR #462 I fixed it by making one `TreeDataProvider` available to extension.js (line [82](https://github.com/zowe/vscode-extension-for-zowe/blob/216fb0f5ec0adb0d15c8c444aeca6e298f2cdac1/src/extension.ts#L82). It should be exported if this is causing problems in other classes. Maybe it belongs in `DatasetTree ` as this class is required for the block in which the `databaseView `is first assigned.

Let me know what you think and I can create a PR for this issue and update PR #462 as well.

**Comment by phaumer** [comment]
I tried that branch (commenting our the compile errors). I still saw the same issue after creating a data set @katelynienaber.

**Comment by katelynienaber** [comment]
@phaumer Could you give me more details? I tried it exactly as it is written in the question and I am able to expand any data set, before and after adding a PDS or a SDS or a DS.

Tried to push to the branch just in case but Everything is up to date.

**Comment by phaumer** [comment]
Works now in 1.2.1. Thanks!
