### ISSUE TITLE
Computing new filters when creating data sets does not cover important cases

### ISSUE THREAD

**Issue by phaumer** [zowe/vscode-extension-for-zowe#486]
When you create a new data set the `createFile()` method checks if the new data set actually matches the current filter so that it would actually be shown to the user after creation. I see several issue with the current test and update method.

1. The test only checks for `.*` wildcards, but just providing a HLC is also a valid filter, which is not covered and hence redundant entries will be created
2. The code that parses the current filter assume spaces between each filter, which also not required. It fails when users specify the comma separated list without spaces
3. The for loop that checks all the current filters does not work as the last entry's test in the filter array will overwrite the previous findings.
4. The newly created filter adds the entire data set name, which will lead to a long list if multiple data sets are created.  It might be more efficient if the filter would use a wildcard.  The downside could be that suddenly many more data sets previously hidden would be displayed, but I wanted to propose this  solution to see what people think. A better solution would use perhaps a user preferences or would prompt the user if suddenly a certain additional number of data sets would be displayed. An item for future exploration.

**Comment by jelaplan** [comment]
Thx Peter for catching all these details.

**Comment by zFernand0** [comment]
resolved by #487
