### ISSUE TITLE
GitHub releases get affected by this change

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#490]
https://github.com/zowe/vscode-extension-for-zowe/blob/c13337b7ef5e37f6365e373240980fc4a6ba2179/Jenkinsfile#L212

**Comment by phaumer** [comment]
Another step that is missing when increasing the version is to run `npm install` and commit the updated package-lock.json file with the new version number.

**Comment by zFernand0** [comment]
> Another step that is missing when increasing the version is to run `npm install` and commit the updated package-lock.json file with the new version number.

Hey @phaumer, since we will be rewriting the pipeline with the shared-libraries soon (#456), I believe this could be addressed then (if that's Ok with you)

**Comment by zFernand0** [comment]
Main issue addressed.
Check this out!
https://github.com/zowe/vscode-extension-for-zowe/releases/tag/v1.2.1
