### ISSUE TITLE
Cannot read property 'profile' on undefined on saving member.

### ISSUE THREAD

**Issue by ishche** [zowe/vscode-extension-for-zowe#495]
Steps to reproduce:
1. In the dataset tab search for dataset <HLQ.SOME.PSDNAME>
2. Open some member for editing
3. Change search to <HLQ.DIFFERENT.PSDNAME>
4. Save member.

Expected result: the content of the member saved on a mainframe.
Actual result: error message, content is not saved on a mainframe. 
![image](https://user-images.githubusercontent.com/590426/73844842-abb35a00-4821-11ea-9551-355176b4ec6f.png)

**Comment by Colin-Stone** [comment]
Thanks @ishche for picking this up @phaumer are you aware of this?.

**Comment by zFernand0** [comment]
This was fixed in v1.2.1 😉
