### ISSUE TITLE
Error encountered while activating and initializing logger! 

### ISSUE THREAD

**Issue by ozzy1981** [zowe/vscode-extension-for-zowe#506]
I am getting a persistent error when installing the Zowe Explorer Extension - 

![image](https://user-images.githubusercontent.com/19739739/73990316-e261af80-499c-11ea-9fbd-c73c159963ab.png)

It will not let me do anything with the extention at all. Can someone please help me with this as I am very keen on contributing to the ZOWE project and this is hampering my efforts.

**Comment by Ashish1981** [comment]
How you able to fix this..??

**Comment by YuriiPaziuk** [comment]
I have the same problem.

**Comment by zFernand0** [comment]
Please see #588
