### ISSUE TITLE
Error encountered in datasetFilterPrompt.optionalProfiles!

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#510]
To re-create:

1. Open VSCode
2. Click RefreshALL Icon
3. Click a profile without saved Credentials. The error will be displayed.

The error happens in  loadNamedProfile() when promptCredentials() is calling it. The type is undefined so the condition is not met.

```
public loadNamedProfile(name: string, type?: string): IProfileLoaded {
        for (const profile of this.allProfiles) {
            if (profile.name === name && (type ? profile.type === type : true)) {
                return profile;
            }
        }
        throw new Error(localize("loadNamedProfile.error.profileName", "Could not find profile named: ")
            + name + localize("loadNamedProfile.error.period", "."));
    }
```

**Comment by jellypuno** [comment]
@Colin-Stone @phaumer Can you please help me understand the code? 

`if (profile.name === name && (type ? profile.type === type : true)) {
                return profile;
            }`

**Comment by phaumer** [comment]
@jellypuno the method parameter `type` is optional, so if it is provided it will use it as a filter and only search in profiles of that type; if it is not provided it will just return the first profile of that name it will find of any type, which is typically zosmf as that is the first type that get registered in the extensibility registry. Other types will follow after. Generally, we want to recommend to define profiles with unique names to avoid confusion, but the CLI allows defining zosmf and zftp profiles with the same name. 

I am not sure what error you are seeing. Can you add the exact error message to this issue? It should not be possible to create a profile without a type.

**Comment by jellypuno** [comment]
Fix was added in #525

**Comment by jellypuno** [comment]
I tried to fix this by adding trim() in the `name` passed to` loadNamedProfile()` but I am still having an error if I create a profile with spaces in the end. 

To Re-Create this error:
1. Create a profile with a space in the end (e.g `sample ` )
2. Click the magnifying glass
3. The error would appear

![Capture](https://user-images.githubusercontent.com/45042840/75770610-8f370e80-5d48-11ea-9ce5-dd0da583cdde.PNG)

Note: I tried to trim `profile.name` in ` loadNamedProfile()` but it ended with an endless loop :(

**Comment by zFernand0** [comment]
Until we implement the ability to update/delete profiles from within the extension, I'm afraid the only workaround for users that already have profiles with spaces is to create new ones (and manually delete old ones if they wanted to). :cry:
