### ISSUE TITLE
Improve messaging and handling for merge conflict resolution in Che/Theia (temporary workaround)

### ISSUE THREAD

**Issue by Alexandru-Dumitru** [zowe/vscode-extension-for-zowe#513]
I propose we have a temporary workaround in place, to better handle the situation when there is a merge conflict while working from a Che/Theia environment. Currently the explorer is able to detect that the file was changed based on etag, but until https://github.com/eclipse-theia/theia/issues/7036 is addressed, we need give users the ability to stop the automatic upload and overwrite of files on mainframe.

My proposition is to intercept this with a Yes/No dialog box, exposing the potential risk of overwrite via a meaningful message and permitting the user to decide is he or she wants to continue or not.
This workaround will not handle any potential conflict resolution. This is left entirely to the user.

**Comment by Alexandru-Dumitru** [comment]
Status update.

Active branch is: https://github.com/zowe/vscode-extension-for-zowe/tree/fix-513

Currently, the extension will detect the Theia env and will behave as follows:
- if no merge conflict detected, act as before (no change here)
- if merge conflict detected, following messages will appear:
![ss1](https://user-images.githubusercontent.com/45846673/75242083-b1b8ad00-57c7-11ea-90d5-75b5df37d0d8.PNG)
- if user selects `NO`, upload is cancelled and the file is marked as `dirty` so that it will indicate that it is not saved:
![ss2](https://user-images.githubusercontent.com/45846673/75242145-ceed7b80-57c7-11ea-8073-8c5724d12992.PNG)
- if user selects `YES`, file is uploaded and overwrites the one on mainframe (without checking against etag):
![ss3](https://user-images.githubusercontent.com/45846673/75242218-f6dcdf00-57c7-11ea-975c-2ffb173b52ae.PNG)

@jelaplan @IgorCATech Would love to get your input on the messaging.

Thanks.

**Comment by IgorCATech** [comment]
@Alexandru-Dumitru Looks good to me. Few minor corrections:
"A merge conflict **has** been detected."
"...inside **the** Theia editor..."
