### ISSUE TITLE
Can't create secure profile if Zowe CLI not installed

### ISSUE THREAD

**Issue by tjohnsonBCM** [zowe/vscode-extension-for-zowe#520]
When using Zowe Explorer in these conditions:
* Zowe CLI is not installed
* "Zowe Security: Credential Key" is defined in VS Code settings

Then this error appears, preventing credentials from being stored securely:
![image](https://user-images.githubusercontent.com/50887074/74542628-f57efd00-4f11-11ea-9ef5-c403e90351ab.png)

This issue was fixed for non-secure profiles in #517, it should be also fixed for secure ones in #516 once the tests pass in that branch.

**Comment by zFernand0** [comment]
fixed by #518
