### ISSUE TITLE
Unable to submit JCLs from Zowe Explorer

### ISSUE THREAD

**Issue by plavjanik** [zowe/vscode-extension-for-zowe#522]
The _Submit JCL_ action fails with me message: `Job submission failed Expect Error: You must provide a JCL string to submit. The 'jcl' field of the provided parameters was undefined.`

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7644758/74587507-a3160d00-4ff3-11ea-8922-07507c8f2ef3.gif)

Steps:
1. Open a JCL from a data set
2. Press Cmd+Shift+P
3. Type: `Submit JCL`
4. Press Enter
5. The error message is displayed

**Comment by Alexandru-Dumitru** [comment]
Hi @plavjanik. Do you have this error only from the Command Palette? Can you please try to submit it from the context menu? right-click on the JCL then select `Submit Job`. Just trying to narrow down the error.
Thanks

**Comment by travatine** [comment]
The problem appears to be in :


public submitJcl(jcl: string, internalReaderRecfm?: string, internalReaderLrecl?: string): Promise<zowe.IJob> {
        return zowe.SubmitJobs.submitJcl(this.getSession(), internalReaderRecfm, internalReaderLrecl);
    }

the 'jcl' argument is not being passed to "submitJcl'
