### ISSUE TITLE
Issuing MVS console command fails due to EMCS console already created in other TSO/E address space

### ISSUE THREAD

**Issue by FreekCornelis** [zowe/vscode-extension-for-zowe#523]
Issuing an MVS console command such as 'D T' using Zowe Explorer in VSCode (press F1, select 'Zowe: Issue MVS command')  for a selected profile is successful.
However, when a second profile is selected for another LPAR in the same SYSPLEX, issuing a  command fails because the  requested EMCS console is already in use:
![image](https://user-images.githubusercontent.com/55885539/74658082-d8586180-5191-11ea-83fe-e124aa666137.png)

Hence, there is a naming conflict when requesting a second console. It seems that for user ID MYUSER, the console name will be MYUSERCN.
The TSO CONSOLE command and Zowe CLI allow the console name to be specified via the NAME()  and --cn option, resp.

Would it be possible to have Zowe Explorer  generate a more random console name if none can be specified? Or perhaps to allow de-allocation of a console?

**Comment by JirkaAichler** [comment]
We are having the same issue with the `api-dev` tool https://github.gwd.broadcom.net/MFD/zowe-rest-api-service-sdk/tree/master/tools/api-dev . 

It is failing with the following error when we are canceling jobs:

```
+ zowe-api-dev stop --job
jobid:   JOB41408
retcode: null
jobname: MASIDT
status:  ACTIVE
Stopping job MASIDT (JOB41408)
Command Error:
z/OSMF REST API Error:
Rest API failure with HTTP(S) status 500
reason:      The requested EMCS console has already been created in other TSO/E address space
return-code: 5
reason-code: 10


Error Details:
HTTP(S) error status "500" received.
Review request details (resource, base path, credentials, payload) and ensure correctness.

Protocol:  https
Host:      usilca31.lvn.broadcom.net
Port:      1443
Base Path: 
Resource:  /zosmf/restconsoles/consoles/defcn
Request:   PUT
Headers:   [{"Content-Type":"application/json"},{"X-CSRF-ZOSMF-HEADER":true}]
Payload:   { cmd: 'P MASIDT', async: 'N' }
    Error: z/OSMF REST API Error:
    Rest API failure with HTTP(S) status 500
    reason:      The requested EMCS console has already been created in other 
    TSO/E address space
    return-code: 5
    reason-code: 10
```

Could you please let us know when are you planning to fix it? Thank you!

**Comment by Joe-Winchester** [comment]
A suggested fix is to allow the `consolename` to be specified on the profile.  

If the profile allowed `consolename` to be specified and used this would avoid the problem users are running into which is where `CN` is added to the user ID and truncated to 6 characters, so `MYUSERID` becomes console `MYUSERCN`.  The problem with having default console name generation is that because the console is visible across the sysplex if it's already being used the error above occurs.

**Comment by MikeBauerCA** [comment]
I agree with you @Joe-Winchester - this was proposed recently in #1667

**Comment by pablocarle** [comment]
Hi, I'm facing the same issue when running MVS commands from zowe explorer, I see both issues referenced are still open in github.
Is there currently a working workaround? Or planned for this issue?

**Comment by JillieBeanSim** [comment]
closing as duplicate of #1667
