### ISSUE TITLE
Terminology consistency

### ISSUE THREAD

**Issue by venkatzhub** [zowe/vscode-extension-for-zowe#536]
When opening a data set member - the UI shows "Opening Dataset.." 
When data set member is edited, and autosave kicks in - the UI shows "Uploading Dataset.." 

But the object is NOT a dataset, its a member. 

The UI should be consistent and portray accurate information to the user.

**Comment by stepanzharychevbroadcom** [comment]
Added fix using generator, so we can extend this approach later: https://github.com/zowe/vscode-extension-for-zowe/pull/558

**Comment by jellypuno** [comment]
Ooops. I thought the fix is already merged 😝

**Comment by venkatzhub** [comment]
This is still not fixed. When Saving a member - it says "Saving Dataset Member" - which is good. But immediately after that you see a message "Dataset uploaded successfully" - It is NOT a dataset that is being uploaded, it is a member still... so requesting the review of the messages for consistency.
