### ISSUE TITLE
Retrieving response from zowe.List

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#538]
Often get this appearing as an error message in the bottom right corner. Possibly related to an invalif password or getting dataset children

**Comment by jellypuno** [comment]
Its related to errorHandling function. 

`default: {
            window.showErrorMessage(moreInfo);
            break;
        }`

I think it needs to be changed to: `window.showErrorMessage(moreInfo + " " + errorDetails);`

**Comment by jellypuno** [comment]
Added fix in PR #525
