### ISSUE TITLE
Lists reload upon collapse

### ISSUE THREAD

**Issue by awharn** [zowe/vscode-extension-for-zowe#543]
When collapsing the profile used to view USS directories, datasets, and jobs, the progress bar appears and indicates the list command for the respective view has been submitted.

**Comment by JillieBeanSim** [comment]
related issue https://github.com/zowe/vscode-extension-for-zowe/issues/754

**Comment by JillieBeanSim** [comment]
fixed with https://github.com/zowe/vscode-extension-for-zowe/pull/1847
