### ISSUE TITLE
Special characters in file names break file explorer

### ISSUE THREAD

**Issue by kristinochka** [zowe/vscode-extension-for-zowe#551]
How to reproduce: 
Create a file or a folder that contains special escape characters in the name.

- ssh into zOS
- use the command line to create a new file 
- `touch myFile.txt`
- Press the escape key or up error on your keyboard after typing the above command
- This will add a special character at the end of the file name
- Type `ls -latb` to list all the files and show all characters in the name
It will look something like this:  `myfile.txt\047\047`

Expected:
Can use zowe explorer as normal

Actual:
Zowe explorer files fail to load completely.

**Comment by jellypuno** [comment]
@kristinochka is there an error message?

**Comment by kristinochka** [comment]
Nope, it just fails to load and this popup appears: 
![image](https://user-images.githubusercontent.com/14590297/75358744-64991180-5881-11ea-8157-addb69008953.png)

**Comment by Colin-Stone** [comment]
> Nope, it just fails to load and this popup appears:
> ![image](https://user-images.githubusercontent.com/14590297/75358744-64991180-5881-11ea-8157-addb69008953.png)

This at least was addressed by https://github.com/zowe/vscode-extension-for-zowe/pull/525 @kristinochka  If you use the latest master do you now get a better popup?
