### ISSUE TITLE
Error in USS Favorites related to non-existing profile

### ISSUE THREAD

**Issue by Alexandru-Dumitru** [zowe/vscode-extension-for-zowe#554]
I am getting the following error when extension is initialized:

![err3](https://user-images.githubusercontent.com/45846673/75367229-47cffe80-58c0-11ea-842c-036f764bdf84.png)

My Favorites list is not populated (error must cut the processing short).

If I remove the elements from the `favorites` array in `Zowe-USS-Persistent` setting, the extension initializes properly, without any error. Then I can add new favorites, array is again populated and I can see the elements inside the `Favorites` tree. When I close and re-open VSCode, I get the error again.

Noticed that the profile name is cut short in the error message as well. 

Zowe Explorer v1.3.0
VSCode v1.42.1

**Comment by jellypuno** [comment]
Line 336 in USSTree.ts trims the sesName wrongly

![Trim](https://user-images.githubusercontent.com/45042840/75431135-afcc2680-594c-11ea-8bf6-5d92148dd45b.jpg)

**Comment by katelynienaber** [comment]
@Alexandru-Dumitru says it is fixed now....wondering how he got favorites in the array without a properly [bracketed] profile name though...
