### ISSUE TITLE
DSNs with same name but different profiles overwrites each other

### ISSUE THREAD

**Issue by zimlu02** [zowe/vscode-extension-for-zowe#559]
Zowe Explorer is temporarily saving the opened member into a temp file with path like:

/Users/myname/.vscode/extensions/zowe.vscode-extension-for-zowe-1.3.0/resources/temp/_D_/**my_profile**/DSN.NEW.COBOL(TEST).cbl

however once added to favorites it gets downloaded into a folder where profile is replaced with "Favorites" keyword, see:

/Users/myname/.vscode/extensions/zowe.vscode-extension-for-zowe-1.3.0/resources/temp/D/**Favorites**/DSN.ALLOCATE.COBOL(member).cbl

So if two different members but with the same name are in favorites with different profiles, it will overwrite each other.

**Comment by jellypuno** [comment]
Additional to this: if tried to edit that member in favorites and you saved it, It is not uploading in mainframe. The changes are only saved in local file.

**Comment by lauren-li** [comment]
I am unable to recreate this issue with Zowe Explorer 1.17.0 (VS Code Marketplace release). @jellypuno or @zimlu02 can you please verify if this issue still exists in the current version of Zowe Explorer (1.17.0)? It may have been addressed in PR #664. Thank you!

**Comment by zimlu02** [comment]
I cannot reproduce. Feel free to close it. Thanks

**Comment by lauren-li** [comment]
@zimlu02 Thank you for confirming!
