### ISSUE TITLE
USSNode delete no longer going via register 

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#564]
Should be 
        await ZoweExplorerApiRegister.getUssApi(node.profile).delete(node.fullPath, isRecursive);
Not
            await zowe.Delete.ussFile(this.getSession(), nodePath, isRecursive);

This was lost whilst merging the API changes with register code v1.2 and v1.3
In retrospect the API Changes should have been made before the register updates

**Comment by zFernand0** [comment]
fixed by #565
