### ISSUE TITLE
Profile affinity Connection grouping

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#568]
Associated with https://github.com/zowe/zowe-cli/issues/679 would be a way to manage multiple connections.

Examples. 
Provide a way to link a TSO profile with the primary (zosmf) profile allowing TSO commands to be submitted. 
A mechanism to allow cli profiles which can manage VSAM files to be associated with a primary profile

**Comment by Colin-Stone** [comment]
Based upon the work for Spike #637 a simple solution is to provide a dialog that allows the user to add additional profiles to a primary. The solution only allows one secondary profile per connection type to be added. The information is then stored on the files system mirroring the profiles folder structure  
![profile_links](https://user-images.githubusercontent.com/30794003/78642799-2f81d500-78ab-11ea-83e2-71fe3633da9b.gif)
After looking at options. Actually altering a profile or a profile's behavior appeared to be too prone to be impacted by change. This solution is simple and independent and could be replaced easily.
Proposal is to add an inline menu to the profiles object in the Zowe Explorer section that will allow user to associate one type of profile. The file is stored mirroring the profiles folder so will be accessible in the same way.

**Comment by zFernand0** [comment]
should this issue be closed?

**Comment by Colin-Stone** [comment]
Implemented in v1.5
