### ISSUE TITLE
USS files are downloaded without taking into account the file encoding tag extended attribute in zFS

### ISSUE THREAD

**Issue by markcocker** [zowe/vscode-extension-for-zowe#57]
I have a file that is encoded and tagged as ISO8859-1 (ASCII), eg notice the `t ISO8859-1` and `T=on`:

```
/u/cicprov/mnt/CICPY000/bundles/cics-nodejs-invoke_1.0.0/META-INF:>ls -lAT
total 16
t ISO8859-1   T=on  -rw-r--r--   1 COCKERM  TSOUSER      338 Apr 25 11:24 cics.xml

/u/cicprov/mnt/CICPY000/bundles/cics-nodejs-invoke_1.0.0/META-INF:>cat cics.xml
<manifest xmlns="http://www.ibm.com/xmlns/prod/cics/bundle" bundleVersion="1" bundleRelease="0" id="cics-nodejs-invoke" bundleMajorVer="1" bundleMinorVer="0" bundleMicroVer="0"><define name="cics-nodejs-invoke" type="http://www.ibm.com/xmlns/prod/cics/bundle/NODEJSAPP" path="nodejsapps/cics-nodejs-invoke.nodejsapp"></define></manifest>
```
When I use the Zowe extension for Visual Studio Code to edit this file it is not shown correctly:
![image](https://user-images.githubusercontent.com/15351000/56738489-a5f1f980-6764-11e9-857b-e456c2d5e461.png).

**Comment by markcocker** [comment]
I also tried clicking on "UTF-8" at the bottom right of the VSC window then selecting "Reopen with Encoding", but the IBM z/OS EBCDIC codepages such as 1047 are not show.

**Comment by Colin-Stone** [comment]
I looked into the codepages and it doesn't look as if that will get addressed in the near future. What we can do is "chtag" the file when you do a get or save. If the file is indicated as binary or has the ISO8859- encoding we treat as a binary. I suggest we only do this if the options being passed into the get or save are not set one way or the other

**Comment by markcocker** [comment]
>  or has the ISO8859- encoding we treat as a binary

Note UTF-8 is also a common encoding.

**Comment by Colin-Stone** [comment]
> > or has the ISO8859- encoding we treat as a binary
> 
> Note UTF-8 is also a common encoding.

What does that look like from a chtag perspective?.

**Comment by markcocker** [comment]
```
ls -lT
total 16
t UTF-8       T=on  -rw-r--r--   1 COCKERM  TSOUSER      502 Apr 26 09:31 cics.xml
```

**Comment by Colin-Stone** [comment]
> ```
> ls -lT
> total 16
> t UTF-8       T=on  -rw-r--r--   1 COCKERM  TSOUSER      502 Apr 26 09:31 cics.xml
> ```

Thanks Mark. I hadn't seen this before. I believe anything starting "UTF-" or "ISO8859-" should be treated as binary

**Comment by Colin-Stone** [comment]
Some clarification about what is happening with the zosmf calls that underpin the get and put. zosmf has two dumb switches. 

- Text = convert between EBCIDC and ASCII
- Binary = dont convert.

I describe the switches as dumb because no logic is applied to discern the codepage even to the point that the chtag values are ignored.

My solution for now is to test for UTF-8, ISO8859- or IBM-850 and if any of these are present I will perform a binary get other leave as the default which is text. This applies if the no other input override has been set e.g. by a the toggle switch.
I will provide additional API's to allow the chtag values to be read.

**Comment by Colin-Stone** [comment]
I think we should still address this in the same way as we did for z/OS Explorer and the USS Explorer API in Zowe by checking what tagging is associated if any. That way users wont have to use the toggle to binary button as frequently. It would also serve by way of an indicator that would highlight if a file was EBCDIC for example with a little 'E' decorator

**Comment by Colin-Stone** [comment]
Dependent upon https://github.com/zowe/zowe-cli/issues/362
