### ISSUE TITLE
Store credentials securely by default

### ISSUE THREAD

**Issue by ghost** [zowe/vscode-extension-for-zowe#574]
The current behavior (in Zowe Explorer 1.5) is as follows:
* If the Secure Credential Store plugin is installed, ZE detects this and always stores credentials securely.
* If the Secure Credential Store plugin is *not* installed, ZE always stores credentials in plain text.

I believe the desired behavior is as follows:
* Zowe Explorer should *always* store credentials securely. It should not matter:
  * Whether Secure Credential Store plugin is installed
  * Whether "Zowe Security: Credential Key" is set or blank
* In case users do not want this behavior, perhaps a new option should be added to ZE that disables the default behavior of storing credentials securely.

**Comment by bearou** [comment]
@tjohnsonBCM - does this apply for both Linux AND Windows ?

**Comment by tjohnsonBCM** [comment]
@bearou Yes, Zowe Explorer supports storing credentials securely across all major platforms (Windows, Linux, and macOS).

**Comment by bearou** [comment]
@tjohnsonBCM @jellypuno thank you for feedbak, However, the package zowe-cli-plugins-1.9.0 does not contain the secure credentials plugin. When I try to install from an online registry, I get:
'request to http://registry.npmjs.org/@zowe%2fsecure-credential-store-for-zowe-cli failed, reason: connect ECONNREFUSED 104.16.17.35:80'... I do not have a lot of npm experience...

**Comment by tjohnsonBCM** [comment]
@bearou The Secure Credential Store plugin can be installed from the package `zowe-cli-package-1.9.0` (which contains a file `secure-credential-store-for-zowe-cli.tgz`). The package can be downloaded from the "Zowe 1.9.0 CLI Core" link [here](https://www.zowe.org/#download).

**Comment by tjohnsonBCM** [comment]
@bearou Because of the ECONNREFUSED error you got, it appears you have firewall restrictions preventing you from downloading NPM packages. Please ignore my previous comment, installing the Secure Credential Store (SCS) plugin from `zowe-cli-package-1.9.0` would likely fail with a similar error.

We are hoping to release a patch soon (v1.9.1) to support installing the SCS plugin without requiring an Internet connection. In the meantime, I've attached a version of this patch that you can test:
[secure-credential-store-offline-install.zip](https://github.com/zowe/vscode-extension-for-zowe/files/4329772/secure-credential-store-offline-install.zip)

To install the plugin, extract the TGZ from the ZIP and run `zowe plugins install zowe-secure-credential-store-for-zowe-cli-4.0.1.tgz`.

**Comment by bearou** [comment]
@tjohnsonBCM "This plugin was successfully validated. Enjoy the plugin."
Thank you! It's weekend now here in Denmark - will verify on monday.
Have a good weekend... Be safe!

**Comment by bearou** [comment]
Hi, as mentionned in https://github.com/zowe/vscode-extension-for-zowe/issues/588, I receive error message. Any experience with this ?

**Comment by tjohnsonBCM** [comment]
@bearou Here are few things to check in a terminal:

1. If you run `zowe plugins list`, does it show "@zowe/secure-credential-store-for-zowe-cli" v4.0.1, and no duplicate versions of the plugin are listed?
2. If you run `zowe config get CredentialManager`, does it show "@zowe/secure-credential-store-for-zowe-cli"?
3. If you run `zowe profiles list zosmf --sc`, do the username and password for all of them show "managed by @zowe/secure-credential-store-for-zowe-cli"?

You said that uninstalling/reinstalling VS Code, Zowe CLI, and Zowe Explorer didn't help. My guess would be there is something in your `~/.zowe` folder that stayed behind which is causing the issue. 

If the suggestions above don't help to narrow down the issue, it might be easier to delete the `~/.zowe` folder, although that would require reinstalling the SCS plugin and recreating any profiles you had before.

**Comment by jellypuno** [comment]
@tjohnsonBCM Since @bearou installed SCS through the tgz file, it should work in VSCode if he added Zowe-Plugin in the settings, right?

**Comment by tjohnsonBCM** [comment]
@jellypuno Yes that is correct. Adding "Zowe-Plugin" to the VSCode settings should work, but isn't necessary, since "Zowe-Plugin" is the default credential key that will be used if the SCS plugin is installed.

**Comment by crawr** [comment]
Implementation of this will be moved to v2.0 along with the Team Config changes, to reduce the impact of breaking changes connected to SCS
