### ISSUE TITLE
Deleting a Job, the interface requires me to reflesh to make it go away

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#578]
When I delete a job, the ZE shows me a message that it has been deleted but it remains in the list of jobs. I can click the refresh button and it will go away. This seems like a bug. If I delete something, it should go away. 
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/3207260/75716006-66593f80-5c9c-11ea-8f80-201429ff2b17.png">

**Comment by stepanzharychevbroadcom** [comment]
Added fix in: https://github.com/zowe/vscode-extension-for-zowe/pull/622
Also moved implementation to the declared with interface.

**Comment by JillieBeanSim** [comment]
this is no longer an issue.  the profile folder will now collapse after deleting a job.  I believe there is another issue to handle that so it will work like the other view trees on delete
