### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#588]
I got this issue while installing installing the extension.
![image](https://user-images.githubusercontent.com/20042870/75924543-27d6a700-5e8d-11ea-889e-57a3c866a0e2.png)

_Originally posted by @Ashish1981 in https://github.com/zowe/vscode-extension-for-zowe/issues/208#issuecomment-594857358_

**Comment by zFernand0** [comment]
Jelly: https://github.com/zowe/vscode-extension-for-zowe/issues/208#issuecomment-595111097

**Comment by zFernand0** [comment]
@ashish1981 @jellypuno, I was able to install the Zowe Explroer on a clean Windows environment without having NodeJS.

Can you provide OS details?

**Comment by Ashish1981** [comment]
> 
> 
> @Ashish1981 @jellypuno, I was able to install the Zowe Explroer on a clean Windows environment without having NodeJS.
> 
> Can you provide OS details?
![image](https://user-images.githubusercontent.com/20042870/76080643-5196e780-5fcd-11ea-922d-92654268335d.png)

**Comment by zFernand0** [comment]
After doing some digging, this could very well be related to another extension preventing the Zowe one from being initialized.

Hope this is not too disruptive, but could you try checking which extension causes this?
The process may be a bit tedious, but may require you to disable all extensions and start enabling one by one and see which one prevents the Zowe Explorer from initializing.

If possible, could you share the list of installed extensions in your VSCode workspace?

**Comment by Ashish1981** [comment]
I do rename the the extension folder and again install zowe. Same problem.
![image](https://user-images.githubusercontent.com/20042870/76109674-f2ec6080-6002-11ea-83a9-19dd4101441b.png)
![image](https://user-images.githubusercontent.com/20042870/76109692-00a1e600-6003-11ea-9bdf-bc905bf5c8c5.png)
![image](https://user-images.githubusercontent.com/20042870/76109737-19120080-6003-11ea-8839-17642a8ba4e0.png)

**Comment by CForrest97** [comment]
I also had this error. I have recently installed the secure credentials plugin for the CLI but hadn't updated my old profiles.
I tried 2 methods to fix this which both worked independently 
- Uninstall the secure credentials store plugin by running `zowe plugins uninstall @zowe/secure-credential-store-for-zowe-cli`
- Update profiles to be secure by running `zowe scs update` 

@Ashish1981 does this resolve your problem too?

**Comment by Ashish1981** [comment]
Great..!! The 1st one worked.. Thanks..!!!

**Comment by jellypuno** [comment]
@zFernand0 @IgorCATech Can we log this error as a known issue? If they encounter it, we can point them to the [Security Doc](https://github.com/zowe/vscode-extension-for-zowe/blob/master/docs/README-Security.md) that we had so they can set-it up.

**Comment by bearou** [comment]
Ever since I installed the  secure credentials store plugin (win7), I too receive 'error encountered while activating and initializing logger'. 
None of above methods works. Still get error.
I uninstalled plugin. Still get error.
Remove extension. Still get error.
Remove Zowe. Still get error.
Uninstall/reinstall VScode. Still get error.
Pls advice ?

**Comment by jellypuno** [comment]
@bearou In your settings .json, Is Zowe Securty:Credential Key set to spaces? 

![ZE-Settings](https://user-images.githubusercontent.com/45042840/76772707-a5f65000-67a1-11ea-8023-ee38ff5572ce.jpg)

If you do not have any Secure Credential Plugin, this field should be blank

**Comment by MikeBauerCA** [comment]
@bearou I experienced this issue and was able to resolve be recreating my existing profiles.

**Comment by juanvasquez72** [comment]
> Great..!! The 1st one worked.. Thanks..!!!

me too!!! :)

**Comment by juanvasquez72** [comment]
> I also had this error. I have recently installed the secure credentials plugin for the CLI but hadn't updated my old profiles.
> I tried 2 methods to fix this which both worked independently
> 
> * Uninstall the secure credentials store plugin by running `zowe plugins uninstall @zowe/secure-credential-store-for-zowe-cli`
> * Update profiles to be secure by running `zowe scs update`
> 
> @Ashish1981 does this resolve your problem too?

Thanks, its works!
