### ISSUE TITLE
Direct reference to zosmf function rather than via ZoweExplorerApiRegister

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#593]
Possible regression. Within ussNodeActions the uploadBinaryFile function refers directly to 
`        await zowe.Upload.fileToUSSFile(node.getSession(), filePath, ussName, true);`

This needs to be via the Api Register as per the uploadFile function

**Comment by Colin-Stone** [comment]
@zFernand0 If we create a v1.3.1 this will need inclusion as it was included in 1.3
@stepanzharychevbroadcom would you be able to address as you are familiar with this area

**Comment by Alexandru-Dumitru** [comment]
I would also suggest to use the new API `zowe.Upload.fileToUssFile()`:
https://github.com/zowe/zowe-cli/blob/f5d82918db5cce5aa8eec4a4c4fbf63bbcd49503/packages/zosfiles/src/api/methods/upload/Upload.ts#L580
- this one takes advantage of `IUploadOptions` and it is consistent with the mvs API
- we can use still use `zowe.Upload.fileToUSSFile()` but we deprecated it for the other one on the CLI level

**Comment by stepanzharychevbroadcom** [comment]
@Colin-Stone @zFernand0 @Alexandru-Dumitru All of the things which you've mentioned here are fixed in https://github.com/zowe/vscode-extension-for-zowe/pull/587/commits/40d9fd5c14eb1660ea2a61723045cb90c8fb0b37 related to issue  #472. Please, take a look, and I think this issue can be closed once we merge #472 into master.

**Comment by stepanzharychevbroadcom** [comment]
Added fixes in: https://github.com/zowe/vscode-extension-for-zowe/pull/600

**Comment by phaumer** [comment]
@Colin-Stone there is one more regression in deleteUSSNode() that breaks zFTP. I created another PR here: https://github.com/zowe/vscode-extension-for-zowe/pull/617

**Comment by Colin-Stone** [comment]
Addressed
