### ISSUE TITLE
Editing PDS member from "Favorites" list only saves locally

### ISSUE THREAD

**Issue by fritzc1** [zowe/vscode-extension-for-zowe#606]
I believe this started after the zowe plugin got an error when saving. The PDS was filled and needed compression. Ever since, if I open a member from favorites, it saves locally.

Editing the same member from my profile section saves normally to the mainframe.
<img width="310" alt="zowesave" src="https://user-images.githubusercontent.com/8673780/76331349-691fea00-62c5-11ea-8ec8-9106369b2a29.png">

**Comment by bearou** [comment]
Same story here... A v1.9.0 issue ?

**Comment by FALLAI-Denis** [comment]
When reopen a file or PDS member from synchronised files list with mainframe, current changes (not saved, and even saved) made in file or PDS member opened from "Favorites" are discarded without warning.

Same issue if reopen from "Favorites" : file or PDS member is refresh from mainframe, discarding current changes (not saved) made on file or PDS member from synchronized files list.
