### ISSUE TITLE
New Rename USS function causes HTTP 500 error

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#616]
The rename code causes a HTTP 500 error which is related to a subsequent chtag call when opening the file again.
![image](https://user-images.githubusercontent.com/30794003/76448723-b635b600-63c2-11ea-882d-3d6ce85301e9.png)

The flow of events is to execute the rename command and then follow with execute an open command. I wonder if the use of execeute rather than a promise and then strategy is presenting a sequencing problem

**Comment by Colin-Stone** [comment]
"HTTP(S) error status "500" received.\nReview request details (resource, base path, credentials, payload) and ensure correctness.\n\nHost:      winmvs3b.hursley.ibm.com\nPort:      32070\nBase Path: \nResource:  /zosmf/restfiles/fs/u%2Fstonecc%2F.test123553\nRequest:   PUT\nHeaders:   [{"Content-Type":"application/json"},{"Content-Length":"35"},{"X-CSRF-ZOSMF-HEADER":true}]\nPayload:   { request: 'chtag', action: 'list' }"
causeErrors:"{"category":7,"rc":266,"reason":0,"stack":"  1 15425A20+000003EE JsonParser::serialize(bool)\n  2 15403E50+000008D4 FileUtilServlet::doPut()\n  3 1540FF58+000000D6 TsoServlet::service()\n  4 1543EB08+00000190 TsoServlet::run()\n  5 1543E468+00000396 main\n  6 06809570+0000127E CEEVROND\n  7 14BFF2A0+000000B4 EDCZHINV\n  8 066A5CA0+000001C6 CEEBBEXT\n"}

**Comment by Colin-Stone** [comment]
Related to issue: https://github.com/zowe/vscode-extension-for-zowe/issues/567 ???

Original PR https://github.com/zowe/vscode-extension-for-zowe/pull/597 ??

1.3.x PR https://github.com/zowe/vscode-extension-for-zowe/pull/613

**Comment by lauren-li** [comment]
I can actually rename USS files without any error, but I do get this error upon renaming a USS folder. (I do not need to open the renamed folder for the error to occur.)

**Comment by phaumer** [comment]
@Colin-Stone the problem is in src/ZoweUSSNode.ts, rename(), line 284.  

Issue 1: zowe.uss.refreshUSSInTree does not refresh the children as their absolute path is changed
Issue 2: zowe.uss.ZoweUSSNode.open tries to open a directory as if it is a file

I am adding a fix in a second commit to this PR, but it might be better that getChildren should be called by the zowe.uss.refreshUSSInTree method already. Feel free to update.

**Comment by phaumer** [comment]
My apologies, my fix is not working. The solution needs to be that zowe.uss.refreshUSSInTree needs to reload the children. I am not sure I full understand how this one works with the event handling. Can you help @Colin-Stone ?

**Comment by Colin-Stone** [comment]
@zFernand0 We are close to releasing 1.3.1 and I think we have to remove this whole piece of function as it may have introduced more issues than it addressed.

**Comment by stepanzharychevbroadcom** [comment]
@Colin-Stone @zFernand0 I still have this branch with updated logic, so I think we can fix it there.
https://github.com/zowe/vscode-extension-for-zowe/pull/576

**Comment by stepanzharychevbroadcom** [comment]
@Colin-Stone @zFernand0 I moved necessary changes to separate PR, so we won't be blocked
https://github.com/zowe/vscode-extension-for-zowe/pull/619

**Comment by phaumer** [comment]
@Colin-Stone we still need PR #617 for 1.3.1 as it fixes the delete bug, plus it removed the error that Lauren saw.  I suspect that rename directory was always broken.

**Comment by stepanzharychevbroadcom** [comment]
Updated PR: https://github.com/zowe/vscode-extension-for-zowe/pull/626

**Comment by zFernand0** [comment]
Should we close this issue?

**Comment by Colin-Stone** [comment]
Sure. I've just reworked that area to be part of the tree also.
