### ISSUE TITLE
Job search with invalid credentials disables password prompt, and simply fails

### ISSUE THREAD

**Issue by katelynienaber** [zowe/vscode-extension-for-zowe#621]
If I try to run a job search from a profile that has no stored password, and I enter my password incorrectly the first time, every following search or refresh of the job tree will not prompt me for my password. Instead I will receive an invalid credentials error and be taken directly to the list of available search options.

Also, after entering my password incorrectly the first time, I am still taken to the list of search options. If my credentials were invalid the dialog should have been canceled.

See related issue [#373](https://github.com/zowe/vscode-extension-for-zowe/issues/373)

**Comment by jellypuno** [comment]
This issue was fixed in v1.6.0
