### ISSUE TITLE
Regressed integration test and missing copyright

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#634]
Fixed in 1.3.1. Address failing integration tests by providing an alternative to downloading a file to test if it exists or not.
Fix missing copyrights in workspace.ts and workspace.unit.tests.ts

**Comment by Colin-Stone** [comment]
Function pasteDataSet is failing for members

**Comment by zFernand0** [comment]
Does PR https://github.com/zowe/vscode-extension-for-zowe/pull/630 fixes (some of) these items?
