### ISSUE TITLE
Invalid member name error message

### ISSUE THREAD

**Issue by katelynienaber** [zowe/vscode-extension-for-zowe#644]
When I create a DS member with a name that is too long, I receive a general error message.

![image](https://user-images.githubusercontent.com/58596139/77752942-d0a99980-7028-11ea-8697-0ffc8d8a70fe.png)

I would like to see something like "Qualifier too long" and no attempt should be made to allocate the DS.

-----------------------------------------------------------------

NOTE: The error message for a qualifier containing invalid characters **does** mention the exact issue, but the error is sent from mainframe and therefore takes a few seconds to arrive. We could check for invalid characters before sending the request to the MF, which would:
- speed up the appearance of the error by a few seconds,
- show only one short error message instead of two.

**Comment by jellypuno** [comment]
For reference regarding naming rules:
https://www.ibm.com/support/knowledgecenter/SSLTBW_2.1.0/com.ibm.zos.v2r1.ikjp100/ikjp10056.htm

https://jazz.net/help-dev/clm/index.jsp?re=1&topic=/com.ibm.team.scm.doc/topics/r_RTCz_datasetparms.html&scope=null

**Comment by billpereira** [comment]
I would like to give a try on this issue... to be easier to validade the dataset name i'm thinking about split that in array and apply to it:
* Initial length before split < 44
After Split:
* Check for length >0 and <=8
* Regex for check 1st char and lasting chars

**Comment by jellypuno** [comment]
@billpereira go for it! would you like me to assign it to you?

**Comment by jellypuno** [comment]
@billpereira It would be great if the error message will appear in the dialog box (similar to the URL validation in Create Connection) itself since you are planning to use regex. Like this:

![Capture](https://user-images.githubusercontent.com/45042840/83275756-e9246480-a1cf-11ea-9b9b-a79e999d4734.PNG)

But I think the minimum requirement is to have a better error message.

**Comment by billpereira** [comment]
Thanks you can assign it to me...  will be my fun during the weekend :D

**Comment by dkelosky** [comment]
Thanks @billpereira for taking this on.  A few of considerations... 

This usability issue also applies to the CLI, so if something were done, perhaps it would be done at the CLI code-level first and then picked up in Zowe Explorer (for a consistent experience between Zowe Explorer & CLI).

Validation gets more complicated when it comes to supporting multiple code pages, for example, I could create a data set with a `£` in the name:
![image](https://user-images.githubusercontent.com/14940561/83412561-4a268500-a3e8-11ea-995e-02551f4987a3.png)

Or create member names with other special characters:
![image](https://user-images.githubusercontent.com/14940561/83413115-4b0be680-a3e9-11ea-9718-23ce76686b8c.png)

We used to have similar validation code in the CLI but ended up [removing it after falsely erroring users when creating valid data set names](https://github.com/zowe/zowe-cli/issues/46).

I wonder if this should be left as is an perhaps we could open RFEs for better messaging for whenever z/OSMF detects errors?

**Comment by JillieBeanSim** [comment]
this was fixed with the DS name validator in v2.4.1
