### ISSUE TITLE
Weird text appears

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#645]
This is the error:
![weirdText](https://user-images.githubusercontent.com/45042840/77828411-8d7c2300-711b-11ea-9b1f-35f2e08601e7.gif)

I have experienced this twice now. At first I thought maybe it was just a VSCode error but it happened again so maybe we need to  take note of it.

Steps I did:
1. Create a new PDS.
2. Scroll down and the text is there.
3. Tried to click refreshAll but it is still there.

**Comment by katelynienaber** [comment]
Is the weird text over the new PDS? Is this in favorites?

**Comment by Pranay154** [comment]
@jellypuno I also used to get this error, I no longer get it however, I've also tried recreating the issue as you suggested, can you confirm if this is still a problem?

**Comment by jellypuno** [comment]
> @jellypuno I also used to get this error, I no longer get it however, I've also tried recreating the issue as you suggested, can you confirm if this is still a problem?

It is not a problem... for now. It is somehow an intermittent error. Sometimes it appears. Sometimes it doesn't. Maybe we can close this issue.

**Comment by Pranay154** [comment]
> It is not a problem... for now. It is somehow an intermittent error. Sometimes it appears. Sometimes it doesn't. Maybe we can close this issue.

Yeah I'm currently not experiencing this issue on my environment, however I have had this problem before. I suppose if it becomes more frequent we can investigate further.

**Comment by Pranay154** [comment]
Hi @jellypuno , I just created a new partitioned data set (wasn't specifically testing this issue) and I get the following weird text as described in the issue 

<img width="188" alt="Screenshot 2020-05-15 at 13 06 52" src="https://user-images.githubusercontent.com/37961978/82048843-3de2be00-96ad-11ea-916a-41ba0810249d.png">
<img width="116" alt="Screenshot 2020-05-15 at 13 07 47" src="https://user-images.githubusercontent.com/37961978/82048854-43d89f00-96ad-11ea-89d0-c88d6b75bd49.png">
Both these images are after I create a partitioned data sets

**Comment by jellypuno** [comment]
@Pranay154 Weird right?

**Comment by Pranay154** [comment]
@jellypuno very, its even weirder because sometimes it happens and sometimes it doesn't!

**Comment by jellypuno** [comment]
@Pranay154 I know! If you refresh this, it won't happen again so really can't pin-point what's happening. sad. 😞

**Comment by Pranay154** [comment]
@jellypuno When I refreshed it, it fixed the weird icon in the second screenshot I posted but not the first, weird text is still there 😕

**Comment by JillieBeanSim** [comment]
This is no longer an issue
