### ISSUE TITLE
Label Error when creating a new pds member

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#647]
Steps to reproduce:
1. Create a new PDS
2. Create a new member
3. Error appears

![labelError](https://user-images.githubusercontent.com/45042840/78004675-b75f6080-733a-11ea-8956-d3aff382de0d.gif)

Note: Click refreshAll() if you want to continue

**Comment by CForrest97** [comment]
I tried to recreate this bug in 1.4.0 but my system managed to create the member successfully

**Comment by jellypuno** [comment]
@CForrest97 I can create the member too. So maybe its not a bug anymore. I found a new one tough. after re-creating this scenario. I hit CTRL+S then it says ContextValue undefined but I think it is connected to another issue

**Comment by zdmullen** [comment]
Can we close this issue then? And create a new issue for the ContextValue undefined?

**Comment by jellypuno** [comment]
@zdmullen Yah we can. We already have #648 for the context value
