### ISSUE TITLE
Spool files to be part of Jobs tree

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#65]
Would it be better if we have the spool file elements for a job as twisties off the jobname in the jobs view?. Could then remove the spool files view completely

**Comment by markcocker** [comment]
This would also mean you could expand more than one jobname to look at their "spool files".

Is the Bin icon a brighter shade of white compared to the other icons deliberately?

For consistency with DATA SETS and UNIX SYSTEM SYSTEMS (USS) sections, could menu options "Set Job Prefix" and "Set Owner" be part of a "search" hour glass?

**Comment by Colin-Stone** [comment]
> This would also mean you could expand more than one jobname to look at their "spool files".
> 
> Is the Bin icon a brighter shade of white compared to the other icons deliberately?
> 
> For consistency with DATA SETS and UNIX SYSTEM SYSTEMS (USS) sections, could menu options "Set Job Prefix" and "Set Owner" be part of a "search" hour glass?

Thanks Mark. The expansion of more than one job is one of the motivating factors. The bin icon may be the wrong luminance for the theme so I will look at that and try and make the icons more consistent. Did you mean search magnifying glass by the way?.

**Comment by markcocker** [comment]
> Did you mean search magnifying glass
Yes :-)

My reference point is the RSE support in Eclipse, where "z/OS UNIX Files", "MVS Files"  and "JES" have  all provide named filters, including defaults such as "My Jobs", "My Data Sets" and "My Home".

**Comment by crshnburn** [comment]
To support the use case of multiple jobs I think it would make sense to condense things into a single view.

I can also see how a Favourites section for the jobs view could be a combination of owner and prefix to add extra consistency with the datasets view.
