### ISSUE TITLE
USS Tree collapses after folder rename

### ISSUE THREAD

**Issue by lauren-li** [zowe/vscode-extension-for-zowe#650]
When renaming a USS folder, the entire tree will collapse (to refresh the contents) after the rename. This means the user has to subsequently go look for the renamed folder in order to continue working with it. It would be a friendlier UX if the tree was able to stay open after the rename. (Perhaps we could achieve this by refreshing at the folder level, rather than refreshing the whole USS tree.)

![ussRename2](https://user-images.githubusercontent.com/45975633/78074371-a598b000-7370-11ea-96c6-17b116edd60c.gif)

In addition: 

USSTree collapses when a new directory or file is created. It is inconsistent with the way Dataset works. The list should just refresh and not collapse
- Note: This just seems to happen at the top level, and not with creation under subfolders.

**Comment by zFernand0** [comment]
Crazy idea: 
- Recursively goo back (or `node->parent`) until the root doing refreshElements (which should keep the parent elements open) :yum:

**Comment by zdmullen** [comment]
Revisit after the pull request for issue #563  is merged.

**Comment by katelynienaber** [comment]
Note: **only renaming a folder** collapses the tree.

Creating a folder/file OR renaming a file does not.

**Comment by JillieBeanSim** [comment]
Thanks @katelynienaber we can revisit this after the PR is merged in
