### ISSUE TITLE
Refactor extension.ts file

### ISSUE THREAD

**Issue by zdmullen** [zowe/vscode-extension-for-zowe#652]
From Stepan and Katelyn: Currently the extension.ts file contains command definitions, command handlers' implementations, and sometimes even utils. The result is a file that merges lots of structures and implementations inside of it, with a lack of splitting into separate methods which contributes to tests files of enormous size and low readability of the code in general.

The proposed refactoring involves breaking extension.ts into folders of type shared/, dataset/, uss/, and job/, inside of which would go the corresponding methods--in the case of a method being utilized by multiple parts of extension, /shared folder should be used. 

This refactoring is part of the effort to clean up unit tests, which is described in another GitHub issue. This will be presented in the April 1 stand-up.

**Comment by katelynienaber** [comment]
Most recent diagram of our changes...
![image](https://user-images.githubusercontent.com/58596139/78120034-974aa280-7409-11ea-8c19-9785a8f8cfac.png)
