### ISSUE TITLE
Refactor Unit Tests

### ISSUE THREAD

**Issue by zdmullen** [zowe/vscode-extension-for-zowe#654]
In conjunction with the refactoring of the extension.ts file, we plan to refactor unit tests and place them in the appropriate folder for their corresponding action. Similarly, we will provide guidance on the creation of unit tests for new functionalities that are implemented. 

The unit tests can be grouped in the following manner, which Stepan will provide greater detail on in his presentation during the April 1 stand-up (and in the discussion here):

- Jobs
- USS
- Data sets
- Shared
- Utils
- Extension.ts (what is kept in the current file)

We will update this issue to provide an example and will work to produce the documentation (guidance) for contributors.

**Comment by katelynienaber** [comment]
To-do list: https://docs.google.com/spreadsheets/d/e/2PACX-1vR0VUpkoWsvVuYSzCeJkCNrE8F7YWYNtSZTVQJFDp3o_76_Lhid2Eh82RV4JwjG3L07dx9ZWlBKaK-g/pubhtml

Here you can see all functions in the entire extension, sorted by file (where they are located AFTER the `extensions.ts` refactoring)

We are working only on functions not marked as EXCLUDED.

I will update this as I work. Unfortunately it is only editable by people at Broadcom. I am not super aware of what Stepan does each day so I will only update his work when I hear about it...

**Feel free to add comments here!**

**Comment by katelynienaber** [comment]
Order of merges for USS test refactoring PRs:
- [Issue #654: Refactoring of ZoweUSSNode.unit.test.ts (refactor-unit-tests-uss)
](https://github.com/zowe/vscode-extension-for-zowe/pull/709)
- [Issue #654: Refactoring of /uss/actions.unit.test.ts (refactor-unit-tests-uss-actions)
](https://github.com/zowe/vscode-extension-for-zowe/pull/714)
- [Issue #654: Refactoring of USSTree.unit.test.ts (refactor-unit-tests-uss-tree)](https://github.com/zowe/vscode-extension-for-zowe/pull/726)

**Comment by zFernand0** [comment]
there should be one or two more PRs left

**Comment by zFernand0** [comment]
Two more PRs are still open
