### ISSUE TITLE
Improve Profiles Experience

### ISSUE THREAD

**Issue by zdmullen** [zowe/vscode-extension-for-zowe#656]
We intend to give users a better experience in Zowe Explorer with regard to profiles. Specifically, users should be able to manage their profiles in Zowe Explorer independent of Zowe CLI. Managing profiles here means the ability to delete and edit profiles. In addition, we will improve the Add new profiles functionality as well as the Validation of profiles. 

For the respective functionalities, Jessielaine developed the following diagrams. Included in each is a list of the existing GitHub issues they will resolve.

**Edit Profiles**
![image](https://user-images.githubusercontent.com/38981509/78166062-8707e700-744c-11ea-858d-1fe90acbe71d.png)

**Delete Profiles**
![image](https://user-images.githubusercontent.com/38981509/78166103-9424d600-744c-11ea-8f57-264c947c467d.png)

**Validate Profiles**
![image](https://user-images.githubusercontent.com/38981509/78166133-9e46d480-744c-11ea-8e80-d1703071fc88.png)

**Add New Profiles**
![image](https://user-images.githubusercontent.com/38981509/78166162-a7d03c80-744c-11ea-8efd-16f3687d20dd.png)

**Re-prompt of credentials**
![image](https://user-images.githubusercontent.com/38981509/78166214-b74f8580-744c-11ea-8627-9afcb5c33703.png)
![image](https://user-images.githubusercontent.com/38981509/78166232-bdddfd00-744c-11ea-95f7-b6d3153b13c5.png)

**Comment by zFernand0** [comment]
The various workflows in this Epic seem to have been implemented
