### ISSUE TITLE
Jenkins: Build for branches are failing 

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#659]
![image](https://user-images.githubusercontent.com/45042840/78274884-25f61700-7511-11ea-952c-c65490c2c3c6.png)

Jenkins build for branches are failing on the Build:Source Step. My guess is because the Branch Name has a "/" on it. If you notice all branches available in this repo, the error normally happens with this scenario.

![Capture3](https://user-images.githubusercontent.com/45042840/78274996-50e06b00-7511-11ea-8928-0ddc19fc7724.PNG)

Solution: Fix JenkinsFile is to handle the slashes in the branch name.

**Comment by JillieBeanSim** [comment]
closing due to move away from Jenkins to GH Actions
