### ISSUE TITLE
Jobs tree profile refresh not working

### ISSUE THREAD

**Issue by tucker01** [zowe/vscode-extension-for-zowe#66]
In 0.14.0, The refresh button on the profile in the jobs tree does not seem to refresh the list after a job is deleted. The refresh button on the Jobs tree itself does the trick.

**Comment by crshnburn** [comment]
PR #88 contains a fix for this.

**Comment by Colin-Stone** [comment]
@tucker01 has Andy's fix addressed this issue?

**Comment by tucker01** [comment]
Looks like it. Thanks.
