### ISSUE TITLE
Issue with saving USS files back to mainframe

### ISSUE THREAD

**Issue by Alexandru-Dumitru** [zowe/vscode-extension-for-zowe#660]
After editing a USS file, the save process only happens on local file system, but the upload is not triggered. Happens in Favorites as well. There is no error in VS Code.

Issue reported on Slack #zowe-explorer by Dan Jast. 

Possibly related with (didn't do any RCA yet): 
https://github.com/zowe/vscode-extension-for-zowe/issues/555
https://github.com/zowe/vscode-extension-for-zowe/issues/606

**Comment by zdmullen** [comment]
I think this is quite a significant issue and should be looked into sooner than later. I will mark it for the 1.7 release to give the squad time to research it and work on it as needed. We can update it if we deem it more pressing.

**Comment by Rappel87** [comment]
This is one of the main functions for many of our devs using the Zowe extension. When will you release 1.7 and plan to fix the bug? Because we are already looking into alternatives to save our data to USS.

**Comment by stepanzharychevbroadcom** [comment]
@Rappel87 Hello, no worries, I will discuss it with my colleagues and keep you posted.

**Comment by zdmullen** [comment]
@Rappel87, I've adjusted the milestone to the 1.5 Release, which will go out at the end of April. As @stepanzharychevbroadcom mentioned, we will present this to the team during the stand-up today and ensure it is ready.

**Comment by Rappel87** [comment]
Thanks for the heads-up.

**Comment by phaumer** [comment]
@Colin-Stone @zFernand0 I think this should be an emergency 1.4.1 fix as users would loose all their edits without warning!

I created a PR for 1.4.x here: https://github.com/zowe/vscode-extension-for-zowe/pull/669

**Comment by tjohnsonBCM** [comment]
@Rappel87 A patch release is now available on the VSCode Marketplace (1.4.1) that fixes the issue with saving USS files.

**Comment by impervachris** [comment]
I am using 1.4.1 and see the same behavior with saving PDS members.  Did no one verify this behavior before the patch was released?  This is a major issue.

**Comment by phaumer** [comment]
@impervachris I did actually. I just tried it again:
- opened a PDS member with a jcl file
- edit, save
- close 
- Pull from Mainframe
> I see my edits.

Do you see any errors in the logs or output windows?

**Comment by impervachris** [comment]
No.  there are no messages in the output window.  It just simply saves it locally.

**Comment by impervachris** [comment]
Maybe it is specific to using WSL?

**Comment by impervachris** [comment]
There must be something particular to wsl or vpn for that matter.  I now notice that even though the messages say that they are saving on the remote system when editing a USS file, it is not actually being saved.  The new behavior is that it then mistranslates the file and it appears as garbage in vscode.  The file is fine under USS though.  So, I figure I would uninstall and reinstall and I get the following message:
Cannot uninstall extension 'Zowe Explorer'. Extension 'IBM Z Open Editor' depends on this.
I will open another ticket for this.

**Comment by impervachris** [comment]
I just realized what the message was telling me.  At first glance, I thought it was telling me I had an open editor.  I'll uninstall the dependents and retry this.

**Comment by impervachris** [comment]
Okay.  I have uninstalled the Z Open Editor and reinstalled ZOWE - without reinstalling the IBM Z Open Editor and I have the same behavior.  For PDSes, If I follow your instructions, I only get a local update, with no message indicating an update.  For USS, If I follow your instructions, I get the message that USS is being updated, but it really isn't and the subsequent mainframe pull fails to do the translate and the display is garbage.
![image](https://user-images.githubusercontent.com/60410449/79129887-956ad280-7d6b-11ea-9990-2714bc19fb08.png)

**Comment by impervachris** [comment]
Okay.  I've narrowed it down.  It is code page specific.  If the file tag is iso8859-1 it fails to update and turns into garbage.  If it is ibm-1047, everything works including the save function.

**Comment by impervachris** [comment]
I guess if you give me enough time....  :)
The PDS problem is specific to favorites.  If I test pds saving from a filtered list, it saves fine.  If it is in a pds in the favorites, it does not save.

The uss file problem is related to code pages.  If the file is iso8859-1, I see various issues including the file being saved in ibm-1047 which of course creates issues.  Do you want me to open a separate issue for this?

**Comment by zFernand0** [comment]
fixed by b3f332e11ae92a17415e0161db458ca4fa0684a8
