### ISSUE TITLE
Placeholder: Back Button for Input Boxes

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#667]
This is a placeholder for implementing the back button. It is quite complicated to implement this feature and I would need more time to think of an architecture to handle this.

For now, these are the reference that I have:

https://github.com/aws/aws-toolkit-vscode/blob/ab650f54d0a4526aadcbff2979136f27ba735717/src/shared/multiStepInputFlowController.ts

**Comment by jelaplan** [comment]
Dan Kelosky shared a link from AWS which includes the back button. 
https://aws.amazon.com/visualstudiocode/

It is too bad the VS Code people haven't made back button an out-of-the-box feature. 
![image](https://user-images.githubusercontent.com/3207260/78674330-71157e80-78b1-11ea-86b0-84517fb2b016.png)

I put a back button into the [design of the Edit profile (Figma link)](https://www.figma.com/file/9iSLJIpwD9m6pWzFLjFbym/Explorer?node-id=734%3A775). I have been thinking about some other ways to create and edit profiles like a VS Code Web View but I suspect that would be more work and introduce more issues than a back button.  The back button addresses one of the bigger usability issues with the Quick Pick allowing a user to correct typing mistakes and review their entries before committing a profile. So, while it might be some effort, I think in the bigger scheme of things, it will be high value feature. There are some other issues too around helping people with profiles such as
* Letting a user view the composition of a profile. The edit feature would do that. We could also just show them like we do for dataset attributes. 
* Signaling to a user when a connection is live / active / working. Other tools like FTP GUIs provide a clear signal that the connection has been made even when it is stateless. People create profiles  but then aren't sure they were created correctly. If they create a profile and then do a bad search, the system gives very unhelpful messages. So, it is just hard for people to know and not be confused or uncertain.

**Comment by JillieBeanSim** [comment]
closing this since not planning any updates to the v1 profile creation since v1 profiles are being removed in v3
