### ISSUE TITLE
Document code samples that supports the Zowe Explorer Conformance Criteria

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#672]
Rules for compliant extensions may include items such as the use of CLI based profiles. 

EDIT: See [Extending.md](https://github.com/zowe/vscode-extension-for-zowe/blob/master/docs/README-Extending.md) for details

**Comment by crawr** [comment]
Linked to: https://github.com/zowe/community/issues/1049

**Comment by lauren-li** [comment]
Linked #1283 (Update Zowe Explorer Extender API docs for IApiRegisterClient)
