### ISSUE TITLE
USS Tree collapses when creating a New File or Directory

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#673]
USSTree collapses when a new directory or file is created. It is inconsistent with the way Dataset works. The list should just refresh and not collapse

**Comment by lauren-li** [comment]
@jellypuno This seems similar to #650 (USS Tree collapses after folder rename). Do we want to perhaps combine the two issues?

**Comment by zdmullen** [comment]
Closed in favor of working on #650 .
