### ISSUE TITLE
Can data set tree node contextValue include the "extension" or data set "type"?

### ISSUE THREAD

**Issue by travatine** [zowe/vscode-extension-for-zowe#686]
Hi,
It'd also be great if the "filetype" of a dataset member could be included in it's context;
e.g.
USER.EXEC
 A
 B
 C

In members A, B and C the context value could include that the parent filetype is ".exec".
Then we could conditionally enable commands such as "Run as (rexx) Exec"

or if the type of dataset was known such as "VSAM" , including that somehow in the context too would be great.

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
