### ISSUE TITLE
Leverage the use of `Contextually`

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#687]
After #652, Some of the functions that were moved away form the extension.ts file could leverage the context functions.

Here is an example

***submitMember***
https://github.com/zowe/vscode-extension-for-zowe/blob/2cb86b96095a78049170c635ef2f408899ebe161/src/extension.ts#L712-L745

**Comment by Colin-Stone** [comment]
This is a regression on previous merged code so will need to be completed for v1.5
New files that have not merged correctly are:
- src/dataset/actions.ts
- src/DatasetTree.ts

Thanks for identifying this issue @zFernand0
