### ISSUE TITLE
Please can the session node contextValue include the type of the connection ( "zosmf" / "rse" / "ftp" )

### ISSUE THREAD

**Issue by travatine** [zowe/vscode-extension-for-zowe#691]
Hi,

If'd be great if the context value could be used to restrict which menu items appear for sessions.
e.g. Today a command which uses TSO APIs will work for ZOSMF connections but not for ftp or rse.

**Comment by jelaplan** [comment]
This request makes a lot of sense. Context menus would follow context values.

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
