### ISSUE TITLE
Can't create profile when using zowe on Visual Studio on Windows 10

### ISSUE THREAD

**Issue by spuchacz** [zowe/vscode-extension-for-zowe#706]
Just installed IBM z Open Editor and Zowe on Visual Studio 1.44.2 on Windows 10.  node.js and the java developer studio are installed.  When I open zowe, data set, USS, and jobs are in the left hand panel.  The I select the "+" in the data sets, nothing happens.

Any ideas?

**Comment by tmclean** [comment]
I was seeing the same thing this morning. There were a couple of things that I had to do to get this working again.

1. Backed up my profiles in C:\Users\username\\.zowe\zosmf
2. The property Zowe-Temp-Folder-Location in settings.json was somehow set to null. This should point to C:\Users\username\\.zowe.
3. Shutdown VS Code
4. Restored my profiles in C:\Users\username\\.zowe.\zosmf
5. Started VS Code

At this point the + button worked again and my profiles were usable again.

BTW, if by chance you are working on the COBOL programming course for the Open Mainframe Project, the lab mainframe has scheduled maintenance today. See https://github.com/openmainframeproject/cobol-programming-course/issues/45.

**Comment by spuchacz** [comment]
Thanks for your advice.

My problem is I have no profiles.  I'm trying to create one.  I had no zowe
or zowe\zosmf directory.  I created the hidden zowe directory, the
zowe\zosmf directory, and edited the Zowe-Temp-Folder-Location per your
advice and closed VS Code.

I reopened VS Code and zowe  and when I tried to add a profile via the +
sign on datasets, all the happened was a message at the bottom of the VS
code window that said activating extension appeared and disappeared and
nothing else happened.  If I reselect the + sign, nothing happens.  The
zosmf director is empty.

I have tried installing and uninstalling VS code and the extensions
multiple times to no avail.  Any other ideas?

God bless,
Sig Puchacz
Spicewood, TX
512-658-0758
http://sigpuchacz.wordpress.com/

**Comment by jellypuno** [comment]
@spuchacz So you have Installed Node.js v8.0 or later and You are accessing a [Mainframe System configured with Zowe](https://docs.zowe.org/stable/user-guide/systemrequirements-zosmf.html#z-os-requirements) in it, correct?

**Comment by spuchacz** [comment]
Yes.  I'm doing the IBM tutoral for COBOL.

God bless,
Sig Puchacz
Spicewood, TX
512-658-0758
http://sigpuchacz.wordpress.com/

**Comment by jellypuno** [comment]
@spuchacz And you are not doing it through any remote system? That's weird because I just installed and it is working perfectly. Alright, I would suggest to join [OMP slack channel](https://openmainframeproject.slack.com) and join #cobol-programming-course. Maybe they can help you there. Because in Zowe Explorer view, there is no issue and .zowe folder is also created as the extension is initialized. Maybe they can help out. What do you think? Can we close this issue and continue there?

**Comment by spuchacz** [comment]
I prefer to leave open.  SOmeone else is looking at this for me as well.

God bless,
Sig Puchacz
Spicewood, TX
512-658-0758
http://sigpuchacz.wordpress.com/

**Comment by spuchacz** [comment]
This is fixed.  I didn't but the period below zowe the first time.  Thanks.

God bless,
Sig Puchacz
Spicewood, TX
512-658-0758
http://sigpuchacz.wordpress.com/

**Comment by jellypuno** [comment]
Cool! I'll close the issue then. Thanks.
