### ISSUE TITLE
Regression : Create New Member no longer works?

### ISSUE THREAD

**Issue by travatine** [zowe/vscode-extension-for-zowe#712]
Since getting vscode 1.44.2 and Zowe 1.4.1 I can no longer use "Create new member"

Steps to reproduce:
1) Select a profile in zowe data sets tree, choose "search Data Sets by entering patterns"
2) Search for a PDSE data set that exists e.g. TRAVIST.JCL
3) The pdse appears under the profile node
4) Right click the data set "travist.jcl", choose "Create New member"
5) Specify a member name "c"
6) A new editor opens on the member
7) Type some text  "hello"
8) Ctrl+s to save

Expected:
The member to be saved without errors.

Actual:
Error in notification area" Cannot read property 'contextValue' of undefined."

Log message:
rejected promise not handled within 1 second: Error: Cannot resolve tree item for element 0/0:TheMainframe /0:TRAVIST.JCL/0:b
extensionHostProcess.js:920
stack trace: Error: Cannot resolve tree item for element 0/0:TheMainframe /0:TRAVIST.JCL/0:b
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:573:767

Environment Information:

```
[Window Title]
Visual Studio Code

[Main Instruction]
Visual Studio Code

[Content]

Version: 1.44.2 (system setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z (4 days ago)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

[OK] [Copy]
```
Enabled Extensions:
Only "Zowe Explorer 1.4.1"

**Comment by jellypuno** [comment]
I believe issue #648 is already opened for this and #680 already fixed this error.

**Comment by travatine** [comment]
Thanks , I'll close this one.
