### ISSUE TITLE
Prompt when adding profile to USS refer to Data Set Explorer

### ISSUE THREAD

**Issue by markcocker** [zowe/vscode-extension-for-zowe#72]
Clicking on the + sign to the right of "UNIX SYSTEM SERVICES (USS)" results in the prompt"Select a Profile to Add to the Data Set Explorer".

This should instead refer to UNIX SYSTEM SERVICES (USS).

By comparison clicking on + next to JOBS results in prompt "Select a Profile to Add to the Jobs Explorer".

**Comment by ChrisBoehmCA** [comment]
Hi thanks for the issue but this is a duplicate of #56

**Comment by ChrisBoehmCA** [comment]
Thanks, fixed in 0.15.1
