### ISSUE TITLE
Doc: Understand how to use Secure Credential Store with Zowe Explorer

### ISSUE THREAD

**Issue by zdmullen** [zowe/vscode-extension-for-zowe#722]
As a user of the Secure Credential Store plug-in, I want to understand what steps I need to take in conjunction with my use of Zowe Explorer. Something like the following would be helpful under the Create a Profile section:

Using Secure Credential Store

1. Issue command `zowe scs u`. This should inform you that your profiles have been updated.
2. Open Zowe Explorer
3. Click the Gear Icon and Go to Zowe Explorer Settings.
4. Fill out this part with the word:  Zowe-Plugin
5. Close your VSCode to restart it
6. Open it again and try again.

Including this section should address concerns in previous GitHub Issues, https://github.com/zowe/vscode-extension-for-zowe/issues/585 the most recent.

**Comment by zFernand0** [comment]
It might be worth noting that (as of today - v1.12.1) we require the SCS plugin to be installed and configured in the CLI in order for the security setting to take effect. 😋 
See https://github.com/zowe/vscode-extension-for-zowe/issues/1223 for details

**Comment by fbeyl** [comment]
@zFernand0 I have node and vsc installed. I can't install zowe cli because of authorisation (I think npm way is not allowed and download myself certainly not). I can install zowe explorer extension in vsc. I need secure storage otherwise I can't store. How do I achieve secure storage inside zowe explorer without zowe cli?

**Comment by zFernand0** [comment]
Have you tried installing the CLI from the bundle on zowe.org?
In the meantime, I believe a possible workaround is to not save credentials in your profiles. Zowe Explorer should ask for them once after every restart of VSCode.
Please let us know if you run into any issues doing this. : )

**Comment by fbeyl** [comment]
I cannot install on this workstation as I'm sysprog and not developer. I can only install what is in our catalog and ZOWE CLI isn't in! If I select to not save the credentials I get following error message
![image](https://user-images.githubusercontent.com/42418931/110798434-74ac4500-827a-11eb-9b68-6962e09b518c.png)
I went back to 1.12.0 and don't get the request to save credentials and don't have the issue anymore. The proposed workaround for 1.12.1 would be fine for me if it works without issue.

**Comment by fbeyl** [comment]
Even in 1.12.0 I have issues with uid/pw. During a vsc session I am prompted several times for credentials when using the same profile. I have 8 zosmf profiles and use them in a vsc session simultaneous. Until now I couldn't find a pattern in the requests for credentials.
Ex.
I use profile1 to edit dataset on system A (codepage 500)
I use profile2 to edit file on system A  (codepage 1047)
I use profile3 to edit dataset on system B (codepage 500)
I use profile4 to edit file on system B (codepage 1047)

I expect to have to enter credentials once per profile during the same vsc session. Is it ok to expect this?
In previous version (not sure which one) I did not have this issue and as I already said I don't have zowe cli secure credential store and can't install it for the moment (working on it to get authorisation to install ...).
I'm trying to convince my not so enthusiastic colleague-sysprogs  to start using 'zowe explorer' but this kind of surprises is not helping me.

**Comment by crawr** [comment]
linked to #820
