### ISSUE TITLE
Display data set attributes

### ISSUE THREAD

**Issue by ChrisBoehmCA** [zowe/vscode-extension-for-zowe#73]
It would be a cool enhancement to be able to right click a data set in the data set explorer and show a popup or another mechanism to display attributes such as volume, size etc. of the data set

**Comment by ChrisBoehmCA** [comment]
![image](https://user-images.githubusercontent.com/42545737/57401154-08a2b680-71a3-11e9-9a7b-0fbbf4e1e6cd.png)

Possible ways to display data set attributes:
a) In a blank text editor like the current spool file view: 
![image](https://user-images.githubusercontent.com/42545737/57401210-27a14880-71a3-11e9-9275-703b7fb229c5.png)

b) In an informational message in the lower right corner (drawback: no newlines, looks ugly)
![image](https://user-images.githubusercontent.com/42545737/57401518-d2196b80-71a3-11e9-99e7-348713e04d37.png)

c) Other suggestions? 

I'm leaning towards a) right now

**Comment by crshnburn** [comment]
I think that a) is the better option, especially as a user can then copy/paste information about the dataset into other places, or save it away for future reference.

A further enhancement to this could be to allocate a new dataset based on the settings of an existing one.

**Comment by Colin-Stone** [comment]
My plan was to have a consistent way of displaying attributes that would work for both USS and datasets and if appropriate jobs. In the case of USS we need to display and potentially make editable the chown, chmod, chtag function/values. 

I had initially planned to use an explorer view (bottom left) replacing the current spool view which would reflect the attributes for the current selection in the tree view. (So, **a.** is my choice :-)
Next step is for the three views for datasets, uss and jobs to fully converge into a single tree structure  

I was also considering maintaining some of the attribute data with the tree items themselves as some of this is available when we get the files but this may not be a longer term objective.

**Comment by Colin-Stone** [comment]
> I think that a) is the better option, especially as a user can then copy/paste information about the dataset into other places, or save it away for future reference.
> 
> A further enhancement to this could be to allocate a new dataset based on the settings of an existing one.

The allocate like function is easier than allocate from scratch. It's something we had in the original Atlas UI's so thumbs up to that.

**Comment by ChrisBoehmCA** [comment]
Implemented in #78
