### ISSUE TITLE
Establish new Zowe Explorer squad

### ISSUE THREAD

**Issue by solsu01** [zowe/vscode-extension-for-zowe#732]
Placeholder for determining the process of launching the new squad for IDEs.

Tasks:
1. Update github.com/zowe/community -- done
No need for mailing list
Assigned: @solsu01 

2. Recruit and staff initial squad by following eligibility 
Agenda proposal @solsu01  -- done
Slack invite @MikeBauerCA  -- done

3. Organize the first call (CLI zoom acct for now, request John for dedicated zoom acct)  -- done
Co-hosted - @solsu01 @MikeBauerCA @MarkAckert @JTonda 
[Agenda](https://docs.google.com/document/d/12gKKSuTE4CkStsUyEgxl7nDk3WlSe9WeJ7LtaBEOIHI/edit?usp=sharing) 
[Presentation draft](https://drive.google.com/file/d/10iBJyfuFY_f_J0ZPXPRIPZDDDwMrY3o9/view?usp=sharing) 
Cover topics:
- Mission of the squad -- @solsu01 
- Review of initial eligibility and list of those interested in joining the Zowe IDE squad  -- @MikeBauerCA 
- Review roles and responsibilities of the new squad -- @MikeBauerCA & @JTonda 
- Election process for squad lead and scrum master -- @solsu01 

4. Enter initial squad members in zowe community repo committers.md -- @MikeBauerCA 

5. Elect Squad lead and Scrum Master -- @solsu01 
Please make sure you reach out to me by 5/14 on slack (Sujay Solomon) if you are interested in either role.
6. New team in GitHub and assign Zoom ID (make it a main team) - @MarkAckert 

Zowe Explorer Initial Squad Candidates, enter your name here, if interested in joining the Zowe Explorer squad and you're already a committer on the CLI squad - current list of CLI squad committers can be found [here](https://github.com/zowe/community/blob/master/COMMITTERS.md#zowe-cli)
Michael Bauer - @MikeBauerCA (michael.bauer2@broadcom.com) - CLI + Explorer
Colin Stone - @Colin-Stone (colin.stone@uk.ibm.com)
Lauren Li - @lauren-li (lauren.li@ibm.com) - Explorer
Rodney Wilson - @rodney-wilson (rodney.wilson@ibm.com) - Explorer
Kristina Mayo - @kristinochka (ktopchi@us.ibm.com)
Craig Forrest - @CForrest97 (Craig.Forrest@ibm.com)
Peter Haumer - @phaumer (phaumer@us.ibm.com) - Explorer 
Pranay Sodani - @Pranay154 (Pranay.Sodani@ibm.com) 
Alexandru-Paul Dumitru - @Alexandru-Dumitru (alexandru.dumitru@broadcom.com)
Katelyn Nienaber - @katelynienaber (katelyn.nienaber@broadcom.com)
Jessielaine Punongbayan - @jellypuno (jessielaine.punongbayan@broadcom.com)
Richelle Craw - @crawr (richelleanne.craw@broadcom.com)
Stepan Zharychev - @stepanzharychevbroadcom (stepan.zharychev@broadcom.com )
Igor Kazmyr - @IgorCATech (igor.kazmyr@broadcom.com)
Vit Gottwald - @VitGottwald (vit.gottwald@broadcom.com)
Fernando Rijo Cedeno - @zFernand0 (fernando.rijocedeno@broadcom.com)
Dan Kelosky - @dkelosky (daniel.kelosky@broadcom.com) - CLI + Explorer
John LaPlante - @jelaplan (john.laplante@broadcom.com)
Zachariah Mullen - @zdmullen (zachariah.mullen@broadcom.com)
Billie Jean Simmons - @JillieBeanSim (BillieJean.Simmons@ibm.com) - Explorer
Travis Thorne - @travatine (email...)
Andrew Harn - @awharn (andrew.harn@broadcom.com)

Meeting details: https://lists.openmainframeproject.org/g/zowe-dev/viewevent?eventid=804521&calstart=2020-05-12

Note:  Please sign up with Zoom prior to joining this meeting (account required - it's free).  It will take a little bit of time to fill everything out and validate your email.

**Comment by solsu01** [comment]
@MarkAckert @MikeBauerCA I opened PR https://github.com/zowe/community/pull/531 for zowe/community update to add Zowe Explorer.

**Comment by solsu01** [comment]
@MikeBauerCA Here's a [google doc](https://docs.google.com/document/d/12gKKSuTE4CkStsUyEgxl7nDk3WlSe9WeJ7LtaBEOIHI/edit?usp=sharing) on a proposed agenda for the meeting. Feel free to edit/add to the agenda.

**Comment by phaumer** [comment]
I would also like to propose Billie Jean Simmons @JillieBeanSim (BillieJean.Simmons@ibm.com) as a committer as she is doing a great job on https://github.com/zowe/vscode-extension-for-zowe/pull/717 that was originally planned for the 1.5 release. She did a presentation and demo to the squad this year about this work as well so people know her from that. She is also the main developer behind IBM's RSE API Zowe CLI plugin.

**Comment by zdmullen** [comment]
@phaumer, I've added Billie Jean to the above list.

**Comment by phaumer** [comment]
@solsu01 can you clarify the rationale or background for the name of the squad? I don't think we want to create entire IDEs.  Would the name Zowe Explorer Squad make more sense? It would clarify the focus of the contribution that we want to be working on. (I already had questions about this and hence this proposal.)

**Comment by solsu01** [comment]
@phaumer the idea behind not naming the squad "zowe explorer squad" was to not restrict them to the single extension or tie them exclusively to VS Code. This is similar to how the API squad is named the API squad and not the "API Mediation Layer squad".

Here's the squad's mission:
To take ownership of all **IDE tooling topics within Zowe**, including (but not limited to)
- maintain and grow the Zowe Explorer extension for VS Code
- deliver Zowe Explorer as part of Zowe Core including an offline package delivered on Zowe.org similar to the offline package for Zowe CLI
- formalize extensions to Zowe Explorer by means of well documented extension points and, if applicable, also define conformance rules
- work with other squads in Zowe to ensure re-use, and synergy across Zowe components

While the IDE Squad’s near-term goal is to maintain and grow Zowe Explorer, nothing stops them from building other extensions or exploring other IDE related tech like what added for [Theia](https://github.com/zowe/vscode-extension-for-zowe/blob/master/docs/README-Theia.md).

**Comment by phaumer** [comment]
@solsu01 in three of your four bullet points you list mentioned Zowe Explorer, which kind of makes my point. We should name the squad with a clear focus in mind. If this expands to something larger then new squads can be formed and split off as it just happened with the CLI Squad. We do not want boil the ocean promising something in the name that we are not planning to do at the moment. 

Also the Web UI could be regarded as an IDE and we do not want to create confusion with that work.

**Comment by venkatzhub** [comment]
I'm in agreement with @phaumer. This squad is not dealing with IDE, but the Zowe Explorer component of the IDE, so naming it accordingly would reduce the confusion. 

Also, the key point about Zowe Explorer being a common component of VSCode, Theia, Che etc. the goal should be stated explicitly to reflect the same - and not be specific to VSCode. This will ensure the architecture and design considerations would be broader to cover the "rich client" as well as "hosted" IDEs.

**Comment by solsu01** [comment]
All - given the community's desire to call this squad "Zowe Explorer squad", we've to go ahead and make that change. Calendar invites and blogs will be updated to reflect the same. Thanks for your feedback while we work to kick off this squad!

**Comment by venkatzhub** [comment]
@solsu01 - who is responsible for the squad mission statement and any related updates to that? As discussed what is above needs some changes.

**Comment by billpereira** [comment]
@MikeBauerCA i would likke to apply for the squad, i had lot of interest on spread content about it and also start contributing with issues as possibles

**Comment by solsu01** [comment]
Thanks to all who attended the kick-off meeting.

I've captured feedback around PR approvers and Zowe recordings/meetings being closed on these git issues:
https://github.com/zowe/zlc/issues/188
https://github.com/zowe/zlc/issues/189

**Comment by solsu01** [comment]
> @solsu01 - who is responsible for the squad mission statement and any related updates to that? As discussed what is above needs some changes.

Sub-projects in Zowe are defined in https://github.com/zowe/community/blob/master/README.md
It is seeded with the current state of Zowe Explorer. The squad is encouraged to grow and evolve the scope of the sub-project within reasonable constraints (for example, it's ok to expand zowe explorer to a different text editor, or add other MF related extensions, but not ok to add a flight simulator under zowe explorer)

I would recommend working with the squad lead (once established) to occasionally review and update the sub-project definition as needed.

**Comment by solsu01** [comment]
Please make sure you reach out to me by 5/14 on slack (Sujay Solomon) if you are interested in either the squad lead or scrum master role.

**Comment by JillieBeanSim** [comment]
@MikeBauerCA 
> Billie Jean Simmons - @JillieBeanSim ([BillieJean.Simmons@ibm.com](mailto:BillieJean.Simmons@ibm.com)) Explorer squad

**Comment by solsu01** [comment]
@MikeBauerCA has updated https://github.com/zowe/community/blob/master/COMMITTERS.md#zowe-explorer with the initial squad members.

For Squad Lead - we have 1 candidate Fernando Rijo Cedeno - @zFernand0 (fernando.rijocedeno@broadcom.com)
For Scrum Master - we have 1 candidate Zachariah Mullen - @zdmullen (zachariah.mullen@broadcom.com)

All [official squad committers](https://github.com/zowe/community/blob/master/COMMITTERS.md#zowe-explorer), please vote on Fernando and Zach becoming Squad Lead and Scrum Master of the newly formed Zowe Explorer squad **by thumbs up or thumbs downing this comment**. Feel free to reach out to me via slack if you have any questions/concerns.

Note: if you're not a squad committer, you may vote but it is a non-binding vote.

**Comment by MikeBauerCA** [comment]
It is important to note that if you are not one of the initial squad members, it does not mean you cannot join the squad. Once Zowe Explorer squad meetings begin, please join our calls. The newly formed squad will then evaluate your contributions and commitment, and welcome you as a squad member if appropriate. Thank you all for your continued interest and support 👍

**Comment by solsu01** [comment]
With 13 +1 votes and 0 -1 votes, congratulations to Fernando Rijo Cedeno - @zFernand0 (fernando.rijocedeno@broadcom.com) for being elected as the Squad Lead and to Zach Mullen - @zdmullen (zachariah.mullen@broadcom.com) for being elected as Scrum Master for the Zowe Explorer Squad!

**Comment by solsu01** [comment]
Last couple tasks before we close this out:

1. Review and confirm sub-project definition [here](https://github.com/zowe/community/blob/master/README.md#zowe-explorer) and the squad mission [here](https://github.com/zowe/community/blob/master/README.md#zowe-community-teams). @zFernand0 
2. Get meetings on the OMP calendar for squad standups and other agile meetings @zdmullen

**Comment by zFernand0** [comment]
In the most recent ZLC call (May 20th, 2020), we discussed Zoom account sharing and recording management.
Action items out of it:
- Create a spreadsheet with information of who's using what accounts and when.
- Use OnBoarding Squad Zoom account in the interim.

An issue will be created in the ZLC repository with more details.
(Will update this comment with a link once we have it)

**Comment by zFernand0** [comment]
Hey @armstro, Do we have a ZLC issue for tracking the creation of the spreadsheet that Sean suggested? (Topic: Zoom accounts and Squads using them)

**Comment by zFernand0** [comment]
Also @RASakach @Joe-Winchester, Would you mind setting up a call with @zdmullen and myself at some point to figure out credentials.

**Comment by solsu01** [comment]
If you guys have your own meetings now, are we good with closing this issue out?

**Comment by zFernand0** [comment]
> If you guys have your own meetings now, are we good with closing this issue out?

I believe we are good to close the issue @solsu01

Wondering of we got a spreadsheet with details on the Zoom accounts. Any thoughts?

**Comment by armstro** [comment]
@zFernand0 Yes we can close this ......my apologies for dropping the ball on Zoom accounts - adding @nkocsis if he can help .......I think he knows some about the current accounts. I assume OMP wants control who knows the passwords - not sure how that is done today (since there was the Zoom attack). I think the main issue is to be sure we have enough accounts for the upcoming PI Planning or if we need to fall back to company webex or other accounts

**Comment by nkocsis** [comment]
I go to JohnM to get a Zoom account. Please send me email if you need one.

**Comment by armstro** [comment]
@nkocsis the "ask" was to inventory the zoom accounts in use to be sure each squad had one OR there was a process to share.......you once listed to me the 5 (or so) zoom accounts that OMP had for Zowe use and wondering if you still had that list that we would refer to with John to be sure we had accounts for each squad?

**Comment by solsu01** [comment]
I've opened https://github.com/zowe/zlc/issues/200 to continue the thread on Zoom host keys for zowe squads. Closing out this issue.
