### ISSUE TITLE
Artifacts under Favorites is not cleaned up when a Profile is "Removed"

### ISSUE THREAD

**Issue by venkatzhub** [zowe/vscode-extension-for-zowe#736]
Scenario:
1. Open VSCode
2. Create a profile using the UI (Clicking the + sign to create a profile) - I named it Profile 1
3. Searched for a set of datasets (BALVE05.SIRIUS.TEST.*) ==> UI got populated with a set of datasets matching the pattern
4. Selected two datasets (BALVE05.SIRIUS.TEST.COBOL and BALVE05.SIRIUS.TEST.JCL) and added to Favorites. 
5. Create another profile using the UI (Clicking the + sign to create a profile) - I named it Profile 2
6. Searched for a dataset (BALVE05.DATA)
7. Selected the dataset and added it to Favorites. 

At this point - I have 3 datasets under Favorites, 2 from Profile 1 and 1 from Profile 2

Now, I selected Profile 2, Right click and chose "Remove Profile" (Curious there is No Delete, so is this indeed a "remove" as opposed to Delete?)

The tree view is updated to show that Profile 2 is removed - but the Dataset belonging to Profile 2 is still in the Favorites node. 

This is NOT expected, I would expect that data to be Removed as well from the Favorites list. 

The unintended consequence would be that if I created two profiles, and between the creation of two profiles, I changed my password, and I accidentally try to expand the dataset from the profile that was created before the password was changed, it is possible for me to lock up my user id due to invalid password.

**Comment by zdmullen** [comment]
Hi Venkat. This issue is now fixed with Richelle's Delete functionality and subsequent bug repair. Thanks.
