### ISSUE TITLE
Zowe Explorer activation does not consider other extenders registering their extension after activation

### ISSUE THREAD

**Issue by phaumer** [zowe/vscode-extension-for-zowe#742]
There are certain items that get loaded during activation of the extension, which are handled and often eliminated too restrictive.  These checks need to assume that certain items belong to extenders that get activated later.

- the profiles listed in previous sessions should not be removed, but ignored until the other extensions are activated again
- Favorites created by other extensions should not throw errors as the other extensions are not activated yet

**Comment by crawr** [comment]
Fixed by #952

**Comment by crawr** [comment]
Reopening to keep track of second bullet point: Favorites created by other extensions should not throw errors as the other extensions are not activated yet

**Comment by crawr** [comment]
Remaining work will be tracked in issue #968
