### ISSUE TITLE
Pressing Escape does not abort Edit profile dialogue

### ISSUE THREAD

**Issue by VitGottwald** [zowe/vscode-extension-for-zowe#748]
When I click the pencil button to edit a profile I get an input box as expected

<img width="607" alt="Screenshot 2020-04-29 at 11 36 10" src="https://user-images.githubusercontent.com/19686979/80586583-73cd4480-8a15-11ea-9bed-8139b075c2be.png">

When I press Escape, the input box does not cancel the wizard but progresses to next input box 
<img width="608" alt="Screenshot 2020-04-29 at 11 52 48" src="https://user-images.githubusercontent.com/19686979/80586499-55ffdf80-8a15-11ea-9673-39a7675fffd5.png">

**Comment by jellypuno** [comment]
Yeah I know this one. And this is because of the return of getURL(). It always has a value and I need to add a different condition specific to edit profiles just to handle this.
