### ISSUE TITLE
Follow symlinks in USS tree

### ISSUE THREAD

**Issue by VitGottwald** [zowe/vscode-extension-for-zowe#750]
Given I have a profile in the USS tree and I look at the a directory (for example the root `/`).
When I click on a symbolic link (for example `etc`)
Then I get a 500 error
<img width="461" alt="Screenshot 2020-04-29 at 12 22 56" src="https://user-images.githubusercontent.com/19686979/80585819-3caa6380-8a14-11ea-9c5e-1cd37da75dab.png"> 
The same error happens regardless if the target is a file or a directory.

I would expect the link to be resolved and be moved to the correct directory or have the correct file downloaded and displayed in editor.

**Comment by zdmullen** [comment]
zOSMF supports symlinks, and is there by default. We need to look at the CLI and how they are handled there and whether we are doing it the right way.

**Comment by Alexandru-Dumitru** [comment]
> zOSMF supports symlinks, and is there by default. We need to look at the CLI and how they are handled there and whether we are doing it the right way.

Just to provide some source of truth and more details. Symlink support is added from  z/OS v2.3 onwards:
https://www.ibm.com/support/knowledgecenter/SSLTBW_2.3.0/com.ibm.zos.v2r3.izua700/IZUHPINFO_API_GetListUNIXfiles.htm

On v2.2 it's not available:
https://www.ibm.com/support/knowledgecenter/SSLTBW_2.2.0/com.ibm.zos.v2r2.izua700/IZUHPINFO_API_GetListUNIXfiles.htm

I think we have to be aware of the version that the user has and act accordingly.

**Comment by zdmullen** [comment]
So this requires a check of how it works in CLI, then how we handle it, and then we may approach it with a fix and/or documentation update.

**Comment by zdmullen** [comment]
We should not treat symlinks as files in case they point to a directory.

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
