### ISSUE TITLE
Cannot add profile created in CLI

### ISSUE THREAD

**Issue by VitGottwald** [zowe/vscode-extension-for-zowe#752]
Given I am in VSCode,
When I add a profile from CLI and then try to add it in the Explorer by clicking `+` in dataset/uss/jobs trees,
Then I do not see the profile in the list.

To see the newly created profile I have to restart VSCode. It would be nice to be able to add the profile to a tree after it was created - without having to restart VSCode.

**Comment by VitGottwald** [comment]
Correction - I do not have to restart VSCode, I can click the _Refresh All_ button 
<img width="266" alt="Screenshot 2020-04-29 at 16 22 00" src="https://user-images.githubusercontent.com/19686979/80607353-b0109d00-8a35-11ea-94b0-7cbba6952d29.png"> . Thank you @crawr 

It would still be nice to get the profile without having to know this and clicking the refresh button.

**Comment by zFernand0** [comment]
In case someone is looking for more background on the refresh button there, please checkout https://github.com/zowe/vscode-extension-for-zowe/issues/161

**Comment by VitGottwald** [comment]
For the case wen a user is clicking the `+` button to add a profile I can imagine that we would read the current list of profiles an offer that, rather than what we have in memory. That way the user will get the up to date list to choose from. If a profile was added it will be there, if it was deleted, it will not be there.

**Comment by VitGottwald** [comment]
I believe this ^^^ would not be too complicated to do.

**Comment by VitGottwald** [comment]
I think we may take the experience another step forward.

When editing the same file in multiple editors like vim/vscode/webstorm I got used to a feature of all these editors that when I switch between apps they update the contents of the file from the disk. This even works when the file is changed from a terminal through some cli command.
 
In case we could hook to the window or app focus event we could do the same thing for profiles - checking if something changed and update the UI acordingly.

What do you think?

**Comment by zdmullen** [comment]
We need to do research to understand how best to read new profile information in the yaml files and complete a refresh. @lauren-li can add more details :)

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
