### ISSUE TITLE
eTag error encountered when saving a file in root of tree (USS)

### ISSUE THREAD

**Issue by crawr** [zowe/vscode-extension-for-zowe#755]
**To reproduce:**
1. Create a file in root of tree
2. The tree is collapsed 
3. If I have optional credentials and I expand the node, I am prompted for credentials again
4. Open the file and edit the contents
5. The file is saved but error message below appears

![save USS](https://user-images.githubusercontent.com/45845502/80614710-0df5b280-8a3f-11ea-8431-a90c8d99398a.PNG)

**Comment by zdmullen** [comment]
This seems to be more of a UX issue. We need to remove the error message so as not to confuse users of Theia.

Might be solved by the refresh of the tree (issues #650, #673 and/or #769). Will have to test following a fix for those.

**Comment by katelynienaber** [comment]
I tried this with and without optional credentials profiles. I did not get this error.

It would be great if someone else would try this and confirm it is not an issue for them before we close this. Theia is generally buggy for me and I don't always get the same errors twice in a row after performing the same actions...
