### ISSUE TITLE
Add icon for creating pds members

### ISSUE THREAD

**Issue by VitGottwald** [zowe/vscode-extension-for-zowe#756]
Given I am looking at the pds contents in dataset tree
When I look at the pds tree node
Then I would expect file icon (with a plus sign) - that I could click and it would issue a create member action

**Comment by jelaplan** [comment]
Vit
Can you clarify your issue? I'm looking at a file icon with a plus. 
![image](https://user-images.githubusercontent.com/3207260/81228874-d9dd3d00-8fbc-11ea-971b-e3cd11a9e229.png)

**Comment by VitGottwald** [comment]
@jelaplan the icon you are showing in the picture is on a _profile node_ in the tree. Its purpose is to create a _dataset_. After Michelle creates a PDS, the next thing she wants to do is to create a _member_ in the PDS.

When you set a filter for datasets, some of them will be a PDS. They have a folder icon in the tree. For them I would like to have this icon, with the purpose of creating a member.

Today, Michelle has to right click the PDS and pick "Create New Member" from the context menu. Having "Create New Member" icon right on the PDS tree node would make this much more intuitive.

PDS is analogous to a directory and having an icon for creating a member is a direct parallel to what Michelle is familiar with for creating a file in a directory.

<img width="263" alt="Screenshot 2020-06-01 at 21 58 38" src="https://user-images.githubusercontent.com/19686979/83449520-1123fa00-a454-11ea-9d37-c53227ce769c.png">

**Comment by JillieBeanSim** [comment]
closing due to removal of icons from tree and actions only being in right-click menu now
