### ISSUE TITLE
Renaming a USS directory changes the tree structure

### ISSUE THREAD

**Issue by crawr** [zowe/vscode-extension-for-zowe#757]
When I rename a directory with same name as an existing directory, the directory is moved inside the directory with the same name

**Comment by zdmullen** [comment]
Can we add a prompt along the lines of "There is already a directory with this name. Do you want to place this..."?

It also keeps the old name of the folder (prior to the rename).

**Comment by zdmullen** [comment]
This is connected to issue #483 and the need for some research/design for the behavior in general.

**Comment by zFernand0** [comment]
Having a similar problem after renaming a binary file on a recently renamed directory. 😋

**Comment by katelynienaber** [comment]
> Having a similar problem after renaming a binary file on a recently renamed directory. 😋

@zFernand0 Do you mean the issue occurs when you rename a binary file to be the same as the directory name? The old directory name, or the new one? Or do you mean if you rename a binary file, which is inside a recently-renamed directory, the file is moved somewhere?

**Comment by zFernand0** [comment]
> > Having a similar problem after renaming a binary file on a recently renamed directory. 😋
> 
>  Do you mean the issue occurs when you rename a binary file to be the same as the directory name? The old directory name, or the new one? Or do you mean if you rename a binary file, which is inside a recently-renamed directory, the file is moved somewhere?

The file gets moved outside the directory (at the same level as folder). Hope this helps:

Before renaming the folder
```
| root
| --folderA
| ----file1.bin 
```
After renaming the folder
```
| root
| --folderB
| ----file1.bin 
```
After renaming the binary file
```
| root
| --file2.bin
| --folderB
```

**Comment by katelynienaber** [comment]
> > > Having a similar problem after renaming a binary file on a recently renamed directory. 😋
> > 
> > 
> > Do you mean the issue occurs when you rename a binary file to be the same as the directory name? The old directory name, or the new one? Or do you mean if you rename a binary file, which is inside a recently-renamed directory, the file is moved somewhere?
> 
> The file gets moved outside the directory (at the same level as folder). Hope this helps:
> 
> Before renaming the folder
> 
> ```
> | root
> | --folderA
> | ----file1.bin 
> ```
> 
> After renaming the folder
> 
> ```
> | root
> | --folderB
> | ----file1.bin 
> ```
> 
> After renaming the binary file
> 
> ```
> | root
> | --file2.bin
> | --folderB
> ```

I am having trouble reproducing this...I tried renaming the parent directory (folderA) and then renaming the file in the directory (file1.bin) but it left the binary file inside the folder.

Also tried it with a text file but no luck...

**Comment by zFernand0** [comment]
I could not reproduce the same issue, even though I ran into a few errors.
I will try to record my Zowe Explorer usage from now own so that I have more steps to replicate any problems I run into.
Thank you for taking the time to try it out! :yum:
