### ISSUE TITLE
Delete from favorites in DS tree does not update tree node

### ISSUE THREAD

**Issue by crawr** [zowe/vscode-extension-for-zowe#758]
When I delete a member from a PDS in the "Favorites" node, the member is deleted from mainframe but the corresponding node in the Data Sets tree is not updated.
I am still able to click the member from the node and view the contents from the local copy.

**Comment by zFernand0** [comment]
Maybe we should at least closer the folder/node in the tree?

Workaround: Close and repoen the node

**Comment by ShellShockQ** [comment]
Is this issue still open and needing attention? Please advise

**Comment by jellypuno** [comment]
Closing this issue. This is fixed in v1.13.0
