### ISSUE TITLE
Editing cred to spaces

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#767]
If I edit the profiles and change it to spaces, the prompt is not triggered

**Comment by Pranay154** [comment]
Hi @jellypuno, was having a look at your PR, and came back to this issue to look at the described problem, could you help me understand the issue further, which prompt is meant to be triggered? Sorry if your I'm missing the point with your initial description I was just having trouble recreating the issue!

**Comment by jellypuno** [comment]
So what happens is this:

1. I created a profile with username and password.
2. I edited that profile and delete the username and password
3. After the successful edit, I will click filter Datasets

Expectation: I should be prompted for my username and password because I changed it to spaces. That is not happening.

**Comment by Pranay154** [comment]
> @Pranay154 So what happens is this:
> 
> 1. I created a profile with username and password.
> 2. I edited that profile and delete the username and password
> 3. After the successful edit, I will click filter Datasets
> 
> Expectation: I should be prompted for my username and password because I changed it to spaces. That is not happening.

Ok thanks! I will try recreating the issue now

**Comment by Pranay154** [comment]
Hey @jellypuno, so I've been trying to recreate the issue, and following your steps, after the edit of my username and passwords to spaces, I click filter datasets and it says I have invalid credentials (therefore prompting me to enter a username and password). @CForrest97 also tested this issue out and he could recreate the issue, we were both running the same version of the explorer, so I for your PR, I think it may be worth separating the two issues addressed into separate PRs, so that the other one isn't blocked.

**Comment by jellypuno** [comment]
@Pranay154 So this profile that you edited, Does it have the correct credentials originally?

**Comment by Pranay154** [comment]
> @Pranay154 So this profile that you edited, Does it have the correct credentials originally?

Yep

**Comment by jellypuno** [comment]
@Pranay154 That's weird. I tried it now and I am not experiencing that.

**Comment by Pranay154** [comment]
@jellypuno Let me create a gif to show you what is going on exactly

**Comment by jellypuno** [comment]
Is this what you are experiencing? I run this using v1.5.0 and this is what I am trying to fix.
![EditProftoSpaces](https://user-images.githubusercontent.com/45042840/81067386-e3907300-8ede-11ea-858d-b1b5780bc5b9.gif)

So If you run the changes, the expected behavior is this:
![EditProftoSpaces2](https://user-images.githubusercontent.com/45042840/81067868-ac6e9180-8edf-11ea-9886-ceb869e6dbdf.gif)

**Comment by Pranay154** [comment]
> Is this what you are experiencing? I run this using v1.5.0 and this is what I am trying to fix. This error is happening because of the missing await in editSession()
> ![EditProftoSpaces](https://user-images.githubusercontent.com/45042840/81067386-e3907300-8ede-11ea-858d-b1b5780bc5b9.gif)
> 
> So If you run the changes, the expected behavior is this:
> ![EditProftoSpaces2](https://user-images.githubusercontent.com/45042840/81067868-ac6e9180-8edf-11ea-9886-ceb869e6dbdf.gif)

Thanks for creating this, yes the first gif is the issue I'm experiencing, and looking at your code I would also assume that it fixes it for me, however when I run the changes, I'm still experiencing the issues in the first GIF. But I can see from the second GIF that your changes do work, perhaps its an issue with mine, let me create a gif to show you

**Comment by Pranay154** [comment]
So this is what I get when I run your changes (which to seems like the issue shown in your first gif)

![May-05-2020 14-04-59](https://user-images.githubusercontent.com/37961978/81069179-74645000-8ed9-11ea-9af0-1788d4aef0cb.gif)

**Comment by jellypuno** [comment]
@Pranay154 I see. Can you try to run `npm i` and `npm run build`? Sometimes the changes are not being captured immediately. When I fetch my branch, I have to run these commands to make sure that everything is compiled from the changes.

**Comment by Pranay154** [comment]
@jellypuno sure let try

**Comment by Pranay154** [comment]
@jellypuno Sorry I took long to respond (got locked out of my account for too many password failures 😅 ) After running `npm i` , `npm run build` and `npm run score:prepublish`, I'm still getting the same error running your changes, which I find very weird, so in terms of your PR I think it will be good to get someone else to review this issue, in the meantime I will look into why it isn't working for me
