### ISSUE TITLE
refreshing USS file list under a directory?

### ISSUE THREAD

**Issue by tucker01** [zowe/vscode-extension-for-zowe#769]
Is there an option to refresh the file list under a directory on the `USS` explorer? Currently, I collapse and reopen to refresh the directories file list, which is an OK workaround, but I'm wonder if there is a button OR better yet a keyboard shortcut? The top level refresh seems to collapse all open lists, which is cumbersome.

**Comment by zdmullen** [comment]
Hi. We are looking into USS-related issues and intend to work on this experience in the coming PI. With respect to your question, there is a similar issue open, #673, and we intend to cover both. Thanks.
