### ISSUE TITLE
USS File in favorites can fail on save

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#793]
Edge Case Regression: 
Rewritten as I get closer to what is happening.

The toggle text binary is not remembered when saving an edited favorite.

Steps to recreate.

1. Use an ASCII file that is not chtagged. In this case zosmf will assume EBCDIC and convert download. The net output is garbled.
2. Switch to binary which will enable to contents to be viewed
3. Modify the file
4. Perform save
5. Close file in editor
6. Download the file. 
7. Open file, it's garbled. Turn back to text and all is well

Result File has been converted to EBCDIC because the binary flag has not been included during the save.

Diagnosis   
The set binary method in ZoweUSS Node does not resolve the parent session reference in the same way as the saveUSSFile function in actions does. This is because the the former uses the node structure to resolve it and "actions" uses the file structure. 
They have to be consistent.  Maybe use the session name rather than an object to maintain these values?

**Comment by Colin-Stone** [comment]
Will retest after 1.5.2 has been released

**Comment by zdmullen** [comment]
Depending on the route we take with this issue, it may be changed in the future with respect to what we decide to do with issue #483 , and how we handle states. Just something to keep in mind.

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
