### ISSUE TITLE
Documentation: Zowe Settings Overview

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#797]
**Is your feature request related to a problem? Please describe.**

There has been a lot of questions regarding how to change the default values for dataset creation.

**Describe the solution you'd like**

I think it is time to create a documentation for an overview of Zowe Explorer Settings in settings.json

**Describe alternatives you've considered**

A blog or a video but it would be outside Zowe Explorer

**Additional context**

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
