### ISSUE TITLE
No way to specify where profiles are located within the extension

### ISSUE THREAD

**Issue by AHumanFromCA** [zowe/vscode-extension-for-zowe#8]
Right now, the extension is hardcoded to look in the `~/.zowe` folder for profiles. This is not ideal.

There should be some sort of mechanism for the extension. At the very least it could also look for the zowe environment variable to determine where profiles are stored. A further item could be added to have vs code look for a config file in a project directory / user settings directory. This file could work similar to how the [markdownlint.json](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint), `tsconfig.json`, or `tslint.json` works.

**Comment by Colin-Stone** [comment]
If this item is picked up please investigate a solution first and propose back to the CLI squad.

**Comment by jellypuno** [comment]
@Colin-Stone Is this function enough to fix this issue? or .zowe should be removed completely?

```
export function getZoweDir(): string {
    ImperativeConfig.instance.loadedConfig = {
        defaultHome: path.join(os.homedir(), ".zowe"),
        envVariablePrefix: "ZOWE"
    };
    return ImperativeConfig.instance.cliHome;
}
```

**Comment by Colin-Stone** [comment]
I was going to suggest speaking to Timothy but he beat me too it with a thumbs up.

**Comment by JTonda** [comment]
We support the CLI env variable.
