### ISSUE TITLE
Not enough Jobs and spool testing 

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/vscode-extension-for-zowe#80]
zosjobs and zosspool unit testing is below the 80% required level.
<img width="507" alt="Screenshot 2019-05-10 at 11 26 50" src="https://user-images.githubusercontent.com/30794003/57520837-994dd380-7316-11e9-86d0-636f79fedb23.png">

Please provide integration tests also

**Comment by Colin-Stone** [comment]
Blocks https://github.com/zowe/vscode-extension-for-zowe/issues/11

**Comment by crshnburn** [comment]
Working on some tests for the Jobs and Spool areas of the extension
