### ISSUE TITLE
View JCL in edit mode alongside the output of a Job

### ISSUE THREAD

**Issue by zdmullen** [zowe/vscode-extension-for-zowe#801]
**Is your feature request related to a problem? Please describe.**

My situation is that I am editing some JCL and then submit it. I go to Jobs to view the output. When I click on the output of the job, the output replaces my edit session. In other words, I cannot view the JCL and the job output at the same time. 

**Describe the solution you'd like**

I'd like to be able to view the JCL and the job output in parallel. 

(Note: This means that somehow we should be able to view files in edit mode next to read-only files.)

**Similar issues/issues that can considered/researched simultaneously**

https://github.com/zowe/vscode-extension-for-zowe/issues/698

Thanks

**Comment by MikeBauerCA** [comment]
VS Code offers this functionality. Before clicking on the output of the job, once you have your JCL open in your editor, simply right click on the file name at the top of the editor and select split up, down, left, or right. Then open the job output in the other pane.

**Comment by jelaplan** [comment]
One way to improve this is to allow people to open data sets in a fixed tab by double-clicking. That is how it works with VS Code explorer but not in Zowe Explorer. In ZE, you can click the edit icon or right-click and choose edit. But, it is more natural to double click. If the user does open in a fixed tab, when they go to view job output, it will open in a separate tab.   I suppose we could take another approach and open files in a fixed tab by default but that would also be inconsistent and I guess there is a reason people want to open in a temporary tab.

**Comment by zdmullen** [comment]
At the same time, though, VS Code allows a double-click to pin a file and then you can open others next to it. I think we should do some research into this to make the user experience more friendly. I had two folks just tell me that they didn't know about what you replied with, people who use VS Code every day...

**Comment by MikeBauerCA** [comment]
Seems similar to #509. When originally implemented, VS Code did not expose the double-click event. I'm not sure if there has been an update on this.

**Comment by zFernand0** [comment]
As Peter H. mentioned here (https://github.com/zowe/vscode-extension-for-zowe/issues/509#issuecomment-589993231), it's a limitation in the APIs exposed by VSCode for extension developers. 😢
