### ISSUE TITLE
Issue Command menu item on a profile - what does it do?

### ISSUE THREAD

**Issue by venkatzhub** [zowe/vscode-extension-for-zowe#802]
**Describe the bug**

A menu item "Issue Command" is showing up on the Profile name, and its unclear as to what this menu item does or what its intent is. Couldn't figure out how to get it to work. 

**To Reproduce**
1.Create a New Profile / Connection using Zowe Explorer 
2. Right click on the newly created Profile/Connection 
3. Select the "Issue Command" menu item
4. A pop up dialog pops up that asks for creation of a new command - but its not clear what command the user is trying to create. Since I selected the connection / profile under Datasets, I tried various MVS commands - but no luck. 
5. This Issue Command menu item does appear on the profile name --> right click in the Jobs and USS views as well.

**Expected behavior**

A context menu should be clear and should relate to the context of the object being selected. Having some help on what commands can be created/issued would be good. 

**Screenshots**

**Desktop (please complete the following information):**

-   OS: Mac
-   Zowe Explorer Version: 1.5.2
-   (Optional) Zowe CLI Version: 2.31.1
-   (Optional) Are you using Secure Credential Store? No

** Additional Context **
Extensions installed are COBOL Bitlang and Code4z.

**Comment by MikeBauerCA** [comment]
Completely agree, "Issue MVS Command" would be much more clear. It isn't clear whether it is a TSO, MVS, or SSH command depending on which tree you are in but I can confirm they are all MVS commands. Try `display t` ... that worked for me... it should open your integrated terminal and show the command and results in the OUTPUT.

**Comment by venkatzhub** [comment]
Thanks @MikeBauerCA  for the pointer on what this action does, I did try display t and that works. So, is the purpose of this to open a "TSO command" shell (or equivalent) of that? If so, why not have a menu item that opens the shell and let the user issue commands in the shell? 

The whole process of creating a command and executing it - to see the output goes somewhere is really odd..

**Comment by VitGottwald** [comment]
Or perhaps "Issue MVS System Command"? That is quite accurate, but probably too long.

**Comment by zFernand0** [comment]
For this one in particular, we could ask ourselves if it makes sense to have it as a menu options of just a command in the command palette that users execute?
If we go with that, we can have a more accurate description like what @VitGottwald describes 😋

**Comment by venkatzhub** [comment]
We need to start with defining what is that we want to provide - what problem are we trying to solve? Based on that, the right approach can be figured out.

**Comment by JillieBeanSim** [comment]
Addressed with PR #1230
