### ISSUE TITLE
Data on USS files is cache'd locally and not cleared, so opened/closed files don't show correct content in some scenarios

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/vscode-extension-for-zowe#806]
**Describe the bug**
Editing files in USS I double click to edit and close, e.g. `/u/myuserid/myfile.txt`
I then use the filter to select a different directory from favourites and open `/u/myuserid/temp/myfile.txt`.
The file that opens is the previous one with the same name.
The same occurs when I edit and save and close a file editor, and then behind the Zowe Explorer I update that file (perhaps through VI or ISPF 3.17

**To Reproduce**
Edit a file, close it, edit another file with the same name.

**Expected behavior**

Once a file editor is closed clear the cache.
I know there is a button "Pull from mainframe" however this isn't obvious to customers to use.
The expected behavior should be that once an editor is closed the local copy is lost, and also that if I open two files with the same name in different paths I get each unique file, rather than the same contents

**Comment by zdmullen** [comment]
This should be covered by a fix for Issue #458 .

**Comment by Joe-Winchester** [comment]
Awesome - tks for fixing this !  I owe you beer/coffee/chocolates !!
