### ISSUE TITLE
Issue Tso Command is not available on Zowe Explorer anymore

### ISSUE THREAD

**Issue by billpereira** [zowe/vscode-extension-for-zowe#809]
**Describe the bug**
When i look the commands available on Zowe Explorer to work with MVS and TSO commands, i see only MVS Commands are available now, even on the description we have both appearing to be the same
![image](https://user-images.githubusercontent.com/38498198/82586955-c14d5500-9b6e-11ea-8dad-6d31f832237a.png)

**To Reproduce**
1. Cmd+Shift+P
2. Keyboard Shortcuts
3. type issue
![image](https://user-images.githubusercontent.com/38498198/82587067-eb9f1280-9b6e-11ea-9621-ddf7219e540e.png)

**Expected behavior**
Expected to have one entry for MVS Command and one for TSO

**Screenshots**

**Desktop (please complete the following information):**

-   OS: OSX
-   Zowe Explorer Version:1.5.2
-   (Optional) Zowe CLI Version:
-   (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by zFernand0** [comment]
whoops
https://github.com/zowe/vscode-extension-for-zowe/blob/07b49c738f5dde246a54a5fdcd5cc16cfaf04e5d/src/extension.ts#L255

**Comment by jellypuno** [comment]
@zFernand0 @zdmullen Maybe we do not have to change the "Issue Command" Text. If we click Issue Command then a dialog box will appear. Choose TSO or MVS Command? What do you think?

**Comment by zdmullen** [comment]
That might be a good way to handle it for now. What do you think @zFernand0 ?

Thanks, Jelly.

**Comment by zFernand0** [comment]
I like the idea, even though people may not want to have an extra step to issue the command.
Would be nice if there was a way to include two buttons in the dialog. (just thinking out loud, not sure if it's possible) :yum:

**Comment by Joe-Winchester** [comment]
+1 to @zFernand0.  I actually got an e-mail from a customer this morning asking whether they could submit TSO commands, and if there was a way to just punch out TSO or MVS commands with a single click that'd be great with two buttons in the dialog.  
One thing that would be great, although I know it's much more work, is to have a TSO console similar to a Terminal, so that against a profile there would be a right mouse click "Open TSO Terminal" that would open a terminal window at the bottom where a user could just issue TSO commands.  Likewise for USS commands that connect through SSH.  That way long running commands could be issued, history could be recalled, and more, ...

**Comment by dkelosky** [comment]
I'm not sure everyone would like an extra step to issue a TSO command.  I'd lobby to keep them separate command groups.  

I think it's likely that users would be able to run TSO commands, but less likely to have authority to issue system commands.  In that scenario, they'll be presented with a choice they don't have.

**Comment by jellypuno** [comment]
@dkelosky Is there a possibility to identify MVS and TSO commands? is it the /? If there is an identifier then we can just have one button and the code will manage it.

**Comment by dkelosky** [comment]
Hmmm, that's a cool idea.  It would model SDSF or CA SYSVIEW behavior where system commands are prefixed with `/`.  But, in a "real" console or CA Remote Console, you don't prefix system commands with a `/`.  

Joe's terminal idea is also cool; perhaps it's a separate issue though 😄 .

**Comment by dkelosky** [comment]
I suppose in fairness, you must also prefix TSO commands in SYSVIEW, e.g. `tso time`...

**Comment by billpereira** [comment]
prefix with TSO could be a good way to identify it... and people are used to that when working on it so would be easy...

**Comment by jellypuno** [comment]
@billpereira that's a possibility. 
@dkelosky What do you think?

**Comment by dkelosky** [comment]
From a `READY` prompt  you don't need to prefix TSO commands and from a console you don't need to prefix.  Depending on the interface you're using, you must prefix, e.g. SYSVIEW - `xmvs` ir `/` for console commands.

Perhaps the cleanest approach is to have an `[Issue] TSO Command` and `[Issue] Console Command`?  Some users won't have authority to use the Console command group, so it might be easier for them to only run TSO commands without needing to prefix?

**Comment by JillieBeanSim** [comment]
Hey @billpereira I have attached this issue to the PR https://github.com/zowe/vscode-extension-for-zowe/pull/1230 addressing what is shown in the command pallet with the search `issue`, for the addition of TSO in Zowe Explorer we will be bringing that functionality in following issue https://github.com/zowe/vscode-extension-for-zowe/issues/684 and adding it, as well as the MVS command, to the APIs so extenders can consume the functionality as well
