### ISSUE TITLE
Add ability to obtain the raw JCL from a job on spool.

### ISSUE THREAD

**Issue by tucker01** [zowe/vscode-extension-for-zowe#81]
The z/OSMF REST API set seems to support getting the raw input JCL: 

```
GET /zosmf/restjobs/jobs/<jobname>/<jobid>/files/JCL/records
```

Some of the spool viewer products on z/OS allow you to get the raw JCL from a previously submitted job. They usually open it in an ISPF edit session, where you can then adjust and re-submit easily. This functionality would be useful in the zowe extension.

**Comment by dkelosky** [comment]
There's a [Zowe CLI API](https://github.com/zowe/zowe-cli/blob/master/packages/zosjobs/src/api/GetJobs.ts#L273) for that!

**Comment by tucker01** [comment]
Nice, we thought this might be a bit more involved if we had to update zowe first. This should be pretty straightforward then. 👍
