### ISSUE TITLE
Refactoring instanceOf in addZoweSession

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#812]
**Is your feature request related to a problem? Please describe.**

We need to refactor this condiiton: https://github.com/zowe/vscode-extension-for-zowe/blob/master/src/extension.ts#L379

It is hard to create unit test for instanceOf and we need to think of different solution. Currently this line is not covered in our unit test.

**Describe the solution you'd like**

Refactor code to remove instanceOf for better test coverage.

**Describe alternatives you've considered**

**Additional context**

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
