### ISSUE TITLE
Esc a dialog/select box should cancel the action

### ISSUE THREAD

**Issue by tucker01** [zowe/vscode-extension-for-zowe#82]
I believe this occurs throughout the extension in different forms, however for example, if you choose the "+" button to add a new profile to the JOBS tree and you hit escape (closes the selection list), you'll get a duplicate entry for your default profile.

**Comment by ChrisBoehmCA** [comment]
Thanks for opening. Maybe all we have to do is check whether the input from the quick pick box is undefined and stop/return if so
