### ISSUE TITLE
Zowe Security: Credential Key is confusing

### ISSUE THREAD

**Issue by VitGottwald** [zowe/vscode-extension-for-zowe#820]
As a new user of ZOWE Explorer, I am confused by options to store credentials.

<img width="518" alt="Screenshot 2020-05-28 at 10 15 39" src="https://user-images.githubusercontent.com/19686979/83117024-d83efa80-a0cc-11ea-83b1-310446d785b7.png">

Better formulation, explanation, or a link to documentation that explains the options would be helpful.

**Comment by tjohnsonBCM** [comment]
I believe there are 2 separate issues here to address:
1. **Bug:**
The description of the option "Zowe Security: Credential Key" is outdated. The following text is misleading:
    > The Default 'blank' represents no security.

    This is no longer true. Most users should not need to change this option or even know about it. If the Secure Credential Store is installed, ZE will always store credentials securely.

    The purpose of this option is for backwards compatibility with old versions of Zowe CLI. Zowe CLI and Explorer must store secure credentials using the same ID, to be compatible with each other. The ID used in the latest versions of Zowe CLI and Explorer is `Zowe-Plugin`.

    If a ZE user has an old version of Zowe CLI installed (known as `@brightside/core` or `lts-incremental`), it stores credentials using a different ID (`@brightside/core`). To make ZE compatible with this old version of the CLI, they can set the following:
   `"Zowe Security: Credential Key": "@brightside/core"`

2. **Enhancement:** 
Zowe Explorer should always store credentials securely rather than checking whether the Secure Credential Store plugin is installed (tracked in #574).

    In case users do not want this behavior, perhaps a new option should be added to ZE that disables the default behavior of storing credentials securely. This could address your suggestion @katelynienaber

**Comment by dkelosky** [comment]
+1 on this being confusing 😄 

Are `Zowe-Plugin` and `@zowe/cli` both valid values?  How do I choose one over the other?

**Comment by zFernand0** [comment]
> Are `Zowe-Plugin` and `@zowe/cli` both valid values? How do I choose one over the other?

They are both valid values. 
https://github.com/zowe/zowe-cli-scs-plugin/blob/cdf3a7d0ac0dfa9d6ddc5feea0cef7a14e902eb4/src/imperative/Constants.ts#L13-L18

The `@zowe/cli` one was added in order to avoid any backwards compatibility issues with version of the SCS plugin older than 4.0.4

**Comment by dkelosky** [comment]
Thanks - Is there a recommended one or any implication on using one value over the other?

**Comment by jelaplan** [comment]
> As a new user of ZOWE Explorer, I am confused by options to store credentials.
> 
> <img alt="Screenshot 2020-05-28 at 10 15 39" width="518" src="https://user-images.githubusercontent.com/19686979/83117024-d83efa80-a0cc-11ea-83b1-310446d785b7.png">
> 
> Better formulation, explanation, or a link to documentation that explains the options would be helpful.

When does this dialog appear? 

>     1. This is no longer true. Most users should not need to change this option or even know about it. If the Secure Credential Store is installed, ZE will always store credentials securely.

When you say it is no longer true, do you mean that most users will not be prompted to answer this question? 

Is your assertion dependent on the user having Zowe CLI installed along with the SCS plugin? It appears to be the case based on #574 and if CLI + SCS is installed then U&P are encrypted and if not they are not encrypted. So, I'm still unsure when this dialog prompt would appear.

**Comment by IgorCATech** [comment]
Is this still a relevant topic?

**Comment by crawr** [comment]
@IgorCATech yes, this is still relevant, but the doc changes will be tracked under #722 
@lauren-li Should we keep this issue to handle the SCS hanges related to #1263 or will there be one PR/issue that will cover all the configuration changes ?

**Comment by lauren-li** [comment]
> @IgorCATech yes, this is still relevant, but the doc changes will be tracked under #722
> @lauren-li Should we keep this issue to handle the SCS hanges related to #1263 or will there be one PR/issue that will cover all the configuration changes ?

@crawr I think it makes sense to keep this issue. #1263 relates to Zowe Explorer setting names, and while it probably will touch on this, I think this issue (#820) might merit a bit deeper discussion into SCS than just naming.

**Comment by IgorCATech** [comment]
Copying the following comment from PR-1340.
 
The instruction is too complex, and rather not very clear, and can be divided for easier consumption. For example:

To enable the Secure Credentials Store plugin, type `Zowe-Plugin` value in the entry field.

I don't understand what exactly 'specify `@zowe/cli` to describe a keytar-based solution' means.
If that's an alternative way of enabling SCS, then we can word the instruction in the following way:

"To enable the Secure Credentials Store plugin, type `Zowe-Plugin` or `@zowe/cli` in the entry field."

Also, what does "...stored in the clear" mean? :) Does it mean that if you don't enable SCS, your credentials are store in plain text? If yes, we should make it clear for our users. In this case, the description will be:

"To enable the Secure Credentials Store plugin, type `Zowe-Plugin` or `@zowe/cli` in the entry field. If you do not use SCS, your username and password are stored in plain text"

or

"To enable the Secure Credentials Store plugin, type `Zowe-Plugin` or `@zowe/cli` in the entry field. If you do not use SCS, your username and password are stored in plain text and are less protected"
