### ISSUE TITLE
Update Issue Templates

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#822]
**Is your feature request related to a problem? Please describe.**

1. Update Issue Template to remove the automatic adding of labels
2. Add more templates (Technical Debt and Question)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by VitGottwald** [comment]
I think "Feature request" is a bit narrow category. Many issues I create are kind of wishes for something to work better, but they are not request for new features per say. I think "Enhancement request" is what I would call them.

**Comment by jellypuno** [comment]
@VitGottwald hmmm. Feature Request is an Enhancement Request. But I understand your point. Feature can be interpreted as a New Feature or Functionality and Enhancement is just improving what we already have. I can update the title, I guess.

**Comment by VitGottwald** [comment]
I think it depends on whether we want to have requests for "features" and requests for "other enhancements" (e.g. improve how something works today) in the same group of if we want them as separate items.
If we want them together, it might make sense to update the title. And if we wanted to have them separate, then it would make sense to have a separate template for "Other Enhancement Requests".

**Comment by VitGottwald** [comment]
I do not have a preference, either is fine.

**Comment by katelynienaber** [comment]
Can we add a place to link the issue, under changelog comment spot?

**Comment by zdmullen** [comment]
Can we ensure that the title of the PR is what will be used for the changelog? And make sure the issue is linked and that the milestone is not included (is removed)? Thanks.

**Comment by IgorCATech** [comment]
I agree with @zdmullen This way it would be much easier to understand what has been changed/added.
