### ISSUE TITLE
Adding other profiles when creating zosmf profile through zowe explorer

### ISSUE THREAD

**Issue by billpereira** [zowe/vscode-extension-for-zowe#825]
**Is your feature request related to a problem? Please describe.**
Usually to get started with tso commands users need to have it's own tso and zosmf profile, and you have to link them when dealing with multiple systems, what is not so intuitive for people starting the use of it

**Describe the solution you'd like**

What about if when we are creating a profile for zosmf on vscode we already ask for the tso account information so user doesnt have to create a tso profile and link, we let them ready... asking because the most common is to use that to set account, in this case users only have to update in case they need to use other parms, but for beginners would be more simpler

**Describe alternatives you've considered**

**Additional context**

**Comment by zdmullen** [comment]
Hey Bill. We'll be looking at taking advantage of the config file for profiles that Zowe CLI squad has been working as an item for our next PI (and beyond). It may very well be that in the future we offer the ability to enter information for multiple profiles, such as zOSMF and TSO, either directly in a JSON file, or with some sort of UI inside Zowe Explorer. Just a bit of news.

**Comment by crawr** [comment]
This issue will be handled by the team config file. #1214
