### ISSUE TITLE
Hiding Default Profile is Only Temporary

### ISSUE THREAD

**Issue by VitGottwald** [zowe/vscode-extension-for-zowe#829]
When I hide a profile in USS/JOB/DSN, after reload of window, it shows up again. This seems to happen only for the "default" profile. However in the UI there is no indication that some profile is "default" or in any way different from the others. Yet it gets resurrected after a reload.

**To Reproduce**

1. Start without any profiles
2. Create a new profile (will become default)
3. Hide the profile in USS tree
4. Reload window
5. The profile is shown in the USS tree

**Expected behavior**

After reload the profile remains hidden.

**Comment by jellypuno** [comment]
This is not a bug but a normal behavior of Zowe Explorer. If this is the first time that you create a profile, it will be tagged as a default profile. And default profiles are always loaded.

If you are requesting for an **enhancement**, loading of default profiles can be removed and can be treated as other non-default profiles but please note that it will result to conflict on other opened issues regarding loading of profiles and as well as UX experience. 

This change may also have an effect on associated profiles but I am not 100% sure.

I'm curious, what is the problem in pre-loading default profiles? Is pre-loading  not helping with UX?

Also, Tagging or Identifying a default profile is not available yet. You can open a another enhancement issue for that. For now, you can use CLI to check default profiles.

**Comment by VitGottwald** [comment]
@jellypuno I am not suggesting any particular solution. I am only pointing out that it is confusing and unexpected behaviour. As a user, I add a (first) profile. Then I hide it in some trees. But after restart it shows up again.

**Comment by VitGottwald** [comment]
@jelapan what do you think?

**Comment by phaumer** [comment]
@jellypuno Every profile type such as zosmf and ftp has their own default profile, though. If the user does not want to use zosmf and has no profile the view will be empty. Instead it should remember that the ftp profile the user used last time should be added back.
@lauren-li is working on some improvements for that also related to favorites i nhttps://github.com/zowe/vscode-extension-for-zowe/issues/742 and perhaps we can merge the two by having her also remember the list of profiles used in the settings files.

**Comment by jellypuno** [comment]
@phaumer yah. I know that and the loading of default profiles in the extension is done everytime VSCode starts. What @VitGottwald is saying is that when he chose to Hide the default profile, he expects that it will not be loaded when he restarts VSCode.

**Comment by venkatzhub** [comment]
@jellypuno @phaumer  - is there any significance for "Default profiles" in the UI - i.e how does that help the end user? 

I can understand that notion in CLI, but in the UI world - a profile is a profile, and the user can choose to hide/view/delete it and I agree with @VitGottwald - the behavior has to be consistent i.e if I as a user hid the profile - it shouldn't matter if its a default profile or not.

**Comment by jellypuno** [comment]
@venkatzhub in the past, default profiles are automatically loaded for UX since CLI is still connected to the extension. It will eliminate the manual adding of your profile during inital use. However, I think that concept changed as time goes by. 

@zFernand0 Please correct me if I am wrong.

We can remove this automatic loading of default profiles because in ZE there is no concept of default profiles. But I don't know if this is okay with ZE extensions. @phaumer @lauren-li what do you think?

**Comment by 3TInfoTinker** [comment]
Greetings to all the seniors,

An Absolute Beginner is here seeking guidance: VScode-Zowe on ubuntu
Learning/Playing with MTM2020 challenges.

I created a profile, and at some point when I was looking for a file and couldn't find besides I saw a message "you have not opened a folder yet", didn't know what is this for.

Created a folder [it was on local HD] with the same name mtm2020, and after that lost my profile. 

So, I deleted that folder and right after that, I can not have Zowe's initial layout.

**Reinstalled VScode several times, but Zowe comes out with no-look and the PLUS sign is not functioning [to me it seem like this], I am unable to access my profile and everything.**

PLEASE guide me on how to solve this and connect with the MTM.

Any help will be highly appreciated. Thanks

**Comment by zFernand0** [comment]
Hey @3TInfoTinker,
Let's chat! 😋 
https://github.com/zowe/vscode-extension-for-zowe/discussions/1106

**Comment by 3TInfoTinker** [comment]
Nice, But how? I click on both links 2nd #tag took me to the post comments, shall I start by writing a comment?

________________________________

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
