### ISSUE TITLE
Job/Uss/Dataset item expansion inconsistency

### ISSUE THREAD

**Issue by VitGottwald** [zowe/vscode-extension-for-zowe#830]
When I click a PDS in Dataset tree, or a directory in USS, it is automatically expanded. But for Jobs, I have to click on the wedge to the left of the Job to expand it. Clicking the Job item only highlights it in the tree.

**To Reproduce**

**Expected behavior**

After clicking the job item, I would expect it to expand, like it happens for Datasets and Uss directories.

**Comment by venkatzhub** [comment]
I like the idea of making things consistent across the board :). 

One question - is expanding the node when a user selects an element the right behavior? The selection of an element in a tree can be for many reasons, but expanding it by default may be annoying to users - especially if the node being expanded contains thousands of elements and might cause the UI to be locked up. 

Thoughts from the UX team?

**Comment by jellypuno** [comment]
Tagging @jelaplan

**Comment by adam-wolfe** [comment]
The original request has been implemented. We may review the UX implications in the future.
