### ISSUE TITLE
Refresh all or some data set members without having to select each individually

### ISSUE THREAD

**Issue by KToddE** [zowe/vscode-extension-for-zowe#832]
This request is not related to a problem today. However, it seems a problem could be introduced by modifying a local, older, cached copy of a member then uploading that member thus overwriting a newer copy of the member. 

I have been working with the developer of the Zowe tasks plugin to enhance a demo environment I support. I accessed a certain PDS and had a ruleset member open in VS Code (the local cached copy). I then executed a Zowe task to update that member with a new email address with a copy of that rule stored in my task project. I verified the upload by accessing OPSMVS to view the updated rule. I then returned to Zowe explorer in VS code, clicked the Refresh All button, the list of datasets and members refreshed but the new _content_ of the rule was not retrieved. I had to click the member's Pull from Mainframe icon to retrieve the updated content. 

Two options come to mind for a solution:
a) Modify Refresh All to update the list of datasets and members of each dataset AND the content of each member
b) Leave Refresh All functionality as-is and change the label to something like Refresh All Lists and add a second icon labeled something like Refresh All Content

Another alternative could be a checkbox next to Refresh All to toggle refreshing content.
Yet another alternative would be a checkbox next to each member in the list. A checkbox and possibly color coding member names could be easy to see visual cues any given member has been refreshed or not refreshed. 

The workaround today is to individually Pull from Mainframe. However, that could get very tedious in a dataset with dozens of members and seems to introduce the possibility of uploading something old.  

![zowe-cached-content](https://user-images.githubusercontent.com/9952557/83561958-5a209080-a4de-11ea-8b04-ba884612de2c.png)

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
