### ISSUE TITLE
Zowe Explorer SDK

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#833]
**Is your feature request related to a problem? Please describe.**

I would like to create a VSCode extension that extends the capabilities of Zowe Explorer but I don't know where to start

**Describe the solution you'd like**

A Zowe Explorer SDK would be helpful. We can have a template that provides a way on how to use and expand the Zowe Explorer APIs.

**Describe alternatives you've considered**

**Additional context**

This question came up during a webinar and I realize that Zowe Explorer doesn't have any SDK similar to Zowe CLI or API ML.

**Comment by jellypuno** [comment]
@zdmullen I want to work on this issue. I've successfully created a simple template. I just need to refine it,.

**Comment by JillieBeanSim** [comment]
this is completed with the Zowe Explorer APIs
