### ISSUE TITLE
Web View on initial use of Zowe Explorer

### ISSUE THREAD

**Issue by zdmullen** [zowe/vscode-extension-for-zowe#839]
**Is your feature request related to a problem? Please describe.**

Based on the experiences of new users, especially those partaking in the COBOL programming course, it is not very intuitive what first steps should be taken when opening Zowe Explorer.

**Describe the solution you'd like**

Zowe Explorer should have a web view that appears on the first open of the extension and displays information that helps new users get started, especially with guidance on creating a connection/profile. 

**Describe alternatives you've considered**

Animating the + sign for new connection, updating the readme.

**Additional context**

The implementation of a web view is not the only element to all of this. Care should be taken to use consistent terminology throughout the extension as well (create a profile vs. create a connection, etc.)

**Comment by zFernand0** [comment]
Similar to https://github.com/zowe/vscode-extension-for-zowe/issues/895

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
