### ISSUE TITLE
Update icon to indicate migration/recall for favourite data sets

### ISSUE THREAD

**Issue by Pranay154** [zowe/vscode-extension-for-zowe#844]
**Describe the bug**

When adding a data set to favourites, then migrating/recalling the data set, the icon in favourites does not update to indicate if the data set is migrated/recalled. Came across the issue when exploring issue #843

**To Reproduce**

1. Add a dataset of any type to your favourites by clicking the **Add to Favourites** button in the context menu
2. Migrate/Recall the data set using the option in the context menu
3. Refresh the data set tree using the Refresh all icon
4. Search for your Data set
5. The icon should be updated in your data sets view, but the favourites icon does not change

 

**Expected behavior**

The data set icon for favourite data sets should update simulatniously with updates to the data set itself in the data set view

**Screenshots**

<img width="366" alt="Screenshot 2020-06-08 at 16 36 22" src="https://user-images.githubusercontent.com/37961978/84050905-483f6180-a9a6-11ea-94d9-532a8da92065.png">

<img width="200" alt="Screenshot 2020-06-08 at 16 36 40" src="https://user-images.githubusercontent.com/37961978/84050912-4bd2e880-a9a6-11ea-874c-21790e8cf6c6.png">

**Desktop (please complete the following information):**

-   OS: Mac OS
-   Zowe Explorer Version: 1.6.0
-   Are you using Secure Credential Store? No

**Additional context**

None

**Comment by zFernand0** [comment]
Seems like this issue has been resovled
![image](https://user-images.githubusercontent.com/37381190/206228163-047b9068-e27b-4792-ac4e-09832ad4429a.png)
