### ISSUE TITLE
Zowe Explorer Known Issues

### ISSUE THREAD

**Issue by IgorCATech** [zowe/vscode-extension-for-zowe#846]
**Is your feature request related to a problem? Please describe.**

Currently, as a Zowe Explorer user, I am unable to find any information about errors that sometimes appear while using the extension.

**Describe the solution you'd like**

I want to have a section in the docs that contains information about existing Zowe Explorer error messages and solutions to these errors. The proposed location/placement of the section is under the Troubleshooting topic https://docs.zowe.org/stable/troubleshoot/troubleshooting.html#known-problems-and-solutions 

**Describe alternatives you've considered**

The only alternative I can think of is an increased workload for developers who will need to tackle a potentially increasing amount of users' requests. 

**Additional context**

As opposed to the other components of Zowe, there's currently no doc that describes the existing error messages and how to deal with them. ZE grows fast, as well as its audience.

**Comment by jellypuno** [comment]
Maybe this issue can be added in the Known Issues part

Error: 
“Error running command zowe.createDataset: z/OSMF REST API Error: http(s) request error event called Error: self signed certificate in certificate chain. This is likely caused by the extension that contributes zowe.createDataset.”

Solution: Set Reject-Unauthorized to false

**Comment by jellypuno** [comment]
This error can be added in Known Issues as well:

![image](https://user-images.githubusercontent.com/45042840/89910287-4f762c00-dbf0-11ea-8848-ad26ddb17cd8.png)

This happens when opening a binary file / packed data in datasets

**Comment by IgorCATech** [comment]
@jellypuno Can you please provide more context for those two cases? 
In my understanding, **the first one** happens when a user tries to create a new data set, using a profile that has the Reject-Unauthorized parameter set to true. So, the solution is to set the parameter's value to false, using the edit a profile function.
**The second one** has to do with opening a binary file. What's the solution here?

**Comment by IgorCATech** [comment]
![Rename USS error](https://user-images.githubusercontent.com/43951184/90632174-41de2900-e224-11ea-8ee1-cefb9fc06b42.png)

I wonder if this error message can still occur. If yes, how can it be reproduced? By having 'encoded slashes' in a file?

**Comment by IgorCATech** [comment]
More questions:

- How do I know what version of ZE is installed, except going to Marketplace in VS Code? Can the version be displayed using the command palette in VS Code?
- Where do I get more Known Issues from?

**Comment by zdmullen** [comment]
You can go to the Command palette, enter "Version", select the option that appears("Install a specific version of a plug-in", designate the plug-in and it will list all available versions, with the one you have installed labeled as "current".

**Comment by zFernand0** [comment]
> You can go to the Command palette, enter "Version", select the option that appears("Install a specific version of a plug-in", designate the plug-in and it will list all available versions, with the one you have installed labeled as "current".

you could also go the the extension manager, search for the extension you have installed, and the current version should appear next to it. 😋

**Comment by IgorCATech** [comment]
Merged PR here https://github.com/zowe/docs-site/pull/1378

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
