### ISSUE TITLE
Adopt strict type checking

### ISSUE THREAD

**Issue by VitGottwald** [zowe/vscode-extension-for-zowe#852]
Currently we have strict type checking [disabled](https://github.com/zowe/vscode-extension-for-zowe/blob/master/tsconfig.json#L13). That means we are not taking advantage of all the guarantees the typescript compiler offers and improves upon with every release.

If we are thinking about improving the codebase quality through tooling we should start here.

This effort could be divided into several steps by gradually enabling the following compiler checks and updating our code to compile:

- noImplicitAny
- strictNullChecks
- noImplicitThis
- strictBindCallApply
- strictFunctionTypes
- strictPropertyInitialization
- alwaysStrict
- strict

**Comment by VitGottwald** [comment]
Any one of these options could be enabled independently of the others. Doing them one by one would provide an incremental path towards strict mode. Once all the options are enabled and the code compiles without errors, the only option that needs to stay is `strict` (because it implies all the others).

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.

**Comment by traeok** [comment]
I think this should be re-opened to avoid future bugs or regressions when expecting data in functions.
The [TypeScript handbook](https://www.typescriptlang.org/docs/handbook/2/basic-types.html#strictnullchecks) highlights the main benefit: "null and undefined is the cause of countless bugs in the world." 

By enforcing strict null checks, we avoid the painful, default behavior of having to perform sanity checks on any parameter before trying to use it.
