### ISSUE TITLE
Upload ... in Command Pallet Fails

### ISSUE THREAD

**Issue by dkelosky** [zowe/vscode-extension-for-zowe#854]
**Describe the bug**
`Upload Files...` & `Upload Member...` commands to not work.

**To Reproduce**

1. Open command pallet (e.g. `Ctrl` + `Shift` + `P`)
2. Choose `Upload Files...` 
3. Select some text file to upload (e.g. `iefbr14.jcl`)

**Expected behavior**

No errors 😄 

**Screenshots**

![image](https://user-images.githubusercontent.com/14940561/84297741-0e906700-ab1c-11ea-907b-cb7c4d1c54db.png)

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Zowe Explorer Version: 1.6.0
-   (Optional) Zowe CLI Version: 6.14.0
-   (Optional) Are you using Secure Credential Store? No

**Additional context**

**Comment by JillieBeanSim** [comment]
this command pallet option is not available anymore
