### ISSUE TITLE
Uploading local files

### ISSUE THREAD

**Issue by phaumer** [zowe/vscode-extension-for-zowe#86]
Currently the MVS and USS views allow creating new files and editing them, but if the user has created files locally and wants to upload them either data set members or uss files I do not see a way of doing that.

Drag and drop could be one solution, but is a challenge as the Zowe activity group is now separated from the Explorer one. We could do drag and drop with editor tabs, but that is a bit awkward.  Another solution could be an Upload Dialog that prompts for files and targets.

**Comment by lauren-li** [comment]
@adambattenburg and I have begun working on this item. We are starting with upload to the MVS.

**Comment by markcocker** [comment]
Note that `zowe zos-files upload dir-to-uss` provides the `--attributes` option that controls file transfer encoding, exclusion, and tagging.

> A .zosattributes file can either be placed in the top-level directory you want
   to upload, or its location can be specified by using the --attributes parameter.
   .zosattributes files that are placed in nested directories are ignored.

It would be nice if this issue could use the `.zosattributes` file if it is in the root of the source file or directory to transfer.

**Comment by kristinochka** [comment]
I'm currently working on this issue.

**Comment by zFernand0** [comment]
If possible, could you assign yourself to the issue too?
I believe we can have more than one person assigned to an issue :)

**Comment by kristinochka** [comment]
@zFernand0 I don't have permission to change anything on this issue. 
![image](https://user-images.githubusercontent.com/14590297/59358633-e8629c00-8cfa-11e9-86de-93dda4acdf02.png)

**Comment by zFernand0** [comment]
> @zFernand0 I don't have permission to change anything on issues in this repo.

@kristinochka, Thanks for letting me know. I believe we need to add your team to have write access to the VSCode repo.
Can you check if you are part of any [Teams on the Zowe](https://github.com/orgs/zowe/teams) organization?
If you don't belong to any team, we may want to create a team for you 😄

**Comment by kristinochka** [comment]
@zFernand0 I'm not a member of any teams.

**Comment by zFernand0** [comment]
> @zFernand0 I'm not a member of any teams.

we will create a VSCE team. I just need confirmation :)
Sorry for any inconveniences.

**Comment by zFernand0** [comment]
A [VSCode Team](https://github.com/orgs/zowe/teams/vscode-team) has been created.
Feel free to request-to-join or accept the invite if you already got it.

**Comment by zFernand0** [comment]
> Currently the MVS and USS views allow creating new files and editing them, but if the user has created files locally and wants to upload them either data set members or uss files I do not see a way of doing that.
> 
> Drag and drop could be one solution, but is a challenge as the Zowe activity group is now separated from the Explorer one. We could do drag and drop with editor tabs, but that is a bit awkward. Another solution could be an Upload Dialog that prompts for files and targets.

Back to the topic though, I do agree with the use-case here.
Out of curiosity though, what is the Zowe Activity Group?

**Comment by kristinochka** [comment]
I believe Peter meant that File Explorer and Zowe Plugin view show up in 2 separate views (you can only see one or the other) so you can't easily drag-n-drop.

**Comment by kristinochka** [comment]
Also, the VSCode Team link takes me to `404 Not Found` page and I have not received any invites.

**Comment by zFernand0** [comment]
> Also, the VSCode Team link takes me to `404 Not Found` page and I have not received any invites.

Hey @kristinochka,
Could you try https://github.com/zowe, and click on the `Teams` tab to go to https://github.com/orgs/zowe/teams
From there, you should be able to search for VSCode
![image](https://user-images.githubusercontent.com/37381190/59457001-977ba200-8de5-11e9-810c-755af7a00295.png)

Then Click on the team and go to `Members` in order to `Request to Join`
https://github.com/orgs/zowe/teams/vscode-team/members
