### ISSUE TITLE
Simplifying the handling of SSL Certificate Validation (a.k.a., Reject Unauthorized)

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#863]
**Problem**
People who take up ZE don't understand the Reject Unauthorized field. In talking to users, they just fill that out as best as they can but they don't understand things like HTTPS, certificates etc. 

**Solution: Ideal**
Behave more like a browser which is end-user facing. Remove the Quick Pick question and prompt when using the interface. Assume SSL certificate validation is desired, and prompt  when SSL certificate validation fails in order to ask the user if she wants to proceed. If she wants to proceed, cache their response for the remainder of the IDE session for that particular service. 

This approach won't prompt someone who has a valid SSL certificate. For users who do NOT, it will ask them if they want to proceeds without. @MikeBauerCA came up with this idea and pretty much everyone we asked prefers this solution. 

We still face some challenges of properly wording it but this would be simpler. We can probably come up with something better than asking about rejecting unauthorized. 

**Solution: Workaround**
Here is short term workaround to make the language clearer. Ultimately this is a bandaid but 
![image](https://user-images.githubusercontent.com/3207260/84545010-6d94de00-accc-11ea-84a1-b6214782a67d.png)

**Comment by zdmullen** [comment]
One comment here: we should have a link in the readme to the blog that details using SSL certificates.
