### ISSUE TITLE
Allow Editing Search Strings

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#864]
**Problem**
Users have trouble refining their searches becasue they can't edit the search string. 

**Solution**
Support editing previous searches.

**Comment by jelaplan** [comment]
I tried to edit a search/filter but couldn't find a way. Has this made it to a release? @zdmullen

**Comment by zFernand0** [comment]
Hey John,
Whenever you click on a search filter, the input box will get automatically filled and the text is highlighted for you to edit.
Tip: use the arrow keys for faster editing!
