### ISSUE TITLE
Allow searching for members

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#868]
**Problem**
Users can't search for members of a dataset. They can only search or data sets themselves. 

**Solution**
Allow searching for the names of members as a more detailed thing to access.

**Comment by bearou** [comment]
It is very important for out organisation, that some kind of search possibility or filter is provided, as our source code is placed in one (!) dataset per environment. Imagine scrolling a member list in Zowe with more than 200K members...

**Comment by MikeBauerCA** [comment]
You can filter the document trees in Visual Studio Code -> https://code.visualstudio.com/docs/getstarted/userinterface#_filtering-the-document-tree

Below is a quick GIF to see it in action. I'd be interested to see if it works with so many members.
![VSCode_filter](https://user-images.githubusercontent.com/35504792/91188385-3b85fc00-e6bf-11ea-8e21-003c4c64f875.gif)

**Comment by jellypuno** [comment]
you can use Ctrl + ALT + P to filter the members that you are looking for but somehow that feature is not working for me.

**Comment by jellypuno** [comment]
> I'd be interested to see if it works with so many members.

@MikeBauerCA Yes it works. This was tested before and results can be found in issue [#327](https://github.com/zowe/vscode-extension-for-zowe/issues/327)

**Comment by MikeBauerCA** [comment]
@jellypuno after opening the PDS to see the 30k members, did you try to perform the local filter? Was it immediate?

**Comment by jellypuno** [comment]
@MikeBauerCA We have an issue with the filtering 😆 . I opened issue #992 .

**Comment by bearou** [comment]
Have used the "filter the document trees in Visual Studio Code" for the first time... Wonder why I havent seen this before !?
It seems like it filters within the VS Code "frontend", hence our problem is not solved as we have 200K+ in one single production source library... usually this is not an issue...

**Comment by bearou** [comment]
In regards to Ctrl + ALT + P, a few of us in the office have tried it, and we all get "Enter pattern..." 
Where do we learn what "pattern" should look like, since nothing happens, no matter what we type in ?

**Comment by MikeBauerCA** [comment]
It appears we need to enhance the Zowe Node SDK to support the `start` and `pattern` query parameters of the REST endpoint (https://www.ibm.com/support/knowledgecenter/SSLTBW_2.4.0/com.ibm.zos.v2r4.izua700/IZUHPINFO_API_GetListDataSetMembers.htm) and then leverage this in both Zowe Explorer and Zowe CLI.

**Comment by bearou** [comment]
> It appears we need to enhance the Zowe Node SDK to support the `start` and `pattern` query parameters of the REST endpoint (https://www.ibm.com/support/knowledgecenter/SSLTBW_2.4.0/com.ibm.zos.v2r4.izua700/IZUHPINFO_API_GetListDataSetMembers.htm) and then leverage this in both Zowe Explorer and Zowe CLI.

Out of curiosity... what about setting the `X-IBM-Max-Items` ? It appears that we do not receive the total number of members in the dataset.

**Comment by martindamp** [comment]
> It appears we need to enhance the Zowe Node SDK to support the `start` and `pattern` query parameters of the REST endpoint (https://www.ibm.com/support/knowledgecenter/SSLTBW_2.4.0/com.ibm.zos.v2r4.izua700/IZUHPINFO_API_GetListDataSetMembers.htm) and then leverage this in both Zowe Explorer and Zowe CLI.

Hi, 
I did create an issue on support for this in zowe-cli and it has now been implemented https://github.com/zowe/zowe-cli/issues/810 . The pull request still needs to be approved but i think it will be soon.

So now we only need it to be implemented in Zowe Explorer.

**Comment by JillieBeanSim** [comment]
My plan going forward on this is to first accept member or member pattern in the initial search filter of a profile and no longer throw an error if this is entered like it does now
![pds-member-filter-error](https://user-images.githubusercontent.com/49491949/98950237-c01a3680-24c6-11eb-9578-e431eb28968b.gif)

Following that we could add an additional approach being a search filter magnifying glass to data sets names or possibly a right click action on data set names to search for a member pattern within that data set.

**Comment by JillieBeanSim** [comment]
@jelaplan here is my work in progress with allowing member search in the filter search bar, what do you think?
![pds-member-filter-working](https://user-images.githubusercontent.com/49491949/99324559-92284f80-2842-11eb-8b3f-95379afb7ad0.gif)

**Comment by JillieBeanSim** [comment]
We were discussing as a team about having a new folder icon with a filter created for data set members that have a filter member search attached to them.

**Comment by jelaplan** [comment]
@crawr and @jellypuno I think it is a great start. I like your suggestion to pick a dataset and then filter the members to make it a two step process where the user can drill down - I think that it would be more obvious/apparent that filtering members can be done. 
>Following that we could add an additional approach being a search filter magnifying glass to data sets names or possibly a right click action on data set names to search for a member pattern within that data set.

I think the dataset(member) syntax is a standard convention in ISPF. But, it might not be all that obvious to the ZE user. We might want to change the quick pick instruction. Perhaps @BrandonJenkins14 or others could offer some suggestions. The current text is 
>+Create a new filter. Comma separate multiple entries (pattern 1, pattern 2, ...)

But we might try putting in an example. Someone with more MF exp probably can suggest something more accurate. 
>+Create a new filter. For example, hlq.aaa.bbb(member), hlq.ccc.ddd*

I was not familiar with @MikeBauerCA 's filter approach. I think @bearou said the same thing. I don't think it works that well. In the example, marble appears in the data set name and the member names and so a filter on mable does narrow it down. But, where the member name doesn't appear in the dataset, filtering ends up hiding everything. 

WRT filtering with cmd+option+p (ctrl+alt+p), I also can't figure that out. I've tried typing a lot of combinations but can't get it to work. 
<img width="536" alt="image" src="https://user-images.githubusercontent.com/3207260/99470467-cc612200-2912-11eb-9e42-6c673bd6391b.png">

Per @JillieBeanSim, a folder icon that indicates an active filter seems promising. It would give some feedback to the user that there is a filter in place. I could make that icon and share it with the team to see if people approve.

**Comment by crawr** [comment]
With the implemented feature in v1.12.0 regarding dataset member filtering, can we now close this issue? @jelaplan @JillieBeanSim

**Comment by JillieBeanSim** [comment]
> With the implemented feature in v1.12.0 regarding dataset member filtering, can we now close this issue? @jelaplan @JillieBeanSim

Did we ever decide if we wanted to also have a right-click action on a data set to filter the members within it?  I think that is why it wasn't attached to the PR

**Comment by jelaplan** [comment]
WRT right click filtering / drill down filtering on a data set, maybe you should create a new story for that. I wouldn't want that to hold things up. I still think it is often easier to narrow in on something step-by-step to make the syntax simpler, but what you've done is good so start with that.

**Comment by JillieBeanSim** [comment]
New issue created for the right-click action on PDS for member filter search within the tree view https://github.com/zowe/vscode-extension-for-zowe/issues/1241
Closing this issue
