### ISSUE TITLE
Enhance interface for jobs that take a long time to run

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#870]
**Problem**
When we test ZE, our jobs tend to run quickly. We are testing on systems that have little load and so respond quickly. We are also likely testing small JCL files. But, users in the field are likely to run into jobs that take a long time to run. 

**Solution**
1. Enhance job status for jobs that take a long time to run. Go beyond the simple message that the Job submitted to give users more status on their job. 
2. Support a terminate job command. 

<img width="313" alt="image" src="https://user-images.githubusercontent.com/3207260/84547231-1f360e00-acd1-11ea-9e3c-79e636acc995.png">

**Comment by zFernand0** [comment]
I believe there was a discussion regarding the implementation of a tracking/monitoring mechanism for submitted jobs that will pop up a notification saying when the job has ended (similar to how deferred actions occur in 3270 panels?)
