### ISSUE TITLE
Repeat Icon Actions in Context Menu

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#873]
**Problem**
Users sometimes ask us for features that exist. For example, add data set that is available through an icon button. Having featured in only one place can be limiting. It is advisable to have icons repeated in menus. 

**Solution**
Add an option for ‘new data set’ to the connection profile context menu. In some cases we have both icons and menu options but we do this inconsistently. We should strive for consistency.

**Comment by jelaplan** [comment]
(See related Zowe Explorer issue #871 734 and #956 about meatballs/dropdown.)

**Comment by JillieBeanSim** [comment]
most icons have been moved into right-click actions only now. closing
