### ISSUE TITLE
Put Save in ZE Menus or buttons

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#877]
**Problem**
The save feature is one of the only ones that ties into VS Code and the shortcuts. You can use control + S to save. You use the file menu to save. But, we don't have save in the ZE menus or buttons. 

**Solution**
Add a Save option to the context menu for the Data Set or Member.

**Comment by JillieBeanSim** [comment]
@zFernand0 is this still something we want to consider? Most vsc users will use keyboard shortcut to save so not sure if this is something else we want to include in right-click menu.
