### ISSUE TITLE
Error on dataset listing

### ISSUE THREAD

**Issue by ishche** [zowe/vscode-extension-for-zowe#881]
When I try to list my datasets I have this error message:

![image](https://user-images.githubusercontent.com/590426/84796102-8f59d200-aff8-11ea-9c83-640ee066ce1d.png)

(There is no ARCHIVED datasets under my filter)

-   OS: macOS
-   Zowe Explorer Version: 1.6.0

Also, where can I find ISPF logs?

**Comment by jellypuno** [comment]
You are viewing an HFS File? you are not allowed to do that even in Mainframe. 
I believe ISPF logs are these: **.ISPF.ISPPROF but I am not sure

**Comment by jellypuno** [comment]
Or is it a PDSE file? I am not sure if z/OSMF APIs are handling PDSEs. Do you know @zFernand0 ?

**Comment by recaph** [comment]
@ishche do you have archived datasets by any chance?

**Comment by dkelosky** [comment]
+1 @recaph - specially if they're archived on pseudo volser ARCIVE...

For example, you try to list data sets on some HLQ.*, any matching data set archived on ARCIVE will probably get this error.

**Comment by ishche** [comment]
> Or is it a PDSE file? I am not sure if z/OSMF APIs are handling PDSEs. Do you know @zFernand0 ?

Yes, I think it's related to PDSE. I do have PDSE on my list and I don't have any archived datasets there.

As the error message says :)

**Comment by jellypuno** [comment]
@ishche Why did you close it? Is it fixed now? My PDSE was defined this way and I can open it in VSCode

![Capture](https://user-images.githubusercontent.com/45042840/84875015-b1e5fc80-b085-11ea-94bc-7edd41fdbcd7.JPG)

**Comment by ishche** [comment]
The only difference that I can see is DSORG. I have PO there.
