### ISSUE TITLE
Datasets are deleted after some time (volume rule)

### ISSUE THREAD

**Issue by ishche** [zowe/vscode-extension-for-zowe#882]
On our system, by default ZE creates dataset in volume with automatic dataset deletion after some time.

Is there a way to specify volume for new datasets?

**Comment by Alexandru-Dumitru** [comment]
Hi Yuriy,

Actually, there is. You can provide a specific volume in the `settings.json` file under the type of data set you want to create. For example, a PDS:
```
"Zowe-Default-Datasets-PDS": {
  "volume": "YOUR_VOLUME_NAME"
}
```
There are some other values which have defaults. For example:
```
"Zowe-Default-Datasets-PDS": {
  "dsorg": "PO",
  "alcunit": "CYL",
  "primary": 1,
  "secondary": 1,
  "dirblk": 5,
  "recfm": "FB",
  "blksize": 6160,
  "lrecl": 80
}
```

**Comment by ishche** [comment]
Thanks!
