### ISSUE TITLE
Proposal: Use .vscodeignore to include rather than exclude files for the VSIX

### ISSUE THREAD

**Issue by lauren-li** [zowe/vscode-extension-for-zowe#883]
**Is your feature request related to a problem? Please describe.**
When new files for development are added into Zowe Explorer, developers need to remember to update the `.vscodeignore` file (particularly if they are at the project root level or in one of the output folders) to exclude them from the final extension VSIX.

**Describe the solution you'd like**
In a [comment](https://github.com/zowe/vscode-extension-for-zowe/pull/860#discussion_r440146392) for PR #860, @tjohnsonBCM suggested that we might want to have `.vscodeignore` ignore everything, and then add back only files that we want included in the final VSIX. (Example [here](https://github.com/Microsoft/vscode-vsce/issues/12#issuecomment-285964473)).

Per Timothy:
> This could prevent new folders/files that are added to the repo in the future from accidentally getting bundled in the VSIX

**Describe alternatives you've considered**
Keep the status quo (i.e. use the `.vscodeignore` file as an exclude list for developer files that we don't want to go into the final extension VSIX).

**Additional context**
N/A

**Comment by jellypuno** [comment]
@lauren-li can we close this issue?

**Comment by lauren-li** [comment]
@jellypuno We have not implemented the changes in this proposal. However, if the Zowe Explorer squad has decided not to do this, I think it is fine to close.

**Comment by jellypuno** [comment]
@lauren-li we don't have to close it. I just saw a .vscodeignore in our repo so I thought it was implemented

**Comment by JillieBeanSim** [comment]
completed with PR #2042
