### ISSUE TITLE
Make it easier to edit datasets and files with num mode on

### ISSUE THREAD

**Issue by recaph** [zowe/vscode-extension-for-zowe#884]
When retrieving a file from MVS with num mode turned on, it becomes inconvenient to adjust the num values on every line modified before saving the file.

Is it possible to retrieve MVS files in by clearing num mode? 
Not sure exactly on num mode's usefulness, but while saving, the num mode can be switched on in the background to preserve setting on the mainframe.

Alternatively, a right-click option can be added in VS Code zos editors to toggle num mode. 

![image](https://user-images.githubusercontent.com/704289/84823354-cd003000-afe3-11ea-939b-6a88afb62701.png)

**Comment by dkelosky** [comment]
Hi @recaph - I think sequence numbers served a purpose when a program was written with punch cards, so if you dropped your program, you could reorganize it 😀.

Do you need these preserved on the mainframe side?  Can you `unnum` in ISPF as a workaround in the meantime?

**Comment by recaph** [comment]
@dkelosky Good to know about the background for sequence numbers... Now that we are years (decades?) past the punch cards, I wonder why IBM still chose to keep seq. nos. in files... to me it feels a lot of storage wasted to just keep unused seq. nos.
 
I have been doing that already - switching to ISPF from VSCode to just **unnum**

But given the aim of the extension is to keep developer (or for that matter anyone) from falling back to ISPF, I feel this is a must-have fix/feature.

**Comment by dkelosky** [comment]
Mainframe is backwards compatible 😄 - presumably they don't know all the ways sequence are numbers are used and retain the behavior.

A fix/feature makes sense, perhaps done at the CLI level first?  Would it be acceptable if this part were excluded:

> ... while saving, the num mode can be switched on in the background to preserve setting on the mainframe.

**Comment by recaph** [comment]
@dkelosky Totally works with me... I never felt the need for seq. nums any... only had the point in case some were using nums. That I think will be in a minority.

**Comment by venkatzhub** [comment]
@dkelosky @recaph - seq numbers are used by some customers to have some audit/change log info. So while no more punch cards, that concept has been put to use for other things. So, while its an annoyance when editing - we need to ensure the solution would preserve what exists in the seq number area.

**Comment by dkelosky** [comment]
Thanks @venkatzhub - in the proposed short term fix, sequence numbers will be preserved unless they take a deliberate action to remove them.  Longer term, maybe we can help users have a better editing experience will keeping sequence.  Do you think the short term fix is acceptable?

**Comment by venkatzhub** [comment]
@dkelosky - yep, I think any solution that will preserve seq numbers is good. In addition to the CLI, would there be an API as well? I'm thinking the editors after open can trigger it automatically (based on a preference)....

**Comment by dkelosky** [comment]
I suppose for an API - perhaps we could check z/OSMF APIs and potentially open an RFE

**Comment by venkatzhub** [comment]
I could not find anything in zOSMF..

**Comment by zFernand0** [comment]
This issue is dependent on https://github.com/zowe/zowe-cli/issues/755

**Comment by zdmullen** [comment]
The squad discussed this and feels that it falls more under a discussion of LSP work perhaps, and less of a feature that would be implemented in Zowe Explorer, if that makes sense.
