### ISSUE TITLE
Simplify text in dialog when creating a profile

### ISSUE THREAD

**Issue by zdmullen** [zowe/vscode-extension-for-zowe#885]
**Is your feature request related to a problem? Please describe.**

Currently, when you create a profile, the first dialog (in the command palette) reads "Chose "Create new..." to define a new profile or select an existing profile to Add to the USS Explorer."

This same message is also displayed when creating a profile for USS and Jobs. 

**Describe the solution you'd like**

Simplify the message in the following manner and propagate it to all profile entry points:
 
Choose "Create new..." to define a new profile or select an existing one

Thanks!

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/38981509/84889112-9b956c00-b098-11ea-9db6-bba75c0c40b6.png)

**Comment by venkatzhub** [comment]
Also, the USS Explorer is misleading....

**Comment by zFernand0** [comment]
> Also, the USS Explorer is misleading....

If I remember correctly this is due to the profile being automatically added to the section in which it was introduced.
For example, if I create a new connection from the datasets node, then the profile gets automatically selected for me :yum:

I do agree that simplifying it will be great!

**Comment by mpettis** [comment]
I would like to add to this: I would like a single page that allows me to enter connection information (name, url, username, password, connection type, etc.) that has all of the fields on that page and a single submit button. Having a sequence of single prompts to fill is cumbersome. Sometimes I have to flip between pieces of information, and if I accidentally hit escape or do something wrong, I have to start from scratch again in the creation of a connection/profile. A stable page where I am allowed to enter all of the config info at once, and then submit, would be a great UI enhancement.

See my comment at: https://github.com/zowe/vscode-extension-for-zowe/issues/861

**Comment by crawr** [comment]
closing in favor of #1123
