### ISSUE TITLE
Editing Zowe Explorer Settings

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#893]
**Describe the bug**

As I tried to edit the Zowe Explorer settings, I clicked edit in settings.json and the value that I get is `null`

![Capture](https://user-images.githubusercontent.com/45042840/85129304-290cc380-b233-11ea-9c6a-bf9556775e96.JPG)
`"Zowe-Default-Datasets-PS": null`

**To Reproduce**

**Expected behavior**

My expectation is it will be in this format:
```
"Zowe-Default-Datasets-PS": {
  "dsorg": "PS",
  "alcunit": "CYL",
  "primary": 1,
  "secondary": 1,
  "recfm": "FB",
  "blksize": 6160,
  "lrecl": 80
}
```

**Screenshots**

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Zowe Explorer Version: latest
-   (Optional) Zowe CLI Version: latest
-   (Optional) Are you using Secure Credential Store? no

**Additional context**

**Comment by JillieBeanSim** [comment]
this is working. closing
