### ISSUE TITLE
What's New in Zowe Explorer VSCode Page

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#895]
**Is your feature request related to a problem? Please describe.**

Whenever we have a release, we can create a "What's New in Zowe Explorer Page" similar to the image below:

![Capture](https://user-images.githubusercontent.com/45042840/85196871-83faf500-b2dd-11ea-89db-970a810de7ec.JPG)

In this way we can specifically point them to the recent enhancement that we have done for that release.

**Describe the solution you'd like**

**Describe alternatives you've considered**

A Youtube Video is also nice but too much work

**Additional context**

**Comment by crawr** [comment]
Another alternative that I saw from GitLens: 

<img src="https://user-images.githubusercontent.com/45845502/99250397-e106c280-280b-11eb-94a2-754a96eb9c4d.png" alt="drawing" width="400"/>

**Comment by crawr** [comment]
Already implemented and part of release procedure
