### ISSUE TITLE
Add Zowe Explorer FAQ

### ISSUE THREAD

**Issue by IgorCATech** [zowe/vscode-extension-for-zowe#897]
**Is your feature request related to a problem? Please describe.**

Unlike CLI, Zowe Explorer doesn't have FAQ in Zowe Docs. 

**Describe the solution you'd like**

Add the ZE-FAQ to Zowe FAQ https://docs.zowe.org/stable/getting-started/freqaskques.html#frequently-asked-questions 
Use https://docs.google.com/document/d/1QD5_eqLU_CDzbNSBUpupwuJnHUHDo9Li6ZpapNxku-Y/edit# for content.

**Comment by IgorCATech** [comment]
First draft https://github.com/zowe/docs-site/blob/FAQ/Known-Issues/docs/getting-started/freqaskques.md

**Comment by IgorCATech** [comment]
PR opened against the docs-staging branch in the Docs Site repo https://github.com/zowe/docs-site/pull/1348

**Comment by IgorCATech** [comment]
Working on Known Issues locally

**Comment by IgorCATech** [comment]
Add RNs of 1.8.0 to summaryofchanges

**Comment by zdmullen** [comment]
This has already been merged and published in Zowe Docs.
