### ISSUE TITLE
System tests / unit tests need sustainability updates

### ISSUE THREAD

**Issue by AHumanFromCA** [zowe/vscode-extension-for-zowe#9]
The System and Unit tests need to be evaluated and re-written to be more sustainable. 

This became apparent while developing #1. This change was a simple removal of code which turned into a nightmare for testing. This simple change caused cascading unit test failures to the point where we aren't really sure why. Most of this could be solved by making test cases much smaller than they currently are right now.

**Comment by Colin-Stone** [comment]
Reduce the size of testcases by increasing the number of tests so they are explicit

**Comment by Colin-Stone** [comment]
Largely addressed with the reworking of extension file to restructure where the different containers were initialized
