### ISSUE TITLE
Implement the "like" data set capability available from zOSMF API

### ISSUE THREAD

**Issue by zdmullen** [zowe/vscode-extension-for-zowe#904]
**Is your feature request related to a problem? Please describe.**

I would like to be able to do "allocate like" inside of Zowe Explorer. This should be available now that zOSMF has a REST parameter for allocate like.

This should be implemented in Zowe CLI so that Zowe Explorer can implement it. 
Please refer to https://github.com/zowe/zowe-cli/issues/754 for SDK implementation details.

**Describe the solution you'd like**

Create a new data set and in the drop down of choices, be able to select "allocate like" at the bottom of the list.

Or

Right + click on a particular data set and select "Allocate like". 

Further refinement with regard to the UX will be needed, of course. 

**Additional context**

IBM documentation about the new REST parameter:

https://www.ibm.com/support/knowledgecenter/SSLTBW_2.4.0/com.ibm.zos.v2r4.izua700/IZUHPINFO_API_CreateDataSet.htm

**Comment by jelaplan** [comment]
An idea here is to implement copying of data sets. And then have two paste options. One to paste the a copy of the dataset and one to allocate like. 

I'm wondering how fixed we are on the term allocate like. I guess that  is a mainstay of ISPF MF users but it is not self-revealing meaning wise. Pasting the file properties might be closer.

**Comment by katelynienaber** [comment]
Working on getting this implemented in CLI [here](https://github.com/zowe/zowe-cli/pull/766).

**Comment by jelaplan** [comment]
I have some concerns with the menu label Allocate Like. It is likely familiar to experienced mainframers. But for the modern developer experience, that name is obscure and hard to interpret. 

I looked at some [IBM doc around Eclipse and Z Open Development](https://www.ibm.com/support/knowledgecenter/SSUFAU_2.0.0/com.ibm.etools.zide.cmn.doc/topics/allocateLike.html) and read the following snippet "click Copy characteristics from an existing data set." That phrase is more descriptive of the feature. I wonder if we might append the menu label. Some ideas:
- Allocate Like (Copy File Type)
- Allocate Like (Copy File Format)
- Allocate Like (New File with Same File Format)
- Allocate Like (Copy DS Characteristics)
- Allocate Like (Copy File Details)
- Allocate Like (Copy File Attributes)
- Allocate Like (New File with  Same Attributes)
- Allocate Like (New Dataset)
- Create New Dataset Modelled on This
- New Dataset with the Same Format
- Create New Dataset Like This One

**Comment by katelynienaber** [comment]
@jelaplan I have changed the name of Allocate Like in the PR to **Allocate Like (Copy File Attributes)**
