### ISSUE TITLE
Enable Zowe Explorer to read base profiles/tokens authorized in CLI

### ISSUE THREAD

**Issue by zdmullen** [zowe/vscode-extension-for-zowe#912]
**Is your feature request related to a problem? Please describe.**

This should be part of the development to provide users with the SSO experience connected to the API ML.

**Describe the solution you'd like**

As a user, if I have created a base profile and had a token created in Zowe CLI, I want to be able to use that profile in Zowe Explorer (already authenticated then). 

In terms of experience, I should be able to just click **+** and the profile should be there (with valid token from CLI)

If the token is invalid, initially we can provide a message like "Hey pal, go and get your token!" 

We address the token question and authorization in a subsequent issue.

**Comment by MikeBauerCA** [comment]
@zdmullen @zFernand0 I would recommend the first step to be to simply respect the default base profile. Today, CLI users still need to create z/OSMF service profiles for their base-path information even when using SSO via APIML. 

CLI users are also leveraging a single base profile to store their username, password, and reject-unauthorized settings in a single place while still using z/OSMF service profiles for hostname, port when going direct to the service.

So for now, the + icon could still simply add z/OSMF service profiles to the view but respect fallback values specified in the default base-profile if they are not found in the service profile.

**Comment by zdmullen** [comment]
As Mike specified in the above comment, the scope for this particular issue will be to enable to loading of z/OSMF service profiles even when they do not contain particular values that can be found in the base profile.

**Comment by jellypuno** [comment]
Closing this issue. this has already been implmneted.
