### ISSUE TITLE
Implement new workflow for creating base profiles

### ISSUE THREAD

**Issue by zdmullen** [zowe/vscode-extension-for-zowe#913]
**Is your feature request related to a problem? Please describe.**

Support for SSO via the API ML

**Describe the solution you'd like**

As a user, not only do I want Zowe Explorer to read/use the base profiles and tokens I've created and authorized via the Zowe CLI, but I also want to be able to create a base profile in Zowe Explorer. Of course, I don't want my experience of creating normal zOSMF profiles greatly changed though. 
**Describe alternatives you've considered**

**Additional context**
This provides a view of the possible flow:

![image](https://user-images.githubusercontent.com/38981509/85838070-48f33880-b799-11ea-8559-ccbbb721081f.png)

**Comment by zdmullen** [comment]
This is actually the next phase of SSO implementation, and will not be addressed during the current PI.

**Comment by jellypuno** [comment]
this will not be implemented
