### ISSUE TITLE
Implement prompting for token/credentials (SSO for API ML)

### ISSUE THREAD

**Issue by zdmullen** [zowe/vscode-extension-for-zowe#914]
**Is your feature request related to a problem? Please describe.**

Part of SSO for API ML implementation

**Describe the solution you'd like**

With base profiles that I have created via Zowe CLI, if my token is no longer valid, I expect be to be prompted and able to log in again to get a token and begin my work. 

**Additional context**

This follows from the previous issue, #913. 

This will require some UX consideration.

**Comment by zFernand0** [comment]
After discussions with the CLI squad, we can collaborate in ways to expose a callback function for providing credentials from the Zowe Explorer. See https://github.com/zowe/imperative/issues/422 for more details.
