### ISSUE TITLE
Validate Profile will require full reload of VS Code to activate an inactive profile

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/vscode-extension-for-zowe#917]
**Describe the bug**
If a profile is labeled inactive due to not being through a firewall, VPN, or the server is down, once through the firewall, VPN is active, or the server is back up the user will have to do a refresh of VS Code to do a new search/ get an active validation of profile.

The user should either be able to just do a new search/validation or refresh the view then proceed.

**To Reproduce**

1. Go to do a search on a profile and to validate profile knowing the validation will fail
2. Do what is needed to fix the issue for the validation whether it is going through a firewall, connecting the VPN, or restarting the server
3. Try to search profile again after server is up and accessible where validation should pass (this will fail again)
4. Refresh the view where validation has failed and try to search profile again once server is up and accessible where validation should pass (this will fail again)
5. Refresh VS Code and once Zowe Explorer is activated try to search profile that server is up and accessible where validation should pass (this will pass)

**Expected behavior**

The user should either be able to just do a new search/validation or refresh the view then proceed.

**Desktop (please complete the following information):**

-   OS:
-   Zowe Explorer Version:
-   (Optional) Zowe CLI Version:
-   (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by jellypuno** [comment]
Unfortunately, I added the splice of profilesForValidation in editSession only. Maybe profilesForValidation should be removed and we can just run validation everytime checkCurrentCredentials is called. I do not like this idea though.

**Comment by JillieBeanSim** [comment]
Branch work is done on: https://github.com/zowe/vscode-extension-for-zowe/tree/issue917-refresh-for-profile-validation

**Comment by JillieBeanSim** [comment]
Get a strange error back where it should read `profile inactive...` while running Dev Host due to webpack not getting error strings or something.  Issue created #944 

![image](https://user-images.githubusercontent.com/49491949/87568609-edc7ae00-c693-11ea-8e9d-75c045f2b2b8.png)

**Comment by JillieBeanSim** [comment]
I redid the work on from the prepare-1.7.1 branch without webpack and here is a gif of it working @jellypuno @dkelosky @zFernand0 @lauren-li 
In this scenario the server is down so the validation fails, I then submit a job to start the server back up then just re-search which revalidates since the `profile.status === "inactive"` and the profile is then active and valid
Let me know what you think.

![revalidation-after-invalid](https://user-images.githubusercontent.com/49491949/87581515-1311e780-c6a7-11ea-8c33-86ecb0d0f9ed.gif)

**Comment by JillieBeanSim** [comment]
The only change is from this:
`// Filter profilesForValidation to check if the profile is already validated`
`this.profilesForValidation.filter((profile) => {`
`      if (profile.name === theProfile.name) {`
`           filteredProfile = {`
`                 status: profile.status,`
`                 name: profile.name`
`            };`
`      }`
` });`
to this:
`// Filter profilesForValidation to check if the profile is already validated as active`
`this.profilesForValidation.filter((profile) => {`
`      if ((profile.name === theProfile.name)&&(profile.status === "active")) {`
`           filteredProfile = {`
`                 status: profile.status,`
`                 name: profile.name`
`            };`
`      }`
` });`

**Comment by JillieBeanSim** [comment]
I have also tested my branch changes with @lauren-li fix PR #945 for issue #944 and all is working as expected

**Comment by lauren-li** [comment]
> I redid the work on a branch created off the prepare-1.7.1 branch without webpack and here is a gif of it working @jellypuno @dkelosky @zFernand0 @lauren-li
> In this scenario the server is down so the validation fails, I then submit a job to start the server back up then just re-search which revalidates since the `profile.status === "inactive"` and the profile is then active and valid
> Let me know what you think.

@JillieBeanSim This seems to work for when the server goes from down to up. Would we also want to implement the same thing in reverse? (I.e. If the server was up but then goes down, the validation circle currently still stays green unless the user reloads VS Code.)

**Comment by JillieBeanSim** [comment]
> Unfortunately, I added the splice of profilesForValidation in editSession only. Maybe profilesForValidation should be removed and we can just run validation everytime checkCurrentCredentials is called. I do not like this idea though.

@jellypuno taking the profilesForValidation out and checking everytime would be ideal for monitoring system changes to address @lauren-li's comment above.  Why do you not like this idea?
