### ISSUE TITLE
Validating profiles blocks Zowe Explorer without notifying the users

### ISSUE THREAD

**Issue by phaumer** [zowe/vscode-extension-for-zowe#918]
**Describe the bug**

The validate profile operation results into a very unresponsive user experience. On some of my LPARs running the validate can take up to 30 seconds, sometimes longer.  When I click the Search icon for such a profile there is no response shown to the user, they do not know what is happening (even if it just takes 3 seconds) and the result will be that the user clicks multiple times and thinks that it does not work.

**To Reproduce**

1. Run CLI command check status and time how long it takes
2. Find your slowest profile and click the Search icon
3. Nothing happens until the validation completes. You can also not do anything else such as adding another profile.

**Expected behavior**

I propose several solutions:

1. Show an info dialog on the lower right telling the user that the profile is being validated. Close it once done.
2. Show the blue working animation at the top  similar to when we expand a data set or load a file. Also show the circle animation next to the profile node.
3. Provide a user setting to switch off automatic validation. 
4. Add a right-click context menu for the user to manually start a validation when the automatic setting is switched off.

**Desktop (please complete the following information):**

-   OS: all
-   Zowe Explorer Version: 1.7
-   (Optional) Zowe CLI Version: 6.3
-   (Optional) Are you using Secure Credential Store? no

**Comment by zdmullen** [comment]
See issues #921 and #922 as the next steps to improving this experience.

**Comment by ishche** [comment]
It seems that this issue somehow related to #977

**Comment by phaumer** [comment]
Fixed upstream
