### ISSUE TITLE
Alert user to validation of profiles

### ISSUE THREAD

**Issue by zdmullen** [zowe/vscode-extension-for-zowe#921]
**Is your feature request related to a problem? Please describe.**

This is related to Pete's issue, #918, and would be the quick fix out of the options. 

**Describe the solution you'd like**

In short, as a user, I want a dialog box and/or spinner that informs/shows me the process of the profile being validated. 

**Describe alternatives you've considered**

The follow up to this will be another issue (#922), providing the ability to disable the validation setting.

**Comment by JillieBeanSim** [comment]
I have a validation notification for this set up, but I would like to know other scenarios to test out other than searching so I can test more to make sure the notification is working in all instances.
Branch: https://github.com/zowe/vscode-extension-for-zowe/tree/issue921-validation-information

![validation-notification](https://user-images.githubusercontent.com/49491949/86368917-c6142700-bc4b-11ea-940f-ebcdf9ef05bc.gif)
