### ISSUE TITLE
The ebcdic x'CA 'character (IBM-1147) is missing after transfer with ZOWE Explorer (with encoding 1147)

### ISSUE THREAD

**Issue by FALLAI-Denis** [zowe/vscode-extension-for-zowe#923]
**Describe the bug**

The ebcdic x'CA 'character (IBM-1147) is not displayed in VS Code editor, but present in transfered file. 
On the other hand the character x'FF 'is displayed whereas in other software it is not.

In transfered file, UTF8 encoding, character is x’AD’. 
In VS Code x’AD’ character seem to be a zero width character.

VS Code encoding is forced to UTF8, ( no autoGuessEnciding).

**To Reproduce**

z/OSMF profile with --encoding 1147.
A member of PDS containing all the characters authorized in IBM-1147 EBCDIC is opened in ZOWE Explorer.
All the characters are well displayed in VS Code except the character coded x'CA' in EBCDIC which is eliminated.

Note: VS Code editor is IBM Z Open Editor, JCL type. 

**Expected behavior**

Restitution of all characters.

**Screenshots**

File on mvs host:

![ZEX-1147-xCA-Host](https://user-images.githubusercontent.com/63861965/86360726-0fc43800-bc73-11ea-802b-a1bcd8ce6c2b.png)

File opened in VS Code:

![ZEX-1147-xCA-ZOWE Explorer](https://user-images.githubusercontent.com/63861965/86361054-8f520700-bc73-11ea-8fa4-72181692334a.png)

File tranfered by ZOWE CLI and opened in an other editor:

![ZEX-1147-xCA-ZOWE CLI](https://user-images.githubusercontent.com/63861965/86362253-47cc7a80-bc75-11ea-8fe7-f3135e9f2a01.png)

Temp folder of ZOWE Explorer extension:

![ZEX-1147-xCA-ZOWE Explorer-2](https://user-images.githubusercontent.com/63861965/86362604-d4773880-bc75-11ea-9937-5b54b56f3a1e.png)

VS Code editor with "Greemlins tracker" and `"editor.renderWhitespace": "all"` setting:

![ZEX-1147-xCA-ZOWE Explorer-3](https://user-images.githubusercontent.com/63861965/86535608-d1808000-bee1-11ea-98a8-d63a2de9f91d.png)

**Desktop (please complete the following information):**

-   OS: Windows 10 PRO 64 "1607"
-   Zowe Explorer Version: 1.7.0  (VS Code 1.46.1)
-   Zowe CLI Version: 6.17.3
-   Are you using Secure Credential Store? Yes

**Comment by FALLAI-Denis** [comment]
This is a Chromium issue...

https://github.com/microsoft/vscode/issues/34176 
https://bugs.chromium.org/p/chromium/issues/detail?id=767950

**Comment by dkelosky** [comment]
Good find!
