### ISSUE TITLE
Favourited search icon changes (incorrectly?)

### ISSUE THREAD

**Issue by Pranay154** [zowe/vscode-extension-for-zowe#924]
**Describe the Question**

When I add a search pattern for datasets/uss/jobs, and add that search to favourites, the icon changes to the icon displayed next to the profile once I click on that favourited search (not sure if this is intended behaviour). Should the search icon remain once I click it?

**To Reproduce**

1. Enter a search pattern for your datasets/uss/jobs

2. Add that search to your favourites

3. Click on the favourited search to execute the search

4. The search icon changes to the icon next your profile 

**Expected behavior**

The search icon should remain so that it is clear for the user that it is a favourited search (maybe I haven't interpreted it the correct way, hence the `question` label rather than a `bug`.

**Screenshots**

<img width="350" alt="Screenshot 2020-07-02 at 16 04 45" src="https://user-images.githubusercontent.com/37961978/86375554-c3cac080-bc7d-11ea-8af1-b9a272ff5fab.png">

The icon when I add the search to favourites ☝️ 

<img width="354" alt="Screenshot 2020-07-02 at 16 03 47" src="https://user-images.githubusercontent.com/37961978/86375486-a72e8880-bc7d-11ea-8e79-c501ae58b142.png">

The icon after I click the favourited search ☝️ 

**Desktop (please complete the following information):**

-   OS: Mac OS 
-   Zowe Explorer Version: 1.7.0
-   (Optional) Are you using Secure Credential Store? No

**Additional context**

Feel free to close the issue if this is intended behaviour 😄

**Comment by jellypuno** [comment]
@lauren-li I feel like this was already fixed

**Comment by lauren-li** [comment]
@jellypuno I believe @JillieBeanSim fixed this as part of her member filtering icon PR #1146.

**Comment by jellypuno** [comment]
Closing this issue. Fix is part of v1.12.1
