### ISSUE TITLE
Job Tree - Refresh Icon Tooltip

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#93]
Issue #66 pointed out that one of the refresh buttons wasn't working. When I look at the window, I see two refresh buttons. The top one seems to be a refresh all and the bttom is for that LPAR. I recommend we change the tooltip on the top one from 'refresh' to 'refresh all'

<img width="329" alt="image" src="https://user-images.githubusercontent.com/3207260/58646227-f4019c00-82d2-11e9-8574-9247cb2d916a.png">

**Comment by Colin-Stone** [comment]
https://github.com/zowe/vscode-extension-for-zowe/pull/247
