### ISSUE TITLE
Increase Unit Test Coverage

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#931]
- [x] Remove: `renameUSSNode` in `src/uss/actions.ts`
- [ ] Unit test: `moveTempFolder` in `src/extension.ts`
- [ ] Unit Test: Initialize a DatasetTree with persistent favorites (see `initialize` in `src/dataset DatasetTree.ts`)
- [ ] [optional?]: Add placeholder tests for placeholder functions in `src/dataset DatasetTree.ts`
- [ ] [optional?]: Unit test `isDirtyInEditor` and `openedDocumentInstance` (getters in `src/uss/ZoweUSSNode.ts`)
- [ ] Items in https://github.com/zowe/vscode-extension-for-zowe/issues/968#issuecomment-675448076

Checkout `increase-coverage` for progress.

**Comment by lauren-li** [comment]
@zFernand0 It looks like if `renameUSSNode` in `src/uss/actions.ts` is removed, then `deleteFromDisk` in the same file (and its unit tests, which are listed under unit tests for `renameUSSNode`) can also be removed, as `renameUSSNode` was the only function that called `deleteFromDisk`.

**Comment by zFernand0** [comment]
closing in favor of:
- #1965 
- #1946
