### ISSUE TITLE
Zowe explorer getting error when trying to retrieve datasets

### ISSUE THREAD

**Issue by joeyb0719** [zowe/vscode-extension-for-zowe#935]
**Describe the bug**
A clear and concise description of what the bug or error is.
i get an error when trying to retrieve dataset. 

Retrieving response from zowe.List Error: z/OSMF REST API Error:
Rest API failure with HTTP(S) status 500
rc:       4
reason:   2
category: 2
message:  startDispatcher: received unexpected TsoServletException while starting dispatcher (see log)

**Steps to Reproduce**

1.
2.

**Expected behavior**
I expected to retrieve datasets.

**Screenshots**
![image](https://user-images.githubusercontent.com/51205930/86964581-4814bc00-c134-11ea-969b-fd471c3bfe7e.png)

**Logs**
If applicable, add server logs collected at the time of your problem.

**Details**
 - Version and build number: [e.g. 0.4.4-SNAPSHOT build # 155]
 - Test environment: [e.g. zD&T, zPDT, MONOPLEX, SYSPLEX, z/OS Rev 2.2, TSS, RACF, ACF2, or any other germane detail]

**Web Browser Details (if the bug relates to Zowe Desktop usage):**
 - OS: [e.g. macOS, Windows]
 - Browser [e.g. Chrome, Safari]
 - Version [e.g. 71.0.3578.98]

**REST API client (in case of REST API issue):**
 - Technology: [e.g. Spring Boot, Node.js, Postman]
 - OS: [e.g. Windows 10]

**Shell Environment Details (if the bug relates to CLI):**
 - Technology: [e.g. zsh, cygwin, cmd, powershell, bash]
 - OS: [e.g. MacOS 10.13, Windows 10, Ubuntu 16.04 LTS]

**Additional context**

**Comment by jellypuno** [comment]
@joeyb0719 If it helps, I've seen this z/OSMF issue with the same category and reason as your error: https://www.ibm.com/support/pages/apar/PI63398

**Comment by jellypuno** [comment]
@joeyb0719 is this still happening?

**Comment by joeyb0719** [comment]
No..I’m good thanks

**Comment by jellypuno** [comment]
ok cool. closing this issue
