### ISSUE TITLE
Allow migrated data sets to be deleted

### ISSUE THREAD

**Issue by Pranay154** [zowe/vscode-extension-for-zowe#938]
**Is your feature request related to a problem? Please describe.**

Add a feature to delete migrated data sets

**Describe the solution you'd like**

When a data set is in a migrated context, I should be able to delete it using the `hdelete` hsmcommand

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by JillieBeanSim** [comment]
This enhancement has had no community activity for 12 months. The issue also has less than 10 up-votes by the community. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed. If you feel that this enhancement should continue to be available for community up-votes, you may reopen this issue.
