### ISSUE TITLE
Commands to make all profiles secure or plain text

### ISSUE THREAD

**Issue by ghost** [zowe/vscode-extension-for-zowe#939]
**Is your feature request related to a problem? Please describe.**

As a Zowe Explorer user, I am unable to easily migrate the credential storage of all my profiles from secure to plain text, or vice versa.

**Describe the solution you'd like**

In the Command Palette, I would like 2 commands:
* Update all profile credentials to be secure
* Revert all profile credentials to be in plain text

**Describe alternatives you've considered**

The Secure Credential Store plugin for Zowe CLI has somewhat of an alternative. It includes an `scs update` command that can be used to migrate credentials from secure to plain text. But it does not support reverting credential storage to plain text, and a solution that requires the CLI will not work for standalone ZE users.

**Additional context**

Perhaps if ZE has the following setting, users should be prompted after changing it whether they want to migrate their profile credential storage.

![image](https://user-images.githubusercontent.com/50887074/87449144-cb1d9280-c5ca-11ea-8d60-b06631ecbf17.png)

**Comment by JillieBeanSim** [comment]
SCS is no longer supported with v2. closing
