### ISSUE TITLE
Profile Validation After Fixing Errors

### ISSUE THREAD

**Issue by dkelosky** [zowe/vscode-extension-for-zowe#940]
I opened a blank request for a question (instead of opening a bug or requesting a feature).  

I tried to use a profile in Zowe Explorer which had an invalid host.  I get:

```
Error: Profile Name tso9 is inactive. Please check if your Zowe server is active or if the URL and port in your profile is correct.
```

I corrected my host name using Zowe CLI commands.  When I try to "Search Data Sets by Entering Patterns" I get:

```
Error: Profile Name tso9 is inactive. Please check if your Zowe server is active or if the URL and port in your profile is correct.
```

It seems I could not get my profile active via the refresh or searching.  Is there any way to activate my profile without restarting VS Code?

**Comment by jellypuno** [comment]
@dkelosky If you run the master branch, do you still experience the error? I believe @JillieBeanSim added the fix for this? I am not sure.

**Comment by dkelosky** [comment]
I have `1.7.0` since I just installed from the market place.  I'll wait until it's published.

What action do I take after I update the profile in Zowe CLI?  Is it a refresh?  

Thank you

**Comment by JillieBeanSim** [comment]
@dkelosky unfortunately a refresh of VS Code is needed to move forward after a profile is labeled inactive and then fixed to be active.  I created an issue for this #917

**Comment by dkelosky** [comment]
Thanks - I'll close this in favor of #917
