### ISSUE TITLE
Zowe Explorer Errors at Load Time with Base Profiles

### ISSUE THREAD

**Issue by dkelosky** [zowe/vscode-extension-for-zowe#941]
This is basically #912.  However, you get errors when launching Zowe Explorer if you use base profiles for your CLI.  

**Describe the bug**

**To Reproduce**

0. Closer Zowe Explorer
1. Create a base profile with Zowe CLI: `zowe profiles create base-profile default --user ibmuser  --password xxxxxxxx --ru=false`
2. Create a z/OSMF profile with Zowe CLI: `zowe profiles create zosmf ca11 --host usilca11.lvn.broadcom.net --port 1443`
3. Launch Zowe Explorer
4. Observe `Error encountered while activating and initializing logger!  Error: Must have user & password OR base64 encoded credentials`

**Expected behavior**

No errors should occur.  

**Screenshots**

Launch error:
![image](https://user-images.githubusercontent.com/14940561/87556542-c4ebec80-c684-11ea-895d-d4485641d6be.png)

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Zowe Explorer Version:
-   (Optional) Zowe CLI Version: 6.17
-   (Optional) Are you using Secure Credential Store?  No 

**Additional context**

**Comment by jellypuno** [comment]
this has already been implemented

**Comment by jellypuno** [comment]
@dkelosky Is this still happening? I feel like this is already fixed in v1.12.1. Can you please verify? thank you!

**Comment by dkelosky** [comment]
I cannot reproduce.  I'll reopen if it occurs again.  Thank you
