### ISSUE TITLE
Unable to Create or User Working Profiles when One Errors

### ISSUE THREAD

**Issue by dkelosky** [zowe/vscode-extension-for-zowe#942]
Similar to #941.  However, after you get initialization errors, you can't use any profiles, even ones that do not have errors or do not rely on a base profile.   

**Describe the bug**

**To Reproduce**

0. Follow steps in #941. 
1. Attempt to create a new profile or load a profile that previously worked.

**Expected behavior**

**Screenshots**

Unable to create or use any profiles when one gets an error:
![error](https://user-images.githubusercontent.com/14940561/87556892-37f56300-c685-11ea-83bf-0c81c9423d30.gif)

**Desktop (please complete the following information):**

-   OS:
-   Zowe Explorer Version:
-   (Optional) Zowe CLI Version:
-   (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by JillieBeanSim** [comment]
Zowe Initializing breaking due to profiles has been addressed
