### ISSUE TITLE
Validate profile error message replaced by "Failed to load message bundle" message

### ISSUE THREAD

**Issue by lauren-li** [zowe/vscode-extension-for-zowe#944]
**Describe the bug**

When the user clicks on an inactive profile in Zowe Explorer, an error message should appear informing them that their profile is inactive. In the latest master branch (commit 91c2fbc), this appears to have been replaced with the below error message about failing to load message bundle:
![image (28)](https://user-images.githubusercontent.com/45975633/87570362-8a8b4b00-c696-11ea-9c75-d8eb80d7f6bb.png)

**To Reproduce**
1. Without logging onto the server, open Zowe Explorer and click on any profile associated with that server.
2. After the profile validation process, the error message appears.

**Expected behavior**
Expected error message for failed profile validation: 
`Error: Profile Name <profileName> is inactive. Please check if your Zowe server is active or if the URL and port in your profile is correct.`

**Desktop (please complete the following information):**

-   OS: Mac OS
-   Zowe Explorer Version: latest master branch (commit 91c2fbc)
-   (Optional) Zowe CLI Version: 6.13.0
-   (Optional) Are you using Secure Credential Store? No

**Additional context**
This probably has to do with the latest merge involving Webpack.

**Comment by lauren-li** [comment]
This appears to just be an issue that happened while resolving merge conflicts. It should be fixed in PR #945.

**Comment by crawr** [comment]
Fixed
