### ISSUE TITLE
Cannot Save Files After USS Directory Rename

### ISSUE THREAD

**Issue by dkelosky** [zowe/vscode-extension-for-zowe#947]
**Describe the bug**

If you edit an EBCDIC file in a USS directory and later rename it's parent directory, saving the file fails.

**To Reproduce**

0. Edit an EBCDIC file using Zowe Explorer USS tree.
1. Rename the file's parent directory.
2. Edit the file again
3. Save
4. Observe errors

**Expected behavior**

Previous directory name `napi2` below appears to be saved in memory.

**Screenshots**

![image](https://user-images.githubusercontent.com/14940561/87841037-93377900-c870-11ea-8a28-f1a53328bdaa.png)

```
z/OSMF REST API Error:
Rest API failure with HTTP(S) status 404
category: 1
rc:       8
reason:   9
message:  Error executing command. exit_code=1
details: 
  - /bin/chtag -p /a/ibmuser/native/node/napi2/binding.gyp
  - chtag: FSUM6180 file \"/a/ibmuser/native/node/napi2/binding.gyp\": EDC5129I No such file or directory. (errno2=0x0594003D)

 Error: z/OSMF REST API Error:
Rest API failure with HTTP(S) status 404
category: 1
rc:       8
reason:   9
message:  Error executing command. exit_code=1
details: 
  - /bin/chtag -p /a/ibmuser/native/node/napi2/binding.gyp
  - chtag: FSUM6180 file \"/a/ibmuser/native/node/napi2/binding.gyp\": EDC5129I No such file or directory. (errno2=0x0594003D)
```

**Desktop (please complete the following information):**

-   OS: Win 10
-   Zowe Explorer Version: 1.7.1
-   (Optional) Zowe CLI Version:
-   (Optional) Are you using Secure Credential Store? No

**Additional context**

**Comment by JillieBeanSim** [comment]
looks like all open files from directory close now upon renaming a USS directory
