### ISSUE TITLE
Open Newly Created USS File for Editing

### ISSUE THREAD

**Issue by dkelosky** [zowe/vscode-extension-for-zowe#948]
**Is your feature request related to a problem? Please describe.**

When you right click to create a new file in USS:
![image](https://user-images.githubusercontent.com/14940561/87855154-56a56500-c8e4-11ea-8f63-ec6486c93d8d.png)

The file is created, but then you need to locate it in the tree, and double-click to open it for editing.  

**Describe the solution you'd like**

In VS Code explorer, if you create a new file, that new file is immediately opened for entering text data.  It would be nice if it worked like this for creating a new USS file:

![editnew](https://user-images.githubusercontent.com/14940561/87855208-b56ade80-c8e4-11ea-9d74-c11bb5d4bd37.gif)

**Describe alternatives you've considered**

**Additional context**

**Comment by JillieBeanSim** [comment]
closing in favor of #985
