### ISSUE TITLE
custom volume-serial PDS creation failed

### ISSUE THREAD

**Issue by ishche** [zowe/vscode-extension-for-zowe#954]
**To Reproduce**

1. Specify volume-serial in user's settings.json
```
    "Zowe-Default-Datasets-PDS": {
        "volume-serial": "SPDO01"
    }
```
2. Try to create PDS dataset

**Expected behavior**
new dataset created

**Screenshots**
![image](https://user-images.githubusercontent.com/590426/88176829-29c8b900-cc28-11ea-8217-478bc70c2a69.png)

**Desktop (please complete the following information):**
-   OS: macOS
-   Zowe Explorer Version: 1.7.1
-   Zowe CLI Version: 2.36.2

**Additional context**
PDS creation from CLI works well.

```
$ zowe files cre pds SHCIU01.TRY.ZOWE --volume-serial SPDO01
Data set created successfully.
```

**Comment by jellypuno** [comment]
Hi @ishche 

Please can you try to add all these default values and add the volume serial? 

```
"Zowe-Default-Datasets-PDS": {
  "dsorg": "PO",
  "alcunit": "CYL",
  "primary": 1,
  "secondary": 1,
  "dirblk": 5,
  "recfm": "FB",
  "blksize": 6160,
  "lrecl": 80
}
```

**Comment by ishche** [comment]
I have the same error message with these settings. :(

**Comment by JillieBeanSim** [comment]
this is fixed with the addition of option to edit ds attributes during creation
