### ISSUE TITLE
deleteDataSet not working 

### ISSUE THREAD

**Issue by Pranay154** [zowe/vscode-extension-for-zowe#963]
**Describe the bug**

When I click "Delete Data set" or "Delete PDS", I get an error message and the data set isn't deleted. (More info in the screenshot below)

**To Reproduce**

1. Create a sequential or partitioned data set
2. Click on Delete Data set/PDS
3. An error message should pop up explaining why the dataset isn't/can't be deleted

**Expected behavior**

The data set should be deleted

**Screenshots**

<img width="1920" alt="Screenshot 2020-07-30 at 15 10 18" src="https://user-images.githubusercontent.com/37961978/88933065-d46b5800-d276-11ea-9002-d76326d93f3d.png">

**Desktop (please complete the following information):**

-   OS: Mac OS
-   Zowe Explorer Version: 1.7.1
-   (Optional) Zowe CLI Version: 6.19.1
-   (Optional) Are you using Secure Credential Store? No

**Additional context**

The integration test "should delete a data set if user verified" in `extension.integration.test.ts` fails :
https://github.com/zowe/vscode-extension-for-zowe/blob/3a54adcfea4726da3bf5cbc7dbfc8e03e98d49d2/__tests__/__integration__/extension.integration.test.ts#L199-L211

**Comment by tucker01** [comment]
Getting the same error on Windows 10.
