### ISSUE TITLE
Jobs view unable to expand job names that have a '#' in them

### ISSUE THREAD

**Issue by suman-gopinath** [zowe/vscode-extension-for-zowe#969]
When the job name has a special character - specifically '#' in it, the Jobs view is unable to open the job details and brings up the following error
![image (20)](https://user-images.githubusercontent.com/69168800/89221493-fa576c00-d598-11ea-9043-83614fea5aac.png)

The job gets submitted on the host successfully, its just the expansion within the Jobs view in vscode that has the issue. This issue appears if the job name has a '#'. 
![image (22)](https://user-images.githubusercontent.com/69168800/89221795-7fdb1c00-d599-11ea-9f0d-3515c0eb1514.png)

It does not appear if the job name has a numeric or a '$' or a '@'
![image (21)](https://user-images.githubusercontent.com/69168800/89221805-84073980-d599-11ea-8780-dd465ad45ea4.png)

1. Create a job that has a # in the job name 
2. Submit the job
3. Retrieve the job in the Jobs view. 
4. Expand the job
5. Job does not expand

**Expected behavior**

The job should expand and the data should be visible in the expanded view as shown in the examples of RUN@REXX and RUN$REXX above. 

-   OS: Mac
-   Zowe Explorer Version: v1.8.0
-   (Optional) Zowe CLI Version: 6.17.3
-   (Optional) Are you using Secure Credential Store? No

**Additional context**

**Comment by katelynienaber** [comment]
Some research: I am able to expand the job, if it has name TESTMEM# or TEST#EM#:
![image](https://user-images.githubusercontent.com/58596139/112977180-0a3e4480-9156-11eb-9836-73dd904cceea.png)

But, I get this error when trying to open output (same JCL with job name TESTMEMB works just fine):
![image](https://user-images.githubusercontent.com/58596139/112977403-4bceef80-9156-11eb-838c-7136fea7d3fc.png)
