### ISSUE TITLE
Setting for temporary "Resources" folder location

### ISSUE THREAD

**Issue by adambattenburg** [zowe/vscode-extension-for-zowe#97]
Currently when remote files are being edited, they are downloaded to a temporary `resources` folder within the extension root. These files are inaccessible outside of the extension, and limit what can be built on top of the `zowe-vscode` extension.

I’d like to propose this folder location be configurable in user settings, so that other extensions can make use of it. Alternatively, temporary `resources` could be downloaded to a common location provided by the CLI directly. 

If people agree defining the temporary folder location is a good approach, I can submit a PR to add an option in settings.

**Comment by adambattenburg** [comment]
As an update, I'm now starting work on this, and will have a PR soon. @Colin-Stone you can assign me the issue if you like.

**Comment by Colin-Stone** [comment]
If you swap this folder does the old one get cleared?.

**Comment by adambattenburg** [comment]
That's how I have it setup for now. Moves the `temp` folder from one location to another.

Still need to make progress getting testings working, but afterward I can submit the PR.

**Comment by Colin-Stone** [comment]
@adambattenburg For the sake of the next release is this issue closed?.

**Comment by adambattenburg** [comment]
I'd like to fix the the false errors that appear with multiple instances that I [mention here](https://github.com/zowe/vscode-extension-for-zowe/issues/140#issuecomment-508158685), as that is a bit of a regression. I'll try to get a PR in for that very soon!
