### ISSUE TITLE
Changelog Updated added in Github Actions

### ISSUE THREAD

**Issue by jellypuno** [zowe/vscode-extension-for-zowe#970]
**Is your feature request related to a problem? Please describe.**

Zowe/Imperative has a github check for Changelog Update in every PR. Maybe we can add it too. It would be helpful if each developer would add a short description of their change instead of the admin doing it.

![image](https://user-images.githubusercontent.com/45042840/89394872-e59be500-d70c-11ea-9c8b-0c20d3042640.png)

**Describe the solution you'd like**

copy the solution from zowe/imperative

**Describe alternatives you've considered**

**Additional context**

**Comment by JillieBeanSim** [comment]
@zFernand0 this could be a good idea and would help remind devs to add the CHANGELOG update along with template update.

**Comment by zFernand0** [comment]
Currently testing this.
More info here: https://github.com/awharn/check_changelog_action/pull/11#issue-1400284451
