### ISSUE TITLE
Include section on Associate Profiles function in documentation

### ISSUE THREAD

**Issue by zdmullen** [zowe/vscode-extension-for-zowe#972]
**Describe the bug**

From John Laplante: I don't know what Associate Profiles does or why I would be interested in using it. There is nothing in the customer documentation about this feature. Can we add something there? 

Note: Take information from the docs section of the repo: https://github.com/zowe/vscode-extension-for-zowe/blob/master/docs/README-Extending.md#associating-zowe-cli-profiles

**Additional context**

We should probably add some use cases detailing multiple profile management.

**Comment by IgorCATech** [comment]
Yes, this is something I need to work on. Can we identify the priority for this task?

**Comment by zFernand0** [comment]
Hey @Colin-Stone,
At the time this was implemented, do you remember how many people were asking for something like this?
I believe this may help us determine how urgent this may be.

(personal opinion) Since this has not been closed yet, seems like it may not be top priority at the moment.

**Comment by IgorCATech** [comment]
https://github.com/zowe/docs-site/pull/1412
