### ISSUE TITLE
Cannot create a new profile on MAC

### ISSUE THREAD

**Issue by zimlu02** [zowe/vscode-extension-for-zowe#974]
**Describe the bug**

After reinstalling VSC and upgrading to the latest ZE 1.8.0 I cannot create a new profile in ZE at all, see the screenshot. When I open ZE I get the following error and the plus button to create a new profile doesn't react at all:

Error encountered while activating and initializing logger! TypeError: t is not iterable
<img width="1680" alt="Screenshot 2020-08-07 at 15 56 28" src="https://user-images.githubusercontent.com/38490125/89659519-49224000-d8d0-11ea-8dd7-e43710bec6d6.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

-   OS: MAC 10.14.6
-   Zowe Explorer Version: 1.8.0
-   (Optional) Zowe CLI Version:
-   (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by zdmullen** [comment]
@lauren-li, if I remember correctly from the times when you've shared your screen, you are using a Mac. Have you ever experienced issues with creating profiles and, if so, was there anything you did to overcome the issue? Lukas' has been having troubles with this for a while... Thanks!

**Comment by lauren-li** [comment]
@zdmullen Thanks for tagging me in this issue; I do indeed use a Mac. I have not run into this issue before, and I am having some trouble recreating it. When you say that Lukas has been having trouble with this "for a while", does that mean he was also encountering the issue on a previous version(s) of Zowe Explorer, as well?

~~
For my attempts to recreate the issue, I simulated a fresh VS Code/Zowe CLI install by appending "BACKUP" to the names of the following folders:
- ~/.vscode
- ~/Library/Application Support/Code 
- ~/.zowe

After installing Zowe Explorer 1.8.0 as my only extension, I was able to create a profile via the GUI. Note that my only VS Code settings here are for the one profile I just created (and the search I ran to test it):
<img width="957" alt="Screen Shot 2020-08-10 at 10 25 19 AM" src="https://user-images.githubusercontent.com/45975633/89793525-f6c16900-daf3-11ea-85a0-cbf8cdbce7e9.png">

**Comment by lauren-li** [comment]
Perhaps the logs (if they get created) could provide more insight on the error.
- On a Mac, I believe the Zowe Explorer log can be found at `~/.vscode/extensions/zowe.vscode-extension-for-zowe-1.8.0/logs/zowe.log`.
- The imperative log at `~/.vscode/extensions/zowe.vscode-extension-for-zowe-1.8.0/logs/imperative.log` may also be helpful.

I'm not quite sure if there will be logs for this event though, as the error in the description screenshot appears to involve the logger, but if there are, it would be worth taking a look at them.

Some additional questions for @zimlu02 :
- Do you have Zowe CLI installed? If so, what version? (You can find this using the command: `zowe --version`)
- Does you have the Secure Credential Store installed? (You can check this with the command: `zowe scs --help`)
- Do you have any other VS Code extensions installed alongside Zowe Explorer 1.8.0?

**Comment by zimlu02** [comment]
@lauren-li please find the logs attached.
I still cannot make ZE working again even though I am trying to remove VSC with all its hidden and config files...

I have installed:

- ZOWE CLI 6.13.0
- no zowe scs
- I just have Code4z installed (COBOL and HLASM LS, Debugger for Mainframe, Bitlang COBOL, Explorer for Endevor and Zowe Explorer

[imperative.log](https://github.com/zowe/vscode-extension-for-zowe/files/5056639/imperative.log)
[zowe.log](https://github.com/zowe/vscode-extension-for-zowe/files/5056643/zowe.log)

**Comment by jellypuno** [comment]
Additional Note: Node and NPM versions are

$ node -v
v10.16.2
$ npm -v
6.12.0

**Comment by zimlu02** [comment]
I have uninstalled VSC and its config files:
rm -rf $HOME/Library/Application\ Support/Code
rm -rf $HOME/.vscode

and this time it helped so I have no more this issue. Now I remember I was updating the "Zowe-DS-Persistent" parameter in settings.json before, so most probably I have somehow corrupted it which lead to this problem. 
I will close this issue.

**Comment by lauren-li** [comment]
Thanks @zimlu02 and @jellypuno for following up on this issue! I'm glad it was resolved.

Going forward, we can examine error handling when Zowe Explorer settings are received with unexpected formatting.
