### ISSUE TITLE
Validation of profile freeze

### ISSUE THREAD

**Issue by ishche** [zowe/vscode-extension-for-zowe#977]
I'm trying to get a list of jobs or datasets. When I click on node there is a process monitor with validation of profile.
![image](https://user-images.githubusercontent.com/590426/90007429-ffa06f00-dc9a-11ea-89b8-fda892a987ee.png)
And it seems like it freezes. Even if I cancel it, I still see a pending operation in a tree view
![image](https://user-images.githubusercontent.com/590426/90007609-560dad80-dc9b-11ea-9190-3a2384b46c57.png)

And it blocks everything.

-   OS: macOS
-   Zowe Explorer Version: 1.8.0
-   (Optional) Are you using Secure Credential Store?
no

**Comment by jellypuno** [comment]
@ishche Can you please check if you can access https://<Hostname:port>/zosmf ?

**Comment by zdmullen** [comment]
Hey @ishche, I talked to Jelly about this and maybe she already mentioned it to you, but I thought I would have this for the squad. We have an issue open that @JillieBeanSim is working on, issue #953, that should fix this.

**Comment by ishche** [comment]
> @ishche Can you please check if you can access https://Hostname:port/zosmf ?

You right, it's not accessible now. But maybe it makes sense to add a timeout for validation?

**Comment by jellypuno** [comment]
@ishche We have added a cancel button during validation and as well as the ability to enable/disable validation. Do you think this is enough? Can we close this issue?

**Comment by ishche** [comment]
👍
