### ISSUE TITLE
Integration tests failures

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#982]
**Describe the bug**

After intermittent integration tests failures (#892) seem to have been resolved (setup and cleanup of tests).
There are still 3 tests failing (see full description in https://github.com/zowe/vscode-extension-for-zowe/pull/929#issuecomment-656039896)
- [ ] MVS command
- [ ] Removing favorites
- [ ] Deleting datasets (Verified user)

There are other tests that can fail depending on user environment. This are related to the use of `Thenable` in the test. For example:
- [ ] `DatasetTree Integration Tests`: `Tests that getChildren returns valid list of elements` 
- [ ] `ZoweNode Integration Tests`: `Testing that getChildren returns the correct Thenable<ZoweDatasetNode[]>`

The last set of integrations test failures people can get are due to system configuration.
- [ ] `Recall` tests (2 tests)
- [ ] `Migrate` tests (2 tests)

**To Reproduce**

Run integration tests

**Expected behavior**

All Integration tests passing! :yum:

**Screenshots**

![image](https://user-images.githubusercontent.com/49491949/85033423-ed98c900-b14e-11ea-90ad-1825a6fee03c.png)
Credits: https://github.com/zowe/vscode-extension-for-zowe/pull/787#issuecomment-646057997

**Desktop (please complete the following information):**

-   OS: ANY
-   Zowe Explorer Version: ANY
-   (Optional) Zowe CLI Version: ANY
-   (Optional) Are you using Secure Credential Store? NO (see #983)

**Additional context**

None

**Comment by lauren-li** [comment]
I am not actively working on this issue, but I have incidentally fixed the failing `removeFavorite()` integration test as part of my PR #984 ("Issue #968: Group data sets’ favorites by profile and allow extenders to activate before loading profiles").

**Comment by zFernand0** [comment]
closing in favor of:
- #1595
