### ISSUE TITLE
Integration tests not running with SCS configuration

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-zowe#983]
**Describe the bug**

Unable to run tests whenever the [SCS plugin](https://github.com/zowe/zowe-cli-scs-plugin) is configured in the CLI.
The problem seems to be that the profile `name` specified below does not load in such configuration. https://github.com/zowe/vscode-extension-for-zowe/blob/33f908853b21ee52c7014773a963483acf7283a8/resources/testProfileData.example.ts#L10

**To Reproduce**

- Make sure you have SCS installed, and configured
- Run the `zowe scs u` command
- Run the integration tests

**Expected behavior**

For integration tests to run as before

**Screenshots**

![image](https://user-images.githubusercontent.com/37381190/90430220-12e57d00-e095-11ea-8591-1c080c0c672b.png)

**Desktop (please complete the following information):**

-   OS: Windows
-   Zowe Explorer Version: 1.8.0 (or master)
-   (Optional) Zowe CLI Version: ANY
-   (Optional) Are you using Secure Credential Store? YES

**Comment by JillieBeanSim** [comment]
this is no longer an issue since SCS is no longer required.
