### ISSUE TITLE
Job with name ??????? causes "undefined:undefined(undefined)" in jobs tab  

### ISSUE THREAD

**Issue by tucker01** [zowe/vscode-extension-for-zowe#986]
**Describe the bug**

Submitting a job with name `????????` causes an entry to be added to the "jobs" list, but spool entries are not viewable and are listed as `undefined:undefined(undefined)`. 

**To Reproduce**

Submit a job from zowe explorer with a jobname of `????????`.

**Expected behavior**

I can view the spool output. 

**Screenshots**

![image](https://user-images.githubusercontent.com/37446232/90668327-ef9a0980-e21d-11ea-8aa8-a4eac9c13916.png)

**Desktop (please complete the following information):**

-   OS: Windows 10 
-   Zowe Explorer Version: 1.8.0 

**Additional context**

**Comment by jellypuno** [comment]
Similar to #845
