### ISSUE TITLE
Editing Base Path on a ZE Connection Profile Doesn't Save it

### ISSUE THREAD

**Issue by jelaplan** [zowe/vscode-extension-for-zowe#989]
If I create a connection profile and then later go in and edit it and either add a base path or edit the base path, it doesn't save to disk. It works for that session but if I quit VS Code and restart, my changes are gone. I also can't go to the CLI and take advantage of the changes.

**Comment by crawr** [comment]
I encountered the same issue with the encoding field, which is a new field in the zosmf schema. 

The edit profile functionality should iterate over the items in this schema, the same way that the create profile does it.

**Comment by katelynienaber** [comment]
Yes I have the opposite problem...if my profile contains a basePath in YAML:

- Remove basePath inside Explorer...profile now authenticates properly
- Restart VSCode
- Try to use profile again...auth fails, now I have to remove the basePath again...

It's just updating the session, not the YAML file, seems like...

**Comment by jellypuno** [comment]
Closing issue. Fix is merged in v1.12.x
