### ISSUE TITLE
Favorites are discarded upon restart (Zowe RSE profile)

### ISSUE THREAD

**Issue by bearou** [zowe/vscode-extension-for-zowe#990]
**Describe the bug**

After adding a favorite dataset and seen it go to the favorite section - this is discarded when VS Code is restarted.

Not only discarded, but an error msg. is shown:
"Error: You have Zowe Data Set favorites that refer to a non-existent CLI profile named: newrse. To resolve this, you can create a profile with this name, or remove the favorites with this profile name from the Zowe-DS-Persistent setting, which can be found in your VS Code user settings. Error: Could not find profile named: newrse.
Source: Zowe Explorer (Extension)"

The CLI profile - used to define the favorite - is not deleted.

**To Reproduce**

Have valid defined a RSE profile defined. Restart VS Code (or dont - doesn't matter).
Open dataset/member and add it to favorites.
See mentionned dataset in favorites.
Close down VS Code
Open VS Code
Not only is the favorite dataset gone; an error msg. is shown (see above)

**Expected behavior**

Expected that the dataset would still be in the favorites section of Zowe.Data Sets.

**Screenshots**

![image](https://user-images.githubusercontent.com/48259804/91142896-eb546d00-e6b1-11ea-8e12-1f5a380e12eb.png)

**Desktop (please complete the following information):**

-   OS: windows
-   Zowe Explorer Version: 1.8.0
-   (Optional) Zowe CLI Version: 1.14
-   (Optional) Are you using Secure Credential Store? Yes

**Additional context**

None

**Comment by oakmount66** [comment]
Just seen that you don't need to restart VScode to experience this error. Just switch to Explorer and Open Folder (Ctrl+K Ctrl+O) and then back to Zowe. Now your RSE-favorites are gone and you'll get the error message that Bearou describes.

**Comment by lauren-li** [comment]
@bearou @oakmount66 Thank you for reporting this issue. It is actively being worked on, and you can view the current progress under issue #968 and its linked pull requests. The proposed solution for the Data Sets view is outlined in the description for pull request #984, but is also applied similarly in the pull requests for the Jobs and USS views (#991 and #997, respectively).

**Comment by lauren-li** [comment]
@bearou @oakmount66 This issue should be resolved in Zowe Explorer versions 1.9.0 and above. If you are still experiencing this issue, please comment here to let us know. Thank you!

**Comment by crawr** [comment]
Error has been fixed. Closing this issue.
